CREATE TYPE [dbo].[WDEA_Layout_T_V2] AS TABLE (
    [Item]                   NVARCHAR (100)  NULL,
    [Purch_Organization]     NVARCHAR (1000) NULL,
    [Cost_Center]            NVARCHAR (1000) NULL,
    [WBS_Element]            NVARCHAR (1000) NULL,
    [Short_Text]             NVARCHAR (MAX)  NULL,
    [Outline_Agreegement]    NVARCHAR (100)  NULL,
    [Validity_Per_Start]     NVARCHAR (100)  NULL,
    [Validity_Period_End]    NVARCHAR (100)  NULL,
    [Deletion_Indicador]     NVARCHAR (100)  NULL,
    [Plant]                  NVARCHAR (100)  NULL,
    [Order_Quantity]         NVARCHAR (100)  NULL,
    [Order_Unit]             NVARCHAR (100)  NULL,
    [Net_Price]              NVARCHAR (100)  NULL,
    [Currency]               NVARCHAR (100)  NULL,
    [Vendor_Supplying_Plant] NVARCHAR (100)  NULL,
    [Purchasing_Document]    NVARCHAR (100)  NULL,
    [Release_State]          NVARCHAR (100)  NULL,
    [Name_of_Vendor]         NVARCHAR (100)  NULL,
    [Order_Price_Unit]       NVARCHAR (100)  NULL,
    [Net_Order_Value]        NVARCHAR (100)  NULL,
    [Requisitioner]          NVARCHAR (100)  NULL,
    [Terminos_Pago]          NVARCHAR (100)  NULL,
    [Justificacion]          NVARCHAR (MAX)  NULL,
    [RowN]                   NVARCHAR (100)  NULL);

