CREATE TYPE CO_Type_SAPPO AS TABLE
(
    [NumeroFila] INT NULL,
    [VersionNumber] INT NULL,
    [SAPVendorNumber] VARCHAR(1000) NULL,
    [ItemNumber] INT NULL,
    [SAPMaterialNumber] VARCHAR(1000) NULL,
    [Quantity] FLOAT NULL,
    [UnitPrice] FLOAT NULL,
    [Currency] VARCHAR(1000) NULL,
    [Total] FLOAT NULL,
    [DeliveryAddress] VARCHAR(1000) NULL,
    [SAPPONumber] VARCHAR(1000) NULL,
    [DeliveryDate] VARCHAR(1000) NULL,
    [Comments] VARCHAR(1000) NULL,
    [CostObject] VARCHAR(1000) NULL,
    [MaterialGroup] VARCHAR(50) NULL,
    [MaterialGroupDescription] VARCHAR(1000) NULL,
    [ServiceLineNumber] VARCHAR(1000) NULL,
    [Quantity2] FLOAT NULL,
    [Price] FLOAT NULL,
    [CostObject2] VARCHAR(1000) NULL,
    [ServiceGroup] VARCHAR(1000) NULL,
    [ShortText] VARCHAR(1000) NULL,
    [ParentLineUOM] VARCHAR(1000) NULL,
    [ServicesShortText] VARCHAR(1000) NULL,
    [ServicesUOM] VARCHAR(1000) NULL,
    [Plant] VARCHAR(1000) NULL,
    [POItemCategory] INT NULL,
    [EsActualizacion] BIT NULL
);