CREATE TABLE [dbo].[CarpetasDocumentosEntregables](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDPadre] [int] NULL,
	[Titulo] [nvarchar](max) NULL,
	[EtapaId] [nvarchar](max) NULL,
	[ReceptorEntregableId] [int] NULL,
	[PozoInstalacionId] [int] NULL,
	[MarcoLegalId] [int] NULL,
	[EtapaPozoId] [int] NULL,
	[EntregableId] [int] NULL,
	[FrecuenciaId] [nvarchar](max) NULL,
	[Frecuencia] [nvarchar](max) NULL,
	[FechaEntregaAnioMes] [nvarchar](max) NULL,
	[FechaProgramadaEntrega] [datetime] NULL,
	[DocumentoEntregableId] [int] NULL,
	[CantidadArchivos] [int] NULL,
	[Detalle] [nvarchar](max) NULL,
	[Icono] [nvarchar](max) NULL,
	[Acciones] [nvarchar](max) NULL,
	[Mime] [nvarchar](max) NULL,
	[Nivel] [int] NULL,
	[TipoArchivo] [nvarchar](max) NULL,
	[FechaCarga] [datetime] NULL,
	[CargadoPor] [nvarchar](max) NULL,
	[Bucket] [nvarchar](max) NULL,
	[Folder] [nvarchar](max) NULL,
	[UUIDAmazon] [uniqueidentifier] NULL,
	[NombreArchivo] [nvarchar](max) NULL,
	[Meta] [nvarchar](max) NULL,
	[SizeBytes] [decimal](18, 0) NULL,
	[IdContrato] [int] NULL,
	[Activo] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
