CREATE TABLE [dbo].[OT_ReporteTablero] (
    [Folio]                       VARCHAR (20)  NULL,
    [Objeto]                      VARCHAR (700) NULL,
    [Tarea]                       VARCHAR (250) NULL,
    [SubTarea]                    VARCHAR (250) NULL,
    [Estatus]                     VARCHAR (30)  NULL,
    [Fecha_Registro_OT]           DATETIME      NULL,
    [Requisitor]                  VARCHAR (150) NULL,
    [Fecha_Rechazo]               DATETIME      NULL,
    [Fecha_AprobacionManager]     DATETIME      NULL,
    [Fecha_Aprobacion_PRSAP]      DATETIME      NULL,
    [No_PR_SAP]                   VARCHAR (50)  NULL,
    [Fecha_Aceptacion_Proveedor]  DATETIME      NULL,
    [Fecha_Carga_Avance]          DATETIME      NULL,
    [Fecha_Cierre_Semana]         DATETIME      NULL,
    [Responsable_Cierre_Semana]   VARCHAR (150) NULL,
    [Fecha_Estimacion]            DATETIME      NULL,
    [Responsable_Estimacion]      VARCHAR (150) NULL,
    [Fecha_Aceptacion_Pedido]     DATETIME      NULL,
    [No_Aceptacion_Pedido]        VARCHAR (50)  NULL,
    [Responsable_Aceptacion]      VARCHAR (150) NULL,
    [Fecha_Pedido]                DATETIME      NULL,
    [No_Pedido]                   VARCHAR (20)  NULL,
    [Moneda]                      VARCHAR (10)  NULL,
    [Costo]                       FLOAT (53)    NULL,
    [Estatus_Pedido]              VARCHAR (50)  NULL,
    [FechaRelacion_PedidoPo]      DATETIME      NULL,
    [Num_PO_SAP]                  VARCHAR (50)  NULL,
    [RegistroPCN]                 VARCHAR (200) NULL,
    [Fecha_Aprobacion_PCN]        DATETIME      NULL,
    [Fecha_Recepcion_Factura]     DATETIME      NULL,
    [ResponsableRecepcionFactura] VARCHAR (200) NULL,
    [Fecha_Aprobacion_Factura]    DATETIME      NULL,
    [SubtotalFactura]             MONEY         NULL,
    [MontoAceptado]               FLOAT (53)    NULL,
    [IdContrato]                  INT           NULL,
    [IdCentroCosto]               INT           NULL,
    [CentroCosto]                 VARCHAR (100) NULL,
    [IdOTSolicitud]               INT           NULL,
    [IdProveedor]                 INT           NULL,
    [RazonSocialProv]             VARCHAR (500) NULL
);

