CREATE TABLE [dbo].[PC_DistribucionIngresos] (
    [IdDistribucionIngresos]          INT           IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                      INT           NULL,
    [MesReporte]                      NVARCHAR (50) NULL,
    [IdSector]                        INT           NULL,
    [IdMaterialPC]                    INT           NULL,
    [IdPtoExpedicionRecepcion]        INT           NULL,
    [IdRegion]                        INT           NULL,
    [IdActivo]                        INT           NULL,
    [IdCampo]                         INT           NULL,
    [ParticipacionVolumetrica]        FLOAT (53)    NULL,
    [FactorDistribucionVolumetrica]   FLOAT (53)    NULL,
    [DistribucionVolumetrica]         FLOAT (53)    NULL,
    [IdUnidadMedida]                  INT           NULL,
    [GPVMaximoPorCampo]               FLOAT (53)    NULL,
    [GPVMaximoPorMaterial]            FLOAT (53)    NULL,
    [GPVPonderadoPorCampo]            FLOAT (53)    NULL,
    [PrecioEquilibrio]                MONEY         NULL,
    [PrecioReferencia]                MONEY         NULL,
    [FactorDistribucionIngresos]      FLOAT (53)    NULL,
    [DistribucionIngresos]            MONEY         NULL,
    [DistribucionIngresosMonedaLocal] MONEY         NULL,
    [IdMonedaLocal]                   INT           NULL,
    [DistrubucionIngresosUSD]         MONEY         NULL,
    [IdMonedaLocal2]                  INT           NULL,
    [IdOrganismo]                     INT           NULL,
    [CreadoPor]                       INT           NULL,
    [CreadoEn]                        DATETIME      NULL,
    CONSTRAINT [PK_PC_DistribucionIngresos1] PRIMARY KEY CLUSTERED ([IdDistribucionIngresos] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_PC_DistribucionIngresos_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK_PC_DistribucionIngresos_CO_Region] FOREIGN KEY ([IdRegion]) REFERENCES [dbo].[CO_Region] ([IdRegion]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_Activo] FOREIGN KEY ([IdActivo]) REFERENCES [dbo].[PC_Activo] ([IdActivo]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_Campo] FOREIGN KEY ([IdCampo]) REFERENCES [dbo].[PC_Campo] ([IdCampo]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_Material] FOREIGN KEY ([IdMaterialPC]) REFERENCES [dbo].[PC_Material] ([IdMaterialPC]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_Organismo] FOREIGN KEY ([IdOrganismo]) REFERENCES [dbo].[PC_Organismo] ([IdOrganismo]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_PtoExpedicionRecepcion] FOREIGN KEY ([IdPtoExpedicionRecepcion]) REFERENCES [dbo].[PC_PtoExpedicionRecepcion] ([IdPtoExpedicionRecepcion]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PC_Sector] FOREIGN KEY ([IdSector]) REFERENCES [dbo].[PC_Sector] ([IdSector]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PV_TipoMoneda1] FOREIGN KEY ([IdMonedaLocal]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda]),
    CONSTRAINT [FK_PC_DistribucionIngresos_PV_TipoMoneda2] FOREIGN KEY ([IdMonedaLocal2]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda])
);

