CREATE TABLE [dbo].[PC_ReporteComercializacion] (
    [IdRC]                          INT            IDENTITY (1, 1) NOT NULL,
    [Factura]                       NVARCHAR (255) NULL,
    [Fecha factura]                 DATETIME       NULL,
    [Sociedad]                      NVARCHAR (255) NULL,
    [Valor neto]                    FLOAT (53)     NULL,
    [Moneda Val# Neto]              NVARCHAR (255) NULL,
    [Importe del impuesto]          FLOAT (53)     NULL,
    [Referencia]                    NVARCHAR (255) NULL,
    [Cantidad facturada]            FLOAT (53)     NULL,
    [Un#medida venta]               NVARCHAR (255) NULL,
    [Material]                      NVARCHAR (255) NULL,
    [Denominación]                  NVARCHAR (255) NULL,
    [Nº documento]                  NVARCHAR (255) NULL,
    [Ejercicio]                     NVARCHAR (255) NULL,
    [Moneda]                        NVARCHAR (255) NULL,
    [Tipo de cambio]                NVARCHAR (255) NULL,
    [Moneda local]                  NVARCHAR (255) NULL,
    [Referencia1]                   NVARCHAR (255) NULL,
    [Importe]                       FLOAT (53)     NULL,
    [Importe ML]                    FLOAT (53)     NULL,
    [Pos#presupuestaria]            NVARCHAR (255) NULL,
    [Centro gestor]                 NVARCHAR (255) NULL,
    [Cuenta de mayor]               NVARCHAR (255) NULL,
    [Doc#compensación]              NVARCHAR (255) NULL,
    [Organización ventas]           NVARCHAR (255) NULL,
    [Canal distribución]            NVARCHAR (255) NULL,
    [Sector]                        NVARCHAR (255) NULL,
    [Centro]                        NVARCHAR (255) NULL,
    [Nombre 1]                      NVARCHAR (255) NULL,
    [Puesto de carga]               NVARCHAR (255) NULL,
    [Denominación1]                 NVARCHAR (255) NULL,
    [Energía]                       FLOAT (53)     NULL,
    [Unidad de salida de condición] NVARCHAR (255) NULL,
    [Cliente]                       NVARCHAR (255) NULL,
    [Nombre Cliente]                NVARCHAR (255) NULL,
    [Importe en dólares]            FLOAT (53)     NULL,
    [Moneda dólares]                NVARCHAR (255) NULL,
    [Nombre del Cliente]            NVARCHAR (255) NULL,
    [Oficina Ventas]                NVARCHAR (255) NULL,
    [Gpo#Cond#]                     NVARCHAR (255) NULL,
    [No#Orden]                      NVARCHAR (255) NULL,
    [Ped#Cliente]                   NVARCHAR (255) NULL,
    [Plan Entrega]                  NVARCHAR (255) NULL,
    [FechaComp]                     DATETIME       NULL,
    [FechaPago]                     DATETIME       NULL,
    [F#Tesorería]                   DATETIME       NULL,
    [F#DPP1]                        FLOAT (53)     NULL,
    [F#DPPV]                        FLOAT (53)     NULL,
    CONSTRAINT [PK_PC_ReporteComercializacion] PRIMARY KEY CLUSTERED ([IdRC] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

