CREATE TABLE [dbo].[PC_VentasAsignacion_V2] (
    [IdVentasAsignacion]             INT            IDENTITY (10000, 1) NOT NULL,
    [FechaReporte]                   DATE           NULL,
    [ASIGNACIÓN]                     NVARCHAR (255) NULL,
    [REGIÓN FISCAL]                  NVARCHAR (255) NULL,
    [REGIÓN]                         NVARCHAR (255) NULL,
    [POZO SNIP]                      NVARCHAR (255) NULL,
    [PRODUCTO POZO]                  NVARCHAR (255) NULL,
    [Producción POZO]                FLOAT (53)     NULL,
    [CAMPO OFICIAL]                  NVARCHAR (255) NULL,
    [Producción CAMPO]               FLOAT (53)     NULL,
    [PRODUCTO UNIF]                  NVARCHAR (255) NULL,
    [FACTOR = ProdPozo/ProdCampo]    FLOAT (53)     NULL,
    [Producción ASIGNACIÓN]          FLOAT (53)     NULL,
    [PRODUCTO AGRUPA]                NVARCHAR (255) NULL,
    [PRODUCTO VENTA]                 NVARCHAR (255) NULL,
    [PUNTO DE VENTA]                 NVARCHAR (255) NULL,
    [VENTA CAMPO MES]                FLOAT (53)     NULL,
    [VENTA ASIGNACIÓN MES]           FLOAT (53)     NULL,
    [UNIDAD VENTA MES]               NVARCHAR (255) NULL,
    [VENTA ASIGNACIÓN DÍA]           FLOAT (53)     NULL,
    [UNIDAD VENTA DÍA]               NVARCHAR (255) NULL,
    [VENTA ASIGNACIÓN MES INGLÉS]    FLOAT (53)     NULL,
    [UNIDAD VENTA MES INGLÉS]        NVARCHAR (255) NULL,
    [VENTA ASIGNACIÓN DÍA INGLÉS]    FLOAT (53)     NULL,
    [UNIDAD VENTA DÍA INGLÉS]        NVARCHAR (255) NULL,
    [API]                            FLOAT (53)     NULL,
    [S]                              FLOAT (53)     NULL,
    [C1]                             FLOAT (53)     NULL,
    [C2]                             FLOAT (53)     NULL,
    [C3]                             FLOAT (53)     NULL,
    [NC4]                            FLOAT (53)     NULL,
    [IC4]                            FLOAT (53)     NULL,
    [C5+]                            FLOAT (53)     NULL,
    [CO2]                            FLOAT (53)     NULL,
    [H2S]                            FLOAT (53)     NULL,
    [N2]                             FLOAT (53)     NULL,
    [PoderCalorif C1]                FLOAT (53)     NULL,
    [PoderCalorif C2]                FLOAT (53)     NULL,
    [PoderCalorif C3]                FLOAT (53)     NULL,
    [PoderCalorif NC4]               FLOAT (53)     NULL,
    [PoderCalorif IC4]               FLOAT (53)     NULL,
    [PoderCalorif C5+]               FLOAT (53)     NULL,
    [PoderCalorif C1Btu/pc]          FLOAT (53)     NULL,
    [PoderCalorif C2Btu/pc]          FLOAT (53)     NULL,
    [PoderCalorif C3Btu/pc]          FLOAT (53)     NULL,
    [PoderCalorif NC4Btu/pc]         FLOAT (53)     NULL,
    [PoderCalorif IC4Btu/pc]         FLOAT (53)     NULL,
    [PoderCalorif C5+Btu/pc]         FLOAT (53)     NULL,
    [PoderCalorif Total Btu/pc]      FLOAT (53)     NULL,
    [Volumen C1]                     FLOAT (53)     NULL,
    [Volumen C2]                     FLOAT (53)     NULL,
    [Volumen C3]                     FLOAT (53)     NULL,
    [Volumen NC4]                    FLOAT (53)     NULL,
    [Volumen IC4]                    FLOAT (53)     NULL,
    [Volumen C5+]                    FLOAT (53)     NULL,
    [Energía C1]                     FLOAT (53)     NULL,
    [Energía C2]                     FLOAT (53)     NULL,
    [Energía C3]                     FLOAT (53)     NULL,
    [Energía NC4]                    FLOAT (53)     NULL,
    [Energía IC4]                    FLOAT (53)     NULL,
    [Energía C5+]                    FLOAT (53)     NULL,
    [Energía Total]                  FLOAT (53)     NULL,
    [Ingreso C1]                     FLOAT (53)     NULL,
    [Ingreso C2]                     FLOAT (53)     NULL,
    [Ingreso C3]                     FLOAT (53)     NULL,
    [Ingreso NC4]                    FLOAT (53)     NULL,
    [Ingreso IC4]                    FLOAT (53)     NULL,
    [Ingreso C5+]                    FLOAT (53)     NULL,
    [Precio C1]                      FLOAT (53)     NULL,
    [Precio C2]                      FLOAT (53)     NULL,
    [Precio C3]                      FLOAT (53)     NULL,
    [Precio NC4]                     FLOAT (53)     NULL,
    [Precio IC4]                     FLOAT (53)     NULL,
    [Precio C5+]                     FLOAT (53)     NULL,
    [Precio ]                        FLOAT (53)     NULL,
    [Ingresos Mes USD]               FLOAT (53)     NULL,
    [Venta Campo mes Facturado]      FLOAT (53)     NULL,
    [Venta ASIGNACIÓN mes Facturado] FLOAT (53)     NULL,
    [Volumen Facturacion]            FLOAT (53)     NULL,
    [Precio Facturación]             FLOAT (53)     NULL,
    [Ingresos Mes Calculado USD]     FLOAT (53)     NULL,
    [CreadoPor]                      INT            NULL,
    [CreadoEn]                       DATETIME       NULL,
    CONSTRAINT [PK_PC_VentasAsignacion_V2] PRIMARY KEY CLUSTERED ([IdVentasAsignacion] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

