CREATE TABLE [dbo].[PR_BalanceMensual] (
    [IdContrato]                   INT           NOT NULL,
    [PuntoEntregaID]               INT           NOT NULL,
    [Fecha]                        DATE          NOT NULL,
    [TipoHidrocarburo]             VARCHAR (50)  NOT NULL,
    [InventarioInicial]            FLOAT (53)    NULL,
    [Desempaque]                   FLOAT (53)    NULL,
    [AlmacenadoTanques]            FLOAT (53)    NULL,
    [AlmacenadoRecipientes]        FLOAT (53)    NULL,
    [VolOtrasEntradas]             FLOAT (53)    NULL,
    [ComentariosEntradas]          VARCHAR (500) NULL,
    [VolGasVenteado]               FLOAT (53)    NULL,
    [VolGasQuemado]                FLOAT (53)    NULL,
    [VolGasTraspasado]             FLOAT (53)    NULL,
    [VolGasBN]                     FLOAT (53)    NULL,
    [VolGasCombustible]            FLOAT (53)    NULL,
    [VolGasYacimientos]            FLOAT (53)    NULL,
    [MermasEvaporacion]            FLOAT (53)    NULL,
    [MermasFugas]                  FLOAT (53)    NULL,
    [VolEmpaque]                   FLOAT (53)    NULL,
    [VolEncogimientoTransporte]    FLOAT (53)    NULL,
    [FactorEncogimientoTransporte] FLOAT (53)    NULL,
    [VolEncogimientoImpurezas]     FLOAT (53)    NULL,
    [FactorEncogimientoImpurezas]  FLOAT (53)    NULL,
    [VolEncogimientoEficiencia]    FLOAT (53)    NULL,
    [FactorEncogimientoEficiencia] FLOAT (53)    NULL,
    [VolEncogimientoLiquidos]      FLOAT (53)    NULL,
    [FactorEncogimientoLiquidos]   FLOAT (53)    NULL,
    [VolTraspaso]                  FLOAT (53)    NULL,
    [VolAutoconsumo]               FLOAT (53)    NULL,
    [InventarioFinal]              FLOAT (53)    NULL,
    [VolPerdidasNoIdentificadas]   FLOAT (53)    NULL,
    [VolOtrasSalidas]              FLOAT (53)    NULL,
    [ComentariosBalance]           VARCHAR (500) NULL,
    [VolumenExtraidoHidrocarburo]  FLOAT (53)    NULL,
    [VolumenExtraidoAgua]          FLOAT (53)    NULL,
    [VolumenIncorporado]           FLOAT (53)    NULL,
    [VolumenExtraidoImpurezas]     FLOAT (53)    NULL,
    [VolumenGasResidual]           FLOAT (53)    NULL,
    [VolEntregadoPtoMedicion]      FLOAT (53)    NULL,
    CONSTRAINT [PK_PR_BalanceMensual] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [PuntoEntregaID] ASC, [Fecha] ASC, [TipoHidrocarburo] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_PR_BalanceMensual_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK_PR_BalanceMensual_CO_PuntosdeEntrega] FOREIGN KEY ([PuntoEntregaID]) REFERENCES [dbo].[CO_PuntosdeEntrega] ([PuntoEntregaID])
);

