CREATE TABLE [dbo].[PR_CalibracionSistemasBitacora] (
    [Id]                    INT            IDENTITY (1, 1) NOT NULL,
    [Accion]                VARCHAR (300)  NULL,
    [CreadoPor]             INT            NULL,
    [CreadoEl]              DATETIME       NULL,
    [IdCalibracion]         INT            NULL,
    [IdContrato]            INT            NULL,
    [IdSistema]             INT            NULL,
    [Certificado]           VARCHAR (250)  NULL,
    [Fecha]                 DATETIME       NULL,
    [FechaProxima]          DATETIME       NULL,
    [IntervaloCalibracion]  VARCHAR (250)  NULL,
    [InvervaloVerificacion] VARCHAR (250)  NULL,
    [IncertidumbreMagnitud] VARCHAR (250)  NULL,
    [Laboratorio]           VARCHAR (250)  NULL,
    [EsAcreditado]          BIT            NULL,
    [PuertoDisponible]      VARCHAR (250)  NULL,
    [ConfiguracionPuerto]   VARCHAR (250)  NULL,
    [ProtocoloComunicacion] VARCHAR (250)  NULL,
    [AreaRestringida]       BIT            NULL,
    [Observaciones]         VARCHAR (2000) NULL,
    [Vigente]               BIT            NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

