CREATE TABLE [dbo].[PR_EquiposAutoconsumoBitacora] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [Accion]               VARCHAR (300)  NULL,
    [CreadoPor]            INT            NULL,
    [CreadoEl]             DATETIME       NULL,
    [IdContrato]           INT            NOT NULL,
    [IdEquipo]             INT            NOT NULL,
    [Fecha]                DATETIME       NULL,
    [UTMX]                 FLOAT (53)     NULL,
    [UTMY]                 FLOAT (53)     NULL,
    [Producto]             VARCHAR (50)   NULL,
    [TipoEquipo]           VARCHAR (250)  NULL,
    [TAG]                  VARCHAR (300)  NULL,
    [FluidoDesplazado]     VARCHAR (300)  NULL,
    [ConsumoTeorico]       FLOAT (53)     NULL,
    [ConsumoReal]          FLOAT (53)     NULL,
    [ConsumoEnergetico]    FLOAT (53)     NULL,
    [DispositivoInyeccion] VARCHAR (1000) NULL,
    [Obervaciones]         VARCHAR (1000) NULL,
    [Activo]               BIT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

