CREATE TABLE [dbo].[PR_PRP_REOLOGICAS_FLUIDO] (
    [Id]           INT             IDENTITY (1, 1) NOT NULL,
    [ITTEM]        DECIMAL (24, 8) NULL,
    [CODE_MUESTRA] VARCHAR (200)   NULL,
    [POZO]         VARCHAR (200)   NULL,
    [TP_O_TR]      VARCHAR (200)   NULL,
    [FECHA]        DATETIME        NULL,
    [API]          DECIMAL (24, 8) NULL,
    [PORC_SED]     DECIMAL (24, 8) NULL,
    [PORC_EMUL]    DECIMAL (24, 8) NULL,
    [PORC_AGUA]    DECIMAL (24, 8) NULL,
    [AT_Y_SED]     DECIMAL (24, 8) NULL,
    [PH]           DECIMAL (24, 8) NULL,
    [TEMP]         DECIMAL (24, 8) NULL,
    [OBSERVACION]  VARCHAR (200)   NULL,
    [SALINIDAD]    DECIMAL (24, 8) NULL,
    [VISCO]        DECIMAL (24, 8) NULL,
    CONSTRAINT [PK_PR_PRP_REOLOGICAS_FLUIDO] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

