CREATE TABLE [dbo].[PR_PozoLog] (
    [IdLog]                INT             IDENTITY (1, 1) NOT NULL,
    [Id]                   INT             NOT NULL,
    [Clave]                VARCHAR (20)    NOT NULL,
    [Nombre]               VARCHAR (200)   NOT NULL,
    [Descripcion]          NVARCHAR (2000) NOT NULL,
    [Estatus]              INT             NOT NULL,
    [LDD]                  INT             NOT NULL,
    [Estacion]             INT             NOT NULL,
    [Campo]                INT             NOT NULL,
    [ProduccionNeta]       DECIMAL (24, 8) NOT NULL,
    [Tanque]               INT             NULL,
    [UltimoControl]        DATETIME        NULL,
    [SubEstado]            INT             NULL,
    [TipoProduccion]       INT             NULL,
    [ActividadIncremental] INT             NULL,
    [TipoSistema]          INT             NULL,
    [PozoTipo]             INT             NULL,
    [Modificado]           DATETIME        NULL,
    [ModificadoPor]        VARCHAR (200)   NULL,
    [ModificadoServer]     DATETIME        NULL,
    [Alta]                 DATETIME        NULL,
    [Comentarios]          NVARCHAR (MAX)  NULL,
    [AnioActividad]        INT             NULL,
    [UltimoControlValido]  INT             NULL,
    [ProduccionBruta]      DECIMAL (24, 8) NULL,
    [PorcentajeAgua]       DECIMAL (8, 4)  NULL,
    [X]                    FLOAT (53)      NULL,
    [Y]                    FLOAT (53)      NULL,
    [PotencialOptimo]      DECIMAL (24, 8) NULL,
    [PotencialOperativo]   DECIMAL (24, 8) NULL,
    [OFM]                  VARCHAR (20)    NULL,
    CONSTRAINT [PK_PR__PozoLog__0C54DBC6038683F8] PRIMARY KEY CLUSTERED ([IdLog] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

