CREATE TABLE [dbo].[PR_ProdDiariaPozo] (
    [Id]                       INT             IDENTITY (1, 1) NOT NULL,
    [ProdDiaria]               INT             NOT NULL,
    [Fecha]                    DATETIME        NULL,
    [Estacion]                 INT             NOT NULL,
    [Pozo]                     INT             NOT NULL,
    [TiempoOperando]           INT             CONSTRAINT [DF_ProdDiariaPozo_TiempoOperando] DEFAULT ((0)) NOT NULL,
    [TiempoParo]               INT             CONSTRAINT [DF_ProdDiariaPozo_TiempoParo] DEFAULT ((0)) NOT NULL,
    [ProduccionControl]        DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionControl] DEFAULT ((0)) NOT NULL,
    [PctAguaControl]           DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_PctAguaControl] DEFAULT ((0)) NOT NULL,
    [ProduccionTeorica]        DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionTeorica] DEFAULT ((0)) NOT NULL,
    [ProduccionDiferida]       DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionDiferida] DEFAULT ((0)) NOT NULL,
    [ProduccionReal]           DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionReal_1] DEFAULT ((0)) NOT NULL,
    [ProduccionAlocadaBruta]   DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionReal] DEFAULT ((0)) NOT NULL,
    [ProduccionAlocadaNeta]    DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_ProduccionAlocadaNeta] DEFAULT ((0)) NOT NULL,
    [PctAguaAlocada]           DECIMAL (24, 8) CONSTRAINT [DF_ProdDiariaPozo_PctAguaAlocada] DEFAULT ((0)) NOT NULL,
    [TipoSAP]                  INT             CONSTRAINT [DF_ProdDiariaPozo_Tipo] DEFAULT ((0)) NOT NULL,
    [LDD]                      TINYINT         CONSTRAINT [DF_ProdDiariaPozo_LDD] DEFAULT ((0)) NOT NULL,
    [Estado]                   INT             CONSTRAINT [DF_ProdDiariaPozo_Estado] DEFAULT ((0)) NULL,
    [Subestado]                INT             CONSTRAINT [DF_ProdDiariaPozo_Subestado] DEFAULT ((0)) NULL,
    [TipoProduccion]           INT             NULL,
    [ActrividadIncremental]    INT             NULL,
    [ControlUtilizado]         INT             CONSTRAINT [DF_ProdDiariaPozo_ControlUtilizado] DEFAULT ((0)) NULL,
    [ProduccionRealGasM3]      DECIMAL (24, 8) NULL,
    [ProduccionRealCondensado] DECIMAL (24, 8) NULL,
    [GradosAPI]                FLOAT (53)      NULL,
    [ContenidoAzufre]          FLOAT (53)      NULL,
    [ContenidoSal]             FLOAT (53)      NULL,
    [MMPCM]                    DECIMAL (24, 8) NULL,
    CONSTRAINT [PK_PR_ProdDiariaPozo] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_ProdDiariaPozo_Pozo] FOREIGN KEY ([Pozo]) REFERENCES [dbo].[PR_Pozo] ([Id]),
    CONSTRAINT [FK_ProdDiariaPozo_ProdDiaria] FOREIGN KEY ([ProdDiaria]) REFERENCES [dbo].[PR_ProdDiaria] ([Id])
);

