CREATE TABLE [dbo].[PR_REGISTROS] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [NUM_ECO]         DECIMAL (24, 8) NULL,
    [NOMBRE_POZO]     VARCHAR (200)   NULL,
    [TERMINACION]     VARCHAR (200)   NULL,
    [FECHA]           DATETIME        NULL,
    [HORA]            DATETIME        NULL,
    [PRESION_TR]      DECIMAL (24, 8) NULL,
    [PRESION_TP]      DECIMAL (24, 8) NULL,
    [PRESION_LDD]     DECIMAL (24, 8) NULL,
    [VELOCIDAD]       DECIMAL (24, 8) NULL,
    [TIPO_NIVEL]      VARCHAR (200)   NULL,
    [NIVEL_MEDIDO]    DECIMAL (24, 8) NULL,
    [NIVEL_CORREGIDO] DECIMAL (24, 8) NULL,
    [INC_PRES]        DECIMAL (24, 8) NULL,
    [TIEMPO_INC]      DECIMAL (24, 8) NULL,
    [TIPO_BOMBA]      VARCHAR (200)   NULL,
    [OBSERVCACIONES]  VARCHAR (200)   NULL,
    [SUMERGENCIA]     DECIMAL (24, 8) NULL,
    [TEMPGAS]         DECIMAL (24, 8) NULL,
    [PRESDISP]        DECIMAL (24, 8) NULL,
    CONSTRAINT [PK_PR_REGISTROS] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

