CREATE TABLE [dbo].[PR_TanqueBitacora] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [Accion]             VARCHAR (300)   NULL,
    [CreadoPor]          INT             NULL,
    [CreadoEl]           DATETIME        NULL,
    [TanqueId]           INT             NULL,
    [Clave]              VARCHAR (20)    NOT NULL,
    [Nombre]             VARCHAR (200)   NOT NULL,
    [Descripcion]        NVARCHAR (2000) NOT NULL,
    [Estatus]            TINYINT         NOT NULL,
    [Estacion]           INT             NULL,
    [Capacidad]          DECIMAL (24, 8) NOT NULL,
    [Producto]           INT             NOT NULL,
    [Diametro]           DECIMAL (24, 8) NOT NULL,
    [Altura]             DECIMAL (24, 8) NOT NULL,
    [Constante]          DECIMAL (24, 8) NOT NULL,
    [PctNoBombeable]     DECIMAL (8, 4)  NOT NULL,
    [VolNoBombeable]     DECIMAL (24, 8) NOT NULL,
    [PctMaximo]          DECIMAL (8, 4)  NOT NULL,
    [VolMaximo]          DECIMAL (24, 8) NOT NULL,
    [PorcentajeAgua]     FLOAT (53)      NULL,
    [ProductoAlmacenado] VARCHAR (250)   NULL,
    [IdTipoTanque]       INT             NULL,
    [MedicionManual]     BIT             NULL,
    [PuntoEntregaID]     INT             NULL,
    [Activo]             BIT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    FOREIGN KEY ([Estacion]) REFERENCES [dbo].[PR_Estacion] ([Id])
);

