CREATE TABLE [dbo].[PR_Tanque] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [Clave]              VARCHAR (20)    NOT NULL,
    [Nombre]             VARCHAR (200)   NOT NULL,
    [Descripcion]        NVARCHAR (2000) NOT NULL,
    [Estatus]            TINYINT         NOT NULL,
    [Estacion]           INT             NULL,
    [Capacidad]          DECIMAL (24, 8) CONSTRAINT [DF_Tanque_Capacidad] DEFAULT ((0)) NOT NULL,
    [Producto]           INT             NOT NULL,
    [Diametro]           DECIMAL (24, 8) CONSTRAINT [DF_Tanque_Diametro] DEFAULT ((0)) NOT NULL,
    [Altura]             DECIMAL (24, 8) CONSTRAINT [DF_Tanque_Altura] DEFAULT ((0)) NOT NULL,
    [Constante]          DECIMAL (24, 8) CONSTRAINT [DF_Tanque_Constante] DEFAULT ((0)) NOT NULL,
    [PctNoBombeable]     DECIMAL (8, 4)  CONSTRAINT [DF_Tanque_PctNoBombeable] DEFAULT ((0)) NOT NULL,
    [VolNoBombeable]     DECIMAL (24, 8) CONSTRAINT [DF_Tanque_VolNoBombeable] DEFAULT ((0)) NOT NULL,
    [PctMaximo]          DECIMAL (8, 4)  CONSTRAINT [DF_Tanque_PctMaximo] DEFAULT ((0)) NOT NULL,
    [VolMaximo]          DECIMAL (24, 8) CONSTRAINT [DF_Tanque_VolumenMaximo] DEFAULT ((0)) NOT NULL,
    [PorcentajeAgua]     FLOAT (53)      NULL,
    [timestamp]          ROWVERSION      NULL,
    [ProductoAlmacenado] VARCHAR (250)   NULL,
    [IdTipoTanque]       INT             NULL,
    [MedicionManual]     BIT             NULL,
    [PuntoEntregaID]     INT             NULL,
    CONSTRAINT [PK_PR_Tanque] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_Tanque_Estacion] FOREIGN KEY ([Estacion]) REFERENCES [dbo].[PR_Estacion] ([Id])
);

