CREATE TABLE [dbo].[produccion_ogarrio] (
    [ID del Contrato o Asignación]               NVARCHAR (255) NULL,
    [Región Fiscal]                              NVARCHAR (255) NULL,
    [Nombre del campo]                           NVARCHAR (255) NULL,
    [ID del Pozo]                                NVARCHAR (255) NULL,
    [Nombre de Pozo]                             NVARCHAR (255) NULL,
    [Fecha]                                      DATETIME       NULL,
    [Días de Producción]                         FLOAT (53)     NULL,
    [Tipo de Fluido_]                            NVARCHAR (255) NULL,
    [Producción de Petróleo Bruto]               FLOAT (53)     NULL,
    [Producción de Petróleo Neto]                FLOAT (53)     NULL,
    [Grados API]                                 FLOAT (53)     NULL,
    [% S]                                        FLOAT (53)     NULL,
    [Sal]                                        FLOAT (53)     NULL,
    [Producción de Condensado Neto]              FLOAT (53)     NULL,
    [Producción de Agua Neto]                    FLOAT (53)     NULL,
    [Producción de Gas Asociado]                 FLOAT (53)     NULL,
    [Producción de Gas No Asociado]              FLOAT (53)     NULL,
    [C1]                                         FLOAT (53)     NULL,
    [C2]                                         FLOAT (53)     NULL,
    [C3]                                         FLOAT (53)     NULL,
    [C4]                                         FLOAT (53)     NULL,
    [IC4]                                        FLOAT (53)     NULL,
    [C5]                                         FLOAT (53)     NULL,
    [IC5]                                        FLOAT (53)     NULL,
    [C6+]                                        FLOAT (53)     NULL,
    [CO2]                                        FLOAT (53)     NULL,
    [H2S]                                        FLOAT (53)     NULL,
    [N2]                                         FLOAT (53)     NULL,
    [Poder Calorífico de Gas]                    FLOAT (53)     NULL,
    [Peso Molecular de Gas]                      NVARCHAR (255) NULL,
    [Energía de Gas]                             FLOAT (53)     NULL,
    [RGA (Asig - AC)]                            FLOAT (53)     NULL,
    [Grados API (Asig - AC)]                     FLOAT (53)     NULL,
    [% S (Asig - AC)]                            FLOAT (53)     NULL,
    [Sal (Asig - AC)]                            FLOAT (53)     NULL,
    [Poder Calorífico de Petróleo (Asig - AC)]   NVARCHAR (255) NULL,
    [C1 (Asig - AC)]                             FLOAT (53)     NULL,
    [C2 (Asig - AC)]                             FLOAT (53)     NULL,
    [C3 (Asig - AC)]                             FLOAT (53)     NULL,
    [C4 (Asig - AC)]                             FLOAT (53)     NULL,
    [IC4 (Asig - AC)]                            FLOAT (53)     NULL,
    [C5+ (Asig - AC)]                            FLOAT (53)     NULL,
    [IC5 (Asig - AC)]                            FLOAT (53)     NULL,
    [C6+ (Asig - AC)]                            FLOAT (53)     NULL,
    [CO2 (Asig - AC)]                            FLOAT (53)     NULL,
    [H2S (Asig - AC)]                            FLOAT (53)     NULL,
    [N2 (Asig - AC)]                             FLOAT (53)     NULL,
    [Poder Calorífico C1 (Asig - AC)]            NVARCHAR (255) NULL,
    [Poder Calorífico C2 (Asig - AC)]            NVARCHAR (255) NULL,
    [Poder Calorífico C3 (Asig - AC)]            NVARCHAR (255) NULL,
    [Poder Calorífico C4 _(Asig - AC)]           NVARCHAR (255) NULL,
    [Poder Calorífico IC4 _(Asig - AC)]          NVARCHAR (255) NULL,
    [Poder Calorífico C5 (Asig - AC)]            NVARCHAR (255) NULL,
    [Poder Calorífico IC5 (Asig - AC)]           NVARCHAR (255) NULL,
    [Poder Calorífico C6+ (Asig - AC)]           NVARCHAR (255) NULL,
    [Poder Calorífico de Asignación (Asig - AC)] NVARCHAR (255) NULL,
    [Energía de Gas (Asig - AC)]                 NVARCHAR (255) NULL,
    [Vol C5+ (Asig - AC)]                        NVARCHAR (255) NULL,
    [Poder Calorífico de C5+ (Asig - AC)]        NVARCHAR (255) NULL,
    [Eventos]                                    NVARCHAR (255) NULL,
    [IdPozo]                                     INT            NULL
);

