CREATE TABLE [dbo].[ProvisionalCardenasMora] (
    [ID]     FLOAT (53)     NULL,
    [PA_04]  NVARCHAR (255) NULL,
    [PA_05]  NVARCHAR (255) NULL,
    [PA_06]  NVARCHAR (255) NULL,
    [PA_07]  NVARCHAR (255) NULL,
    [PA_08]  NVARCHAR (255) NULL,
    [PA_09]  NVARCHAR (255) NULL,
    [PA_10]  NVARCHAR (255) NULL,
    [PA_11]  NVARCHAR (255) NULL,
    [PA_12]  NVARCHAR (255) NULL,
    [PA_13]  NVARCHAR (255) NULL,
    [PA_14]  NVARCHAR (255) NULL,
    [PA_15]  NVARCHAR (255) NULL,
    [PA_16]  NVARCHAR (255) NULL,
    [PA_17]  MONEY          NULL,
    [PA_18]  MONEY          NULL,
    [PA_19]  MONEY          NULL,
    [PA_20]  MONEY          NULL,
    [PA_21]  MONEY          NULL,
    [PA_22]  MONEY          NULL,
    [PA_23]  MONEY          NULL,
    [PA_24]  MONEY          NULL,
    [PA_25]  MONEY          NULL,
    [PA_26]  MONEY          NULL,
    [PA_27]  MONEY          NULL,
    [PA_28]  MONEY          NULL,
    [PA_29]  MONEY          NULL,
    [PA_30]  MONEY          NULL,
    [PA_31]  MONEY          NULL,
    [PA_32]  MONEY          NULL,
    [PA_33]  MONEY          NULL,
    [PA_34]  MONEY          NULL,
    [PA_35]  MONEY          NULL,
    [PA_36]  MONEY          NULL,
    [PA_37]  MONEY          NULL,
    [PA_38]  MONEY          NULL,
    [PA_39]  MONEY          NULL,
    [PA_40]  MONEY          NULL,
    [PA_41]  MONEY          NULL,
    [PA_42]  MONEY          NULL,
    [PA_43]  MONEY          NULL,
    [PA_44]  MONEY          NULL,
    [PA_45]  MONEY          NULL,
    [PA_46]  MONEY          NULL,
    [PA_47]  MONEY          NULL,
    [PA_48]  MONEY          NULL,
    [PA_49]  MONEY          NULL,
    [PA_50]  MONEY          NULL,
    [PA_51]  MONEY          NULL,
    [PA_52]  MONEY          NULL,
    [PA_53]  MONEY          NULL,
    [PA_54]  MONEY          NULL,
    [PA_55]  MONEY          NULL,
    [PA_56]  MONEY          NULL,
    [PA_57]  MONEY          NULL,
    [PA_58]  MONEY          NULL,
    [PA_59]  MONEY          NULL,
    [PA_60]  MONEY          NULL,
    [PA_61]  MONEY          NULL,
    [PA_62]  MONEY          NULL,
    [PA_63]  MONEY          NULL,
    [PA_64]  MONEY          NULL,
    [PA_65]  MONEY          NULL,
    [PA_66]  MONEY          NULL,
    [PA_67]  MONEY          NULL,
    [PA_68]  MONEY          NULL,
    [PA_69]  MONEY          NULL,
    [PA_70]  MONEY          NULL,
    [PA_71]  MONEY          NULL,
    [PA_72]  MONEY          NULL,
    [PA_73]  MONEY          NULL,
    [PA_74]  MONEY          NULL,
    [PA_75]  MONEY          NULL,
    [PA_76]  MONEY          NULL,
    [PA_77]  MONEY          NULL,
    [PA_78]  MONEY          NULL,
    [PA_79]  MONEY          NULL,
    [PA_80]  MONEY          NULL,
    [PA_81]  MONEY          NULL,
    [PA_82]  MONEY          NULL,
    [PA_83]  MONEY          NULL,
    [PA_84]  MONEY          NULL,
    [PA_85]  MONEY          NULL,
    [PA_86]  MONEY          NULL,
    [PA_87]  MONEY          NULL,
    [PA_88]  MONEY          NULL,
    [PA_89]  MONEY          NULL,
    [PA_90]  MONEY          NULL,
    [PA_91]  MONEY          NULL,
    [PA_92]  MONEY          NULL,
    [PA_93]  MONEY          NULL,
    [PA_94]  MONEY          NULL,
    [PA_95]  MONEY          NULL,
    [PA_96]  MONEY          NULL,
    [PA_97]  MONEY          NULL,
    [PA_98]  MONEY          NULL,
    [PA_99]  MONEY          NULL,
    [PA_100] MONEY          NULL,
    [PA_101] MONEY          NULL,
    [PA_102] MONEY          NULL,
    [PA_103] MONEY          NULL,
    [PA_104] MONEY          NULL,
    [PA_105] MONEY          NULL,
    [PA_106] MONEY          NULL,
    [PA_107] MONEY          NULL,
    [PA_108] MONEY          NULL,
    [PA_109] MONEY          NULL,
    [PA_110] MONEY          NULL,
    [PA_111] MONEY          NULL,
    [PA_112] MONEY          NULL,
    [PA_113] MONEY          NULL,
    [PA_114] MONEY          NULL,
    [PA_115] MONEY          NULL,
    [PA_116] MONEY          NULL,
    [PA_117] MONEY          NULL,
    [PA_118] MONEY          NULL,
    [PA_119] MONEY          NULL,
    [PA_120] MONEY          NULL,
    [PA_121] MONEY          NULL,
    [PA_122] MONEY          NULL,
    [PA_123] MONEY          NULL,
    [PA_124] MONEY          NULL,
    [PA_125] MONEY          NULL,
    [PA_126] MONEY          NULL,
    [PA_127] MONEY          NULL,
    [PA_128] MONEY          NULL,
    [PA_129] MONEY          NULL,
    [PA_130] MONEY          NULL,
    [PA_131] MONEY          NULL,
    [PA_132] MONEY          NULL,
    [PA_133] MONEY          NULL,
    [PA_134] MONEY          NULL,
    [PA_135] MONEY          NULL,
    [PA_136] MONEY          NULL
);

