CREATE TABLE [dbo].[PV_CuentaBancaria] (
    [DatoBancarioID] INT            IDENTITY (1, 1) NOT NULL,
    [BancoID]        INT            NULL,
    [Titular]        VARCHAR (MAX)  NULL,
    [Sucursal]       VARCHAR (MAX)  NULL,
    [NumeroCuenta]   VARCHAR (MAX)  NULL,
    [CuentaClave]    VARCHAR (MAX)  NULL,
    [NumeroTarjeta]  NVARCHAR (MAX) NULL,
    [TipoMonedaID]   INT            NULL,
    [IdProveedor]    INT            NULL,
    [Predeterminado] BIT            NULL,
    [IdTipoCuenta]   INT            NULL,
    [TipoCuentaTemp] NVARCHAR (50)  NULL,
    [Codigo]         INT            NULL,
    [claveBanco]     NVARCHAR (50)  NULL,
    [RFC]            NVARCHAR (300) NULL,
    [IdContratista]  INT            NULL,
    [Activa]         BIT            CONSTRAINT [DF_PV_CuentaBancaria_Activa] DEFAULT ((1)) NULL,
    [CreadoPor]      INT            NULL,
    [CreadoEn]       DATETIME       NULL,
    [Eliminada]      BIT            NULL,
    [Alias]          NVARCHAR (MAX) NULL,
    [IdCuenta]       INT            NULL,
    CONSTRAINT [PK_DatosBancarios] PRIMARY KEY CLUSTERED ([DatoBancarioID] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_DatosBancarios_TipoMoneda] FOREIGN KEY ([TipoMonedaID]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda]),
    CONSTRAINT [FK_PV_CuentaBancaria_PV_MetodoPago] FOREIGN KEY ([IdTipoCuenta]) REFERENCES [dbo].[PV_MetodoPago] ([idMetodoPago]),
    CONSTRAINT [FK_PV_CuentaBancaria_PV_Subcontratista] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista])
);

