CREATE TABLE [dbo].[PV_GastoDomiciliado] (
    [idDomiciliado]        INT           IDENTITY (1, 1) NOT NULL,
    [Servicio]             VARCHAR (MAX) NOT NULL,
    [Proveedor]            VARCHAR (MAX) NULL,
    [Sitio]                VARCHAR (MAX) NULL,
    [IdRecurrencia]        INT           NULL,
    [DiaCobro]             VARCHAR (MAX) NULL,
    [IdMetodoPreferente]   INT           NULL,
    [Domiciliacion]        BIT           NULL,
    [MetodoAlternativo]    VARCHAR (50)  NULL,
    [IdNacionalidad]       INT           NULL,
    [ComprobanteFiscal]    BIT           NULL,
    [Importe]              MONEY         NULL,
    [IdMoneda]             INT           NULL,
    [idCriticidad]         INT           NULL,
    [ClasificacionInterna] VARCHAR (MAX) NULL,
    [FechaContratacion]    DATETIME      NULL,
    [ProximoPago]          DATETIME      NULL,
    CONSTRAINT [PK_PV_GastoDomiciliado] PRIMARY KEY CLUSTERED ([idDomiciliado] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_PV_GastoDomiciliado_PV_Criticidad] FOREIGN KEY ([idCriticidad]) REFERENCES [dbo].[PV_Criticidad] ([idCriticidad]),
    CONSTRAINT [FK_PV_GastoDomiciliado_PV_MetodoPago] FOREIGN KEY ([IdMetodoPreferente]) REFERENCES [dbo].[PV_MetodoPago] ([idMetodoPago]),
    CONSTRAINT [FK_PV_GastoDomiciliado_PV_Nacionalidad] FOREIGN KEY ([IdNacionalidad]) REFERENCES [dbo].[PV_Nacionalidad] ([NacionalidadID]),
    CONSTRAINT [FK_PV_GastoDomiciliado_PV_Recurrencia] FOREIGN KEY ([IdRecurrencia]) REFERENCES [dbo].[PV_Recurrencia] ([idRecurrecia]),
    CONSTRAINT [FK_PV_GastoDomiciliado_PV_TipoMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda])
);

