CREATE TABLE [dbo].[RESPALDOACTIVOSELIMINADOS] (
    [IdEntregable]                     INT            IDENTITY (10000, 1) NOT NULL,
    [DocumentoEntregable]              VARCHAR (8000) NULL,
    [IdMarcoLegal]                     INT            NULL,
    [TituloAnexo]                      VARCHAR (8000) NULL,
    [Capitulo]                         VARCHAR (8000) NULL,
    [Descripcion]                      VARCHAR (8000) NULL,
    [Seccion]                          VARCHAR (8000) NULL,
    [Articulo]                         VARCHAR (8000) NULL,
    [Inciso]                           VARCHAR (8000) NULL,
    [Apartado]                         VARCHAR (8000) NULL,
    [Observaciones]                    VARCHAR (8000) NULL,
    [ArchivoNormatividad]              VARCHAR (8000) NULL,
    [ArchivoEntregable]                VARCHAR (8000) NULL,
    [IdRegulador]                      INT            NULL,
    [IdEtapa]                          INT            NULL,
    [IdReceptorEntregable]             INT            NULL,
    [IdResponsableGenerador]           INT            NULL,
    [IdFrecuenciaEntregable]           INT            NULL,
    [TiempoEntrega]                    VARCHAR (8000) NULL,
    [IdTiempoRespuesta]                INT            NULL,
    [FechaPublicacion]                 DATETIME       NULL,
    [FechaModificacion]                DATETIME       NULL,
    [CreadoPor]                        INT            NULL,
    [CreadoEn]                         DATETIME       NULL,
    [ModificadoPor]                    INT            NULL,
    [ModificadoEn]                     DATETIME       NULL,
    [IsActivo]                         BIT            NULL,
    [IsEliminado]                      BIT            NULL,
    [Consecutivo]                      VARCHAR (8000) NULL,
    [TCLicencia]                       BIT            NULL,
    [TCProducionCompartida]            BIT            NULL,
    [TCLicenciaFarmOuts]               BIT            NULL,
    [TCProducionCompartidaFarmOuts]    BIT            NULL,
    [UGTerrestre]                      BIT            NULL,
    [UGCostaFuera]                     BIT            NULL,
    [REReguladores]                    BIT            NULL,
    [REOperadores]                     BIT            NULL,
    [APAdministracionContratos]        BIT            NULL,
    [APPozoAlivio]                     BIT            NULL,
    [APCierreDesmantelamientoAbandono] BIT            NULL,
    [APPerforacion]                    BIT            NULL,
    [APTerminacion]                    BIT            NULL,
    [APActProduccion]                  BIT            NULL,
    [APEstimulacion]                   BIT            NULL,
    [APPruebaProduccion]               BIT            NULL,
    [APConstruccionCamino]             BIT            NULL,
    [APConstruccionLocalizacion]       BIT            NULL,
    [APRehabilitacionCamino]           BIT            NULL,
    [APRehabilitacionLocalizacion]     BIT            NULL,
    [APTomaInformacionSismica]         BIT            NULL,
    [APCorteNucleos]                   BIT            NULL,
    [APConstruccionLineaDescarga]      BIT            NULL,
    [APSistemaArtificialProduccion]    BIT            NULL,
    [APMedicionPozos]                  BIT            NULL,
    [APTomaInformacionPozo]            BIT            NULL,
    [APReparacionMayor]                BIT            NULL,
    [APReparacionMenor]                BIT            NULL,
    [APTransporteHidrocarburos]        BIT            NULL,
    [APQuemaGas]                       BIT            NULL,
    [BitInterno]                       BIT            NULL,
    [EsDeProceso]                      BIT            NULL,
    [Formato]                          VARCHAR (500)  NULL,
    [IdClasificacion]                  INT            NULL,
    [RequiereRespuesta]                BIT            NULL,
    [Actividad]                        VARCHAR (500)  NULL,
    [Proceso]                          VARCHAR (500)  NULL,
    [DeliverableName]                  VARCHAR (8000) NULL,
    [BitJOA]                           BIT            NULL,
    [BitMostrarMensaje]                BIT            NULL,
    [BitAwareness]                     BIT            NULL
);

