CREATE TABLE [dbo].[RESPALDOCONFIGBP_2020] (
    [IDCONTRATO]           INT NULL,
    [IDENTREGABLE]         INT NULL,
    [IDCONTRATOENTREGABLE] INT NOT NULL,
    [ACTIVIDADIDELAB]      INT NOT NULL,
    [IDUSUARIOELAB]        INT NOT NULL,
    [ACTIVIDADIDREV]       INT NULL,
    [IDUSUARIOREV]         INT NULL,
    [ACTIVIDADIDAPROB]     INT NULL,
    [IDUSUARIOAPROB]       INT NULL,
    [ACTIVIDADIDACUSE]     INT NULL,
    [IDUSUARIOACUSE]       INT NULL
);

