CREATE TABLE [dbo].[RespaldoRegistro] (
    [IdRegistro]                      INT             NULL,
    [IdPrograma]                      INT             NULL,
    [IdFactura]                       INT             NULL,
    [MontoRegistro]                   DECIMAL (18, 4) NULL,
    [InicioEjecucion]                 DATE            NULL,
    [FinEjecucion]                    DATE            NULL,
    [Comentarios]                     NVARCHAR (MAX)  NULL,
    [MesPresentacion]                 DATE            NULL,
    [IdEstado]                        INT             NULL,
    [IdUsuarioCreadoPor]              INT             NULL,
    [IdUsuarioModPor]                 INT             NULL,
    [FecMovto]                        DATETIME        NULL,
    [IdInstalacion]                   INT             NULL,
    [CreadoPor]                       INT             NULL,
    [Fila]                            INT             NULL,
    [IdPedimentoComprobante]          INT             NULL,
    [CvTipoDocFacturacion]            INT             NULL,
    [IdCatalogoCuentasSH]             INT             NULL,
    [Poliza]                          NVARCHAR (MAX)  NULL,
    [IsEditable]                      BIT             NULL,
    [CostosAtribuiblesAdministracion] BIT             NULL,
    [EstadoDePresentacion]            BIT             NULL,
    [MesCertificadoCIEP]              DATE            NULL,
    [IdGastoRubro]                    TINYINT         NULL,
    [PCN]                             FLOAT (53)      NULL,
    [Importado]                       BIT             NULL,
    [BitPCNP]                         BIT             NULL,
    [IdCBSISH]                        INT             NULL,
    [IdAceptacionPedidoDetalle]       INT             NULL,
    [MesGasto]                        DATE            NULL,
    [ModificadoEn]                    DATE            NULL,
    [CapexOpexEdicion]                BIT             NULL
);

