CREATE TABLE [dbo].[RML_FMP_50_M] (
    [ID del contratista asignado por el SIPAC (RF_00)]                 VARCHAR (255)  NULL,
    [ID registro fiduciario del contrato (RI_00)]                      VARCHAR (255)  NULL,
    [ID del contrato asignado por CNH (RF01_01)]                       VARCHAR (255)  NULL,
    [Mes de reporte (RM50_00)]                                         VARCHAR (255)  NULL,
    [Año de reporte (RM50_01)]                                         VARCHAR (255)  NULL,
    [Producción: Volumen contractual de petróleo (RM50_02)]            VARCHAR (255)  NULL,
    [Volumen contractual: producción de metano de gas natural asociad] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de etano de gas natural asociado] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de propano de gas natural asocia] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de butano de gas natural asociad] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de metano de gas natural no asoc] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de etano de gas natural no asoci] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de propano de gas natural no aso] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de butano de gas natural no asoc] VARCHAR (255)  NULL,
    [Producción: Volumen contractual de condensados (RM50_11)]         VARCHAR (255)  NULL,
    [Precio contractual: petróleo (RM50_12)]                           VARCHAR (255)  NULL,
    [Precio contractual: metano (RM50_13)]                             VARCHAR (255)  NULL,
    [Precio contractual: etano (RM50_14)]                              VARCHAR (255)  NULL,
    [Precio contractual: propano (RM50_15)]                            VARCHAR (255)  NULL,
    [Precio contractual: butano (RM50_16)]                             VARCHAR (255)  NULL,
    [Precio contractual: condensados (RM50_17)]                        VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contrac] VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contra1] VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contra2] VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contra3] VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contra4] VARCHAR (255)  NULL,
    [Tipo de precio que aplicó en la determinación del precio contra5] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?: ] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:1] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:2] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:3] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:4] VARCHAR (255)  NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:5] VARCHAR (255)  NULL,
    [Valor contractual: petróleo (RM50_30)]                            VARCHAR (255)  NULL,
    [Valor contractual: metano de gas natural asociado (RM50_31)]      VARCHAR (255)  NULL,
    [Valor contractual: etano de gas natural asociado (RM50_32)]       VARCHAR (255)  NULL,
    [Valor contractual: propano de gas natural asociado (RM50_33)]     VARCHAR (255)  NULL,
    [Valor contractual: butano de gas natural asociado (RM50_34)]      VARCHAR (255)  NULL,
    [Valor contractual: metano de gas natural no asociado (RM50_35)]   VARCHAR (255)  NULL,
    [Valor contractual: etano de gas natural no asociado (RM50_36)]    VARCHAR (255)  NULL,
    [Valor contractual: propano de gas natural no asociado (RM50_37)]  VARCHAR (255)  NULL,
    [Valor contractual: butano de gas natural no asociado (RM50_38)]   VARCHAR (255)  NULL,
    [Valor contractual: condensados (RM50_39)]                         VARCHAR (255)  NULL,
    [Total del valor contractual de los hidrocarburos (RM50_40)]       VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: petróleo (RM50_4] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas na] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas nat] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas n] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas na] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas n1] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas na1] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas 1] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas n1] VARCHAR (255)  NULL,
    [Tasa aplicable para el pago de la Regalía Base: condensados (RM5] VARCHAR (255)  NULL,
    [¿Se aplicó el mecanismo de ajuste? (RM50_51)]                     VARCHAR (255)  NULL,
    [Factor de ajuste para la determinación del monto de la contrapre] VARCHAR (255)  NULL,
    [Factor de ajuste para la determinación del monto de la contrapr1] VARCHAR (255)  NULL,
    [Tasa aplicable al valor contractual del petróleo y condensados e] VARCHAR (255)  NULL,
    [Tasa aplicable al valor contractual del gas natural en el period] VARCHAR (255)  NULL,
    [Estado (activo)]                                                  VARCHAR (1500) NULL,
    [Fecha registro (fechaRegistro)]                                   VARCHAR (1500) NULL
);

