CREATE TABLE [dbo].[ROCHistory] (
    [Fecha]                 DATETIME       NULL,
    [F2]                    NVARCHAR (255) NULL,
    [F3]                    NVARCHAR (255) NULL,
    [ID Contrato]           NVARCHAR (255) NULL,
    [Campo]                 NVARCHAR (255) NULL,
    [Petróleo (bl)]         FLOAT (53)     NULL,
    [°API]                  FLOAT (53)     NULL,
    [%S]                    FLOAT (53)     NULL,
    [Gas (mmpc)]            FLOAT (53)     NULL,
    [C1 (mmbtu)]            FLOAT (53)     NULL,
    [C2 (mmbtu)]            FLOAT (53)     NULL,
    [C3 (mmbtu)]            FLOAT (53)     NULL,
    [C4 (mmbtu)]            FLOAT (53)     NULL,
    [Condensado _Eq# (bl)]  FLOAT (53)     NULL,
    [Condensado _Liq# (bl)] FLOAT (53)     NULL,
    [C1]                    FLOAT (53)     NULL,
    [C2]                    FLOAT (53)     NULL,
    [C3]                    FLOAT (53)     NULL,
    [C4]                    FLOAT (53)     NULL,
    [IC4]                   FLOAT (53)     NULL,
    [C5]                    FLOAT (53)     NULL,
    [IC5]                   FLOAT (53)     NULL,
    [C6+]                   FLOAT (53)     NULL,
    [xml]                   NVARCHAR (255) NULL,
    [Facturs Gas]           FLOAT (53)     NULL,
    [Factura Crudo]         FLOAT (53)     NULL
);

