CREATE TABLE [dbo].[ROCImport] (
    [Fecha]                  DATETIME       NULL,
    [F2]                     NVARCHAR (255) NULL,
    [ID Contrato]            NVARCHAR (255) NULL,
    [Campo]                  NVARCHAR (255) NULL,
    [Petróleo (bl)]          FLOAT (53)     NULL,
    [°API]                   FLOAT (53)     NULL,
    [%S]                     FLOAT (53)     NULL,
    [Gas (mmpc)]             FLOAT (53)     NULL,
    [C1 (mmbtu)]             FLOAT (53)     NULL,
    [C2 (mmbtu)]             FLOAT (53)     NULL,
    [C3 (mmbtu)]             FLOAT (53)     NULL,
    [C4 (mmbtu)]             FLOAT (53)     NULL,
    [Condensado _Eq# (bl)]   FLOAT (53)     NULL,
    [Condensado _Liq# (bl)]  FLOAT (53)     NULL,
    [C1]                     FLOAT (53)     NULL,
    [C2]                     FLOAT (53)     NULL,
    [C3]                     FLOAT (53)     NULL,
    [C4]                     FLOAT (53)     NULL,
    [IC4]                    FLOAT (53)     NULL,
    [C5]                     FLOAT (53)     NULL,
    [IC5]                    FLOAT (53)     NULL,
    [C6+]                    FLOAT (53)     NULL,
    [xml]                    NVARCHAR (255) NULL,
    [Factura Gas]            FLOAT (53)     NULL,
    [Factura Crudo]          FLOAT (53)     NULL,
    [F26]                    NVARCHAR (255) NULL,
    [Factura Gas - Ligar]    FLOAT (53)     NULL,
    [Factura Crudo - Ligar]  FLOAT (53)     NULL,
    [Reglas Mercado]         NVARCHAR (255) NULL,
    [Ajuste Formula]         NVARCHAR (255) NULL,
    [F31]                    NVARCHAR (255) NULL,
    [C11]                    FLOAT (53)     NULL,
    [C21]                    FLOAT (53)     NULL,
    [C31]                    FLOAT (53)     NULL,
    [C41]                    FLOAT (53)     NULL,
    [Condensado]             FLOAT (53)     NULL,
    [Crudo]                  FLOAT (53)     NULL,
    [F38]                    NVARCHAR (255) NULL,
    [Petróleo (bl)1]         FLOAT (53)     NULL,
    [Gas (mmpc)1]            FLOAT (53)     NULL,
    [C1 (mmbtu)1]            FLOAT (53)     NULL,
    [C2 (mmbtu)1]            FLOAT (53)     NULL,
    [C3 (mmbtu)1]            FLOAT (53)     NULL,
    [C4 (mmbtu)1]            FLOAT (53)     NULL,
    [Condensado _Eq# (bl)1]  FLOAT (53)     NULL,
    [Condensado _Liq# (bl)1] FLOAT (53)     NULL,
    [F47]                    NVARCHAR (255) NULL,
    [Factura]                NVARCHAR (255) NULL,
    [Petróleo (bl)2]         NVARCHAR (255) NULL,
    [Gas (mmpc)2]            NVARCHAR (255) NULL,
    [C1 (mmbtu)2]            NVARCHAR (255) NULL,
    [C2 (mmbtu)2]            NVARCHAR (255) NULL,
    [C3 (mmbtu)2]            NVARCHAR (255) NULL,
    [C4 (mmbtu)2]            NVARCHAR (255) NULL,
    [Condensado _Eq# (bl)2]  NVARCHAR (255) NULL,
    [Condensado _Liq# (bl)2] NVARCHAR (255) NULL,
    [F57]                    NVARCHAR (255) NULL,
    [Factura1]               NVARCHAR (255) NULL,
    [Petróleo (bl)3]         NVARCHAR (255) NULL,
    [Gas (mmpc)3]            NVARCHAR (255) NULL,
    [C1 (mmbtu)3]            NVARCHAR (255) NULL,
    [C2 (mmbtu)3]            NVARCHAR (255) NULL,
    [C3 (mmbtu)3]            NVARCHAR (255) NULL,
    [C4 (mmbtu)3]            NVARCHAR (255) NULL,
    [Condensado _Eq# (bl)3]  NVARCHAR (255) NULL,
    [Condensado _Liq# (bl)3] NVARCHAR (255) NULL
);

