CREATE TABLE [dbo].[SC_SubContrato] (
    [IdSubContrato]     INT           NOT NULL,
    [IdSubContratista]  INT           NOT NULL,
    [IdContratista]     INT           NOT NULL,
    [NumeroSubContrato] VARCHAR (MAX) NOT NULL,
    [CreadoPor]         INT           NOT NULL,
    [CreadoEl]          DATETIME      NOT NULL,
    [ModificadoPor]     INT           NULL,
    [ModificadoEl]      DATETIME      NULL,
    [IsActivo]          BIT           NULL,
    [IsEliminado]       BIT           NULL,
    [Objeto]            VARCHAR (300) NULL,
    [IdPedido]          INT           NULL,
    [PrefijoOT]         VARCHAR (13)  NULL,
    [IdContrato]        INT           NULL,
    [IdCentroCosto]     INT           NULL,
    [IdMoneda]          INT           NULL,
    [IdTipoPedido]      INT           NULL,
    [FechaInicio]       DATETIME      NULL,
    [FechaFin]          DATETIME      NULL,
    [DiasCredito]       INT           NULL,
    CONSTRAINT [PK_SC_SubContratos] PRIMARY KEY CLUSTERED ([IdSubContrato] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK__SC_SubCon__IdCon__22227BB6] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK_SC_SubContratos_CO_Contratista] FOREIGN KEY ([IdContratista]) REFERENCES [dbo].[CO_Contratista] ([IdContratista]),
    CONSTRAINT [FK_SC_SubContratos_PV_Subcontratista] FOREIGN KEY ([IdSubContratista]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista])
);

