CREATE TABLE [dbo].[SCOC_CalculoDiario_Petroleo] (
    [IdContrato]      INT        NOT NULL,
    [MesReporte]      DATE       NOT NULL,
    [FechaReporte]    DATE       NOT NULL,
    [FechaEntrega]    DATE       NOT NULL,
    [Dia]             INT        NOT NULL,
    [CampoID]         INT        NOT NULL,
    [M3_20Grados]     FLOAT (53) NULL,
    [BL_20C]          FLOAT (53) NULL,
    [M3_60F]          FLOAT (53) NULL,
    [BL_60F]          FLOAT (53) NULL,
    [PorcDistEdo]     FLOAT (53) NULL,
    [PorcDistContra]  FLOAT (53) NULL,
    [Compensacion]    FLOAT (53) NULL,
    [DistEdo]         FLOAT (53) NULL,
    [DistContratista] FLOAT (53) NULL,
    [Aplicada]        FLOAT (53) NULL,
    [Pendiente]       FLOAT (53) NULL,
    [CreadoPor]       INT        NULL,
    [CreadoEn]        DATETIME   NULL,
    [ModificadoPor]   INT        NULL,
    [ModificadoEn]    DATETIME   NULL,
    CONSTRAINT [PK_SCOC_CalculoDiario_Petroleo] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [MesReporte] ASC, [Dia] ASC, [CampoID] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_CalculoDiario_Petroleo_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Petroleo_AP_Usuario2] FOREIGN KEY ([ModificadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Petroleo_Campo] FOREIGN KEY ([CampoID]) REFERENCES [dbo].[SCOC_Campo] ([CampoID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Petroleo_CO_CONTRATO] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

