CREATE TABLE [dbo].[SCOC_Contrato] (
    [IdContrato]                    INT            NOT NULL,
    [SubdireccionProduccion]        VARCHAR (250)  NULL,
    [ActivoIntegral]                VARCHAR (250)  NULL,
    [PetroleoEntregadoA]            VARCHAR (250)  NULL,
    [DireccionPetroleoEntregadoA]   VARCHAR (250)  NULL,
    [PetroleoEntregadoEn]           VARCHAR (250)  NULL,
    [PetroleoTransporte]            VARCHAR (250)  NULL,
    [GasEntregadoA]                 VARCHAR (250)  NULL,
    [DireccionGasEntregadoA]        VARCHAR (250)  NULL,
    [GasEntregadoEn]                VARCHAR (250)  NULL,
    [GasTransporte]                 VARCHAR (250)  NULL,
    [CondensadoEntregadoA]          VARCHAR (250)  NULL,
    [DireccionCondensadoEntregadoA] VARCHAR (250)  NULL,
    [CondensadoEntregadoEn]         VARCHAR (250)  NULL,
    [CondensadoTransporte]          VARCHAR (250)  NULL,
    [InicialesSocio]                VARCHAR (50)   NULL,
    [DescripcionSocio]              VARCHAR (250)  NULL,
    [PuntosLecturaCroma]            VARCHAR (250)  NULL,
    [AplicaFactorCompresibilidad]   BIT            NULL,
    [Balance]                       BIT            NULL,
    [Condensable]                   BIT            NULL,
    [CreadoPor]                     INT            NULL,
    [CreadoEn]                      DATETIME       NULL,
    [ModificadoPor]                 INT            NULL,
    [ModificadoEn]                  DATETIME       NULL,
    [BitPetroleo]                   BIT            NULL,
    [BitGas]                        BIT            NULL,
    [VolumenGasEntregadoPor]        NVARCHAR (250) NULL,
    [VolumenPetroleoEntregadoPor]   NVARCHAR (250) NULL,
    [ApruebaRepPEP]                 BIT            NULL,
    CONSTRAINT [PK_SCOC_Contrato] PRIMARY KEY CLUSTERED ([IdContrato] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_Contrato_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_Contrato_AP_Usuario2] FOREIGN KEY ([ModificadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_Contrato_CO_CONTRATO] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

