CREATE TABLE [dbo].[SCOC_EnvioNotificacion] (
    [IdContrato]              INT            NOT NULL,
    [MesReporte]              DATE           NOT NULL,
    [EnviadoContratista]      BIT            NULL,
    [FechaEnvioContratista]   DATE           NULL,
    [AprobadoSCOC]            BIT            NULL,
    [FechaAprobacion]         DATE           NULL,
    [IdUsuarioAprobadoSCOC]   INT            NULL,
    [Comentarios]             NVARCHAR (MAX) NULL,
    [CreadoPor]               INT            NULL,
    [CreadoEn]                DATETIME       NULL,
    [ModificadoPor]           INT            NULL,
    [ModificadoEn]            DATETIME       NULL,
    [FechaAprobacionRepPEP]   DATE           NULL,
    [AprobadoRepPEP]          BIT            NULL,
    [IdUsuarioAprobadoRepPEP] INT            NULL,
    [idEstatus]               INT            NULL,
    CONSTRAINT [PK_SCOC_EnvioNotificacion] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [MesReporte] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_EnvioNotificacion_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_EnvioNotificacion_AP_Usuario2] FOREIGN KEY ([ModificadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_EnvioNotificacion_CO_CONTRATO] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [fkIdUsuarioAprobadoRepPEP_Usuario] FOREIGN KEY ([IdUsuarioAprobadoRepPEP]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [SCOC_Estatus_SCOC_EnvioNotificacion] FOREIGN KEY ([idEstatus]) REFERENCES [dbo].[SCOC_Estatus] ([idEstatus])
);

