CREATE TABLE [dbo].[SCOC_ValoresEstandaresGPA_2145] (
    [IdComponente]     INT        NOT NULL,
    [IdFecIniVigencia] DATETIME   NOT NULL,
    [FecFinVigencia]   DATETIME   NOT NULL,
    [Metano_C1]        FLOAT (53) NULL,
    [Etano_C2]         FLOAT (53) NULL,
    [Propano_C3]       FLOAT (53) NULL,
    [Butano_iC4]       FLOAT (53) NULL,
    [Butano_nC4]       FLOAT (53) NULL,
    [Pentano_iC5]      FLOAT (53) NULL,
    [Pentano_nC5]      FLOAT (53) NULL,
    [Hexano_C6]        FLOAT (53) NULL,
    [Heptano_C7]       FLOAT (53) NULL,
    [Octano_C8]        FLOAT (53) NULL,
    [Nonano_C9]        FLOAT (53) NULL,
    [Decano_C10]       FLOAT (53) NULL,
    [Etileno]          FLOAT (53) NULL,
    [Propileno]        FLOAT (53) NULL,
    [CO2]              FLOAT (53) NULL,
    [H2S]              FLOAT (53) NULL,
    [Nitrogeno_N2]     FLOAT (53) NULL,
    [Oxigeno_O2]       FLOAT (53) NULL,
    [Helio]            FLOAT (53) NULL,
    [Aire]             FLOAT (53) NULL,
    [Agua]             FLOAT (53) NULL,
    [CreadoPor]        INT        NULL,
    [CreadoEn]         DATETIME   NULL,
    CONSTRAINT [PK_SCOC_ValoresEstandaresGPA_2145] PRIMARY KEY CLUSTERED ([IdComponente] ASC, [IdFecIniVigencia] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_ValoresEstandaresGPA_2145_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_ValoresEstandaresGPA_2145_SCOC_ComponentesGPA_2145] FOREIGN KEY ([IdComponente]) REFERENCES [dbo].[SCOC_ComponentesGPA_2145] ([IdComponente])
);

