CREATE TABLE [dbo].[SCOC_ReporteDiarioGas] (
    [IdContrato]            INT        NOT NULL,
    [MesReporte]            DATE       NOT NULL,
    [FechaReporte]          DATE       NOT NULL,
    [FechaEntrega]          DATE       NOT NULL,
    [Dia]                   INT        NOT NULL,
    [M3_20Grados]           FLOAT (53) NULL,
    [MMPC_NoAprov_20Grados] FLOAT (53) NULL,
    [H2S]                   FLOAT (53) NULL,
    [CO2]                   FLOAT (53) NULL,
    [N2]                    FLOAT (53) NULL,
    [C1]                    FLOAT (53) NULL,
    [C2]                    FLOAT (53) NULL,
    [C3]                    FLOAT (53) NULL,
    [IC4]                   FLOAT (53) NULL,
    [NC4]                   FLOAT (53) NULL,
    [IC5]                   FLOAT (53) NULL,
    [NC5]                   FLOAT (53) NULL,
    [C6]                    FLOAT (53) NULL,
    [PM]                    FLOAT (53) NULL,
    [PoderCalBTU]           FLOAT (53) NULL,
    [DensidadRelativa]      FLOAT (53) NULL,
    [FechaCromatografia]    DATE       NOT NULL,
    [CreadoPor]             INT        NULL,
    [CreadoEn]              DATETIME   NULL,
    [ModificadoPor]         INT        NULL,
    [ModificadoEn]          DATETIME   NULL,
    [MMPC20BN]              FLOAT (53) NULL,
    [C7]                    FLOAT (53) NULL,
    [C8]                    FLOAT (53) NULL,
    [C9]                    FLOAT (53) NULL,
    [C10]                   FLOAT (53) NULL,
    [IdUnidadMedida]        INT        NULL,
    [Volumen15Grados]       FLOAT (53) NULL,
    [Temperatura]           FLOAT (53) NULL,
    [CampoID]               INT        DEFAULT ((1)) NOT NULL,
    [CombustibleMTC]        FLOAT (53) NULL,
    [CombustibleEC]         FLOAT (53) NULL,
    [CombustibleCAB]        FLOAT (53) NULL,
    CONSTRAINT [PK_SCOC_ReporteDiarioGas] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [MesReporte] ASC, [Dia] ASC, [CampoID] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_ReporteDiarioGas_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_ReporteDiarioGas_AP_Usuario2] FOREIGN KEY ([ModificadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_ReporteDiarioGas_Campo] FOREIGN KEY ([CampoID]) REFERENCES [dbo].[SCOC_Campo] ([CampoID]),
    CONSTRAINT [FK_SCOC_ReporteDiarioGas_CO_CONTRATO] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [fkIdUnidadMedidaDiarioGas] FOREIGN KEY ([IdUnidadMedida]) REFERENCES [dbo].[CO_UnidadMedida] ([idUnidadMedida])
);

