CREATE TABLE [dbo].[SCOC_CalculoDiario_Gas] (
    [IdContrato]            INT        NOT NULL,
    [MesReporte]            DATE       NOT NULL,
    [FechaReporte]          DATE       NOT NULL,
    [FechaEntrega]          DATE       NOT NULL,
    [Dia]                   INT        NOT NULL,
    [CampoID]               INT        NOT NULL,
    [M3_20Grados]           FLOAT (53) NULL,
    [MMPC_NoAprov_20Grados] FLOAT (53) NULL,
    [BarrilesC5_Equiv]      FLOAT (53) NULL,
    [M3_20C_GasNoAprov]     FLOAT (53) NULL,
    [M3_20C_GasEntregado]   FLOAT (53) NULL,
    [MMPC_20C_GasEntregado] FLOAT (53) NULL,
    [MMPC_60F_Gas]          FLOAT (53) NULL,
    [MPC_60_F]              FLOAT (53) NULL,
    [MPC_20_C]              FLOAT (53) NULL,
    [M3_60_F]               FLOAT (53) NULL,
    [MMBTU_60F]             FLOAT (53) NULL,
    [MMBTU_C1]              FLOAT (53) NULL,
    [MMBTU_C2]              FLOAT (53) NULL,
    [MMBTU_C3]              FLOAT (53) NULL,
    [MMBTU_C4]              FLOAT (53) NULL,
    [MMBTU_C5]              FLOAT (53) NULL,
    [PorcDistEdo]           FLOAT (53) NULL,
    [PorcDistContra]        FLOAT (53) NULL,
    [Compensacion_C1]       FLOAT (53) NULL,
    [Compensacion_C2]       FLOAT (53) NULL,
    [Compensacion_C3]       FLOAT (53) NULL,
    [Compensacion_C4]       FLOAT (53) NULL,
    [Compensacion_C5]       FLOAT (53) NULL,
    [Compensacion_Barriles] FLOAT (53) NULL,
    [DistEdo_C1]            FLOAT (53) NULL,
    [DistEdo_C2]            FLOAT (53) NULL,
    [DistEdo_C3]            FLOAT (53) NULL,
    [DistEdo_C4]            FLOAT (53) NULL,
    [DistEdo_C5]            FLOAT (53) NULL,
    [DistBarriles]          FLOAT (53) NULL,
    [DistContra_C1]         FLOAT (53) NULL,
    [DistContra_C2]         FLOAT (53) NULL,
    [DistContra_C3]         FLOAT (53) NULL,
    [DistContra_C4]         FLOAT (53) NULL,
    [DistContra_C5]         FLOAT (53) NULL,
    [DistContra_Barriles]   FLOAT (53) NULL,
    [Aplicada_C1]           FLOAT (53) NULL,
    [Aplicada_C2]           FLOAT (53) NULL,
    [Aplicada_C3]           FLOAT (53) NULL,
    [Aplicada_C4]           FLOAT (53) NULL,
    [Aplicada_C5]           FLOAT (53) NULL,
    [Aplicada_Barriles]     FLOAT (53) NULL,
    [Pendiente_C1]          FLOAT (53) NULL,
    [Pendiente_C2]          FLOAT (53) NULL,
    [Pendiente_C3]          FLOAT (53) NULL,
    [Pendiente_C4]          FLOAT (53) NULL,
    [Pendiente_C5]          FLOAT (53) NULL,
    [Pendiente_Barriles]    FLOAT (53) NULL,
    [TotalMMBTU_Edo]        FLOAT (53) NULL,
    [TotalMMBTUEdo_C1C4]    FLOAT (53) NULL,
    [TotalMMBTUEdo_C5]      FLOAT (53) NULL,
    [Edo_MMPC_C5]           FLOAT (53) NULL,
    [Edo_MMPC_C1C4]         FLOAT (53) NULL,
    [TotalMMBTU_Contra]     FLOAT (53) NULL,
    [TotalMMBTUContra_C1C4] FLOAT (53) NULL,
    [TotalMMBTUContra_C5]   FLOAT (53) NULL,
    [Contra_MMPC_C5]        FLOAT (53) NULL,
    [Contra_MMPC_C1C4]      FLOAT (53) NULL,
    [FactorCompresibilidad] FLOAT (53) NULL,
    [CreadoPor]             INT        NULL,
    [CreadoEn]              DATETIME   NULL,
    [ModificadoPor]         INT        NULL,
    [ModificadoEn]          DATETIME   NULL,
    CONSTRAINT [PK_SCOC_CalculoDiario_Gas] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [MesReporte] ASC, [Dia] ASC, [CampoID] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SCOC_CalculoDiario_Gas_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Gas_AP_Usuario2] FOREIGN KEY ([ModificadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Gas_Campo] FOREIGN KEY ([CampoID]) REFERENCES [dbo].[SCOC_Campo] ([CampoID]),
    CONSTRAINT [FK_SCOC_CalculoDiario_Gas_CO_CONTRATO] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

