CREATE TABLE [dbo].[SIPAC_RM_FMP_54_M] (
    [ID del contratista asignado por el SIPAC (RF_00)]                 NVARCHAR (255) NULL,
    [ID registro fiduciario del contrato (RI_00)]                      NVARCHAR (255) NULL,
    [ID del contrato asignado por CNH (RF01_01)]                       NVARCHAR (255) NULL,
    [Mes de reporte (RM54_00)]                                         INT            NULL,
    [Año de reporte (RM54_01)]                                         INT            NULL,
    [Producción: Volumen contractual de petróleo (RM54_02)]            INT            NULL,
    [Volumen contractual: producción de metano de gas natural asociad] INT            NULL,
    [Producción: Volumen contractual de etano de gas natural asociado] INT            NULL,
    [Producción: Volumen contractual de propano de gas natural asocia] INT            NULL,
    [Producción: Volumen contractual de butano de gas natural asociad] INT            NULL,
    [Producción: Volumen contractual de metano de gas natural no asoc] INT            NULL,
    [Producción: Volumen contractual de etano de gas natural no asoci] INT            NULL,
    [Producción: Volumen contractual de propano de gas natural no aso] INT            NULL,
    [Producción: Volumen contractual de butano de gas natural no asoc] INT            NULL,
    [Producción: Volumen contractual de condensados (RM54_11)]         INT            NULL,
    [Precio contractual: petróleo (RM54_12)]                           MONEY          NULL,
    [Precio contractual: metano (RM54_13)]                             MONEY          NULL,
    [Precio contractual: etano (RM54_14)]                              MONEY          NULL,
    [Precio contractual: propano (RM54_15)]                            MONEY          NULL,
    [Precio contractual: butano (RM54_16)]                             MONEY          NULL,
    [Precio contractual: condensados (RM54_17)]                        MONEY          NULL,
    [Tipo de precio que aplicó en la determinación del precio contrac] INT            NULL,
    [Tipo de precio que aplicó en la determinación del precio contra1] INT            NULL,
    [Tipo de precio que aplicó en la determinación del precio contra2] INT            NULL,
    [Tipo de precio que aplicó en la determinación del precio contra3] INT            NULL,
    [Tipo de precio que aplicó en la determinación del precio contra4] INT            NULL,
    [Tipo de precio que aplicó en la determinación del precio contra5] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Pe] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Me] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Et] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Pr] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Bu] INT            NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Co] INT            NULL,
    [Valor contractual: petróleo (RM54_30)]                            MONEY          NULL,
    [Valor contractual: metano de gas natural asociado (RM54_31)]      MONEY          NULL,
    [Valor contractual: etano de gas natural asociado (RM54_32)]       MONEY          NULL,
    [Valor contractual: propano de gas natural asociado (RM54_33)]     MONEY          NULL,
    [Valor contractual: butano de gas natural asociado (RM54_34)]      MONEY          NULL,
    [Valor contractual: metano de gas natural no asociado (RM54_35)]   MONEY          NULL,
    [Valor contractual: etano de gas natural no asociado (RM54_36)]    MONEY          NULL,
    [Valor contractual: propano de gas natural no asociado (RM54_37)]  MONEY          NULL,
    [Valor contractual: butano de gas natural no asociado (RM54_38)]   MONEY          NULL,
    [Valor contractual: condensados (RM54_39)]                         MONEY          NULL,
    [Total del valor contractual de los hidrocarburos (RM54_40)]       MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: petróleo (RM54_4] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas na] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas nat] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas n] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas na] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas n1] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas na1] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas 1] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas n1] MONEY          NULL,
    [Tasa aplicable para el pago de la Regalía Base: condensados (RM5] MONEY          NULL,
    [Monto de Regalía Base (RM54_51)]                                  MONEY          NULL,
    [Costos registrados por el contratista: Recuperables reconocidos ] MONEY          NULL,
    [Costos registrados por el contratista:  No reconocidos (RM54_53)] MONEY          NULL,
    [Recuperación de costos por concepto de gastos de operación (RM54] MONEY          NULL,
    [Recuperación de costos por concepto de gastos de inversión (RM54] MONEY          NULL,
    [Total de costos recuperados (RM54_56)]                            MONEY          NULL,
    [¿Se alcanzó el límite de recuperación de costos? (RM54_57)]       INT            NULL,
    [Saldo de costos recuperables remanentes al final del periodo (RM] MONEY          NULL,
    [Utilidad Operativa (RM54_59)]                                     FLOAT (53)     NULL,
    [Métrica del Resultado Operativo del Contratista del periodo ante] FLOAT (53)     NULL,
    [¿Se activó el mecanismo de ajuste? (RM54_61)]                     INT            NULL,
    ["Participación del Estado sobre la Utilidad Operativa SCA_t" (RM] FLOAT (53)     NULL,
    ["Participación del contratista sobre la Utilidad Operativa SG_t"] FLOAT (53)     NULL,
    [Contraprestación por Utilidad Operativa a favor del Estado (RM54] MONEY          NULL,
    [Contraprestación por Utilidad Operativa a favor del contratista ] MONEY          NULL
);

