CREATE TABLE [dbo].[SIPAC_RCCONT21M] (
    [IdRccont21]                            INT            IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                            INT            NULL,
    [Periodo]                               VARCHAR (50)   NULL,
    [IdContratistaRF00]                     VARCHAR (100)  NULL,
    [IdRegistroFiduciarioRI00]              VARCHAR (100)  NULL,
    [IdContratoCNHRF0101]                   VARCHAR (100)  NULL,
    [IdentificaciónCNHRC2100]               VARCHAR (100)  NULL,
    [MesRC2101]                             INT            NULL,
    [AnioRC2102]                            INT            NULL,
    [NumeroReferenciaRC2103]                INT            NULL,
    [TipoDocumentoRC2104]                   VARCHAR (50)   NULL,
    [IdentificadorCFDIRC2105]               VARCHAR (300)  NULL,
    [IdentificadorPedimentoRC2106]          VARCHAR (300)  NULL,
    [IdentificadorComprobanteRC2107]        VARCHAR (300)  NULL,
    [TipoComprobanteCFDIRC2108]             VARCHAR (50)   NULL,
    [MétodoPagoCFDIRC2_09]                  VARCHAR (50)   NULL,
    [ActividadRC2110]                       VARCHAR (300)  NULL,
    [SubActividadRC2111]                    VARCHAR (300)  NULL,
    [TareaRC2112]                           VARCHAR (300)  NULL,
    [CostosAtribuiblesAdministracionRC2113] INT            NULL,
    [CampoRC2114]                           VARCHAR (300)  NULL,
    [YacimientoRC2115]                      VARCHAR (300)  NULL,
    [PozoRC2116]                            VARCHAR (300)  NULL,
    [NumeroCuentaContableRC2117]            VARCHAR (300)  NULL,
    [DescripcionCuentaContableRC2118]       NVARCHAR (MAX) NULL,
    [NumeroPolizaContableRC2119]            VARCHAR (300)  NULL,
    [ConceptoOperacionRC2120]               NVARCHAR (MAX) NULL,
    [OperacionInversionRC2121]              FLOAT (53)     NULL,
    [MontoAumentarRC2122]                   FLOAT (53)     NULL,
    [MontoDisminuirRC2123]                  FLOAT (53)     NULL,
    [MonedaFuncionalRC2124]                 VARCHAR (50)   NULL,
    [TipoCambioRC2125]                      FLOAT (53)     NULL,
    [TipoOperacionRC2126]                   INT            NULL,
    [EstadoActivo]                          VARCHAR (50)   NULL,
    [FechaRegistro]                         DATETIME       NULL,
    [CreadoPor]                             INT            NULL,
    [CreadoEn]                              DATETIME       NULL,
    [ID]                                    INT            NULL,
    CONSTRAINT [PK_SIPAC_RCCONT21M] PRIMARY KEY CLUSTERED ([IdRccont21] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

