CREATE TABLE [dbo].[SIPAC_ImportRML_CONT_27_M] (
    [Id]         INT             IDENTITY (1, 1) NOT NULL,
    [IdBitacora] INT             NULL,
    [RF_00]      VARCHAR (200)   NULL,
    [RI_00]      VARCHAR (200)   NULL,
    [RF01_01]    VARCHAR (200)   NULL,
    [RMLCT27_00] DATE            NULL,
    [RMLCT27_01] INT             NULL,
    [RMLCT27_02] TINYINT         NULL,
    [RMLCT27_03] INT             NULL,
    [RMLCT27_04] DECIMAL (10, 4) NULL,
    [RMLCT27_05] DECIMAL (10, 4) NULL,
    [RMLCT27_06] DECIMAL (10, 4) NULL,
    [RMLCT27_07] VARCHAR (50)    NULL,
    [RMLCT27_08] VARCHAR (50)    NULL,
    [RMLCT27_09] VARCHAR (50)    NULL,
    [RMLCT27_10] VARCHAR (50)    NULL,
    [RMLCT27_11] TINYINT         NULL,
    [RMLCT27_12] TINYINT         NULL,
    [RMLCT27_13] TINYINT         NULL,
    [CreadoPor]  INT             NULL,
    [CreadoEl]   DATETIME        NULL,
    CONSTRAINT [PK_SIPAC_ImportRML_CONT_27_M] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_27_M_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_27_M_SIPAC_ImportBitacora] FOREIGN KEY ([IdBitacora]) REFERENCES [dbo].[SIPAC_ImportBitacora] ([Id])
);

