CREATE TABLE [dbo].[SIPAC_ImportRML_CONT_26_M] (
    [Id]         INT             IDENTITY (1, 1) NOT NULL,
    [IdBitacora] INT             NOT NULL,
    [RF_00]      VARCHAR (200)   NULL,
    [RI_00]      VARCHAR (200)   NULL,
    [RF01_01]    VARCHAR (200)   NULL,
    [RMLCT26_00] TINYINT         NULL,
    [RMLCT26_01] SMALLINT        NULL,
    [RMLCT26_02] INT             NULL,
    [RMLCT26_03] INT             NULL,
    [RMLCT26_04] INT             NULL,
    [RMLCT26_05] INT             NULL,
    [RMLCT26_06] INT             NULL,
    [RMLCT26_07] INT             NULL,
    [RMLCT26_08] INT             NULL,
    [RMLCT26_09] INT             NULL,
    [RMLCT26_10] INT             NULL,
    [RMLCT26_11] INT             NULL,
    [RMLCT26_12] INT             NULL,
    [RMLCT26_13] INT             NULL,
    [RMLCT26_14] INT             NULL,
    [RMLCT26_15] INT             NULL,
    [RMLCT26_16] INT             NULL,
    [RMLCT26_17] DECIMAL (10, 4) NULL,
    [RMLCT26_18] DECIMAL (10, 4) NULL,
    [RMLCT26_19] DECIMAL (10, 4) NULL,
    [RMLCT26_20] DECIMAL (10, 4) NULL,
    [RMLCT26_21] DECIMAL (10, 2) NULL,
    [RMLCT26_22] TINYINT         NULL,
    [RMLCT26_23] TINYINT         NULL,
    [RMLCT26_24] TINYINT         NULL,
    [RMLCT26_25] TINYINT         NULL,
    [RMLCT26_26] TINYINT         NULL,
    [RMLCT26_27] TINYINT         NULL,
    [RMLCT26_28] TINYINT         NULL,
    [RMLCT26_29] TINYINT         NULL,
    [RMLCT26_30] TINYINT         NULL,
    [RMLCT26_31] TINYINT         NULL,
    [RMLCT26_32] FLOAT (53)      NULL,
    [RMLCT26_33] FLOAT (53)      NULL,
    [RMLCT26_34] FLOAT (53)      NULL,
    [RMLCT26_35] FLOAT (53)      NULL,
    [RMLCT26_36] FLOAT (53)      NULL,
    [CreadoPor]  INT             NULL,
    [CreadoEl]   DATETIME        NULL,
    CONSTRAINT [PK_SIPAC_ImportRML_CONT_26_M] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_26_M_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_26_M_SIPAC_ImportBitacora] FOREIGN KEY ([IdBitacora]) REFERENCES [dbo].[SIPAC_ImportBitacora] ([Id])
);

