CREATE TABLE [dbo].[SIPAC_RM_FMP_53_M] (
    [IdRMFMP53M]                                              INT            IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                                              INT            NULL,
    [IDSIPAC]                                                 NVARCHAR (255) NULL,
    [IDRegistroFiduciario]                                    NVARCHAR (255) NULL,
    [IDContratoCNH]                                           NVARCHAR (255) NULL,
    [MesReporte]                                              INT            NULL,
    [AnioReporte]                                             INT            NULL,
    [ContraprestacionEstadoCuotaExplo]                        MONEY          NULL,
    [ContraprestacioneEstadoProdInsuficiente]                 MONEY          NULL,
    [VolCalculadoDistribucionFinalEstadoPetroleo]             INT            NULL,
    [VolCalculadoDistribucionFinalEstadoC1]                   INT            NULL,
    [VolCalculadoDistribucionFinalEstadoC2]                   INT            NULL,
    [VolCalculadoDistribucionFinalEstadoC3]                   INT            NULL,
    [VolCalculadoDistribucionFinalEstadoC4]                   INT            NULL,
    [VolCalculadoDistribucionFinalEstadoCondensados]          INT            NULL,
    [VolCalculadoDistribucionFinalContratistaPetroleo]        INT            NULL,
    [VolCalculadoDistribucionFinalContratistaC1]              INT            NULL,
    [VolCalculadoDistribucionFinalContratistaC2]              INT            NULL,
    [VolCalculadoDistribucionFinalContratistaC3]              INT            NULL,
    [VolCalculadoDistribucionFinalContratistaC4]              INT            NULL,
    [VolCalculadoDistribucionFinalContratistaCondensado]      INT            NULL,
    [VolRecibidoEstadoPuntoMedPetroleo]                       INT            NULL,
    [VolRecibidoEstadoPuntoMedC1]                             INT            NULL,
    [VolRecibidoEstadoPuntoMedC2]                             INT            NULL,
    [VolRecibidoEstadoPuntoMedC3]                             INT            NULL,
    [VolRecibidoEstadoPuntoMedC4]                             INT            NULL,
    [VolRecibidoEstadoPuntoMedCondensado]                     INT            NULL,
    [VolRecibidoContratistaPuntoMedPetroleo]                  INT            NULL,
    [VolRecibidoContratistaPuntoMedC1]                        INT            NULL,
    [VolRecibidoContratistaPuntoMedC2]                        INT            NULL,
    [VolRecibidoContratistaPuntoMedC3]                        INT            NULL,
    [VolRecibidoContratistaPuntoMedC4]                        INT            NULL,
    [VolRecibidoContratistaPuntoMedCondensado]                INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoPetroleo]             INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoC1]                   INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoC2]                   INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoC3]                   INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoC4]                   INT            NULL,
    [CompensacionVolSaldoAcumuladoEstadoCondensado]           INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaPetroleo]        INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaC1]              INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaC2]              INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaC3]              INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaC4]              INT            NULL,
    [CompensacionVolSaldoAcumuladoContratistaCondensado]      INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoPetroleo]        INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoC1]              INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoC2]              INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoC3]              INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoC4]              INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoEstadoCondensado]      INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaPetroleo]   INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaC1]         INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaC2]         INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaC3]         INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaC4]         INT            NULL,
    [CompensacionVolNuevoSaldoAcumuladoContratistaCondensado] INT            NULL,
    [NuevaDistribucionProvisionalEstado]                      FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratista]                 FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratistaC1]               FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratistaC2]               FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratistaC3]               FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratistaC4]               FLOAT (53)     NULL,
    [NuevaDistribucionProvisionalContratistaC5]               FLOAT (53)     NULL,
    CONSTRAINT [PK_SIPAC_RM_FMP_53_M] PRIMARY KEY CLUSTERED ([IdRMFMP53M] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SIPAC_RM_FMP_53_M_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

