CREATE TABLE [dbo].[SIPACReporteMensual] (
    [IdReporteMensual]                 INT           IDENTITY (1, 1) NOT NULL,
    [IDContratistaSIPAC]               NVARCHAR (4)  NULL,
    [IDRegistroFContrato]              NVARCHAR (16) NULL,
    [PeriodoReporte]                   DATE          NULL,
    [ExtensionAreaExpEval]             FLOAT (53)    NULL,
    [ExtensionAreaExtr]                FLOAT (53)    NULL,
    [VolumenPetroleoPuntoMed]          FLOAT (53)    NULL,
    [GradosAPI]                        FLOAT (53)    NULL,
    [ContenidoAzufre]                  FLOAT (53)    NULL,
    [VolumenMetanoGasA]                FLOAT (53)    NULL,
    [VolumenEtanoGasA]                 FLOAT (53)    NULL,
    [VolumenPropanoGasA]               FLOAT (53)    NULL,
    [VolumenButanoGasA]                FLOAT (53)    NULL,
    [VolumenMetanoGasNA]               FLOAT (53)    NULL,
    [VolumenEtanoGasNA]                FLOAT (53)    NULL,
    [VolumenPropanoGasNA]              FLOAT (53)    NULL,
    [VolumenButanoGasNA]               FLOAT (53)    NULL,
    [VolumenCondensadosPuntoMed]       FLOAT (53)    NULL,
    [VolumenPetroleoVendidoCondMer]    FLOAT (53)    NULL,
    [VolumenMetanoVendidoCondMer]      FLOAT (53)    NULL,
    [VolumenEtanoVendidoCondMer]       FLOAT (53)    NULL,
    [VolumenPropanoVendidoCondMer]     FLOAT (53)    NULL,
    [VolumenButanoVendidoCondMer]      FLOAT (53)    NULL,
    [VolumenCondensadosVendidoCondMer] FLOAT (53)    NULL,
    [PrecioContractualPetroleo]        FLOAT (53)    NULL,
    [PrecioContractualMetano]          FLOAT (53)    NULL,
    [PrecioContractualEtano]           FLOAT (53)    NULL,
    [PrecioContractualPropano]         FLOAT (53)    NULL,
    [PrecioContractualButno]           FLOAT (53)    NULL,
    [PrecioContractualCondensados]     FLOAT (53)    NULL,
    [TipoPrecioPetroleo]               INT           NULL,
    [TipoPrecioMetano]                 INT           NULL,
    [TipoPrecioEtano]                  INT           NULL,
    [TipoPrecioPropano]                INT           NULL,
    [TipoPrecioButano]                 INT           NULL,
    [TipoPrecioCondensados]            INT           NULL,
    [AjustePetroleo]                   BIT           NULL,
    [AjusteMetano]                     BIT           NULL,
    [AjusteEtano]                      BIT           NULL,
    [AjustePropano]                    BIT           NULL,
    [AjusteButano]                     BIT           NULL,
    [AjusteCondensados]                BIT           NULL,
    [CasoFortuito]                     BIT           NULL,
    [DiasCasoFortuito]                 INT           NULL,
    [IngresosPrestacionServicios]      MONEY         NULL,
    [Fecha]                            DATE          NULL,
    CONSTRAINT [PK_SIPACReporteMensual] PRIMARY KEY CLUSTERED ([IdReporteMensual] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

