SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SIPAC_ImportCFDI](
	[IdBitacora] [int] NOT NULL,
	[IdFactura] [int] NOT NULL,
	[CreadoEl] [datetime] NOT NULL,
 CONSTRAINT [PK_SIPAC_ImportCFDI] PRIMARY KEY CLUSTERED 
(
	[IdBitacora] ASC,
	[IdFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SIPAC_ImportCFDI]  WITH CHECK ADD  CONSTRAINT [FK_SIPAC_ImportCFDI_FI_Factura] FOREIGN KEY([IdFactura])
REFERENCES [dbo].[FI_Factura] ([IdFactura])
GO

ALTER TABLE [dbo].[SIPAC_ImportCFDI] CHECK CONSTRAINT [FK_SIPAC_ImportCFDI_FI_Factura]
GO

ALTER TABLE [dbo].[SIPAC_ImportCFDI]  WITH CHECK ADD  CONSTRAINT [FK_SIPAC_ImportCFDI_SIPAC_ImportBitacora] FOREIGN KEY([IdBitacora])
REFERENCES [dbo].[SIPAC_ImportBitacora] ([Id])
GO

ALTER TABLE [dbo].[SIPAC_ImportCFDI] CHECK CONSTRAINT [FK_SIPAC_ImportCFDI_SIPAC_ImportBitacora]
GO


