CREATE TABLE [dbo].[SIPAC_ImportRML_CONT_25_M] (
    [Id]         INT             IDENTITY (1, 1) NOT NULL,
    [IdBitacora] INT             NOT NULL,
    [RF_00]      VARCHAR (200)   NULL,
    [RI_00]      VARCHAR (200)   NULL,
    [RF01_01]    VARCHAR (200)   NULL,
    [RMLCT25_00] TINYINT         NULL,
    [RMLCT25_01] SMALLINT        NULL,
    [RMLCT25_02] INT             NULL,
    [RMLCT25_03] DECIMAL (5, 2)  NULL,
    [RMLCT25_04] DECIMAL (5, 2)  NULL,
    [RMLCT25_05] INT             NULL,
    [RMLCT25_06] INT             NULL,
    [RMLCT25_07] INT             NULL,
    [RMLCT25_08] INT             NULL,
    [RMLCT25_09] INT             NULL,
    [RMLCT25_10] INT             NULL,
    [RMLCT25_11] INT             NULL,
    [RMLCT25_12] INT             NULL,
    [RMLCT25_13] INT             NULL,
    [RMLCT25_14] INT             NULL,
    [RMLCT25_15] INT             NULL,
    [RMLCT25_16] INT             NULL,
    [RMLCT25_17] INT             NULL,
    [RMLCT25_18] INT             NULL,
    [RMLCT25_19] INT             NULL,
    [RMLCT25_20] INT             NULL,
    [RMLCT25_21] INT             NULL,
    [RMLCT25_22] DECIMAL (10, 4) NULL,
    [RMLCT25_23] DECIMAL (10, 4) NULL,
    [RMLCT25_24] DECIMAL (10, 4) NULL,
    [RMLCT25_25] DECIMAL (10, 4) NULL,
    [RMLCT25_26] DECIMAL (10, 4) NULL,
    [RMLCT25_27] DECIMAL (10, 4) NULL,
    [RMLCT25_28] TINYINT         NULL,
    [RMLCT25_29] TINYINT         NULL,
    [RMLCT25_30] TINYINT         NULL,
    [RMLCT25_31] TINYINT         NULL,
    [RMLCT25_32] TINYINT         NULL,
    [RMLCT25_33] TINYINT         NULL,
    [RMLCT25_34] TINYINT         NULL,
    [RMLCT25_35] TINYINT         NULL,
    [RMLCT25_36] TINYINT         NULL,
    [RMLCT25_37] TINYINT         NULL,
    [RMLCT25_38] TINYINT         NULL,
    [RMLCT25_39] TINYINT         NULL,
    [RMLCT25_40] DECIMAL (10, 4) NULL,
    [RMLCT25_41] DECIMAL (10, 4) NULL,
    [RMLCT25_42] DECIMAL (10, 4) NULL,
    [RMLCT25_43] DECIMAL (10, 4) NULL,
    [RMLCT25_44] DECIMAL (10, 4) NULL,
    [RMLCT25_45] DECIMAL (10, 4) NULL,
    [CreadoPor]  INT             NULL,
    [CreadoEl]   DATETIME        NULL,
    CONSTRAINT [PK_SIPAC_ImportRML_CONT_25_M] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_25_M_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_SIPAC_ImportRML_CONT_25_M_SIPAC_ImportBitacora] FOREIGN KEY ([IdBitacora]) REFERENCES [dbo].[SIPAC_ImportBitacora] ([Id])
);

