CREATE TABLE [dbo].[TMP_AC5] (
    [Contratista]                   NVARCHAR (255) NULL,
    [Numero de Contrato]            NVARCHAR (255) NULL,
    [Bloque]                        NVARCHAR (255) NULL,
    [Fecha Presentación]            FLOAT (53)     NULL,
    [Fecha Aprobación]              FLOAT (53)     NULL,
    [id_Actividad petrolera]        NVARCHAR (255) NULL,
    [Actividad petrolera]           NVARCHAR (255) NULL,
    [id_Sub-actividad petrolera]    NVARCHAR (255) NULL,
    [Sub-actividad petrolera]       NVARCHAR (255) NULL,
    [id_Tarea]                      NVARCHAR (255) NULL,
    [Tarea]                         NVARCHAR (255) NULL,
    [id_Sub-tarea]                  NVARCHAR (255) NULL,
    [Sub-tarea]                     NVARCHAR (255) NULL,
    [Elegible]                      NVARCHAR (255) NULL,
    [Area]                          NVARCHAR (255) NULL,
    [Campo*]                        NVARCHAR (255) NULL,
    [Yacimiento*]                   NVARCHAR (255) NULL,
    [Pozo]                          NVARCHAR (255) NULL,
    [Mano de Obra ($)]              NVARCHAR (255) NULL,
    [F20]                           NVARCHAR (255) NULL,
    [Bienes ($)]                    NVARCHAR (255) NULL,
    [F22]                           NVARCHAR (255) NULL,
    [ Servicios ($)]                FLOAT (53)     NULL,
    [F24]                           FLOAT (53)     NULL,
    [Capacitación ($)]              NVARCHAR (255) NULL,
    [F26]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia]   NVARCHAR (255) NULL,
    [Infraestructura (Social)]      NVARCHAR (255) NULL,
    [F29]                           FLOAT (53)     NULL,
    [Mano de Obra ($)1]             NVARCHAR (255) NULL,
    [F31]                           NVARCHAR (255) NULL,
    [Bienes ($)1]                   NVARCHAR (255) NULL,
    [F33]                           NVARCHAR (255) NULL,
    [ Servicios ($)1]               FLOAT (53)     NULL,
    [F35]                           FLOAT (53)     NULL,
    [Capacitación ($)1]             NVARCHAR (255) NULL,
    [F37]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia1]  NVARCHAR (255) NULL,
    [Infraestructura (Social)1]     NVARCHAR (255) NULL,
    [F40]                           FLOAT (53)     NULL,
    [Mano de Obra ($)2]             NVARCHAR (255) NULL,
    [F42]                           NVARCHAR (255) NULL,
    [Bienes ($)2]                   NVARCHAR (255) NULL,
    [F44]                           NVARCHAR (255) NULL,
    [ Servicios ($)2]               FLOAT (53)     NULL,
    [F46]                           FLOAT (53)     NULL,
    [Capacitación ($)2]             NVARCHAR (255) NULL,
    [F48]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia2]  NVARCHAR (255) NULL,
    [Infraestructura (Social)2]     NVARCHAR (255) NULL,
    [F51]                           FLOAT (53)     NULL,
    [Mano de Obra ($)3]             NVARCHAR (255) NULL,
    [F53]                           NVARCHAR (255) NULL,
    [Bienes ($)3]                   NVARCHAR (255) NULL,
    [F55]                           NVARCHAR (255) NULL,
    [ Servicios ($)3]               FLOAT (53)     NULL,
    [F57]                           FLOAT (53)     NULL,
    [Capacitación ($)3]             NVARCHAR (255) NULL,
    [F59]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia3]  NVARCHAR (255) NULL,
    [Infraestructura (Social)3]     NVARCHAR (255) NULL,
    [F62]                           FLOAT (53)     NULL,
    [Mano de Obra ($)4]             NVARCHAR (255) NULL,
    [F64]                           NVARCHAR (255) NULL,
    [Bienes ($)4]                   NVARCHAR (255) NULL,
    [F66]                           NVARCHAR (255) NULL,
    [ Servicios ($)4]               FLOAT (53)     NULL,
    [F68]                           FLOAT (53)     NULL,
    [Capacitación ($)4]             NVARCHAR (255) NULL,
    [F70]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia4]  NVARCHAR (255) NULL,
    [Infraestructura (Social)4]     NVARCHAR (255) NULL,
    [F73]                           FLOAT (53)     NULL,
    [Mano de Obra ($)5]             NVARCHAR (255) NULL,
    [F75]                           NVARCHAR (255) NULL,
    [Bienes ($)5]                   NVARCHAR (255) NULL,
    [F77]                           NVARCHAR (255) NULL,
    [ Servicios ($)5]               FLOAT (53)     NULL,
    [F79]                           FLOAT (53)     NULL,
    [Capacitación ($)5]             NVARCHAR (255) NULL,
    [F81]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia5]  NVARCHAR (255) NULL,
    [Infraestructura (Social)5]     NVARCHAR (255) NULL,
    [F84]                           FLOAT (53)     NULL,
    [Mano de Obra ($)6]             NVARCHAR (255) NULL,
    [F86]                           NVARCHAR (255) NULL,
    [Bienes ($)6]                   NVARCHAR (255) NULL,
    [F88]                           NVARCHAR (255) NULL,
    [ Servicios ($)6]               FLOAT (53)     NULL,
    [F90]                           FLOAT (53)     NULL,
    [Capacitación ($)6]             NVARCHAR (255) NULL,
    [F92]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia6]  NVARCHAR (255) NULL,
    [Infraestructura (Social)6]     NVARCHAR (255) NULL,
    [F95]                           FLOAT (53)     NULL,
    [Mano de Obra ($)7]             NVARCHAR (255) NULL,
    [F97]                           NVARCHAR (255) NULL,
    [Bienes ($)7]                   NVARCHAR (255) NULL,
    [F99]                           NVARCHAR (255) NULL,
    [ Servicios ($)7]               FLOAT (53)     NULL,
    [F101]                          FLOAT (53)     NULL,
    [Capacitación ($)7]             NVARCHAR (255) NULL,
    [F103]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia7]  NVARCHAR (255) NULL,
    [Infraestructura (Social)7]     NVARCHAR (255) NULL,
    [F106]                          FLOAT (53)     NULL,
    [Mano de Obra ($)8]             NVARCHAR (255) NULL,
    [F108]                          NVARCHAR (255) NULL,
    [Bienes ($)8]                   NVARCHAR (255) NULL,
    [F110]                          NVARCHAR (255) NULL,
    [ Servicios ($)8]               FLOAT (53)     NULL,
    [F112]                          FLOAT (53)     NULL,
    [Capacitación ($)8]             NVARCHAR (255) NULL,
    [F114]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia8]  NVARCHAR (255) NULL,
    [Infraestructura (Social)8]     NVARCHAR (255) NULL,
    [F117]                          FLOAT (53)     NULL,
    [Mano de Obra ($)9]             NVARCHAR (255) NULL,
    [F119]                          NVARCHAR (255) NULL,
    [Bienes ($)9]                   NVARCHAR (255) NULL,
    [F121]                          NVARCHAR (255) NULL,
    [ Servicios ($)9]               FLOAT (53)     NULL,
    [F123]                          FLOAT (53)     NULL,
    [Capacitación ($)9]             NVARCHAR (255) NULL,
    [F125]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia9]  NVARCHAR (255) NULL,
    [Infraestructura (Social)9]     NVARCHAR (255) NULL,
    [F128]                          FLOAT (53)     NULL,
    [Mano de Obra ($)10]            NVARCHAR (255) NULL,
    [F130]                          NVARCHAR (255) NULL,
    [Bienes ($)10]                  NVARCHAR (255) NULL,
    [F132]                          NVARCHAR (255) NULL,
    [ Servicios ($)10]              FLOAT (53)     NULL,
    [F134]                          FLOAT (53)     NULL,
    [Capacitación ($)10]            NVARCHAR (255) NULL,
    [F136]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia10] NVARCHAR (255) NULL,
    [Infraestructura (Social)10]    NVARCHAR (255) NULL,
    [F139]                          FLOAT (53)     NULL,
    [Mano de Obra ($)11]            NVARCHAR (255) NULL,
    [F141]                          NVARCHAR (255) NULL,
    [Bienes ($)11]                  NVARCHAR (255) NULL,
    [F143]                          NVARCHAR (255) NULL,
    [ Servicios ($)11]              FLOAT (53)     NULL,
    [F145]                          FLOAT (53)     NULL,
    [Capacitación ($)11]            NVARCHAR (255) NULL,
    [F147]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia11] NVARCHAR (255) NULL,
    [Infraestructura (Social)11]    NVARCHAR (255) NULL,
    [F150]                          FLOAT (53)     NULL,
    [Mano de Obra ($)12]            NVARCHAR (255) NULL,
    [F152]                          NVARCHAR (255) NULL,
    [Bienes ($)12]                  NVARCHAR (255) NULL,
    [F154]                          NVARCHAR (255) NULL,
    [ Servicios ($)12]              FLOAT (53)     NULL,
    [F156]                          FLOAT (53)     NULL,
    [Capacitación ($)12]            NVARCHAR (255) NULL,
    [F158]                          NVARCHAR (255) NULL,
    [Transferencia_de Tecnologia]   NVARCHAR (255) NULL,
    [Infraestructura (Social)12]    NVARCHAR (255) NULL
);

