CREATE TABLE [dbo].[TMP_EN_Entregables] (
    [F1]                                  FLOAT (53)     NULL,
    [eliminar]                            NVARCHAR (MAX) NULL,
    [IdEntregable]                        FLOAT (53)     NULL,
    [Consecutivo]                         NVARCHAR (MAX) NULL,
    [Regulador]                           NVARCHAR (MAX) NULL,
    [MarcoLegal]                          NVARCHAR (MAX) NULL,
    [Articulo]                            NVARCHAR (MAX) NULL,
    [Documento Entregable]                NVARCHAR (MAX) NULL,
    [Etapa]                               NVARCHAR (MAX) NULL,
    [Receptor Entregable]                 NVARCHAR (MAX) NULL,
    [Responsable Generador]               NVARCHAR (MAX) NULL,
    [FrecuenciaEntregable]                NVARCHAR (MAX) NULL,
    [Tiempo Entrega]                      NVARCHAR (MAX) NULL,
    [Tiempo Respuesta]                    NVARCHAR (MAX) NULL,
    [Licencia]                            NVARCHAR (MAX) NULL,
    [Produccion Compartida]               NVARCHAR (MAX) NULL,
    [Licencia_Farmaouts]                  NVARCHAR (MAX) NULL,
    [Produccion Compartida_Farmaouts]     NVARCHAR (MAX) NULL,
    [Terrestre]                           NVARCHAR (MAX) NULL,
    [Costa Fuera]                         NVARCHAR (MAX) NULL,
    [Reguladores ]                        NVARCHAR (MAX) NULL,
    [Operadores]                          NVARCHAR (MAX) NULL,
    [Administracion de Contratos]         NVARCHAR (MAX) NULL,
    [Pozo de alivio]                      NVARCHAR (MAX) NULL,
    [Cierre, Desmantelamiento, Abandono]  NVARCHAR (MAX) NULL,
    [Perforacion]                         NVARCHAR (MAX) NULL,
    [Terminacion]                         NVARCHAR (MAX) NULL,
    [Actividades de Produccion]           NVARCHAR (MAX) NULL,
    [Estimulacion]                        NVARCHAR (MAX) NULL,
    [Prueba de Produccion]                NVARCHAR (MAX) NULL,
    [Construccion de Camino]              NVARCHAR (MAX) NULL,
    [Construccion de Localizacion]        NVARCHAR (MAX) NULL,
    [ Reabilitacion de Camino]            NVARCHAR (MAX) NULL,
    [ Reabilitacion de Localizacion]      NVARCHAR (MAX) NULL,
    [Toma de Informacion Sismica]         NVARCHAR (MAX) NULL,
    [Corte de Nucleos]                    NVARCHAR (MAX) NULL,
    [Construccion de Lineas de descargas] NVARCHAR (MAX) NULL,
    [Sistemas Artificiales de Produccion] NVARCHAR (MAX) NULL,
    [Medicion de Pozos]                   NVARCHAR (MAX) NULL,
    [Toma de Informacion en Pozos]        NVARCHAR (MAX) NULL,
    [Reparacion Mayor]                    NVARCHAR (MAX) NULL,
    [Reparacion Menor]                    NVARCHAR (MAX) NULL,
    [Transporte de Hidrocarbuross]        NVARCHAR (MAX) NULL,
    [Quema de GAS]                        NVARCHAR (MAX) NULL
);

