CREATE TABLE [dbo].[TMP_DEA18] (
    [ID]           FLOAT (53)     NULL,
    [RF_00]        NVARCHAR (255) NULL,
    [PA_00]        NVARCHAR (255) NULL,
    [PA_01]        NVARCHAR (255) NULL,
    [PA_04]        NVARCHAR (255) NULL,
    [PA_05]        NVARCHAR (255) NULL,
    [PA_06]        NVARCHAR (255) NULL,
    [PA_07]        NVARCHAR (255) NULL,
    [PA_08]        NVARCHAR (255) NULL,
    [PA_09]        NVARCHAR (255) NULL,
    [PA_10]        NVARCHAR (255) NULL,
    [PA_11]        NVARCHAR (255) NULL,
    [PA_12]        NVARCHAR (255) NULL,
    [PA_13]        FLOAT (53)     NULL,
    [F15]          NVARCHAR (255) NULL,
    [PA_14F]       DATETIME       NULL,
    [PA_15F]       DATETIME       NULL,
    [PA_16]        NVARCHAR (255) NULL,
    [PA_17]        NVARCHAR (255) NULL,
    [PA_18]        NVARCHAR (255) NULL,
    [PA_19]        NVARCHAR (255) NULL,
    [PA_20]        NVARCHAR (255) NULL,
    [PA_21]        FLOAT (53)     NULL,
    [PA_22]        NVARCHAR (255) NULL,
    [PA_23]        NVARCHAR (255) NULL,
    [PolizaEgreso] FLOAT (53)     NULL,
    [Pagado]       NVARCHAR (255) NULL,
    [FechaPoliza]  DATETIME       NULL,
    [VendorNumber] FLOAT (53)     NULL,
    [Split]        NVARCHAR (255) NULL,
    [FechaFactura] DATETIME       NULL,
    [EurDol]       NVARCHAR (255) NULL,
    [FechaPago]    DATETIME       NULL
);

