CREATE TABLE [dbo].[TMP_E21] (
    [Consecutivo]                      NVARCHAR (255) NULL,
    [Regulador]                        NVARCHAR (255) NULL,
    [MarcoLegal]                       NVARCHAR (255) NULL,
    [TituloAnexo]                      NVARCHAR (255) NULL,
    [Capitulo]                         NVARCHAR (255) NULL,
    [Descripcion]                      NVARCHAR (255) NULL,
    [Articulo]                         NVARCHAR (MAX) NULL,
    [DocumentoEntregable]              NVARCHAR (MAX) NULL,
    [Etapa]                            NVARCHAR (255) NULL,
    [ReceptorEntregable]               NVARCHAR (255) NULL,
    [ResponsableGenerador]             NVARCHAR (255) NULL,
    [FrecuenciaEntregable]             NVARCHAR (255) NULL,
    [TiempoEntrega]                    NVARCHAR (255) NULL,
    [TiempoRespuesta]                  NVARCHAR (255) NULL,
    [TCLicencia]                       NVARCHAR (255) NULL,
    [TCProducionCompartida]            NVARCHAR (255) NULL,
    [TCLicenciaFarmOuts]               NVARCHAR (255) NULL,
    [TCProducionCompartidaFarmOuts]    NVARCHAR (255) NULL,
    [UGTerrestre]                      NVARCHAR (255) NULL,
    [UGCostaFuera]                     NVARCHAR (255) NULL,
    [REReguladores]                    NVARCHAR (255) NULL,
    [REOperadores]                     NVARCHAR (255) NULL,
    [APAdministracionContratos]        NVARCHAR (255) NULL,
    [APPozoAlivio]                     NVARCHAR (255) NULL,
    [APCierreDesmantelamientoAbandono] NVARCHAR (255) NULL,
    [APPerforacion]                    NVARCHAR (255) NULL,
    [APTerminacion]                    NVARCHAR (255) NULL,
    [APActProduccion]                  NVARCHAR (255) NULL,
    [APEstimulacion]                   NVARCHAR (255) NULL,
    [APPruebaProduccion]               NVARCHAR (255) NULL,
    [APConstruccionCamino]             NVARCHAR (255) NULL,
    [APConstruccionLocalizacion]       NVARCHAR (255) NULL,
    [APRehabilitacionCamino]           NVARCHAR (255) NULL,
    [APRehabilitacionLocalizacion]     NVARCHAR (255) NULL,
    [APTomaInformacionSismica]         NVARCHAR (255) NULL,
    [APCorteNucleos]                   NVARCHAR (255) NULL,
    [APConstruccionLineaDescarga]      NVARCHAR (255) NULL,
    [APSistemaArtificialProduccion]    NVARCHAR (255) NULL,
    [APMedicionPozos]                  NVARCHAR (255) NULL,
    [APTomaInformacionPozo]            NVARCHAR (255) NULL,
    [APReparacionMayor]                NVARCHAR (255) NULL,
    [APReparacionMenor]                NVARCHAR (255) NULL,
    [APTransporteHidrocarburos]        NVARCHAR (255) NULL,
    [APQuemaGas]                       NVARCHAR (255) NULL,
    [IdMarcoLegal]                     INT            NULL,
    [IdRegulador]                      INT            NULL,
    [IdEtapa]                          INT            NULL,
    [IdReceptorEntregable]             INT            NULL,
    [IdFrecuenciaEntregable]           INT            NULL,
    [IdTiempoRespuesta]                INT            NULL,
    [IdResponsableGenerador]           INT            NULL
);

