CREATE TABLE [dbo].[TMP_MURPHY04] (
    [Id]                    FLOAT (53)     NULL,
    [Date]                  FLOAT (53)     NULL,
    [Account Number]        NVARCHAR (255) NULL,
    [Bank ID]               NVARCHAR (255) NULL,
    [Transaction]           NVARCHAR (255) NULL,
    [Currency]              NVARCHAR (255) NULL,
    [Amount]                FLOAT (53)     NULL,
    [ExRate]                FLOAT (53)     NULL,
    [Credit/Debit]          NVARCHAR (255) NULL,
    [Customer Reference]    NVARCHAR (255) NULL,
    [Bank Reference]        NVARCHAR (255) NULL,
    [Vendor]                NVARCHAR (255) NULL,
    [TaxID]                 NVARCHAR (255) NULL,
    [Vendor Bank]           NVARCHAR (255) NULL,
    [Vendor Account Number] NVARCHAR (255) NULL,
    [Invoice (s)]           NVARCHAR (255) NULL,
    [Folio Fiscal]          NVARCHAR (255) NULL,
    [Journal Entry]         FLOAT (53)     NULL,
    [Payment Entry]         FLOAT (53)     NULL,
    [AC]                    NVARCHAR (255) NULL,
    [SA]                    NVARCHAR (255) NULL,
    [TA]                    NVARCHAR (255) NULL,
    [GL Account]            FLOAT (53)     NULL,
    [Hidrocarburos]         NVARCHAR (255) NULL,
    [Balance/Value Date]    NVARCHAR (255) NULL,
    [Text]                  NVARCHAR (MAX) NULL
);

