CREATE TABLE [dbo].[TMP_DEM201910] (
    [F1]                  FLOAT (53)    NOT NULL,
    [ID]                  FLOAT (53)    NULL,
    [NumeroContrato]      VARCHAR (255) NULL,
    [Bloque]              VARCHAR (255) NULL,
    [Referencia Bancaria] VARCHAR (255) NULL,
    [FechaPago]           DATETIME      NULL,
    [Banco]               VARCHAR (255) NULL,
    [Titular]             VARCHAR (255) NULL,
    [NumeroCuenta]        VARCHAR (255) NULL,
    [Moneda]              VARCHAR (255) NULL,
    [Banco Destino]       VARCHAR (255) NULL,
    [Titular1]            VARCHAR (255) NULL,
    [Numero Cuenta]       VARCHAR (255) NULL,
    [Moneda1]             VARCHAR (255) NULL,
    [RFCTitular]          VARCHAR (255) NULL,
    [MontoPagado]         FLOAT (53)    NULL,
    [Concepto]            FLOAT (53)    NULL,
    [Poliza]              FLOAT (53)    NULL,
    [UUID]                VARCHAR (255) NULL,
    [Archivo]             VARCHAR (255) NOT NULL,
    [Complemento]         VARCHAR (255) NULL,
    [MetodoPAgo]          VARCHAR (255) NULL
);

