CREATE TABLE [dbo].[TMP_Entregables] (
    [Regulador]              NVARCHAR (MAX) NULL,
    [IdRegulador]            INT            NULL,
    [MarcoLegal]             NVARCHAR (MAX) NULL,
    [IdMarcoLegal]           INT            NULL,
    [FechaPublicacion]       DATE           NULL,
    [UltimaModificacion]     DATE           NULL,
    [TituloAnexo]            NVARCHAR (MAX) NULL,
    [Capitulo]               NVARCHAR (MAX) NULL,
    [Seccion]                NVARCHAR (MAX) NULL,
    [Articulo]               NVARCHAR (MAX) NULL,
    [Apartado]               NVARCHAR (MAX) NULL,
    [Fraccion]               NVARCHAR (MAX) NULL,
    [Inciso]                 NVARCHAR (MAX) NULL,
    [Descripcion]            NVARCHAR (MAX) NULL,
    [DocumentoEntregable]    NVARCHAR (MAX) NULL,
    [ResponsableGenerador]   NVARCHAR (MAX) NULL,
    [IdResponsableGenerador] INT            NULL,
    [ReceptorEntregable]     NVARCHAR (MAX) NULL,
    [IdReceptorEntregable]   INT            NULL,
    [TiempoEntrega]          NVARCHAR (MAX) NULL,
    [IdTiempoEntrega]        INT            NULL,
    [TiempoRespuesta]        NVARCHAR (MAX) NULL,
    [IdTiempoRespuesta]      INT            NULL,
    [Frecuencia]             NVARCHAR (MAX) NULL,
    [IdFrecuenciaEntregable] INT            NULL,
    [Observaciones]          NVARCHAR (MAX) NULL,
    [Archivo]                NVARCHAR (MAX) NULL
);

