CREATE TABLE [dbo].[TMP_DEAMAR18] (
    [ID]                 FLOAT (53)     NULL,
    [Contratista]        FLOAT (53)     NULL,
    [NumeroContrato]     NVARCHAR (255) NULL,
    [Bloque]             NVARCHAR (255) NULL,
    [ReferenciaBancaria] FLOAT (53)     NULL,
    [FechaPago]          DATETIME       NULL,
    [Banco]              NVARCHAR (255) NULL,
    [Titular]            NVARCHAR (255) NULL,
    [Sucursal]           NVARCHAR (255) NULL,
    [NumeroCuenta]       NVARCHAR (255) NULL,
    [CuentaClabe]        NVARCHAR (255) NULL,
    [NumeroTarjeta]      DATETIME       NULL,
    [Moneda]             NVARCHAR (255) NULL,
    [BancoDestino]       NVARCHAR (255) NULL,
    [Titular1]           NVARCHAR (255) NULL,
    [Sucursal1]          FLOAT (53)     NULL,
    [Numero Cuenta]      NVARCHAR (255) NULL,
    [CuentaClabe1]       NVARCHAR (255) NULL,
    [NumeroTarjeta1]     DATETIME       NULL,
    [Moneda1]            NVARCHAR (255) NULL,
    [RFCTitular]         NVARCHAR (255) NULL,
    [MontoPagado]        FLOAT (53)     NULL,
    [Concepto]           NVARCHAR (255) NULL,
    [NumeroPoliza]       FLOAT (53)     NULL,
    [Intereses]          NVARCHAR (255) NULL,
    [UUID]               NVARCHAR (255) NULL,
    [F27]                NVARCHAR (255) NULL
);

