CREATE TABLE [dbo].[TMP_PDA_CO2019] (
    [ID]                                             FLOAT (53)     NULL,
    [INFORME]                                        NVARCHAR (255) NULL,
    [Year]                                           FLOAT (53)     NULL,
    [Numero Factura Proveedor Pemex]                 NVARCHAR (255) NULL,
    [UUID LUM]                                       NVARCHAR (255) NULL,
    [Fecha de la Factura]                            DATETIME       NULL,
    [Cía Relacionada/_Subcontratista]                NVARCHAR (255) NULL,
    [Mes de Informe]                                 NVARCHAR (255) NULL,
    [Ajuste]                                         NVARCHAR (255) NULL,
    [NumerodeFacturaOriginal]                        NVARCHAR (255) NULL,
    [UUID ORIGINAL]                                  NVARCHAR (255) NULL,
    [Fecha Factura Original]                         DATETIME       NULL,
    [Periodo Facturación Original]                   DATETIME       NULL,
    [Proveedor Original]                             NVARCHAR (255) NULL,
    [Fecha Inicio]                                   DATETIME       NULL,
    [Fecha Termino]                                  DATETIME       NULL,
    [Período Ejecución]                              DATETIME       NULL,
    [Orden de Servicio/Orden Compra]                 FLOAT (53)     NULL,
    [Partida]                                        NVARCHAR (255) NULL,
    [Unidad]                                         NVARCHAR (255) NULL,
    [P#U# USD]                                       FLOAT (53)     NULL,
    [P#U# MXN]                                       FLOAT (53)     NULL,
    [Cantidad Real]                                  FLOAT (53)     NULL,
    [Importe Factura Original _USD/MXP]              FLOAT (53)     NULL,
    [Importe Factura Original _USD/MXP c/markup]     FLOAT (53)     NULL,
    [TC Banxico_4 Digitos]                           FLOAT (53)     NULL,
    [Moneda]                                         NVARCHAR (255) NULL,
    [Importe USD_(Conver MXN a USD)]                 FLOAT (53)     NULL,
    [Tipo Markup %]                                  FLOAT (53)     NULL,
    [Markup %]                                       FLOAT (53)     NULL,
    [Importe Estimado USD]                           FLOAT (53)     NULL,
    [Presupuesto (PPT)]                              NVARCHAR (255) NULL,
    [Homologacion PAT PPD 120 a PAT 2019_(Servicio)] NVARCHAR (255) NULL,
    [CAPEX/OPEX]                                     NVARCHAR (255) NULL,
    [Descripción general de Trabajo]                 NVARCHAR (255) NULL,
    [id Formula]                                     NVARCHAR (255) NULL,
    [sumas reporte mensual]                          NVARCHAR (255) NULL,
    [aux co]                                         NVARCHAR (255) NULL,
    [Aux Sub Act]                                    NVARCHAR (255) NULL,
    [Aux Pres]                                       NVARCHAR (255) NULL,
    [aux PASAPI CIEP]                                NVARCHAR (255) NULL,
    [AUX PRESEN]                                     NVARCHAR (255) NULL,
    [pto 2]                                          NVARCHAR (255) NULL,
    [COMENTARIOS]                                    NVARCHAR (255) NULL,
    [Monto Aprobado Certificado]                     FLOAT (53)     NULL,
    [Monto Pendiente Certificar]                     FLOAT (53)     NULL,
    [CGE Aprobado Pemex]                             NVARCHAR (255) NULL,
    [AÑO DE CERTIFICADO]                             NVARCHAR (255) NULL,
    [MES DE CERTIFICADO]                             NVARCHAR (255) NULL,
    [Estatuts_Certificado]                           NVARCHAR (255) NULL,
    [Cuenta Operativa]                               NVARCHAR (255) NULL,
    [Actividad]                                      NVARCHAR (255) NULL,
    [Rubro]                                          NVARCHAR (255) NULL,
    [Servicio]                                       NVARCHAR (255) NULL,
    [Aplicación Especifica]                          NVARCHAR (255) NULL,
    [Pozo / Instalación]                             NVARCHAR (255) NULL,
    [F57]                                            NVARCHAR (255) NULL,
    [F58]                                            NVARCHAR (255) NULL,
    [F59]                                            NVARCHAR (255) NULL,
    [F60]                                            NVARCHAR (255) NULL,
    [F61]                                            NVARCHAR (255) NULL,
    [F62]                                            NVARCHAR (255) NULL,
    [F63]                                            NVARCHAR (255) NULL,
    [F64]                                            NVARCHAR (255) NULL,
    [F65]                                            NVARCHAR (255) NULL,
    [F66]                                            NVARCHAR (255) NULL,
    [F67]                                            NVARCHAR (255) NULL,
    [F68]                                            NVARCHAR (255) NULL,
    [F69]                                            NVARCHAR (255) NULL,
    [F70]                                            NVARCHAR (255) NULL,
    [F71]                                            NVARCHAR (255) NULL,
    [F72]                                            NVARCHAR (255) NULL,
    [F73]                                            NVARCHAR (255) NULL,
    [F74]                                            NVARCHAR (255) NULL,
    [F75]                                            NVARCHAR (255) NULL,
    [F76]                                            NVARCHAR (255) NULL,
    [F77]                                            NVARCHAR (255) NULL,
    [F78]                                            NVARCHAR (255) NULL,
    [F79]                                            NVARCHAR (255) NULL,
    [F80]                                            NVARCHAR (255) NULL,
    [F81]                                            NVARCHAR (255) NULL,
    [F82]                                            NVARCHAR (255) NULL,
    [F83]                                            NVARCHAR (255) NULL,
    [F84]                                            NVARCHAR (255) NULL,
    [F85]                                            NVARCHAR (255) NULL,
    [F86]                                            NVARCHAR (255) NULL,
    [F87]                                            NVARCHAR (255) NULL,
    [F88]                                            NVARCHAR (255) NULL,
    [F89]                                            NVARCHAR (255) NULL,
    [F90]                                            NVARCHAR (255) NULL,
    [F91]                                            NVARCHAR (255) NULL,
    [F92]                                            NVARCHAR (255) NULL,
    [F93]                                            NVARCHAR (255) NULL,
    [F94]                                            NVARCHAR (255) NULL,
    [F95]                                            NVARCHAR (255) NULL,
    [F96]                                            NVARCHAR (255) NULL,
    [F97]                                            NVARCHAR (255) NULL,
    [F98]                                            NVARCHAR (255) NULL,
    [F99]                                            NVARCHAR (255) NULL,
    [F100]                                           NVARCHAR (255) NULL,
    [F101]                                           NVARCHAR (255) NULL,
    [F102]                                           NVARCHAR (255) NULL,
    [F103]                                           NVARCHAR (255) NULL,
    [F104]                                           NVARCHAR (255) NULL,
    [F105]                                           NVARCHAR (255) NULL,
    [F106]                                           NVARCHAR (255) NULL,
    [F107]                                           NVARCHAR (255) NULL,
    [F108]                                           NVARCHAR (255) NULL,
    [F109]                                           NVARCHAR (255) NULL,
    [F110]                                           NVARCHAR (255) NULL,
    [F111]                                           NVARCHAR (255) NULL,
    [F112]                                           NVARCHAR (255) NULL,
    [F113]                                           NVARCHAR (255) NULL,
    [F114]                                           NVARCHAR (255) NULL,
    [F115]                                           NVARCHAR (255) NULL,
    [F116]                                           NVARCHAR (255) NULL,
    [F117]                                           NVARCHAR (255) NULL,
    [F118]                                           NVARCHAR (255) NULL,
    [F119]                                           NVARCHAR (255) NULL,
    [F120]                                           NVARCHAR (255) NULL,
    [F121]                                           NVARCHAR (255) NULL,
    [F122]                                           NVARCHAR (255) NULL,
    [F123]                                           NVARCHAR (255) NULL,
    [F124]                                           NVARCHAR (255) NULL,
    [F125]                                           NVARCHAR (255) NULL,
    [F126]                                           NVARCHAR (255) NULL,
    [F127]                                           NVARCHAR (255) NULL,
    [F128]                                           NVARCHAR (255) NULL,
    [F129]                                           NVARCHAR (255) NULL,
    [F130]                                           NVARCHAR (255) NULL,
    [F131]                                           NVARCHAR (255) NULL,
    [F132]                                           NVARCHAR (255) NULL,
    [F133]                                           NVARCHAR (255) NULL,
    [F134]                                           NVARCHAR (255) NULL,
    [F135]                                           NVARCHAR (255) NULL,
    [F136]                                           NVARCHAR (255) NULL,
    [F137]                                           NVARCHAR (255) NULL,
    [F138]                                           NVARCHAR (255) NULL,
    [F139]                                           NVARCHAR (255) NULL,
    [F140]                                           NVARCHAR (255) NULL,
    [F141]                                           NVARCHAR (255) NULL,
    [F142]                                           NVARCHAR (255) NULL,
    [F143]                                           NVARCHAR (255) NULL,
    [F144]                                           NVARCHAR (255) NULL,
    [F145]                                           NVARCHAR (255) NULL,
    [F146]                                           NVARCHAR (255) NULL,
    [F147]                                           NVARCHAR (255) NULL,
    [F148]                                           NVARCHAR (255) NULL,
    [F149]                                           NVARCHAR (255) NULL,
    [F150]                                           NVARCHAR (255) NULL,
    [F151]                                           NVARCHAR (255) NULL,
    [F152]                                           NVARCHAR (255) NULL,
    [F153]                                           NVARCHAR (255) NULL,
    [F154]                                           NVARCHAR (255) NULL,
    [F155]                                           NVARCHAR (255) NULL,
    [F156]                                           NVARCHAR (255) NULL,
    [F157]                                           NVARCHAR (255) NULL,
    [F158]                                           NVARCHAR (255) NULL,
    [F159]                                           NVARCHAR (255) NULL,
    [F160]                                           NVARCHAR (255) NULL,
    [F161]                                           NVARCHAR (255) NULL,
    [F162]                                           NVARCHAR (255) NULL,
    [F163]                                           NVARCHAR (255) NULL,
    [F164]                                           NVARCHAR (255) NULL,
    [F165]                                           NVARCHAR (255) NULL,
    [F166]                                           NVARCHAR (255) NULL,
    [F167]                                           NVARCHAR (255) NULL,
    [F168]                                           NVARCHAR (255) NULL,
    [F169]                                           NVARCHAR (255) NULL,
    [F170]                                           NVARCHAR (255) NULL,
    [F171]                                           NVARCHAR (255) NULL,
    [F172]                                           NVARCHAR (255) NULL,
    [F173]                                           NVARCHAR (255) NULL,
    [F174]                                           NVARCHAR (255) NULL,
    [F175]                                           NVARCHAR (255) NULL,
    [F176]                                           NVARCHAR (255) NULL,
    [F177]                                           NVARCHAR (255) NULL,
    [F178]                                           NVARCHAR (255) NULL,
    [F179]                                           NVARCHAR (255) NULL,
    [F180]                                           NVARCHAR (255) NULL,
    [F181]                                           NVARCHAR (255) NULL,
    [F182]                                           NVARCHAR (255) NULL,
    [F183]                                           NVARCHAR (255) NULL,
    [F184]                                           NVARCHAR (255) NULL,
    [F185]                                           NVARCHAR (255) NULL,
    [F186]                                           NVARCHAR (255) NULL,
    [F187]                                           NVARCHAR (255) NULL,
    [F188]                                           NVARCHAR (255) NULL,
    [F189]                                           NVARCHAR (255) NULL,
    [F190]                                           NVARCHAR (255) NULL
);

