CREATE TABLE [dbo].[TMP_Jaguar_V00] (
    [F1]                            FLOAT (53)     NULL,
    [Contratista]                   NVARCHAR (255) NULL,
    [Numero de Contrato]            NVARCHAR (255) NULL,
    [Bloque]                        NVARCHAR (255) NULL,
    [Fecha Presentación]            FLOAT (53)     NULL,
    [Fecha Aprobación]              FLOAT (53)     NULL,
    [id_Actividad petrolera]        NVARCHAR (255) NULL,
    [Actividad petrolera]           NVARCHAR (255) NULL,
    [id_Sub-actividad petrolera]    NVARCHAR (255) NULL,
    [Sub-actividad petrolera]       NVARCHAR (255) NULL,
    [id_Tarea]                      NVARCHAR (255) NULL,
    [Tarea]                         NVARCHAR (255) NULL,
    [id_Sub-tarea]                  NVARCHAR (255) NULL,
    [Sub-tarea]                     NVARCHAR (255) NULL,
    [Elegible]                      NVARCHAR (255) NULL,
    [Area]                          NVARCHAR (255) NULL,
    [Campo*]                        NVARCHAR (255) NULL,
    [Yacimiento*]                   NVARCHAR (255) NULL,
    [Pozo]                          NVARCHAR (255) NULL,
    [Mano de Obra ($)]              NVARCHAR (255) NULL,
    [F21]                           NVARCHAR (255) NULL,
    [Bienes ($)]                    NVARCHAR (255) NULL,
    [F23]                           NVARCHAR (255) NULL,
    [ Servicios ($)]                FLOAT (53)     NULL,
    [F25]                           FLOAT (53)     NULL,
    [Capacitación ($)]              NVARCHAR (255) NULL,
    [F27]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia]   NVARCHAR (255) NULL,
    [Infraestructura (Social)]      NVARCHAR (255) NULL,
    [Mano de Obra ($)1]             NVARCHAR (255) NULL,
    [F31]                           NVARCHAR (255) NULL,
    [Bienes ($)1]                   NVARCHAR (255) NULL,
    [F33]                           NVARCHAR (255) NULL,
    [ Servicios ($)1]               FLOAT (53)     NULL,
    [F35]                           FLOAT (53)     NULL,
    [Capacitación ($)1]             NVARCHAR (255) NULL,
    [F37]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia1]  NVARCHAR (255) NULL,
    [Infraestructura (Social)1]     NVARCHAR (255) NULL,
    [Mano de Obra ($)2]             NVARCHAR (255) NULL,
    [F41]                           NVARCHAR (255) NULL,
    [Bienes ($)2]                   NVARCHAR (255) NULL,
    [F43]                           NVARCHAR (255) NULL,
    [ Servicios ($)2]               FLOAT (53)     NULL,
    [F45]                           FLOAT (53)     NULL,
    [Capacitación ($)2]             NVARCHAR (255) NULL,
    [F47]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia2]  NVARCHAR (255) NULL,
    [Infraestructura (Social)2]     NVARCHAR (255) NULL,
    [Mano de Obra ($)3]             NVARCHAR (255) NULL,
    [F51]                           NVARCHAR (255) NULL,
    [Bienes ($)3]                   NVARCHAR (255) NULL,
    [F53]                           NVARCHAR (255) NULL,
    [ Servicios ($)3]               FLOAT (53)     NULL,
    [F55]                           FLOAT (53)     NULL,
    [Capacitación ($)3]             NVARCHAR (255) NULL,
    [F57]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia3]  NVARCHAR (255) NULL,
    [Infraestructura (Social)3]     NVARCHAR (255) NULL,
    [Mano de Obra ($)4]             NVARCHAR (255) NULL,
    [F61]                           NVARCHAR (255) NULL,
    [Bienes ($)4]                   NVARCHAR (255) NULL,
    [F63]                           NVARCHAR (255) NULL,
    [ Servicios ($)4]               FLOAT (53)     NULL,
    [F65]                           FLOAT (53)     NULL,
    [Capacitación ($)4]             NVARCHAR (255) NULL,
    [F67]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia4]  NVARCHAR (255) NULL,
    [Infraestructura (Social)4]     NVARCHAR (255) NULL,
    [Mano de Obra ($)5]             NVARCHAR (255) NULL,
    [F71]                           NVARCHAR (255) NULL,
    [Bienes ($)5]                   NVARCHAR (255) NULL,
    [F73]                           NVARCHAR (255) NULL,
    [ Servicios ($)5]               FLOAT (53)     NULL,
    [F75]                           FLOAT (53)     NULL,
    [Capacitación ($)5]             NVARCHAR (255) NULL,
    [F77]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia5]  NVARCHAR (255) NULL,
    [Infraestructura (Social)5]     NVARCHAR (255) NULL,
    [Mano de Obra ($)6]             NVARCHAR (255) NULL,
    [F81]                           NVARCHAR (255) NULL,
    [Bienes ($)6]                   NVARCHAR (255) NULL,
    [F83]                           NVARCHAR (255) NULL,
    [ Servicios ($)6]               FLOAT (53)     NULL,
    [F85]                           FLOAT (53)     NULL,
    [Capacitación ($)6]             NVARCHAR (255) NULL,
    [F87]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia6]  NVARCHAR (255) NULL,
    [Infraestructura (Social)6]     NVARCHAR (255) NULL,
    [Mano de Obra ($)7]             NVARCHAR (255) NULL,
    [F91]                           NVARCHAR (255) NULL,
    [Bienes ($)7]                   NVARCHAR (255) NULL,
    [F93]                           NVARCHAR (255) NULL,
    [ Servicios ($)7]               FLOAT (53)     NULL,
    [F95]                           FLOAT (53)     NULL,
    [Capacitación ($)7]             NVARCHAR (255) NULL,
    [F97]                           NVARCHAR (255) NULL,
    [Transferencia de Tecnologia7]  NVARCHAR (255) NULL,
    [Infraestructura (Social)7]     NVARCHAR (255) NULL,
    [Mano de Obra ($)8]             NVARCHAR (255) NULL,
    [F101]                          NVARCHAR (255) NULL,
    [Bienes ($)8]                   NVARCHAR (255) NULL,
    [F103]                          NVARCHAR (255) NULL,
    [ Servicios ($)8]               FLOAT (53)     NULL,
    [F105]                          FLOAT (53)     NULL,
    [Capacitación ($)8]             NVARCHAR (255) NULL,
    [F107]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia8]  NVARCHAR (255) NULL,
    [Infraestructura (Social)8]     NVARCHAR (255) NULL,
    [Mano de Obra ($)9]             NVARCHAR (255) NULL,
    [F111]                          NVARCHAR (255) NULL,
    [Bienes ($)9]                   NVARCHAR (255) NULL,
    [F113]                          NVARCHAR (255) NULL,
    [ Servicios ($)9]               NVARCHAR (255) NULL,
    [F115]                          NVARCHAR (255) NULL,
    [Capacitación ($)9]             NVARCHAR (255) NULL,
    [F117]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia9]  NVARCHAR (255) NULL,
    [Infraestructura (Social)9]     NVARCHAR (255) NULL,
    [Mano de Obra ($)10]            NVARCHAR (255) NULL,
    [F121]                          NVARCHAR (255) NULL,
    [Bienes ($)10]                  NVARCHAR (255) NULL,
    [F123]                          NVARCHAR (255) NULL,
    [ Servicios ($)10]              NVARCHAR (255) NULL,
    [F125]                          NVARCHAR (255) NULL,
    [Capacitación ($)10]            NVARCHAR (255) NULL,
    [F127]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia10] NVARCHAR (255) NULL,
    [Infraestructura (Social)10]    NVARCHAR (255) NULL,
    [Mano de Obra ($)11]            NVARCHAR (255) NULL,
    [F131]                          NVARCHAR (255) NULL,
    [Bienes ($)11]                  NVARCHAR (255) NULL,
    [F133]                          NVARCHAR (255) NULL,
    [ Servicios ($)11]              NVARCHAR (255) NULL,
    [F135]                          NVARCHAR (255) NULL,
    [Capacitación ($)11]            NVARCHAR (255) NULL,
    [F137]                          NVARCHAR (255) NULL,
    [Transferencia de Tecnologia11] NVARCHAR (255) NULL,
    [Infraestructura (Social)11]    NVARCHAR (255) NULL,
    [Mano de Obra ($)12]            FLOAT (53)     NULL,
    [F141]                          FLOAT (53)     NULL,
    [Bienes ($)12]                  FLOAT (53)     NULL,
    [F143]                          FLOAT (53)     NULL,
    [ Servicios ($)12]              FLOAT (53)     NULL,
    [F145]                          FLOAT (53)     NULL,
    [Capacitación ($)12]            FLOAT (53)     NULL,
    [F147]                          FLOAT (53)     NULL,
    [Transferencia_de Tecnologia]   FLOAT (53)     NULL,
    [Infraestructura (Social)12]    FLOAT (53)     NULL,
    [F150]                          FLOAT (53)     NULL
);

