CREATE TABLE [dbo].[tmpfacturas] (
    [IdFactura]             INT             NOT NULL,
    [Serie]                 NVARCHAR (MAX)  NULL,
    [Folio]                 NVARCHAR (MAX)  NULL,
    [Fecha]                 DATETIME        NULL,
    [Sello]                 NVARCHAR (MAX)  NULL,
    [FormaPago]             NVARCHAR (MAX)  NULL,
    [NoCertificado]         NVARCHAR (MAX)  NULL,
    [Certificado]           NVARCHAR (MAX)  NULL,
    [CondicionesDePago]     NVARCHAR (MAX)  NULL,
    [SubTotal]              MONEY           NULL,
    [Descuento]             MONEY           NULL,
    [TipoCambio]            MONEY           NULL,
    [Moneda]                NVARCHAR (MAX)  NULL,
    [MontoConIva]           DECIMAL (18, 4) NULL,
    [TipoComprobante]       NVARCHAR (MAX)  NULL,
    [MetodoPago]            NVARCHAR (MAX)  NULL,
    [LugarExpedicion]       NVARCHAR (MAX)  NULL,
    [NumCtaPago]            NVARCHAR (MAX)  NULL,
    [Emisor]                NVARCHAR (MAX)  NULL,
    [Receptor]              NVARCHAR (MAX)  NULL,
    [UUID]                  NVARCHAR (MAX)  NULL,
    [FechaTimbrado]         DATETIME        NULL,
    [SelloCFD]              NVARCHAR (MAX)  NULL,
    [NoCertificadoSAT]      NVARCHAR (MAX)  NULL,
    [SelloSAT]              NVARCHAR (MAX)  NULL,
    [Tipo]                  NVARCHAR (MAX)  NULL,
    [FechaRecepcion]        DATETIME        NULL,
    [Activa]                BIT             NULL,
    [PDF]                   VARBINARY (MAX) NULL,
    [IdFacturaConcepto]     BIGINT          NOT NULL,
    [Expr1]                 INT             NULL,
    [Descripcion]           VARCHAR (MAX)   NULL,
    [Cantidad]              FLOAT (53)      NULL,
    [Unidad]                NVARCHAR (MAX)  NULL,
    [ValorUnitario]         MONEY           NULL,
    [Importe]               MONEY           NULL,
    [NoIdentificacion]      NVARCHAR (MAX)  NULL,
    [IdPMI]                 INT             NOT NULL,
    [Expr3]                 INT             NULL,
    [FechaReporte]          DATE            NULL,
    [Sociedad]              NVARCHAR (255)  NULL,
    [Estado]                NVARCHAR (255)  NULL,
    [TipoDoc]               NVARCHAR (255)  NULL,
    [NombreCliente]         NVARCHAR (255)  NULL,
    [Expr4]                 NVARCHAR (255)  NULL,
    [Ejercicio]             NVARCHAR (255)  NULL,
    [Expr5]                 NVARCHAR (255)  NULL,
    [Factura]               NVARCHAR (255)  NULL,
    [Expr6]                 NVARCHAR (255)  NULL,
    [Expr7]                 NVARCHAR (255)  NULL,
    [FechaFactura]          NVARCHAR (50)   NULL,
    [TipoComp]              NVARCHAR (255)  NULL,
    [Expr8]                 MONEY           NULL,
    [Impuestos]             MONEY           NULL,
    [Total]                 MONEY           NULL,
    [FechaExpedicion]       NVARCHAR (50)   NULL,
    [Expr9]                 NVARCHAR (50)   NULL,
    [Tasa]                  FLOAT (53)      NULL,
    [ClaveCliente]          NVARCHAR (255)  NULL,
    [Expr10]                NVARCHAR (255)  NULL,
    [Expr11]                NVARCHAR (50)   NULL,
    [Expr12]                NVARCHAR (255)  NULL,
    [IdComercializacion]    INT             NULL,
    [Expr15]                INT             NULL,
    [Expr16]                DATE            NULL,
    [Expr17]                NVARCHAR (255)  NULL,
    [Expr18]                NVARCHAR (50)   NULL,
    [Expr19]                NVARCHAR (255)  NULL,
    [ValorNeto]             FLOAT (53)      NULL,
    [MonedaValNeto]         NVARCHAR (255)  NULL,
    [ImporteImpuesto]       FLOAT (53)      NULL,
    [Referencia1]           NVARCHAR (255)  NULL,
    [CantidadFacturada]     FLOAT (53)      NULL,
    [UniMedidaVenta]        NVARCHAR (255)  NULL,
    [Material]              NVARCHAR (255)  NULL,
    [Denominación]          NVARCHAR (255)  NULL,
    [NoDocumento]           NVARCHAR (255)  NULL,
    [Expr20]                NVARCHAR (255)  NULL,
    [Expr21]                NVARCHAR (255)  NULL,
    [Expr22]                NVARCHAR (255)  NULL,
    [MonedaLocal]           NVARCHAR (255)  NULL,
    [Referencia2]           NVARCHAR (255)  NULL,
    [Expr23]                FLOAT (53)      NULL,
    [ImporteML]             FLOAT (53)      NULL,
    [PosPresupuestaria]     NVARCHAR (255)  NULL,
    [CentroGestor]          NVARCHAR (255)  NULL,
    [CuentaMayor]           NVARCHAR (255)  NULL,
    [DocCompensación]       NVARCHAR (255)  NULL,
    [OrganizaciónVentas]    NVARCHAR (255)  NULL,
    [CanalDistribución]     NVARCHAR (255)  NULL,
    [Sector]                NVARCHAR (255)  NULL,
    [Centro]                NVARCHAR (255)  NULL,
    [Nombre1]               NVARCHAR (255)  NULL,
    [PuestoCarga]           NVARCHAR (255)  NULL,
    [Denominación1]         NVARCHAR (255)  NULL,
    [Energía]               FLOAT (53)      NULL,
    [UnidadSalidaCondición] NVARCHAR (255)  NULL,
    [Cliente]               NVARCHAR (255)  NULL,
    [NombreCliente1]        NVARCHAR (255)  NULL,
    [ImporteDolares]        FLOAT (53)      NULL,
    [MonedaDolares]         NVARCHAR (255)  NULL,
    [NombreCliente2]        NVARCHAR (255)  NULL,
    [OficinaVentas]         NVARCHAR (255)  NULL,
    [GpoCond]               NVARCHAR (255)  NULL,
    [NoOrden]               NVARCHAR (255)  NULL,
    [PedCliente]            NVARCHAR (255)  NULL,
    [PlanEntrega]           NVARCHAR (255)  NULL,
    [FechaComp]             NVARCHAR (50)   NULL,
    [FechaPago]             NVARCHAR (50)   NULL,
    [FTesorería]            NVARCHAR (50)   NULL,
    [FDPP1]                 FLOAT (53)      NULL,
    [FDPPV]                 FLOAT (53)      NULL
);

