CREATE TABLE [dbo].[Tonalli2018] (
    [ID]    FLOAT (53)      NULL,
    [PA_04] NVARCHAR (255)  NULL,
    [PA_05] NVARCHAR (255)  NULL,
    [PA_06] NVARCHAR (255)  NULL,
    [PA_07] NVARCHAR (255)  NULL,
    [PA_08] NVARCHAR (255)  NULL,
    [PA_09] NVARCHAR (255)  NULL,
    [PA_10] NVARCHAR (255)  NULL,
    [PA_11] NVARCHAR (2000) NULL,
    [PA_13] FLOAT (53)      NULL,
    [PA_14] NVARCHAR (255)  NULL,
    [PA_15] NVARCHAR (255)  NULL,
    [PA_16] NVARCHAR (255)  NULL,
    [PA_17] MONEY           NULL,
    [PA_18] MONEY           NULL,
    [PA_19] MONEY           NULL,
    [PA_20] MONEY           NULL,
    [PA_21] MONEY           NULL,
    [PA_22] MONEY           NULL,
    [PA_23] MONEY           NULL,
    [PA_24] MONEY           NULL,
    [PA_25] MONEY           NULL,
    [PA_26] MONEY           NULL,
    [PA_27] MONEY           NULL,
    [PA_28] MONEY           NULL,
    [PA_29] MONEY           NULL,
    [PA_30] MONEY           NULL,
    [PA_31] MONEY           NULL,
    [PA_32] MONEY           NULL,
    [PA_33] MONEY           NULL,
    [PA_34] MONEY           NULL,
    [PA_35] MONEY           NULL,
    [PA_36] MONEY           NULL
);

