CREATE TABLE [dbo].[TranferenciasPCM] (
    [FECHA_FACTURA]            DATETIME       NULL,
    [RFC_EMISOR]               NVARCHAR (255) NULL,
    [NOMBRE_PROVEEDOR]         NVARCHAR (255) NULL,
    [FORMA_PAGO]               NVARCHAR (255) NULL,
    [BANCO_ORIGEN]             NVARCHAR (255) NULL,
    [CUENTA_ORIGEN]            NVARCHAR (255) NULL,
    [BANCO_DESTINO]            NVARCHAR (255) NULL,
    [CUENTA_DESTINO]           NVARCHAR (255) NULL,
    [FECHA_PAGO]               DATETIME       NULL,
    [MONTO_PAGADO]             FLOAT (53)     NULL,
    [INTERES]                  FLOAT (53)     NULL,
    [MONEDA_PAGO]              NVARCHAR (255) NULL,
    [CONCEPTO]                 NVARCHAR (255) NULL,
    [NO_POLIZA]                FLOAT (53)     NULL,
    [UUID]                     NVARCHAR (255) NULL,
    [VALOR_FACTURA]            FLOAT (53)     NULL,
    [MONEDA_FACTURA]           NVARCHAR (255) NULL,
    [IdCuentaOrigen]           INT            NULL,
    [IdCuentaDestino]          INT            NULL,
    [IdMoneda]                 INT            NULL,
    [IdClasificacionDocumento] INT            NULL,
    [IdMetodoPago]             INT            NULL,
    [IdFactura]                INT            NULL,
    [IdProveedor]              INT            NULL,
    [IdTransfer]               INT            NULL
);

