CREATE TABLE [dbo].[WS_Transferencia] (
    [IdWSTransfer]             INT           NOT NULL,
    [IdContratistaSIPAC]       VARCHAR (20)  NULL,
    [IdFiduciarioContrato]     VARCHAR (100) NULL,
    [PeriodoReporte]           DATETIME      NULL,
    [IdComprobantePago]        VARCHAR (50)  NULL,
    [NombreArchivoAsociado]    VARCHAR (250) NULL,
    [ReferenciaBancariaOp]     VARCHAR (50)  NULL,
    [FechaPago]                DATETIME      NULL,
    [Beneficiario]             VARCHAR (250) NULL,
    [MontoPagado]              MONEY         NULL,
    [MonedaNacional]           VARCHAR (10)  NULL,
    [CuentaOrigen]             VARCHAR (20)  NULL,
    [BancoOrigenNacional]      VARCHAR (50)  NULL,
    [BancoOrigenExtranjero]    VARCHAR (50)  NULL,
    [CuentaDestino]            VARCHAR (20)  NULL,
    [BancoDestinoNacional]     VARCHAR (50)  NULL,
    [BancoDestinoExtranjero]   VARCHAR (50)  NULL,
    [MontoEquivalenteUSD]      MONEY         NULL,
    [TipoCambioUSD]            MONEY         NULL,
    [IdClasificacionDocumento] INT           NULL,
    [ChequeNumero]             VARCHAR (10)  NULL,
    [MontoPagadoLetra]         VARCHAR (250) NULL,
    [WSFechaRegistro]          DATETIME      NULL,
    [WSError]                  VARCHAR (250) NULL,
    [TransferenciaAplicada]    BIT           NULL,
    CONSTRAINT [PK_WS_Transfer] PRIMARY KEY CLUSTERED ([IdWSTransfer] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

