CREATE TABLE [dbo].[A_PIActividadMalva] (
    [RF_00]                   NVARCHAR (255) NULL,
    [PA_00]                   NVARCHAR (255) NULL,
    [PA_01]                   NVARCHAR (255) NULL,
    [PA_02]                   DATE           NULL,
    [PA_03]                   DATE           NULL,
    [PA_04]                   NVARCHAR (255) NULL,
    [PA_05]                   NVARCHAR (255) NULL,
    [PA_06]                   NVARCHAR (255) NULL,
    [PA_07]                   NVARCHAR (255) NULL,
    [PA_08]                   NVARCHAR (255) NULL,
    [PA_09]                   NVARCHAR (255) NULL,
    [PA_10]                   NVARCHAR (255) NULL,
    [PA_11]                   NVARCHAR (255) NULL,
    [PA_12]                   FLOAT (53)     NULL,
    [PA_13]                   FLOAT (53)     NULL,
    [PA_14]                   FLOAT (53)     NULL,
    [PA_15]                   FLOAT (53)     NULL,
    [PA_16]                   FLOAT (53)     NULL,
    [PA_17]                   FLOAT (53)     NULL,
    [PA_18]                   FLOAT (53)     NULL,
    [PA_19]                   FLOAT (53)     NULL,
    [PA_20]                   FLOAT (53)     NULL,
    [PA_21]                   FLOAT (53)     NULL,
    [PA_22]                   FLOAT (53)     NULL,
    [PA_23]                   FLOAT (53)     NULL,
    [IdActividadPetrolera]    INT            NULL,
    [IdSubactividadPetrolera] INT            NULL,
    [IdTareaPetrolera]        INT            NULL,
    [IdSubtareaPetrolera]     INT            NULL
);

