CREATE TABLE [dbo].[AA_FMP_53] (
    [ID del contratista asignado por el SIPAC (RF_00)]                 NVARCHAR (255) NULL,
    [ID registro fiduciario del contrato (RI_00)]                      NVARCHAR (255) NULL,
    [ID del contrato asignado por CNH (RF01_01)]                       NVARCHAR (255) NULL,
    [Mes de reporte (RM53_00)]                                         NVARCHAR (255) NULL,
    [Año de reporte (RM53_01)]                                         NVARCHAR (255) NULL,
    [Cálculo de contraprestaciones en efectivo a favor del Estado: Cu] NVARCHAR (255) NULL,
    [Cálculo de contraprestaciones en efectivo a favor del Estado: Pa] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor del] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de1] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de2] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de3] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de4] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de5] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de6] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de7] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de8] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor de9] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor d10] NVARCHAR (255) NULL,
    [Volumen calculado por concepto de Distribución Final a favor d11] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto d] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto 1] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto 2] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto 3] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto 4] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Estado en el punto 5] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el pu] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el p1] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el p2] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el p3] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el p4] NVARCHAR (255) NULL,
    [Volumen total efectivamente recibido por el Contratista en el p5] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de petróleo a favor] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de metano a favor d] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de etano a favor de] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de propano a favor ] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de butano a favor d] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de condensados a fa] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de petróleo a favo1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de metano a favor 1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de etano a favor d1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de propano a favor1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de butano a favor 1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Saldo acumulado de condensados a f1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de petróleo a] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de metano a f] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de etano a fa] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de propano a ] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de butano a f] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de condensado] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de petróleo 1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de metano a 1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de etano a f1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de propano a1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de butano a 1] NVARCHAR (255) NULL,
    [Compensaciones volumétricas: Nuevo saldo acumulado de condensad1] NVARCHAR (255) NULL,
    [Nueva Distribución Provisional a favor del Estado (RM53_52)]      NVARCHAR (255) NULL,
    [Nueva Distribución Provisional a favor del Contratista (RM53_53)] NVARCHAR (255) NULL,
    [Estado (activo)]                                                  VARCHAR (255)  NULL,
    [Fecha registro (fechaRegistro)]                                   VARCHAR (255)  NULL
);

