CREATE TABLE [dbo].[AA_FMP_54] (
    [ID del contratista asignado por el SIPAC (RF_00)]                 NVARCHAR (255) NULL,
    [ID registro fiduciario del contrato (RI_00)]                      NVARCHAR (255) NULL,
    [ID del contrato asignado por CNH (RF01_01)]                       NVARCHAR (255) NULL,
    [Mes de reporte (RM54_00)]                                         NVARCHAR (255) NULL,
    [Año de reporte (RM54_01)]                                         NVARCHAR (255) NULL,
    [Producción: Volumen contractual de petróleo (RM54_02)]            NVARCHAR (255) NULL,
    [Volumen contractual: producción de metano de gas natural asociad] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de etano de gas natural asociado] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de propano de gas natural asocia] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de butano de gas natural asociad] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de metano de gas natural no asoc] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de etano de gas natural no asoci] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de propano de gas natural no aso] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de butano de gas natural no asoc] NVARCHAR (255) NULL,
    [Producción: Volumen contractual de condensados (RM54_11)]         NVARCHAR (255) NULL,
    [Precio contractual: petróleo (RM54_12)]                           NVARCHAR (255) NULL,
    [Precio contractual: metano (RM54_13)]                             NVARCHAR (255) NULL,
    [Precio contractual: etano (RM54_14)]                              NVARCHAR (255) NULL,
    [Precio contractual: propano (RM54_15)]                            NVARCHAR (255) NULL,
    [Precio contractual: butano (RM54_16)]                             NVARCHAR (255) NULL,
    [Precio contractual: condensados (RM54_17)]                        NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contrac] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra1] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra2] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra3] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra4] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra5] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Pe] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Me] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Et] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Pr] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Bu] NVARCHAR (255) NULL,
    [Se aplicó ajuste por utilizar fórmula en periodos anteriores: Co] NVARCHAR (255) NULL,
    [Valor contractual: petróleo (RM54_30)]                            NVARCHAR (255) NULL,
    [Valor contractual: metano de gas natural asociado (RM54_31)]      NVARCHAR (255) NULL,
    [Valor contractual: etano de gas natural asociado (RM54_32)]       NVARCHAR (255) NULL,
    [Valor contractual: propano de gas natural asociado (RM54_33)]     NVARCHAR (255) NULL,
    [Valor contractual: butano de gas natural asociado (RM54_34)]      NVARCHAR (255) NULL,
    [Valor contractual: metano de gas natural no asociado (RM54_35)]   NVARCHAR (255) NULL,
    [Valor contractual: etano de gas natural no asociado (RM54_36)]    NVARCHAR (255) NULL,
    [Valor contractual: propano de gas natural no asociado (RM54_37)]  NVARCHAR (255) NULL,
    [Valor contractual: butano de gas natural no asociado (RM54_38)]   NVARCHAR (255) NULL,
    [Valor contractual: condensados (RM54_39)]                         NVARCHAR (255) NULL,
    [Total del valor contractual de los hidrocarburos (RM54_40)]       NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: petróleo (RM54_4] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas na] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas nat] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas n] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas na] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas n1] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas na1] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas 1] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas n1] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: condensados (RM5] NVARCHAR (255) NULL,
    [Monto de Regalía Base (RM54_51)]                                  NVARCHAR (255) NULL,
    [Costos registrados por el contratista: Recuperables reconocidos ] NVARCHAR (255) NULL,
    [Costos registrados por el contratista:  No reconocidos (RM54_53)] NVARCHAR (255) NULL,
    [Recuperación de costos por concepto de gastos de operación (RM54] NVARCHAR (255) NULL,
    [Recuperación de costos por concepto de gastos de inversión (RM54] NVARCHAR (255) NULL,
    [Total de costos recuperados (RM54_56)]                            NVARCHAR (255) NULL,
    [¿Se alcanzó el límite de recuperación de costos? (RM54_57)]       NVARCHAR (255) NULL,
    [Saldo de costos recuperables remanentes al final del periodo (RM] NVARCHAR (255) NULL,
    [Utilidad Operativa (RM54_59)]                                     NVARCHAR (255) NULL,
    [Métrica del Resultado Operativo del Contratista del periodo ante] NVARCHAR (255) NULL,
    [¿Se activó el mecanismo de ajuste? (RM54_61)]                     NVARCHAR (255) NULL,
    ["Participación del Estado sobre la Utilidad Operativa SCA_t" (RM] NVARCHAR (255) NULL,
    ["Participación del contratista sobre la Utilidad Operativa SG_t"] NVARCHAR (255) NULL,
    [Contraprestación por Utilidad Operativa a favor del Estado (RM54] NVARCHAR (255) NULL,
    [Contraprestación por Utilidad Operativa a favor del contratista ] NVARCHAR (255) NULL
);

