CREATE TABLE [dbo].[ACTIVIDADESCRISTEL_RESP] (
    [IDCONTRATOENTREGABLE] INT NOT NULL,
    [ACTIVIDADID]          INT NOT NULL,
    [ESTADOID]             INT NOT NULL,
    [IDUSUARIO]            INT NOT NULL
);

