CREATE TABLE [dbo].[AP_Rutas] (
    [idRuta] INT            IDENTITY (10000, 1) NOT NULL,
    [Ruta]   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([idRuta] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

