CREATE TABLE [dbo].[BG01202301] (
    [IdGasto]           INT            IDENTITY (1, 1) NOT NULL,
    [RFCFactura]        NVARCHAR (255) NULL,
    [FechaRegistro]     FLOAT (53)     NULL,
    [FechaFactura]      FLOAT (53)     NULL,
    [PolizaGasto]       NVARCHAR (255) NULL,
    [NumCuenta]         FLOAT (53)     NULL,
    [NombreCuenta]      NVARCHAR (255) NULL,
    [TareaProyecto]     NVARCHAR (255) NULL,
    [CodigoOT]          FLOAT (53)     NULL,
    [Importe]           FLOAT (53)     NULL,
    [MonedaOriginal]    NVARCHAR (255) NULL,
    [ImporteOriginal]   FLOAT (53)     NULL,
    [Descripcion]       NVARCHAR (255) NULL,
    [DocExterno]        FLOAT (53)     NULL,
    [Procedencia]       NVARCHAR (255) NULL,
    [NombreProcedencia] NVARCHAR (255) NULL,
    [UUID]              NVARCHAR (255) NULL,
    [OrdenPago]         NVARCHAR (255) NULL,
    [TipoCambio]        FLOAT (53)     NULL,
    [ImporteUSD]        FLOAT (53)     NULL,
    [COdigoCN]          NVARCHAR (255) NULL,
    [ProporcionCN]      FLOAT (53)     NULL,
    [ContenidoNacional] FLOAT (53)     NULL,
    [Extranjero]        FLOAT (53)     NULL,
    [Bloque]            NVARCHAR (255) NULL,
    [PPTOCNH]           NVARCHAR (255) NULL,
    [CuentaCNH]         NVARCHAR (255) NULL,
    [PozoEstacion]      NVARCHAR (255) NULL,
    [Clave]             NVARCHAR (255) NULL,
    [Servicio]          NVARCHAR (255) NULL,
    [Procesado]         BIT            NULL
);

