CREATE TABLE [dbo].[CAMBIOSPRESUPJAGUAR2019_PARTE2] (
    [NumeroContrato]                   NVARCHAR (255) NULL,
    [NombreAreaContractual]            NVARCHAR (255) NULL,
    [IdRegistro]                       FLOAT (53)     NULL,
    [Servicio]                         NVARCHAR (255) NULL,
    [InstalacionPresupuestada]         NVARCHAR (255) NULL,
    [FechaInicio]                      DATETIME       NULL,
    [FechaFin]                         DATETIME       NULL,
    [TipoDocumento]                    NVARCHAR (255) NULL,
    [Numero]                           NVARCHAR (255) NULL,
    [FechaDocumento]                   DATETIME       NULL,
    [MontoUSD]                         FLOAT (53)     NULL,
    [Subcontratista]                   NVARCHAR (255) NULL,
    [InstalacionRegistro]              NVARCHAR (255) NULL,
    [InicioEjecucion]                  DATETIME       NULL,
    [FinEjecucion]                     DATETIME       NULL,
    [CreadoPor]                        NVARCHAR (255) NULL,
    [MontoRegistro]                    FLOAT (53)     NULL,
    [Moneda]                           NVARCHAR (255) NULL,
    [MesPresentacion]                  DATETIME       NULL,
    [TipoDeServicio]                   NVARCHAR (255) NULL,
    [Actividad]                        NVARCHAR (255) NULL,
    [SubActividad]                     NVARCHAR (255) NULL,
    [EstadoValidacion]                 NVARCHAR (255) NULL,
    [Area]                             NVARCHAR (255) NULL,
    [Comentarios]                      NVARCHAR (255) NULL,
    [Identificador]                    FLOAT (53)     NULL,
    [LineaPresupuesto]                 FLOAT (53)     NULL,
    [Presupuesto]                      NVARCHAR (255) NULL,
    [Mes]                              NVARCHAR (255) NULL,
    [Año]                              FLOAT (53)     NULL,
    [Mes2]                             NVARCHAR (255) NULL,
    [FechaTransferencia]               DATETIME       NULL,
    [MontoTransferencia]               FLOAT (53)     NULL,
    [Id_Tarea]                         NVARCHAR (255) NULL,
    [RubroCN]                          NVARCHAR (255) NULL,
    [PCN]                              FLOAT (53)     NULL,
    [MontoFactura]                     FLOAT (53)     NULL,
    [MonedaFactura]                    NVARCHAR (255) NULL,
    [UUID]                             NVARCHAR (255) NULL,
    [Tarea correcta]                   NVARCHAR (255) NULL,
    [Column1]                          NVARCHAR (255) NULL,
    [IdLineaPresupuestoMes_Nueva]      INT            NULL,
    [IdLineaPresupuestoMes_NoElegible] INT            NULL,
    [IdServicio_Nvo]                   INT            NULL
);

