CREATE TABLE [dbo].[CAMBIOSFECHAS] (
    [IDCONTRATOENTREGABLE]  INT           NULL,
    [CONTRATO]              VARCHAR (250) NULL,
    [NUEVAFRECUENCIA]       VARCHAR (250) NULL,
    [CONSECUTIVO]           VARCHAR (100) NULL,
    [NUEVOTIEMPOENTREGA]    VARCHAR (300) NULL,
    [IDINSTANCIAENTREGABLE] INT           NULL,
    [FECHAINICIOELAB]       DATE          NULL,
    [NUEVOSDIASELAB]        INT           NULL,
    [NUEVAFECHAINTERNA]     DATE          NULL,
    [NUEVAFECHAREGULADOR]   DATE          NULL,
    [COMENTARIOS]           VARCHAR (500) NULL,
    [IDCONTRATO]            INT           NULL,
    [IDENTREGABLE]          INT           NULL,
    [IDFRECUENCIA]          INT           NULL
);

