CREATE TABLE [dbo].[CambiosPresupJaguar2019] (
    [NumeroContrato]                   NVARCHAR (255) NULL,
    [NombreAreaContractual]            NVARCHAR (255) NULL,
    [IdRegistro]                       FLOAT (53)     NULL,
    [Servicio]                         NVARCHAR (255) NULL,
    [Numero]                           NVARCHAR (255) NULL,
    [FechaDocumento]                   DATETIME       NULL,
    [MontoUSD]                         FLOAT (53)     NULL,
    [Subcontratista]                   NVARCHAR (255) NULL,
    [SubActividad]                     NVARCHAR (255) NULL,
    [EstadoValidacion]                 NVARCHAR (255) NULL,
    [Area]                             NVARCHAR (255) NULL,
    [Identificador]                    FLOAT (53)     NULL,
    [LineaPresupuesto]                 FLOAT (53)     NULL,
    [Presupuesto]                      NVARCHAR (255) NULL,
    [Mes]                              NVARCHAR (255) NULL,
    [Año]                              FLOAT (53)     NULL,
    [Mes2]                             NVARCHAR (255) NULL,
    [FechaTransferencia]               DATETIME       NULL,
    [MontoTransferencia]               FLOAT (53)     NULL,
    [Id_Tarea]                         NVARCHAR (255) NULL,
    [RubroCN]                          NVARCHAR (255) NULL,
    [PCN]                              FLOAT (53)     NULL,
    [MontoFactura]                     FLOAT (53)     NULL,
    [MonedaFactura]                    NVARCHAR (255) NULL,
    [UUID]                             NVARCHAR (255) NULL,
    [Tarea correcta]                   NVARCHAR (255) NULL,
    [IdLineaPresupuestoMes_Nueva]      INT            NULL,
    [IdLineaPresupuestoMes_NoElegible] INT            NULL,
    [IdServicio_Nvo]                   INT            NULL
);

