CREATE TABLE [dbo].[cargaENI2020] (
    [ID]                  INT            NULL,
    [CONTRATO]            VARCHAR (150)  NULL,
    [CONSECUTIVO]         VARCHAR (250)  NULL,
    [DOCUMENTOENTREGABLE] VARCHAR (8000) NULL,
    [COMENTARIO_JAVIER]   VARCHAR (8000) NULL,
    [ACTIVO]              VARCHAR (5)    NULL,
    [AREA]                VARCHAR (250)  NULL,
    [ELABORADOR]          VARCHAR (250)  NULL,
    [REVISOR]             VARCHAR (250)  NULL,
    [APROBADOR]           VARCHAR (250)  NULL,
    [DIASELABORAR]        INT            NULL,
    [DIASREVISAR]         INT            NULL,
    [DIASAPROBAR]         INT            NULL,
    [DIASALERTA]          INT            NULL,
    [FECHAREGULADOR]      DATE           NULL,
    [FECHAINTERNA]        DATE           NULL,
    [IDCONTRATO]          INT            NULL,
    [IDENTREGABE]         INT            NULL,
    [IDAREA]              INT            NULL,
    [IDELABORA]           INT            NULL,
    [IDREVISA]            INT            NULL,
    [IDAPRUEBA]           INT            NULL,
    [geology]             BIT            NULL
);

