CREATE TABLE [dbo].[CargaJOAB35] (
    [COOWNER]              VARCHAR (50)   NULL,
    [CATEGORY]             VARCHAR (250)  NULL,
    [JOATOPIC]             VARCHAR (500)  NULL,
    [CLAUSE]               VARCHAR (5000) NULL,
    [OVERVIEWPROCESS]      VARCHAR (5000) NULL,
    [OBLIGATIONSUMMARY]    VARCHAR (8000) NULL,
    [FULLREFERENCEARTICLE] VARCHAR (8000) NULL,
    [FRECUENCY]            VARCHAR (1500) NULL,
    [DELIVERABLETOSHELL]   DATE           NULL,
    [DELIVERABLETOCOOWNER] VARCHAR (2000) NULL,
    [FUNCION]              VARCHAR (1500) NULL,
    [ACCOUNTABE]           VARCHAR (1500) NULL,
    [RESPONSIBLE]          VARCHAR (1500) NULL,
    [BackupP]              VARCHAR (250)  NULL,
    [OWNERR]               VARCHAR (250)  NULL,
    [ID]                   INT            NULL,
    [IDCONTRATO]           INT            NULL,
    [IDSOCIO]              INT            NULL,
    [IDCLASIFICACION]      INT            NULL,
    [IDFRECUENCIA]         INT            NULL,
    [IDENTREGABLE]         INT            NULL,
    [IDAREA]               INT            NULL,
    [IDELABORADOR]         INT            NULL,
    [CORREOACCOUNTABLE]    VARCHAR (300)  NULL,
    [CORREOACOMPLIANCE]    VARCHAR (300)  NULL
);

