CREATE TABLE [dbo].[CarpetasDocumentosEntregables] (
    [ID]                     INT              IDENTITY (1, 1) NOT NULL,
    [IDPadre]                INT              NULL,
    [Titulo]                 NVARCHAR (MAX)   NULL,
    [EtapaId]                NVARCHAR (MAX)   NULL,
    [ReceptorEntregableId]   INT              NULL,
    [PozoInstalacionId]      INT              NULL,
    [MarcoLegalId]           INT              NULL,
    [EtapaPozoId]            INT              NULL,
    [EntregableId]           INT              NULL,
    [FrecuenciaId]           NVARCHAR (MAX)   NULL,
    [Frecuencia]             NVARCHAR (MAX)   NULL,
    [FechaEntregaAnioMes]    NVARCHAR (MAX)   NULL,
    [FechaProgramadaEntrega] DATETIME         NULL,
    [DocumentoEntregableId]  INT              NULL,
    [CantidadArchivos]       INT              NULL,
    [Detalle]                NVARCHAR (MAX)   NULL,
    [Icono]                  NVARCHAR (MAX)   NULL,
    [Acciones]               NVARCHAR (MAX)   NULL,
    [Mime]                   NVARCHAR (MAX)   NULL,
    [Nivel]                  INT              NULL,
    [TipoArchivo]            NVARCHAR (MAX)   NULL,
    [FechaCarga]             DATETIME         NULL,
    [CargadoPor]             NVARCHAR (MAX)   NULL,
    [Bucket]                 NVARCHAR (MAX)   NULL,
    [Folder]                 NVARCHAR (MAX)   NULL,
    [UUIDAmazon]             UNIQUEIDENTIFIER NULL,
    [NombreArchivo]          NVARCHAR (MAX)   NULL,
    [Meta]                   NVARCHAR (MAX)   NULL,
    [SizeBytes]              DECIMAL (18)     NULL,
    [IdContrato]             INT              NULL,
    [Activo]                 BIT              NOT NULL,
    [IdCarpeta]              INT              NULL,
    [IdDocPadre]             INT              NULL
);

