CREATE TABLE [dbo].[CAT_TiposBDT] (
    [IdTipoBDT] INT          NOT NULL,
    [TipoBDT]   VARCHAR (20) NULL,
    CONSTRAINT [PK_CAT_TiposBDT] PRIMARY KEY CLUSTERED ([IdTipoBDT] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

