CREATE TABLE [dbo].[CAT_Paises] (
    [IdPais] INT            NOT NULL,
    [Pais]   NVARCHAR (600) NULL,
    CONSTRAINT [PK_CAT_Paises] PRIMARY KEY CLUSTERED ([IdPais] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

