CREATE TABLE [dbo].[CGI_Layout] (
    [IdCGILayout]         INT            IDENTITY (1, 1) NOT NULL,
    [CompanyCode]         NVARCHAR (200) NULL,
    [DocumentType]        NVARCHAR (150) NULL,
    [Documento]           NVARCHAR (200) NULL,
    [FiscalYear]          INT            NULL,
    [PostingPeriod]       TINYINT        NULL,
    [PostingDate]         DATE           NULL,
    [DocumentDate]        DATE           NULL,
    [JointVenture]        NVARCHAR (200) NULL,
    [AccountNumber]       NVARCHAR (200) NULL,
    [AreaContractual]     NVARCHAR (100) NULL,
    [Texto]               NVARCHAR (MAX) NULL,
    [WBSElement]          NVARCHAR (200) NULL,
    [CostCenter]          NVARCHAR (500) NULL,
    [TransactionAmount]   FLOAT (53)     NULL,
    [TransactionCurrency] NVARCHAR (100) NULL,
    [JoinOperAgreem]      NVARCHAR (200) NULL,
    [LocalAmount]         FLOAT (53)     NULL,
    [Subtotal]            FLOAT (53)     NULL,
    [LocalCurrency]       NVARCHAR (100) NULL,
    [Vendor]              NVARCHAR (200) NULL,
    [Activo]              BIT            NULL,
    [CreadoEl]            DATETIME       NULL,
    [CreadoPor]           INT            NULL,
    [ModificadoPor]       INT            NULL,
    [ModificadoEl]        DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([IdCGILayout] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

