CREATE TABLE [dbo].[CNH_R02_L03_CS_04_2017_ACT] (
    [ID]                      FLOAT (53)     NULL,
    [ACTIVIDAD]               NVARCHAR (255) NULL,
    [SUBACTIVIDAD]            NVARCHAR (255) NULL,
    [TAREA]                   NVARCHAR (255) NULL,
    [IDSUBTAREA]              NVARCHAR (255) NULL,
    [SERVICIO]                VARCHAR (8000) NULL,
    [UNIDAD]                  NVARCHAR (255) NULL,
    [ACREDITAUT]              NVARCHAR (255) NULL,
    [UTXACTIVIDAD]            FLOAT (53)     NULL,
    [UTTOTALES]               FLOAT (53)     NULL,
    [MES01]                   FLOAT (53)     NULL,
    [MES02]                   FLOAT (53)     NULL,
    [MES03]                   FLOAT (53)     NULL,
    [MES04]                   FLOAT (53)     NULL,
    [MES05]                   FLOAT (53)     NULL,
    [MES06]                   FLOAT (53)     NULL,
    [MES07]                   FLOAT (53)     NULL,
    [MES08]                   FLOAT (53)     NULL,
    [MES09]                   FLOAT (53)     NULL,
    [MES10]                   FLOAT (53)     NULL,
    [MES11]                   FLOAT (53)     NULL,
    [MES12]                   FLOAT (53)     NULL,
    [MES13]                   FLOAT (53)     NULL,
    [MES14]                   FLOAT (53)     NULL,
    [MES15]                   FLOAT (53)     NULL,
    [MES16]                   FLOAT (53)     NULL,
    [MES17]                   FLOAT (53)     NULL,
    [MES18]                   FLOAT (53)     NULL,
    [MES19]                   FLOAT (53)     NULL,
    [MES20]                   FLOAT (53)     NULL,
    [MES21]                   FLOAT (53)     NULL,
    [MES22]                   FLOAT (53)     NULL,
    [MES23]                   FLOAT (53)     NULL,
    [MES24]                   FLOAT (53)     NULL,
    [MES25]                   FLOAT (53)     NULL,
    [MES26]                   FLOAT (53)     NULL,
    [MES27]                   FLOAT (53)     NULL,
    [MES28]                   FLOAT (53)     NULL,
    [MES29]                   FLOAT (53)     NULL,
    [MES30]                   FLOAT (53)     NULL,
    [MES31]                   FLOAT (53)     NULL,
    [MES32]                   FLOAT (53)     NULL,
    [MES33]                   FLOAT (53)     NULL,
    [MES34]                   FLOAT (53)     NULL,
    [MES35]                   FLOAT (53)     NULL,
    [MES36]                   FLOAT (53)     NULL,
    [TOTAL]                   FLOAT (53)     NULL,
    [IdActividadPetrolera]    INT            NULL,
    [IdSubactividadPetrolera] INT            NULL,
    [IdTareaPetrolera]        INT            NULL,
    [IdServicio]              INT            NULL
);

