CREATE TABLE [dbo].[CNH_R03_L01_G_BG_05_2018] (
    [Identificador]          FLOAT (53)     NULL,
    [Consecutivo]            NVARCHAR (255) NULL,
    [Arearesponsable]        NVARCHAR (255) NULL,
    [Elabora]                NVARCHAR (255) NULL,
    [Revisa]                 NVARCHAR (255) NULL,
    [Aprueba]                NVARCHAR (255) NULL,
    [FechaLimiteInterna]     NVARCHAR (255) NULL,
    [FechaEntregaRegulador]  NVARCHAR (255) NULL,
    [Activo]                 NVARCHAR (255) NULL,
    [Desarrollo]             FLOAT (53)     NULL,
    [Exploración]            FLOAT (53)     NULL,
    [Evaluación]             FLOAT (53)     NULL,
    [Transicion]             FLOAT (53)     NULL,
    [AbandonodelArea]        FLOAT (53)     NULL,
    [AbandonodePozo]         FLOAT (53)     NULL,
    [Liderdelarea]           VARCHAR (500)  NULL,
    [ResponsableRegulatorio] VARCHAR (500)  NULL,
    [Elaborainterno]         VARCHAR (500)  NULL,
    [Actividad]              NVARCHAR (255) NULL,
    [IdContratoEntregable]   INT            NULL,
    [IdArea]                 INT            NULL,
    [identregable]           INT            NULL,
    [idusuario]              INT            NULL,
    [IDCONTRATO]             INT            NULL,
    [accountablecompliance]  VARCHAR (250)  NULL,
    [focalpoint]             VARCHAR (250)  NULL
);

