CREATE TABLE [dbo].[CO_Amatitlan_2020] (
    [ID]                                        FLOAT (53)     NULL,
    [INFORME]                                   NVARCHAR (255) NULL,
    [Year]                                      FLOAT (53)     NULL,
    [NumeroFacturaProveedorPemex]               NVARCHAR (255) NULL,
    [FechaFactura]                              DATETIME       NULL,
    [UUIDLUM]                                   NVARCHAR (255) NULL,
    [Proveedor]                                 NVARCHAR (255) NULL,
    [MesInforme]                                NVARCHAR (255) NULL,
    [Ajuste]                                    NVARCHAR (255) NULL,
    [NumeroFacturaOriginal]                     NVARCHAR (255) NULL,
    [UUIDFAC]                                   VARCHAR (255)  NULL,
    [FechaFacturaOriginal]                      DATETIME       NULL,
    [PeriodoFacturacionOriginal]                DATETIME       NULL,
    [ProveedorOriginal]                         NVARCHAR (255) NULL,
    [DescripcionServicio]                       VARCHAR (8000) NULL,
    [FechaInicio]                               FLOAT (53)     NULL,
    [FechaTermino]                              FLOAT (53)     NULL,
    [PeríodoEjecución]                          FLOAT (53)     NULL,
    [OrdenCompra]                               NVARCHAR (255) NULL,
    [Partida]                                   NVARCHAR (255) NULL,
    [Unidad]                                    NVARCHAR (255) NULL,
    [PUUSD]                                     NVARCHAR (255) NULL,
    [PUMXN]                                     FLOAT (53)     NULL,
    [CantidadReal]                              FLOAT (53)     NULL,
    [ImporteFacturaOriginal]                    FLOAT (53)     NULL,
    [ImporteFacturaOriginal2 _USD/MXP c/markup] FLOAT (53)     NULL,
    [TC]                                        FLOAT (53)     NULL,
    [Moneda]                                    NVARCHAR (255) NULL,
    [ImporteUSD_(Conver MXN a USD)]             FLOAT (53)     NULL,
    [TipoMarkup]                                FLOAT (53)     NULL,
    [Markup]                                    FLOAT (53)     NULL,
    [ImporteEstimadoUSD]                        FLOAT (53)     NULL,
    [IVA]                                       FLOAT (53)     NULL,
    [TOTAL]                                     FLOAT (53)     NULL,
    [MontoAprobadoCertificado]                  FLOAT (53)     NULL,
    [MontoPendienteCertificar]                  FLOAT (53)     NULL,
    [CGEAprobadoPemex]                          NVARCHAR (255) NULL,
    [AnioCertificado]                           NVARCHAR (255) NULL,
    [MESCERTIFICADO]                            NVARCHAR (255) NULL,
    [Estatuts_Certificado]                      NVARCHAR (255) NULL,
    [CuentaOperativa]                           NVARCHAR (255) NULL,
    [Actividad]                                 NVARCHAR (255) NULL,
    [Rubro]                                     NVARCHAR (255) NULL,
    [Servicio]                                  NVARCHAR (255) NULL,
    [AplicacionEspecifica]                      NVARCHAR (255) NULL,
    [Pozo]                                      NVARCHAR (255) NULL,
    [Presupuesto]                               NVARCHAR (255) NULL,
    [Homologacion_(Servicio)]                   NVARCHAR (255) NULL,
    [CAPEXOPEX]                                 NVARCHAR (255) NULL,
    [DescripcionGral]                           NVARCHAR (255) NULL,
    [idFormula]                                 NVARCHAR (255) NULL,
    [sumasreportemensual]                       NVARCHAR (255) NULL,
    [auxco]                                     NVARCHAR (255) NULL,
    [AuxSubAct]                                 NVARCHAR (255) NULL,
    [AuxPres]                                   NVARCHAR (255) NULL,
    [auxPASAPICIEP]                             NVARCHAR (255) NULL,
    [AUXPRESEN]                                 NVARCHAR (255) NULL,
    [pto 2]                                     NVARCHAR (255) NULL,
    [COMENTARIOS]                               NVARCHAR (255) NULL,
    [IdPresupuestoMes]                          INT            NULL
);

