CREATE TABLE [dbo].[CO_ConstantesCalcPreciosApi] (
    [idConstantes]               INT        IDENTITY (1, 1) NOT NULL,
    [PoderCalorificoC1_GPA2145]  FLOAT (53) NULL,
    [PoderCalorificoC2_GPA2145]  FLOAT (53) NULL,
    [PoderCalorificoC3_GPA2145]  FLOAT (53) NULL,
    [PoderCalorificoC4_GPA2145]  FLOAT (53) NULL,
    [PoderCalorificoIC4_GPA2145] FLOAT (53) NULL,
    [bi_C1]                      FLOAT (53) NULL,
    [bi_C2]                      FLOAT (53) NULL,
    [bi_C3]                      FLOAT (53) NULL,
    [bi_C4]                      FLOAT (53) NULL,
    [bi_IC4]                     FLOAT (53) NULL,
    [bi_CO2]                     FLOAT (53) NULL,
    [bi_H2S]                     FLOAT (53) NULL,
    [bi_N2]                      FLOAT (53) NULL,
    [C1_FT3]                     FLOAT (53) NULL,
    [C2_Ft3]                     FLOAT (53) NULL,
    [C3_Ft3]                     FLOAT (53) NULL,
    [C4_Ft3]                     FLOAT (53) NULL,
    [IC4_Ft3]                    FLOAT (53) NULL,
    [C5_Ft3]                     FLOAT (53) NULL,
    [CO2_Ft3]                    FLOAT (53) NULL,
    [H2S_Ft3]                    FLOAT (53) NULL,
    [N2_Ft3]                     FLOAT (53) NULL,
    [IdPtoExpedicionRecepcion]   INT        NULL,
    [idContrato]                 INT        NULL,
    CONSTRAINT [PK__CO_Const__8D9AD3A2A941CCD3] PRIMARY KEY CLUSTERED ([idConstantes] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK__CO_Consta__idCon__6721B179] FOREIGN KEY ([idContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK__CO_Consta__IdPto__47A90620] FOREIGN KEY ([IdPtoExpedicionRecepcion]) REFERENCES [dbo].[PC_PtoExpedicionRecepcion] ([IdPtoExpedicionRecepcion])
);

