CREATE TABLE [dbo].[CO_GastosAmatitlan_Mayo2018] (
    [IdGasto]                               INT            IDENTITY (1, 1) NOT NULL,
    [Pozo]                                  NVARCHAR (MAX) NULL,
    [IdInstalacion]                         INT            NULL,
    [NumeroDeOrdenServicio]                 NVARCHAR (MAX) NULL,
    [Partida]                               NVARCHAR (MAX) NULL,
    [Unidad]                                NVARCHAR (MAX) NULL,
    [DescripciónPartidaServicio]            NVARCHAR (MAX) NULL,
    [P_U_USD]                               FLOAT (53)     NULL,
    [P_U_MXN]                               FLOAT (53)     NULL,
    [CantidadReal]                          FLOAT (53)     NULL,
    [FechaInicio]                           DATETIME       NULL,
    [FechaTermino]                          DATETIME       NULL,
    [PeriodoEjecucion]                      NVARCHAR (MAX) NULL,
    [ProveedorOriginal]                     NVARCHAR (MAX) NULL,
    [IdSubcontratista]                      INT            NULL,
    [NumeroFacturaOriginal]                 NVARCHAR (MAX) NULL,
    [IdFactura]                             INT            NULL,
    [FechaFacturaOriginal]                  DATETIME       NULL,
    [PeriodoFacturaciónOriginal]            NVARCHAR (MAX) NULL,
    [ImporteFacturaOriginalUSD_MXP]         FLOAT (53)     NULL,
    [Moneda]                                NVARCHAR (MAX) NULL,
    [TipoCambioBanxico_4_Digitos]           FLOAT (53)     NULL,
    [Importe_USD_ConverMXNUSD]              FLOAT (53)     NULL,
    [Markup]                                NVARCHAR (MAX) NULL,
    [CiaRelacionada_Subcontratista]         NVARCHAR (MAX) NULL,
    [NumeroFacturaProveedorPemex]           NVARCHAR (MAX) NULL,
    [FechaFactura]                          DATETIME       NULL,
    [ImporteEstimadoUSD]                    FLOAT (53)     NULL,
    [MesGEAprobadoPemex]                    NVARCHAR (MAX) NULL,
    [PeriodoInforme]                        NVARCHAR (MAX) NULL,
    [IdPrograma]                            INT            NULL,
    [CuentaOperativa]                       NVARCHAR (MAX) NULL,
    [Actividad]                             NVARCHAR (MAX) NULL,
    [SubActividad]                          NVARCHAR (MAX) NULL,
    [ActividadAcuerdoPresupuestoprogramado] NVARCHAR (MAX) NULL,
    [AplicacióEspecifica]                   NVARCHAR (MAX) NULL,
    [Presupuesto_PPT]                       NVARCHAR (MAX) NULL,
    [CAPEX_OPEX]                            NVARCHAR (MAX) NULL,
    [Status]                                NVARCHAR (MAX) NULL,
    [FechaExcel]                            DATETIME       NULL,
    CONSTRAINT [PK_CO_GastosAmatitlan_Mayo2018] PRIMARY KEY CLUSTERED ([IdGasto] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

