CREATE TABLE [dbo].[CO_GastosPEMISA] (
    [fila]                                                     FLOAT (53)     NULL,
    [Linea]                                                    FLOAT (53)     NULL,
    [Cuenta Operativa]                                         NVARCHAR (255) NULL,
    [Actividad]                                                NVARCHAR (255) NULL,
    [RUBRO 2]                                                  NVARCHAR (255) NULL,
    [ACTIVIDAD2]                                               NVARCHAR (255) NULL,
    [XXX]                                                      NVARCHAR (255) NULL,
    [Actividad1]                                               NVARCHAR (255) NULL,
    [Tipo de Servicio]                                         NVARCHAR (255) NULL,
    [Sub Actividad]                                            NVARCHAR (255) NULL,
    [ID Actividad]                                             NVARCHAR (255) NULL,
    [Code]                                                     FLOAT (53)     NULL,
    [MES FACTURA ORIGINAL]                                     NVARCHAR (255) NULL,
    [AÑO DE FACTURA ORIGINAL]                                  FLOAT (53)     NULL,
    [FECHA FACTURA ORIGINAL]                                   FLOAT (53)     NULL,
    [PERIODO DE EJECUCIÓN]                                     NVARCHAR (255) NULL,
    [AÑO EJECUCIÓN]                                            FLOAT (53)     NULL,
    [NUMERO DE FACTURA ORIGINAL]                               FLOAT (53)     NULL,
    [RELACIÓN ENTRE FULL PICTURE Y ARCHIVO GENERAL]            NVARCHAR (255) NULL,
    [POZO]                                                     NVARCHAR (255) NULL,
    [PROVEEROR ORIGINAL]                                       NVARCHAR (255) NULL,
    [REVISIÓN COMPLETA A PRESENTAR]                            NVARCHAR (255) NULL,
    [PROVEEDOR PEMEX]                                          NVARCHAR (255) NULL,
    [NUMERO DE FACTURA ]                                       FLOAT (53)     NULL,
    [COMENTARIOS GENERALES]                                    NVARCHAR (255) NULL,
    [ODC PEMISA]                                               NVARCHAR (255) NULL,
    [REVISION INCLUIDAS EN CONCENTRADO]                        NVARCHAR (255) NULL,
    [ FECHA FACTURA PARA PEMEX]                                FLOAT (53)     NULL,
    [MES  DISPONIBLE PARA PRESENTACIÓN GASTO CUENTA OPERATIVA] NVARCHAR (255) NULL,
    [AÑO DISPONIBLE PARA PRESENTACIÓN GASTO CUENTA OPERATIVA]  NVARCHAR (255) NULL,
    [MES DE REGISTRO EN CUENTA OPERATIVA]                      NVARCHAR (255) NULL,
    [AÑO DE REGISTRO EN CUENTA OPERATIVA]                      FLOAT (53)     NULL,
    [MES DE GASTO APROBADO EN CUENTA OPERATIVA]                NVARCHAR (255) NULL,
    [AÑO DE GASTO APROBADO EN CUENTA OPERATIVA]                FLOAT (53)     NULL,
    [STATUS DE GASTO ELEGIBLE]                                 NVARCHAR (255) NULL,
    [MONEDA ORIGINAL]                                          NVARCHAR (255) NULL,
    [ MONTO FACTURA ORIGINAL EN MXN ]                          FLOAT (53)     NULL,
    [MARK UP 5#4 MXN]                                          FLOAT (53)     NULL,
    [TOTAL MONTO MXN (ORIGINAL + MARK UP)]                     FLOAT (53)     NULL,
    [MONTO FACTURA ORIGINAL EN  USD ]                          NVARCHAR (255) NULL,
    [MARK UP 5#4 USD]                                          NVARCHAR (255) NULL,
    [TOTAL MONTO USD (ORIGINAL + MARK UP)]                     NVARCHAR (255) NULL,
    [CÁLCULO TIPO DE CAMBIO CONSIDERADO PARA COBRO]            FLOAT (53)     NULL,
    [CÁLCULO TIPO DE CAMBIO PROMEDIO BANXICO (MES COMPLETO)]   NVARCHAR (255) NULL,
    [DIFERENCIA TIPO CAMBIO]                                   NVARCHAR (255) NULL,
    [ SUBTOTAL DE FACTURA EN USD]                              FLOAT (53)     NULL,
    [MENOS APLICACIÓN DE NOTA DE CREDITO]                      NVARCHAR (255) NULL,
    [ SUBTOTAL FINAL DE FACTURA EN USD]                        FLOAT (53)     NULL,
    [IVA]                                                      FLOAT (53)     NULL,
    [TOTAL FACTURA]                                            FLOAT (53)     NULL,
    [OBSERVACIONES PEMEX]                                      NVARCHAR (255) NULL,
    [FECHA DE OBSERVACIONES PEMEX]                             NVARCHAR (255) NULL,
    [OBSERVACIONES PEMEX1]                                     NVARCHAR (255) NULL,
    [FECHA DE OBSERVACIONES PEMEX1]                            NVARCHAR (255) NULL,
    [IdProveedorPEMEX]                                         INT            NULL,
    [IdFactura]                                                INT            NULL,
    [NumeroFactura]                                            NVARCHAR (MAX) NULL,
    [MesEjec]                                                  DATE           NULL,
    [Encontrado]                                               BIT            CONSTRAINT [DF_CO_GastosPEMISA_Encontrado] DEFAULT ((0)) NULL
);

