CREATE TABLE [dbo].[CO_LineaPresupuestoMes] (
    [IdLineaPresupuestoMes]       INT             IDENTITY (10000, 1) NOT NULL,
    [IdPresupuesto]               INT             NULL,
    [IdTipoServicio]              INT             NULL,
    [IdActividad]                 INT             NULL,
    [IdSubactividad]              INT             NULL,
    [IdClasificacion]             INT             NULL,
    [IdSubactividad002]           INT             NULL,
    [AC_TERMINADO]                BIT             NULL,
    [IdInstalacion]               INT             NULL,
    [AC_PRESUP_MES]               DATE            NULL,
    [IdServicio]                  INT             NULL,
    [AC_FEC_INI]                  DATE            NULL,
    [AC_FEC_FIN]                  DATE            NULL,
    [IdActvidadHidrocarburo]      INT             NULL,
    [ID_PADRE]                    NVARCHAR (50)   NULL,
    [IdArea]                      INT             NULL,
    [IdRubro]                     INT             NULL,
    [Volumetria]                  REAL            NULL,
    [PrecioUnitario]              DECIMAL (18, 4) NULL,
    [Monto]                       DECIMAL (18, 4) NULL,
    [IdUsuario]                   INT             NULL,
    [FecMovto]                    DATETIME        NULL,
    [IdExcel]                     INT             NULL,
    [IdAnexo4]                    INT             NULL,
    [IdRubroInterno]              INT             NULL,
    [CPXOPX]                      NCHAR (5)       NULL,
    [Actividad]                   BIT             NULL,
    [MesActividadIni]             DATE            NULL,
    [MesActividadFin]             DATE            NULL,
    [IdActividadPetrolera]        INT             NULL,
    [IdSubactividadPetrolera]     INT             NULL,
    [IdTareaPetrolera]            INT             NULL,
    [IdCatalogoCuentasSH]         INT             NULL,
    [MOExt]                       DECIMAL (18, 4) NULL,
    [MOCNac]                      DECIMAL (18, 4) NULL,
    [BSExt]                       DECIMAL (18, 4) NULL,
    [BSCNac]                      DECIMAL (18, 4) NULL,
    [CreadoPor]                   INT             NULL,
    [IdLineaProgramaActividadMes] INT             NULL,
    [CAPEX]                       BIT             NULL,
    [AC_DESCRIPCION]              NVARCHAR (MAX)  NULL,
    [SExt]                        DECIMAL (18, 4) NULL,
    [SNac]                        DECIMAL (18, 4) NULL,
    [CExt]                        DECIMAL (18, 4) NULL,
    [CNac]                        DECIMAL (18, 4) NULL,
    [TTec]                        DECIMAL (18, 4) NULL,
    [ISoc]                        DECIMAL (18, 4) NULL,
    CONSTRAINT [PK_LineaPresupuestoMes] PRIMARY KEY CLUSTERED ([IdLineaPresupuestoMes] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_AP_Usuario] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_ActividadCIEP] FOREIGN KEY ([IdActividad]) REFERENCES [dbo].[CO_ActividadCIEP] ([IdActividad]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_ActividadHidrocarburoCIEP] FOREIGN KEY ([IdActvidadHidrocarburo]) REFERENCES [dbo].[CO_ActividadHidrocarburoCIEP] ([IdActividadHidrocarburo]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_ActividadPetroleraCNH] FOREIGN KEY ([IdActividadPetrolera]) REFERENCES [dbo].[CO_ActividadPetroleraCNH] ([IdActividadPetrolera]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Area] FOREIGN KEY ([IdArea]) REFERENCES [dbo].[CO_Area] ([IdArea]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_CatalogoCuentaSH] FOREIGN KEY ([IdCatalogoCuentasSH]) REFERENCES [dbo].[CO_CatalogoCuentaSH] ([IdCatalogoCuentasSH]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Clasificacion] FOREIGN KEY ([IdClasificacion]) REFERENCES [dbo].[CO_Clasificacion] ([IdClasificacion]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_ClasificacionAnexo4] FOREIGN KEY ([IdAnexo4]) REFERENCES [dbo].[CO_ClasificacionAnexo4] ([IdAnexo4]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Instalacion] FOREIGN KEY ([IdInstalacion]) REFERENCES [dbo].[CO_Instalacion] ([IdInstalacion]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_LineaProgramaActividadMes] FOREIGN KEY ([IdLineaProgramaActividadMes]) REFERENCES [dbo].[CO_LineaProgramaActividadMes] ([IdLineaProgramaActividadMes]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Presupuesto] FOREIGN KEY ([IdPresupuesto]) REFERENCES [dbo].[CO_Presupuesto] ([IdPresupuesto]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Rubro] FOREIGN KEY ([IdRubro]) REFERENCES [dbo].[CO_Rubro] ([IdRubro]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_Servicio] FOREIGN KEY ([IdServicio]) REFERENCES [dbo].[CO_Servicio] ([IdServicio]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_SubactividadCIEP] FOREIGN KEY ([IdSubactividad]) REFERENCES [dbo].[CO_SubactividadCIEP] ([IdSubactividad]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_SubactividadPetrolera] FOREIGN KEY ([IdSubactividadPetrolera]) REFERENCES [dbo].[CO_SubactividadPetrolera] ([IdSubactividadPetrolera]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_TareaPetrolera] FOREIGN KEY ([IdTareaPetrolera]) REFERENCES [dbo].[CO_TareaPetrolera] ([IdTareaPetrolera]),
    CONSTRAINT [FK_CO_LineaPresupuestoMes_CO_TipoServicio] FOREIGN KEY ([IdTipoServicio]) REFERENCES [dbo].[CO_TipoServicio] ([IdTipoServicio])
);

