CREATE TABLE [dbo].[CO_LINEAPRESUPUESTOMES_RESP20191209] (
    [IdLineaPresupuestoMes]       INT             IDENTITY (10000, 1) NOT NULL,
    [IdPresupuesto]               INT             NULL,
    [IdTipoServicio]              INT             NULL,
    [IdActividad]                 INT             NULL,
    [IdSubactividad]              INT             NULL,
    [IdClasificacion]             INT             NULL,
    [IdSubactividad002]           INT             NULL,
    [AC_TERMINADO]                BIT             NULL,
    [IdInstalacion]               INT             NULL,
    [AC_PRESUP_MES]               DATE            NULL,
    [IdServicio]                  INT             NULL,
    [AC_FEC_INI]                  DATE            NULL,
    [AC_FEC_FIN]                  DATE            NULL,
    [IdActvidadHidrocarburo]      INT             NULL,
    [ID_PADRE]                    NVARCHAR (50)   NULL,
    [IdArea]                      INT             NULL,
    [IdRubro]                     INT             NULL,
    [Volumetria]                  REAL            NULL,
    [PrecioUnitario]              DECIMAL (18, 4) NULL,
    [Monto]                       DECIMAL (18, 4) NULL,
    [IdUsuario]                   INT             NULL,
    [FecMovto]                    DATETIME        NULL,
    [IdExcel]                     INT             NULL,
    [IdAnexo4]                    INT             NULL,
    [IdRubroInterno]              INT             NULL,
    [CPXOPX]                      NCHAR (5)       NULL,
    [Actividad]                   BIT             NULL,
    [MesActividadIni]             DATE            NULL,
    [MesActividadFin]             DATE            NULL,
    [IdActividadPetrolera]        INT             NULL,
    [IdSubactividadPetrolera]     INT             NULL,
    [IdTareaPetrolera]            INT             NULL,
    [IdCatalogoCuentasSH]         INT             NULL,
    [MOExt]                       DECIMAL (18, 4) NULL,
    [MOCNac]                      DECIMAL (18, 4) NULL,
    [BSExt]                       DECIMAL (18, 4) NULL,
    [BSCNac]                      DECIMAL (18, 4) NULL,
    [CreadoPor]                   INT             NULL,
    [IdLineaProgramaActividadMes] INT             NULL,
    [CAPEX]                       BIT             NULL,
    [AC_DESCRIPCION]              NVARCHAR (MAX)  NULL,
    [SExt]                        DECIMAL (18, 4) NULL,
    [SNac]                        DECIMAL (18, 4) NULL,
    [CExt]                        DECIMAL (18, 4) NULL,
    [CNac]                        DECIMAL (18, 4) NULL,
    [TTec]                        DECIMAL (18, 4) NULL,
    [ISoc]                        DECIMAL (18, 4) NULL
);

