CREATE TABLE [dbo].[CO_NMSipacVenta] (
    [idSipacVenta]   INT        IDENTITY (1000, 1) NOT NULL,
    [idcontrato]     INT        NULL,
    [Mes]            DATE       NULL,
    [Petroleo_bl]    FLOAT (53) NULL,
    [API_Petroleo]   FLOAT (53) NULL,
    [API_Condensado] FLOAT (53) NULL,
    [Factor]         FLOAT (53) NULL,
    [Gas_mmpc]       FLOAT (53) NULL,
    [Condensado_bl]  FLOAT (53) NULL,
    [Metano_C1]      FLOAT (53) NULL,
    [Etano_C2]       FLOAT (53) NULL,
    [Propano_c3]     FLOAT (53) NULL,
    [Butano_nc4]     FLOAT (53) NULL,
    [Butano_IC4]     FLOAT (53) NULL,
    [Pentano_nc5]    FLOAT (53) NULL,
    [Pentano_IC5]    FLOAT (53) NULL,
    [Hexano_C6]      FLOAT (53) NULL,
    [Mol_CO2]        FLOAT (53) NULL,
    [Mol_h2s]        FLOAT (53) NULL,
    [Mol_N2]         FLOAT (53) NULL,
    PRIMARY KEY CLUSTERED ([idSipacVenta] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    FOREIGN KEY ([idcontrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

