CREATE TABLE [dbo].[CO_Registro_MG] (
    [IdRegistro]                      INT             NOT NULL,
    [IdPrograma]                      INT             NULL,
    [IdFactura]                       INT             NULL,
    [MontoRegistro]                   DECIMAL (18, 4) NULL,
    [InicioEjecucion]                 DATE            NULL,
    [FinEjecucion]                    DATE            NULL,
    [Comentarios]                     NVARCHAR (MAX)  NULL,
    [MesPresentacion]                 DATE            NULL,
    [IdEstado]                        INT             NULL,
    [IdUsuarioCreadoPor]              INT             NULL,
    [IdUsuarioModPor]                 INT             NULL,
    [FecMovto]                        DATETIME        NULL,
    [IdInstalacion]                   INT             NULL,
    [CreadoPor]                       INT             NULL,
    [Fila]                            INT             NULL,
    [IdPedimentoComprobante]          INT             NULL,
    [CvTipoDocFacturacion]            INT             CONSTRAINT [DF_CO_Registro_MG_CvTipoDocFacturacion] DEFAULT ((1)) NULL,
    [IdCatalogoCuentasSH]             INT             NULL,
    [Poliza]                          NVARCHAR (MAX)  NULL,
    [IsEditable]                      BIT             NULL,
    [CostosAtribuiblesAdministracion] BIT             NULL,
    [EstadoDePresentacion]            BIT             CONSTRAINT [DF_CO_Registro_MG_EstadoDePresentacion] DEFAULT ((0)) NULL,
    [MesCertificadoCIEP]              DATE            NULL,
    [IdGastoRubro]                    TINYINT         NULL,
    [PCN]                             FLOAT (53)      NULL,
    [Importado]                       BIT             NULL,
    [BitPCNP]                         BIT             CONSTRAINT [DF_CO_Registro_MG_BitPetrovendor] DEFAULT ((0)) NULL,
    [IdCBSISH]                        INT             NULL,
    [IdAceptacionPedidoDetalle]       INT             NULL,
    [MesGasto]                        DATE            CONSTRAINT [DF_CO_Registro_MG_MesGasto] DEFAULT (NULL) NULL,
    CONSTRAINT [PK_Registros_MG] PRIMARY KEY CLUSTERED ([IdRegistro] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CO_Registro_MG_CO_CatalogoCuentaSH] FOREIGN KEY ([IdCatalogoCuentasSH]) REFERENCES [dbo].[CO_CatalogoCuentaSH] ([IdCatalogoCuentasSH]),
    CONSTRAINT [FK_CO_Registro_MG_FI_PedimentoComprobante] FOREIGN KEY ([IdPedimentoComprobante]) REFERENCES [dbo].[FI_PedimentoComprobante] ([IdPedimentoComprobante])
);

