CREATE TABLE [dbo].[CO_SAPSES] (
    [IdContrato]         INT           NOT NULL,
    [SESNumber]          VARCHAR (50)  NOT NULL,
    [SESLine]            VARCHAR (50)  NOT NULL,
    [PO_SAPNumer]        VARCHAR (50)  NOT NULL,
    [POLineNumber]       VARCHAR (50)  NOT NULL,
    [Quantity]           FLOAT (53)    NULL,
    [UnitPrice]          FLOAT (53)    NULL,
    [Currency]           VARCHAR (50)  NULL,
    [Importe]            FLOAT (53)    NULL,
    [AccountAssignment]  VARCHAR (50)  NULL,
    [CostObject]         VARCHAR (50)  NULL,
    [MaterialGroup]      VARCHAR (50)  NULL,
    [MaterialGroupDesc2] VARCHAR (150) NULL,
    [CreadoEl]           DATETIME      NULL,
    [CreadoPor]          INT           NULL,
    [UOM]                VARCHAR (50)  NULL,
    [SESPostingDate]     VARCHAR (15)  NULL,
    [SESServiceStart]    VARCHAR (15)  NULL,
    [SESServiceEnd]      VARCHAR (15)  NULL,
    [Plant]              VARCHAR (15)  NULL,
    [SESReferenceNumber] VARCHAR (20)  NULL,   
    CONSTRAINT [FK_CO_MapeoInterfazApprovedSES_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_CO_MapeoInterfazApprovedSES_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

