CREATE TABLE [dbo].[CO_SAPPO] (
    [IdContrato]               INT           NOT NULL,
    [SAPPONumber]              VARCHAR (20)  NOT NULL,
    [ItemNumber]               SMALLINT      NOT NULL,
    [VersionNumber]            TINYINT       NULL,
    [SAPVendorNumber]          VARCHAR (20)  NULL,
    [SAPMaterialNumber]        VARCHAR (50)  NULL,
    [Quantity]                 FLOAT (53)    NULL,
    [UnitPrice]                FLOAT (53)    NULL,
    [Currency]                 VARCHAR (50)  NULL,
    [Total]                    FLOAT (53)    NULL,
    [Deliveryaddress]          VARCHAR (250) NULL,
    [DeliveryDate]             VARCHAR (8)   NULL,
    [Comments]                 VARCHAR (250) NULL,
    [CostObject]               VARCHAR (20)  NULL,
    [MaterialGroup]            VARCHAR (50)  NULL,
    [MaterialGroupDescription] VARCHAR (250) NULL,
    [ServiceLineNumber]        VARCHAR (50)  NULL,
    [Quantity2]                FLOAT (53)    NULL,
    [Price2]                   FLOAT (53)    NULL,
    [CostObject2]              VARCHAR (20)  NULL,
    [ServiceGroup]             VARCHAR (50)  NULL,
    [CreadoEl]                 DATETIME      NULL,
    [CreadoPor]                INT           NULL,
    [ModificadoEl]             DATETIME      NULL,
    [ShortText]                VARCHAR (100) NULL,
    [ParentLineUOM]            VARCHAR (50)  NULL,
    [ServiceShortText]         VARCHAR (50)  NULL,
    [ServicesUOM]              VARCHAR (50)  NULL,
    [Plant]                    VARCHAR (15)  NULL,
    [POItemCategory]           TINYINT       NULL,
    [POActivo]                 BIT           NULL,
    [CancaladoPor]             INT           NULL,
    [CancaladoEl]              DATETIME      NULL,
    CONSTRAINT [PK_CO_MapeoInterfazPO] PRIMARY KEY CLUSTERED ([IdContrato] ASC, [SAPPONumber] ASC, [ItemNumber] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CO_MapeoInterfazPO_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID])
);

