CREATE TABLE [dbo].[CO_WDEA_Produccion_Diaria_Detalle] (
    [IdDetalle]               INT           IDENTITY (1, 1) NOT NULL,
    [Id]                      INT           NULL,
    [Pozo]                    VARCHAR (500) NULL,
    [BateriaSeparacion]       VARCHAR (500) NULL,
    [Operativo]               BIT           NULL,
    [Descarga]                VARCHAR (10)  NULL,
    [Sistema]                 VARCHAR (100) NULL,
    [BN]                      VARCHAR (10)  NULL,
    [MedicionFecha]           DATETIME      NULL,
    [MedicionCIA]             VARCHAR (100) NULL,
    [MedicionQBruto]          FLOAT (53)    NULL,
    [MedicionQNeto]           FLOAT (53)    NULL,
    [MedicionQAgua]           FLOAT (53)    NULL,
    [MedicionFAgua]           FLOAT (53)    NULL,
    [MedicionQGasTotal]       FLOAT (53)    NULL,
    [MedicionQGasForm]        FLOAT (53)    NULL,
    [MedicionQGasiny]         FLOAT (53)    NULL,
    [CA_LAB_Fw]               FLOAT (53)    NULL,
    [ProduccionQBruto]        FLOAT (53)    NULL,
    [ProduccionQNeto]         FLOAT (53)    NULL,
    [ProduccionQAgua]         FLOAT (53)    NULL,
    [ProduccionFAgua]         FLOAT (53)    NULL,
    [ProduccionQGasTotal]     FLOAT (53)    NULL,
    [ProduccionQGasForm]      FLOAT (53)    NULL,
    [ProduccionQGasiny]       FLOAT (53)    NULL,
    [ProduccionPGasiny]       FLOAT (53)    NULL,
    [ProduccionRGA]           FLOAT (53)    NULL,
    [ProduccionEstTp]         VARCHAR (100) NULL,
    [ProduccionPTP]           FLOAT (53)    NULL,
    [ProduccionObservaciones] VARCHAR (500) NULL,
    [EstadoQBruto]            FLOAT (53)    NULL,
    [EstadoQNeto]             FLOAT (53)    NULL,
    [EstadoQAgua]             FLOAT (53)    NULL,
    [EstadoFAgua]             FLOAT (53)    NULL,
    [EstadoQGasTotal]         FLOAT (53)    NULL,
    [EstadoQGasForm]          FLOAT (53)    NULL,
    [EstadoQGasiny]           FLOAT (53)    NULL,
    [EstadoRGA]               FLOAT (53)    NULL,
    [DiferenciaQBruto]        FLOAT (53)    NULL,
    [DiferenciaQNeto]         FLOAT (53)    NULL,
    [DiferenciaQAgua]         FLOAT (53)    NULL,
    [DiferenciaFAgua]         FLOAT (53)    NULL,
    [DiferenciaQGasTotal]     FLOAT (53)    NULL,
    [DiferenciaQGasForm]      FLOAT (53)    NULL,
    [DiferenciaQGasiny]       FLOAT (53)    NULL,
    [DiferenciaRGA]           FLOAT (53)    NULL,
    [DiferenciaObservaciones] VARCHAR (500) NULL,
    [MovimientoPozo]          VARCHAR (500) NULL,
    [MovimientoSistema]       VARCHAR (500) NULL,
    [MovimientoBateria]       VARCHAR (500) NULL,
    [Movimiento]              VARCHAR (500) NULL,
    [MovimientoHrsCierre]     VARCHAR (50)  NULL,
    [MovimientoPB]            FLOAT (53)    NULL,
    [MovimientoAgua]          FLOAT (53)    NULL,
    [MovimientoPN]            FLOAT (53)    NULL,
    [MovimientoGF]            FLOAT (53)    NULL,
    [MovimientoGI]            FLOAT (53)    NULL,
    [MovimientoPB_BLS]        FLOAT (53)    NULL,
    [MovimientoPN_BLS]        FLOAT (53)    NULL,
    [MovimientoPRES_TP]       FLOAT (53)    NULL,
    [MovimientoPRES_LDD]      FLOAT (53)    NULL,
    [MovimientoAjusteEst]     VARCHAR (100) NULL,
    [MovimientoAjustePB]      FLOAT (53)    NULL,
    [MovimientoAjustePN]      FLOAT (53)    NULL,
    [MovimientoAjusteGF]      FLOAT (53)    NULL,
    [MovimientoAjusteGI]      FLOAT (53)    NULL,
    [CreadoEl]                DATETIME      NULL,
    [CreadoPor]               INT           NULL,
    CONSTRAINT [PK_CO_WDEA_Produccion_Diaria_Detalle] PRIMARY KEY CLUSTERED ([IdDetalle] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CO_WDEA_Produccion_Diaria_Detalle_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_CO_WDEA_Produccion_Diaria_Detalle_CO_WDEA_Produccion_Diaria] FOREIGN KEY ([Id]) REFERENCES [dbo].[CO_WDEA_Produccion_Diaria] ([Id])
);

