CREATE TABLE [dbo].[CO_WDEA_Produccion_Diaria] (
    [Id]                        INT           IDENTITY (1, 1) NOT NULL,
    [IdContrato]                INT           NOT NULL,
    [IdAWS]                     INT           NULL,
    [Fecha]                     DATETIME      NULL,
    [AceiteBrutoOG2_Balance]    FLOAT (53)    NULL,
    [AceiteBrutoOG5_Balance]    FLOAT (53)    NULL,
    [AceiteBrutoTotal_Balance]  FLOAT (53)    NULL,
    [AceiteNetoOG2_Balance]     FLOAT (53)    NULL,
    [AceiteNetoOG5_Balance]     FLOAT (53)    NULL,
    [AceiteNetoTotal_Balance]   FLOAT (53)    NULL,
    [CDeAguaOG2_Balance]        FLOAT (53)    NULL,
    [CDeAguaOG5_Balance]        FLOAT (53)    NULL,
    [CDeAguaTotal_Balance]      FLOAT (53)    NULL,
    [GasFormOG2_Balance]        FLOAT (53)    NULL,
    [GasFormOG5_Balance]        FLOAT (53)    NULL,
    [GasFormTotal_Balance]      FLOAT (53)    NULL,
    [GasInyTotalOG2_Balance]    FLOAT (53)    NULL,
    [GasInyTotalOG5_Balance]    FLOAT (53)    NULL,
    [GasInyTotal_Balance]       FLOAT (53)    NULL,
    [GasInySecoOG2_Balance]     FLOAT (53)    NULL,
    [GasInySecoOG5_Balance]     FLOAT (53)    NULL,
    [GasInySecoTotal_Balance]   FLOAT (53)    NULL,
    [GasInyHumedoOG2_Balance]   FLOAT (53)    NULL,
    [GasInyHumedoOG5_Balance]   FLOAT (53)    NULL,
    [GasInyHumedoTotal_Balance] FLOAT (53)    NULL,
    [AceiteBrutoOG2_PEP]        FLOAT (53)    NULL,
    [AceiteBrutoOG5_PEP]        FLOAT (53)    NULL,
    [AceiteBrutoTotal_PEP]      FLOAT (53)    NULL,
    [AceiteNetoOG2_PEP]         FLOAT (53)    NULL,
    [AceiteNetoOG5_PEP]         FLOAT (53)    NULL,
    [AceiteNetoTotal_PEP]       FLOAT (53)    NULL,
    [CDeAguaOG2_PEP]            FLOAT (53)    NULL,
    [CDeAguaOG5_PEP]            FLOAT (53)    NULL,
    [CDeAguaTotal_PEP]          FLOAT (53)    NULL,
    [GasFormOG2_PEP]            FLOAT (53)    NULL,
    [GasFormOG5_PEP]            FLOAT (53)    NULL,
    [GasFormTotal_PEP]          FLOAT (53)    NULL,
    [GasInyTotalOG2_PEP]        FLOAT (53)    NULL,
    [GasInyTotalOG5_PEP]        FLOAT (53)    NULL,
    [GasInyTotal_PEP]           FLOAT (53)    NULL,
    [GasInySecoOG2_PEP]         FLOAT (53)    NULL,
    [GasInySecoOG5_PEP]         FLOAT (53)    NULL,
    [GasInySecoTotal_PEP]       FLOAT (53)    NULL,
    [GasInyHumedoOG2_PEP]       FLOAT (53)    NULL,
    [GasInyHumedoOG5_PEP]       FLOAT (53)    NULL,
    [GasInyHumedoTotal_PEP]     FLOAT (53)    NULL,
    [Actualizado]               BIT           NULL,
    [CreadoPor]                 INT           NULL,
    [CreadoEl]                  DATETIME      NULL,
    [Error]                     BIT           NULL,
    [Alerta]                    BIT           NULL,
    [Observaciones]             VARCHAR (MAX) NULL,
    CONSTRAINT [PK_CO_WDEA_Produccion_Diaria] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_CO_WDEA_Produccion_Diaria_AP_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_CO_WDEA_Produccion_Diaria_AWS_Documentos] FOREIGN KEY ([IdAWS]) REFERENCES [dbo].[AWS_Documentos] ([AWSDocumentoId]),
    CONSTRAINT [FK_CO_WDEA_Produccion_Diaria_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

