CREATE TABLE [dbo].[COM_DistribucionIngresos] (
    [IdDistribucionIngresos]          INT            IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                      INT            NULL,
    [Mes]                             NVARCHAR (255) NULL,
    [IdMes]                           DATE           NULL,
    [Sector]                          NVARCHAR (255) NULL,
    [Material]                        NVARCHAR (255) NULL,
    [Textobrevematerial]              NVARCHAR (255) NULL,
    [PuntoExpedicion]                 NVARCHAR (255) NULL,
    [Denominacion]                    NVARCHAR (255) NULL,
    [Region]                          NVARCHAR (255) NULL,
    [DescripcionRegionOrganizacional] NVARCHAR (255) NULL,
    [DescripcionActivo]               NVARCHAR (255) NULL,
    [ClaveActivo]                     NVARCHAR (255) NULL,
    [DescripcionCampo]                NVARCHAR (255) NULL,
    [ClaveCampo]                      NVARCHAR (255) NULL,
    [Volumetrica]                     FLOAT (53)     NULL,
    [FactorDistribucionVolumetrica]   FLOAT (53)     NULL,
    [DistribucionVolumetrica]         FLOAT (53)     NULL,
    [UnidadMedidaVenta]               NVARCHAR (255) NULL,
    [GPVMaxCampo]                     FLOAT (53)     NULL,
    [GPVMaxMaterial]                  FLOAT (53)     NULL,
    [GPVPonderado]                    FLOAT (53)     NULL,
    [PrecioDeEquilibrio]              FLOAT (53)     NULL,
    [PrecioDeReferencia]              FLOAT (53)     NULL,
    [FactorDistribucionIngresos]      FLOAT (53)     NULL,
    [DistribucionIngresos]            FLOAT (53)     NULL,
    [IngresosMonedaLocal]             FLOAT (53)     NULL,
    [MonedaLocal]                     NVARCHAR (255) NULL,
    [IngresosUSD]                     FLOAT (53)     NULL,
    [MonedalLocal2]                   NVARCHAR (255) NULL,
    [OrganismoSecundario]             NVARCHAR (255) NULL,
    [DescripcionOrganismoSecundario]  NVARCHAR (255) NULL,
    CONSTRAINT [PK_COM_Distribucion] PRIMARY KEY CLUSTERED ([IdDistribucionIngresos] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_COM_DistribucionIngresos_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

