CREATE TABLE [dbo].[COM_OperacionComercializacion_RESP20190104] (
    [IdOperacionComercializacion]   INT           IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                    INT           NULL,
    [MesReporte]                    DATE          NULL,
    [FechaTransaccion]              DATE          NULL,
    [IdTipoHidrocarburo]            INT           NULL,
    [VolumenVendido]                FLOAT (53)    NULL,
    [PrecioVentaUnitario]           MONEY         NULL,
    [CostoUnitarioComercializacion] MONEY         NULL,
    [PrecioPuntoMedicion]           MONEY         NULL,
    [IdFactura]                     INT           NULL,
    [NumeroFolioPedimento]          NVARCHAR (15) NULL,
    [EPT]                           BIT           NULL,
    [OperacionBajoReglasMercado]    BIT           NULL,
    [ClasificacionDocumentoSoporte] INT           NULL,
    [CreadoPor]                     INT           NULL,
    [CreadoEl]                      DATETIME      NULL,
    [ModificadoPor]                 INT           NULL,
    [ModificadoEl]                  DATETIME      NULL,
    [Activo]                        BIT           NULL,
    [PVUAnterior]                   MONEY         NULL,
    [PPMAnterior]                   MONEY         NULL,
    [NuevoPrecioVentaUnitario]      MONEY         NULL,
    [PuntoEntregaID]                INT           NULL,
    [EsCondensable]                 BIT           NULL,
    [PenaEconomica]                 FLOAT (53)    NULL
);

