CREATE TABLE [dbo].[DatosImport] (
    [idExcel] INT            IDENTITY (1, 1) NOT NULL,
    [RF_00]   NVARCHAR (MAX) NULL,
    [PA_00]   NVARCHAR (MAX) NULL,
    [PA_01]   NVARCHAR (MAX) NULL,
    [PA_02]   DATE           NULL,
    [PA_03]   DATE           NULL,
    [PA_04]   NVARCHAR (MAX) NULL,
    [PA_05]   NVARCHAR (MAX) NULL,
    [PA_06]   NVARCHAR (MAX) NULL,
    [PA_07]   NVARCHAR (MAX) NULL,
    [PA_08]   NVARCHAR (MAX) NULL,
    [PA_09]   NVARCHAR (MAX) NULL,
    [PA_10]   NVARCHAR (MAX) NULL,
    [PA_11]   NVARCHAR (MAX) NULL,
    [PA_12]   NVARCHAR (MAX) NULL,
    [PA_13]   NVARCHAR (MAX) NULL,
    [PA_14]   NVARCHAR (MAX) NULL,
    [PA_15]   NVARCHAR (MAX) NULL,
    [PA_16]   NVARCHAR (MAX) NULL,
    [PA_17]   FLOAT (53)     NULL,
    [PA_18]   FLOAT (53)     NULL,
    [PA_19]   FLOAT (53)     NULL,
    [PA_20]   FLOAT (53)     NULL,
    [PA_21]   FLOAT (53)     NULL,
    [PA_22]   FLOAT (53)     NULL,
    [PA_23]   FLOAT (53)     NULL,
    [PA_24]   FLOAT (53)     NULL,
    [PA_25]   FLOAT (53)     NULL,
    [PA_26]   FLOAT (53)     NULL,
    CONSTRAINT [PK__DatosImp__86CBAE05586701EB] PRIMARY KEY CLUSTERED ([idExcel] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

