CREATE TABLE [dbo].[DEA092019] (
    [ID]                           FLOAT (53)     NULL,
    [Contratista]                  FLOAT (53)     NULL,
    [Numero de Contrato]           NVARCHAR (255) NULL,
    [Bloque]                       NVARCHAR (255) NULL,
    [Referencia Bancaria]          NVARCHAR (255) NULL,
    [FechaPago]                    DATETIME       NULL,
    [Banco]                        NVARCHAR (255) NULL,
    [Titular]                      NVARCHAR (255) NULL,
    [Sucursal]                     NVARCHAR (255) NULL,
    [Numero Cuenta]                NVARCHAR (255) NULL,
    [Cuenta Clabe]                 NVARCHAR (255) NULL,
    [Numero Tarjeta]               NVARCHAR (255) NULL,
    [Moneda]                       NVARCHAR (255) NULL,
    [Banco Destino]                NVARCHAR (255) NULL,
    [Titular1]                     NVARCHAR (255) NULL,
    [Sucursal1]                    NVARCHAR (255) NULL,
    [Numero Cuenta1]               NVARCHAR (255) NULL,
    [Cuenta Clabe1]                NVARCHAR (255) NULL,
    [Numero Tarjeta1]              NVARCHAR (255) NULL,
    [Moneda1]                      FLOAT (53)     NULL,
    [RFC Titular]                  NVARCHAR (255) NULL,
    [Monto Pagado]                 FLOAT (53)     NULL,
    [Concepto]                     FLOAT (53)     NULL,
    [Numero Poliza Contable]       FLOAT (53)     NULL,
    [Intereses]                    NVARCHAR (255) NULL,
    [UUID]                         VARCHAR (50)   NULL,
    [Numero Pedimento Comprobante] NVARCHAR (255) NULL,
    [F28]                          NVARCHAR (255) NULL,
    [F29]                          DATETIME       NULL,
    [Mes de registro]              DATETIME       NULL,
    [Voucher name]                 NVARCHAR (255) NULL,
    [F32]                          DATETIME       NULL
);

