CREATE TABLE [dbo].[DEA_ImportarGastosNomina] (
    [Assignment]             VARCHAR (500)  NULL,
    [DocumentNumber]         VARCHAR (100)  NULL,
    [BusinessArea]           VARCHAR (100)  NULL,
    [DocumentType]           VARCHAR (100)  NULL,
    [DocumentDate]           VARCHAR (100)  NULL,
    [PostingKey]             VARCHAR (100)  NULL,
    [TaxCode]                VARCHAR (100)  NULL,
    [ClearingDocument]       VARCHAR (500)  NULL,
    [Text]                   VARCHAR (8000) NULL,
    [AmountInDocCurr]        VARCHAR (100)  NULL,
    [AmountInLocalCurrency]  VARCHAR (100)  NULL,
    [AmountInLocalCurrency2] VARCHAR (100)  NULL,
    [AmountInLocalCurrency3] VARCHAR (100)  NULL,
    [WBSElement]             VARCHAR (200)  NULL,
    [Account]                VARCHAR (100)  NULL,
    [LocalCurrency3]         VARCHAR (50)   NULL,
    [DocumentCurrency]       VARCHAR (50)   NULL,
    [GeneralLedgerCurrency]  VARCHAR (50)   NULL,
    [LocalCurrency2]         VARCHAR (50)   NULL,
    [LocalCurrency]          VARCHAR (50)   NULL,
    [YearMonth]              VARCHAR (50)   NULL,
    [CostCenter]             VARCHAR (500)  NULL,
    [RecoveryIndicator]      VARCHAR (50)   NULL,
    [JoinVenture]            VARCHAR (100)  NULL,
    [PostingPeriod]          VARCHAR (50)   NULL,
    [ReversedWith]           VARCHAR (50)   NULL,
    [TradingPartner]         VARCHAR (50)   NULL,
    [CompanyCode]            VARCHAR (50)   NULL,
    [InvoiceReference]       VARCHAR (50)   NULL,
    [IdContrato]             INT            NULL,
    [IdUsuario]              INT            NULL,
    [FechaDeCargaSQL]        DATETIME       NULL
);

