CREATE TABLE DEA_CuotaPatronalDetalle(IdCuotaPatronal INT,LineItem NVARCHAR(200), GLAccount NVARCHAR(200), PostingKey NVARCHAR(500),AccountShortText NVARCHAR(500), Amount NVARCHAR(100), Currency NVARCHAR(100), Text NVARCHAR(1000), WBS NVARCHAR(200), CC NVARCHAR(100),  BusinessArea NVARCHAR(100), TaxCode NVARCHAR(500), RI NVARCHAR(100), USD NVARCHAR(500), EUR NVARCHAR(500), MXN NVARCHAR(500),
FOREIGN KEY (IdCuotaPatronal) REFERENCES CuotaPatronal(IdCuotaPatronal)
 )
