CREATE TABLE [dbo].[DEMPAY042018] (
    [Contratista]                  FLOAT (53)     NULL,
    [Numero de Contrato]           NVARCHAR (255) NULL,
    [Bloque]                       NVARCHAR (255) NULL,
    [ReferenciaBancaria]           FLOAT (53)     NULL,
    [FechaPago]                    DATETIME       NULL,
    [Banco]                        NVARCHAR (255) NULL,
    [Titular]                      NVARCHAR (255) NULL,
    [Sucursal]                     NVARCHAR (255) NULL,
    [Numero Cuenta]                NVARCHAR (255) NULL,
    [Cuenta Clabe]                 NVARCHAR (255) NULL,
    [Numero Tarjeta]               DATETIME       NULL,
    [Moneda]                       NVARCHAR (255) NULL,
    [Banco Destino]                NVARCHAR (255) NULL,
    [Titular1]                     NVARCHAR (255) NULL,
    [Sucursal1]                    DATETIME       NULL,
    [Numero Cuenta1]               DATETIME       NULL,
    [Cuenta Clabe1]                NVARCHAR (255) NULL,
    [Numero Tarjeta1]              DATETIME       NULL,
    [Moneda1]                      NVARCHAR (255) NULL,
    [RFC Titular]                  NVARCHAR (255) NULL,
    [Monto Pagado]                 FLOAT (53)     NULL,
    [Concepto]                     NVARCHAR (255) NULL,
    [Numero Poliza Contable]       FLOAT (53)     NULL,
    [Intereses]                    NVARCHAR (255) NULL,
    [UUID]                         NVARCHAR (255) NULL,
    [Numero Pedimento Comprobante] NVARCHAR (255) NULL
);

