CREATE TABLE [dbo].[DesarrolloMalva2018] (
    [ID]    FLOAT (53)     NULL,
    [RF_00] NVARCHAR (255) NULL,
    [PA_00] NVARCHAR (255) NULL,
    [PA_01] NVARCHAR (255) NULL,
    [PA_02] DATETIME       NULL,
    [PA_03] DATETIME       NULL,
    [PA_04] NVARCHAR (255) NULL,
    [PA_05] NVARCHAR (255) NULL,
    [PA_06] NVARCHAR (255) NULL,
    [PA_07] NVARCHAR (255) NULL,
    [PA_08] NVARCHAR (255) NULL,
    [PA_09] NVARCHAR (255) NULL,
    [PA_10] NVARCHAR (255) NULL,
    [PA_11] NVARCHAR (255) NULL,
    [PA_12] NVARCHAR (255) NULL,
    [PA_13] FLOAT (53)     NULL,
    [PA_14] NVARCHAR (255) NULL,
    [PA_15] NVARCHAR (255) NULL,
    [PA_16] NVARCHAR (255) NULL,
    [PA_17] MONEY          NULL,
    [PA_18] MONEY          NULL,
    [PA_19] MONEY          NULL,
    [PA_20] MONEY          NULL,
    [PA_21] MONEY          NULL,
    [PA_22] MONEY          NULL,
    [PA_23] MONEY          NULL,
    [PA_24] MONEY          NULL,
    [PA_25] MONEY          NULL,
    [PA_26] MONEY          NULL,
    [PA_27] MONEY          NULL,
    [PA_28] MONEY          NULL,
    [PA_29] MONEY          NULL,
    [PA_30] MONEY          NULL,
    [PA_31] MONEY          NULL,
    [PA_32] MONEY          NULL,
    [PA_33] MONEY          NULL,
    [PA_34] MONEY          NULL,
    [PA_35] MONEY          NULL,
    [PA_36] MONEY          NULL,
    [PA_37] MONEY          NULL,
    [PA_38] MONEY          NULL,
    [PA_39] MONEY          NULL,
    [PA_40] MONEY          NULL,
    [PA_41] MONEY          NULL,
    [PA_42] MONEY          NULL,
    [PA_43] MONEY          NULL,
    [PA_44] MONEY          NULL,
    [PA_45] MONEY          NULL,
    [PA_46] MONEY          NULL,
    [PA_47] MONEY          NULL,
    [PA_48] MONEY          NULL,
    [PA_49] MONEY          NULL,
    [PA_50] MONEY          NULL,
    [PA_51] MONEY          NULL,
    [PA_52] MONEY          NULL,
    [PA_53] MONEY          NULL,
    [PA_54] MONEY          NULL,
    [PA_55] MONEY          NULL,
    [PA_56] MONEY          NULL,
    [PA_57] MONEY          NULL,
    [PA_58] MONEY          NULL,
    [PA_59] MONEY          NULL,
    [PA_60] MONEY          NULL,
    [PA_61] MONEY          NULL,
    [PA_62] MONEY          NULL,
    [PA_63] MONEY          NULL,
    [PA_64] MONEY          NULL
);

