CREATE TABLE [dbo].[DG_DatosGrafica] (
    [idDatoGrafica]      INT            IDENTITY (10000, 1) NOT NULL,
    [IdGrafica]          INT            NULL,
    [Lenguaje]           INT            NULL,
    [IdContrato]         INT            NULL,
    [Titulo]             NVARCHAR (MAX) NULL,
    [Subtitulo]          NVARCHAR (MAX) NULL,
    [Titulo_yAxis]       NVARCHAR (MAX) NULL,
    [Titulo_xAxis]       NVARCHAR (MAX) NULL,
    [Fecha]              NVARCHAR (MAX) NULL,
    [Fecha_NuevoFormato] NVARCHAR (MAX) NULL,
    [CantidadSeries]     INT            NULL,
    [valueSuffix]        NVARCHAR (MAX) NULL,
    [SerieName0]         NVARCHAR (MAX) NULL,
    [SerieValues0]       REAL           NULL,
    [SerieType0]         NVARCHAR (MAX) NULL,
    [SerieColor0]        NVARCHAR (MAX) NULL,
    [SerieName1]         NVARCHAR (MAX) NULL,
    [SerieValues1]       REAL           NULL,
    [SerieType1]         NVARCHAR (MAX) NULL,
    [SerieColor1]        NVARCHAR (MAX) NULL,
    [SerieName2]         NVARCHAR (MAX) NULL,
    [SerieValues2]       REAL           NULL,
    [SerieType2]         NVARCHAR (MAX) NULL,
    [SerieColor2]        NVARCHAR (MAX) NULL,
    [SerieName3]         NVARCHAR (MAX) NULL,
    [SerieValues3]       REAL           NULL,
    [SerieType3]         NVARCHAR (MAX) NULL,
    [SerieColor3]        NVARCHAR (MAX) NULL,
    [SerieName4]         NVARCHAR (MAX) NULL,
    [SerieValues4]       REAL           NULL,
    [SerieType4]         NVARCHAR (MAX) NULL,
    [SerieColor4]        NVARCHAR (MAX) NULL,
    [SerieName5]         NVARCHAR (MAX) NULL,
    [SerieValues5]       REAL           NULL,
    [SerieType5]         NVARCHAR (MAX) NULL,
    [SerieColor5]        NVARCHAR (MAX) NULL,
    [SerieName6]         NVARCHAR (MAX) NULL,
    [SerieValues6]       REAL           NULL,
    [SerieType6]         NVARCHAR (MAX) NULL,
    [SerieColor6]        NVARCHAR (MAX) NULL
);

