CREATE TABLE [dbo].[EN_ContratoEntregable_RespRepetidos] (
    [IdContratoEntregable]        INT            NOT NULL,
    [IdContrato]                  INT            NULL,
    [IdEntregable]                INT            NULL,
    [AreaResponsable]             NVARCHAR (MAX) NULL,
    [Elabora]                     NVARCHAR (MAX) NULL,
    [Revisa]                      NVARCHAR (MAX) NULL,
    [Aprueba]                     NVARCHAR (MAX) NULL,
    [UsuarioElabora]              INT            NULL,
    [UsuarioRevision]             INT            NULL,
    [UsuarioAprueba]              INT            NULL,
    [DiasRevision]                INT            NULL,
    [DiasAprobacion]              INT            NULL,
    [DiasAlerta]                  INT            NULL,
    [ReceptorAlerta]              NVARCHAR (MAX) NULL,
    [CreadoPor]                   INT            NULL,
    [CreadoEl]                    DATETIME       NULL,
    [ModificadoPor]               INT            NULL,
    [ModificadoEl]                DATETIME       NULL,
    [Activo]                      BIT            NULL,
    [Entrega]                     VARCHAR (300)  NULL,
    [FechaLimiteEntrega]          DATETIME       NULL,
    [FechaLimiteEntregaRegulador] DATE           NULL,
    [DiasElaboracion]             INT            NULL
);

