CREATE TABLE [dbo].[EN_DocumentoGeneral] (
    [DocumentoId]         INT              IDENTITY (1, 1) NOT NULL,
    [NivelPadre]          INT              NULL,
    [ContratoId]          INT              NULL,
    [EtapaId]             INT              NULL,
    [ReceptorId]          INT              NULL,
    [InstalacionId]       INT              NULL,
    [MarcoLegalId]        INT              NULL,
    [EntregableId]        INT              NULL,
    [Bucket]              NVARCHAR (MAX)   NULL,
    [Folder]              NVARCHAR (MAX)   NULL,
    [UUIDAmazon]          UNIQUEIDENTIFIER NULL,
    [NombreArchivo]       NVARCHAR (MAX)   NULL,
    [Meta]                NVARCHAR (MAX)   NULL,
    [CreadoPor]           INT              NULL,
    [CreadoEl]            DATETIME         NULL,
    [ModificadoPor]       INT              NULL,
    [ModificadoEl]        DATETIME         NULL,
    [Activo]              BIT              NULL,
    [TipoArchivo]         NVARCHAR (100)   NULL,
    [SizeBytes]           DECIMAL (18)     NULL,
    [Comentarios]         NVARCHAR (MAX)   NULL,
    [Frecuencia]          NVARCHAR (MAX)   NULL,
    [FechaEntregaAnioMes] NVARCHAR (MAX)   NULL,
    [EtapaPozoId]         INT              NULL,
    CONSTRAINT [PK_EN_DocumentoGeneral] PRIMARY KEY CLUSTERED ([DocumentoId] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_EN_DocumentoGeneral_CO_Contrato] FOREIGN KEY ([ContratoId]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

