CREATE TABLE [dbo].[EN_Entregable_RespRepetidos] (
    [IdEntregable]                     INT            NOT NULL,
    [DocumentoEntregable]              NVARCHAR (MAX) NULL,
    [IdMarcoLegal]                     INT            NULL,
    [TituloAnexo]                      NVARCHAR (MAX) NULL,
    [Capitulo]                         NVARCHAR (MAX) NULL,
    [Descripcion]                      NVARCHAR (MAX) NULL,
    [Seccion]                          NVARCHAR (MAX) NULL,
    [Articulo]                         NVARCHAR (MAX) NULL,
    [Inciso]                           NVARCHAR (MAX) NULL,
    [Apartado]                         NVARCHAR (MAX) NULL,
    [Observaciones]                    NVARCHAR (MAX) NULL,
    [ArchivoNormatividad]              NVARCHAR (MAX) NULL,
    [ArchivoEntregable]                NVARCHAR (MAX) NULL,
    [IdRegulador]                      INT            NULL,
    [IdEtapa]                          INT            NULL,
    [IdReceptorEntregable]             INT            NULL,
    [IdResponsableGenerador]           INT            NULL,
    [IdFrecuenciaEntregable]           INT            NULL,
    [TiempoEntrega]                    NVARCHAR (MAX) NULL,
    [IdTiempoRespuesta]                INT            NULL,
    [FechaPublicacion]                 DATETIME       NULL,
    [FechaModificacion]                DATETIME       NULL,
    [CreadoPor]                        INT            NULL,
    [CreadoEn]                         DATETIME       NULL,
    [ModificadoPor]                    INT            NULL,
    [ModificadoEn]                     DATETIME       NULL,
    [IsActivo]                         BIT            NULL,
    [IsEliminado]                      BIT            NULL,
    [Consecutivo]                      NVARCHAR (MAX) NULL,
    [TCLicencia]                       BIT            NULL,
    [TCProducionCompartida]            BIT            NULL,
    [TCLicenciaFarmOuts]               BIT            NULL,
    [TCProducionCompartidaFarmOuts]    BIT            NULL,
    [UGTerrestre]                      BIT            NULL,
    [UGCostaFuera]                     BIT            NULL,
    [REReguladores]                    BIT            NULL,
    [REOperadores]                     BIT            NULL,
    [APAdministracionContratos]        BIT            NULL,
    [APPozoAlivio]                     BIT            NULL,
    [APCierreDesmantelamientoAbandono] BIT            NULL,
    [APPerforacion]                    BIT            NULL,
    [APTerminacion]                    BIT            NULL,
    [APActProduccion]                  BIT            NULL,
    [APEstimulacion]                   BIT            NULL,
    [APPruebaProduccion]               BIT            NULL,
    [APConstruccionCamino]             BIT            NULL,
    [APConstruccionLocalizacion]       BIT            NULL,
    [APRehabilitacionCamino]           BIT            NULL,
    [APRehabilitacionLocalizacion]     BIT            NULL,
    [APTomaInformacionSismica]         BIT            NULL,
    [APCorteNucleos]                   BIT            NULL,
    [APConstruccionLineaDescarga]      BIT            NULL,
    [APSistemaArtificialProduccion]    BIT            NULL,
    [APMedicionPozos]                  BIT            NULL,
    [APTomaInformacionPozo]            BIT            NULL,
    [APReparacionMayor]                BIT            NULL,
    [APReparacionMenor]                BIT            NULL,
    [APTransporteHidrocarburos]        BIT            NULL,
    [APQuemaGas]                       BIT            NULL
);

