CREATE TABLE [dbo].[EN_Etapa] (
    [IdEtapa] INT            IDENTITY (1, 1) NOT NULL,
    [Etapa]   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_EN_Etapa] PRIMARY KEY CLUSTERED ([IdEtapa] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);


GO
CREATE NONCLUSTERED INDEX [IX_EN_Etapa]
    ON [dbo].[EN_Etapa]([IdEtapa] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON);

