CREATE TABLE [dbo].[Entregables20191107_2] (
    [ID]                               INT            NULL,
    [Consecutivo]                      VARCHAR (100)  NULL,
    [FrecuenciaEntregable]             VARCHAR (250)  NULL,
    [Regulador]                        VARCHAR (100)  NULL,
    [MarcoLegal]                       VARCHAR (500)  NULL,
    [TituloAnexo]                      VARCHAR (5000) NULL,
    [Descripcion]                      VARCHAR (5000) NULL,
    [Capitulo]                         VARCHAR (5000) NULL,
    [Articulo]                         VARCHAR (8000) NULL,
    [DocumentoEntregable]              VARCHAR (5000) NULL,
    [ReguladorOperador]                VARCHAR (100)  NULL,
    [Inciso]                           VARCHAR (100)  NULL,
    [Apartado]                         VARCHAR (100)  NULL,
    [Observaciones]                    VARCHAR (100)  NULL,
    [ArchivoNormatividad]              VARCHAR (100)  NULL,
    [Etapa]                            VARCHAR (150)  NULL,
    [ReceptorEntregable]               VARCHAR (100)  NULL,
    [ResponsableGenerador]             VARCHAR (100)  NULL,
    [TiempoEntrega]                    VARCHAR (1500) NULL,
    [TiempoRespuesta]                  VARCHAR (1500) NULL,
    [IsActivo]                         BIT            NULL,
    [TCLicencia]                       BIT            NULL,
    [TCProducionCompartida]            BIT            NULL,
    [TCLicenciaFarmOuts]               BIT            NULL,
    [TCProducionCompartidaFarmOuts]    BIT            NULL,
    [UGTerrestre]                      BIT            NULL,
    [UGCostaFuera]                     BIT            NULL,
    [REReguladores]                    BIT            NULL,
    [REOperadores]                     BIT            NULL,
    [APAdministracionContratos]        BIT            NULL,
    [APPozoAlivio]                     BIT            NULL,
    [APCierreDesmantelamientoAbandono] BIT            NULL,
    [APPerforacion]                    BIT            NULL,
    [APTerminacion]                    BIT            NULL,
    [APActProduccion]                  BIT            NULL,
    [APEstimulacion]                   BIT            NULL,
    [APPruebaProduccion]               BIT            NULL,
    [APConstruccionCamino]             BIT            NULL,
    [APConstruccionLocalizacion]       BIT            NULL,
    [APRehabilitacionCamino]           BIT            NULL,
    [APRehabilitacionLocalizacion]     BIT            NULL,
    [APTomaInformacionSismica]         BIT            NULL,
    [APCorteNucleos]                   BIT            NULL,
    [APConstruccionLineaDescarga]      BIT            NULL,
    [APSistemaArtificialProduccion]    BIT            NULL,
    [APMedicionPozos]                  BIT            NULL,
    [APTomaInformacionPozo]            BIT            NULL,
    [APReparacionMayor]                BIT            NULL,
    [APReparacionMenor]                BIT            NULL,
    [APTransporteHidrocarburos]        BIT            NULL,
    [APQuemaGas]                       BIT            NULL,
    [IdMarcoLegal]                     INT            NULL,
    [IdRegulador]                      INT            NULL,
    [IdEtapa]                          INT            NULL,
    [IdReceptorEntregable]             INT            NULL,
    [IdFrecuenciaEntregable]           INT            NULL,
    [IdTiempoRespuesta]                INT            NULL,
    [IdResponsableGenerador]           INT            NULL
);

