CREATE TABLE [dbo].[ENTREGABLESCRISTEL_RESP] (
    [IDCONTRATOENTREGABLE]  INT           IDENTITY (10000, 1) NOT NULL,
    [FOCALPOINT]            VARCHAR (250) NULL,
    [ACCOUNTABLECOMPLIANCE] VARCHAR (250) NULL
);

