CREATE TABLE [dbo].[EntregablesContratosRepsol] (
    [IDCONTRATO]             FLOAT (53)     NULL,
    [Consecutivo]            VARCHAR (250)  NULL,
    [Arearesponsable]        VARCHAR (250)  NULL,
    [Elabora]                VARCHAR (500)  NULL,
    [Revisa]                 VARCHAR (500)  NULL,
    [Aprueba]                VARCHAR (500)  NULL,
    [FechaEntregaRegulador]  DATE           NULL,
    [FechaLimiteInterna]     DATE           NULL,
    [Activo]                 VARCHAR (50)   NULL,
    [Desarrollo]             FLOAT (53)     NULL,
    [Exploración]            FLOAT (53)     NULL,
    [Evaluación]             FLOAT (53)     NULL,
    [Transicion]             FLOAT (53)     NULL,
    [AbandonodelArea]        FLOAT (53)     NULL,
    [AbandonodePozo]         FLOAT (53)     NULL,
    [Liderdelarea]           VARCHAR (1500) NULL,
    [ResponsableRegulatorio] VARCHAR (1500) NULL,
    [Elaborainterno]         VARCHAR (1500) NULL,
    [Actividad]              VARCHAR (500)  NULL,
    [IdContratoEntregable]   INT            NULL,
    [IdArea]                 INT            NULL,
    [identregable]           INT            NULL,
    [idusuario]              INT            NULL,
    [accountablecompliance]  VARCHAR (250)  NULL,
    [focalpoint]             VARCHAR (250)  NULL
);

