CREATE TABLE [dbo].[Farmouts_1_2] (
    [Ronda]                            NVARCHAR (255) NULL,
    [IdEntregable]                     NVARCHAR (255) NULL,
    [Consecutivo]                      NVARCHAR (255) NULL,
    [FrecuenciaEntregable]             NVARCHAR (255) NULL,
    [Regulador]                        NVARCHAR (255) NULL,
    [MarcoLegal]                       NVARCHAR (255) NULL,
    [Articulo]                         NVARCHAR (MAX) NULL,
    [DocumentoEntregable]              NVARCHAR (MAX) NULL,
    [TituloAnexo]                      NVARCHAR (255) NULL,
    [Capitulo]                         NVARCHAR (255) NULL,
    [Descripcion]                      NVARCHAR (255) NULL,
    [Seccion]                          FLOAT (53)     NULL,
    [Inciso]                           NVARCHAR (255) NULL,
    [Apartado]                         NVARCHAR (255) NULL,
    [Observaciones]                    NVARCHAR (255) NULL,
    [ArchivoNormatividad]              NVARCHAR (255) NULL,
    [Etapa]                            NVARCHAR (255) NULL,
    [ReceptorEntregable]               NVARCHAR (255) NULL,
    [ResponsableGenerador]             NVARCHAR (255) NULL,
    [TiempoEntrega]                    NVARCHAR (255) NULL,
    [TiempoRespuesta]                  NVARCHAR (255) NULL,
    [IsActivo]                         FLOAT (53)     NULL,
    [TCLicencia]                       FLOAT (53)     NULL,
    [TCProducionCompartida]            FLOAT (53)     NULL,
    [TCLicenciaFarmOuts]               FLOAT (53)     NULL,
    [TCProducionCompartidaFarmOuts]    FLOAT (53)     NULL,
    [UGTerrestre]                      FLOAT (53)     NULL,
    [UGCostaFuera]                     FLOAT (53)     NULL,
    [REReguladores]                    FLOAT (53)     NULL,
    [REOperadores]                     FLOAT (53)     NULL,
    [APAdministracionContratos]        FLOAT (53)     NULL,
    [APPozoAlivio]                     FLOAT (53)     NULL,
    [APCierreDesmantelamientoAbandono] FLOAT (53)     NULL,
    [APPerforacion]                    FLOAT (53)     NULL,
    [APTerminacion]                    FLOAT (53)     NULL,
    [APActProduccion]                  FLOAT (53)     NULL,
    [APEstimulacion]                   FLOAT (53)     NULL,
    [APPruebaProduccion]               FLOAT (53)     NULL,
    [APConstruccionCamino]             FLOAT (53)     NULL,
    [APConstruccionLocalizacion]       FLOAT (53)     NULL,
    [APRehabilitacionCamino]           FLOAT (53)     NULL,
    [APRehabilitacionLocalizacion]     FLOAT (53)     NULL,
    [APTomaInformacionSismica]         FLOAT (53)     NULL,
    [APCorteNucleos]                   FLOAT (53)     NULL,
    [APConstruccionLineaDescarga]      FLOAT (53)     NULL,
    [APSistemaArtificialProduccion]    FLOAT (53)     NULL,
    [APMedicionPozos]                  FLOAT (53)     NULL,
    [APTomaInformacionPozo]            FLOAT (53)     NULL,
    [APReparacionMayor]                FLOAT (53)     NULL,
    [APReparacionMenor]                FLOAT (53)     NULL,
    [APTransporteHidrocarburos]        FLOAT (53)     NULL,
    [APQuemaGas]                       FLOAT (53)     NULL,
    [IdMarcoLegal]                     INT            NULL,
    [IdRegulador]                      INT            NULL,
    [IdEtapa]                          INT            NULL,
    [IdReceptorEntregable]             INT            NULL,
    [IdFrecuenciaEntregable]           INT            NULL,
    [IdTiempoRespuesta]                INT            NULL,
    [IdResponsableGenerador]           INT            NULL,
    [IdRonda]                          INT            NULL
);

