CREATE TABLE [dbo].[FI_FacturaPCM] (
    [IdFactura]                 INT            NULL,
    [Serie]                     NVARCHAR (MAX) NULL,
    [Folio]                     NVARCHAR (MAX) NULL,
    [Fecha]                     DATETIME       NULL,
    [Sello]                     NVARCHAR (MAX) NULL,
    [FormaPago]                 NVARCHAR (MAX) NULL,
    [NoCertificado]             NVARCHAR (MAX) NULL,
    [Certificado]               NVARCHAR (MAX) NULL,
    [CondicionesDePago]         NVARCHAR (MAX) NULL,
    [SubTotal]                  MONEY          NULL,
    [Descuento]                 MONEY          NULL,
    [TipoCambio]                MONEY          NULL,
    [Moneda]                    NVARCHAR (MAX) NULL,
    [MontoConIva]               MONEY          NULL,
    [TipoComprobante]           NVARCHAR (MAX) NULL,
    [MetodoPago]                NVARCHAR (MAX) NULL,
    [LugarExpedicion]           NVARCHAR (MAX) NULL,
    [NumCtaPago]                NVARCHAR (MAX) NULL,
    [Emisor]                    NVARCHAR (MAX) NULL,
    [Receptor]                  NVARCHAR (MAX) NULL,
    [UUID]                      VARCHAR (500)  NULL,
    [FechaTimbrado]             DATETIME       NULL,
    [SelloCFD]                  NVARCHAR (MAX) NULL,
    [NoCertificadoSAT]          NVARCHAR (MAX) NULL,
    [SelloSAT]                  NVARCHAR (MAX) NULL,
    [Tipo]                      NVARCHAR (MAX) NULL,
    [FechaRecepcion]            DATETIME       NULL,
    [IdSubcontratista]          INT            NULL,
    [IdMoneda]                  INT            NULL,
    [IdContrato]                INT            NULL,
    [XML]                       NVARCHAR (MAX) NULL,
    [Activa]                    BIT            NULL,
    [ArchivoPDF]                NVARCHAR (MAX) NULL,
    [ArchivoXML]                NVARCHAR (MAX) NULL,
    [CreadoPor]                 INT            NULL,
    [CreadoEn]                  DATETIME       NULL,
    [ModificadoPor]             INT            NULL,
    [ModificadoEn]              DATETIME       NULL,
    [NombreXML]                 NVARCHAR (MAX) NULL,
    [IdEstudioPrecioTransfer]   INT            NULL,
    [IdDocFacturacionSIPAC]     NVARCHAR (50)  NULL,
    [ProcesadoSIPAC]            BIT            NULL,
    [RegimenFiscal]             NVARCHAR (MAX) NULL,
    [UsoCFDI]                   NVARCHAR (MAX) NULL,
    [VersionCFDI]               NVARCHAR (MAX) NULL,
    [TotalImpuestosTrasladados] MONEY          NULL,
    [TotalImpuestosRetenidos]   MONEY          NULL
);

