CREATE TABLE [dbo].[FI_PedimentoComprobante] (
    [IdPedimentoComprobante]            INT            IDENTITY (1, 1) NOT NULL,
    [IdContrato]                        INT            NULL,
    [NumeroPedimento]                   NVARCHAR (50)  NULL,
    [ClavePedimento]                    INT            NULL,
    [FolioComprobante]                  NVARCHAR (50)  NULL,
    [FechaPago]                         DATE           NULL,
    [Regimen]                           NVARCHAR (200) NULL,
    [IdSubcontratistaImportador]        INT            NULL,
    [AduanaES]                          NVARCHAR (50)  NULL,
    [IdSubcontratistaExportador]        INT            NULL,
    [IdFormaPago]                       INT            CONSTRAINT [DF_FI_PedimentoComprobante_IdFormaPago] DEFAULT ((1)) NULL,
    [IdMoneda]                          INT            NULL,
    [AcuseElectronico]                  NVARCHAR (200) NULL,
    [IdEstudioPrecioTransfer]           INT            NULL,
    [IdDocFacturacionSIPAC]             NVARCHAR (50)  NULL,
    [CvTipoDocFacturacion]              INT            NULL,
    [ProcesadoSIPAC]                    BIT            CONSTRAINT [DF_FI_PedimentoComprobante_ProcesadoSIPAC] DEFAULT ((0)) NULL,
    [CreadoPor]                         INT            NULL,
    [CreadoEn]                          DATETIME       NULL,
    [ModificadoPor]                     INT            NULL,
    [ModificadoEn]                      DATETIME       NULL,
    [HashSHA256]                        NVARCHAR (300) NULL,
    [Activo]                            BIT            NULL,
    [IdOrigen]                          INT            NULL,
    [IdPedimentoComprobantePetrovendor] INT            NULL,
    [FechaIntercambio]                  DATETIME       NULL,
    [FechaModificacionIntercambio]      DATETIME       NULL,
    [IdFiscalP]                         NVARCHAR (50)  NULL,
    [RazonSocialP]                      NVARCHAR (MAX) NULL,
    [NumFacturaC]                       NVARCHAR (50)  NULL,
    [Reportado]                         BIT            NULL,
    [EsnotaCredito]                     BIT            NULL,
    [CuentaBancaria]                    NVARCHAR (500) NULL,
    [ProcesadoHash]                     BIT            DEFAULT ((0)) NULL,
    CONSTRAINT [PK_FI_PedimentoComprobante] PRIMARY KEY CLUSTERED ([IdPedimentoComprobante] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_FI_PedimentoComprobante_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK_FI_PedimentoComprobante_FI_ClavesPedimento] FOREIGN KEY ([ClavePedimento]) REFERENCES [dbo].[FI_ClavesPedimento] ([IdPedimento]),
    CONSTRAINT [FK_FI_PedimentoComprobante_FI_EstudioPreciosTransfer] FOREIGN KEY ([IdEstudioPrecioTransfer]) REFERENCES [dbo].[FI_EstudioPreciosTransfer] ([IdEstudioPrecioTransfer]),
    CONSTRAINT [FK_FI_PedimentoComprobante_PV_SubcontratistaExportador] FOREIGN KEY ([IdSubcontratistaExportador]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista]),
    CONSTRAINT [FK_FI_PedimentoComprobante_PV_SubcontratistaImportador] FOREIGN KEY ([IdSubcontratistaImportador]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista]),
    CONSTRAINT [FK_FI_PedimentoComprobante_PV_TipoMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda])
);

