CREATE TABLE [dbo].[FI_TextoPDFConfig] (
    [Id]  INT          NOT NULL,
    [RFC] VARCHAR (14) NOT NULL,
    CONSTRAINT [PK_FI_ImportarTextoPDFConfig] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FI_ImportarTextoPDFConfig]
    ON [dbo].[FI_TextoPDFConfig]([RFC] ASC) WITH (STATISTICS_NORECOMPUTE = ON);

