CREATE TABLE [dbo].[FI_Transfer] (
    [IdTransferencia]            INT            IDENTITY (1, 1) NOT NULL,
    [IdContrato]                 INT            NULL,
    [IdComprobantePago]          NVARCHAR (50)  NULL,
    [NombreExtencionArchivo]     NVARCHAR (MAX) NULL,
    [ReferenciaBancaria]         NVARCHAR (50)  NULL,
    [FechaPago]                  DATE           NULL,
    [IdCuentaOrigen]             INT            NULL,
    [IdCuentaDestino]            INT            NULL,
    [MontoPagado]                MONEY          NULL,
    [IdMoneda]                   INT            NULL,
    [IdClasificacionDocumento]   INT            CONSTRAINT [DF_FI_Transfer_IdClasificacionDocumento] DEFAULT ((2)) NULL,
    [Concepto]                   NVARCHAR (MAX) NULL,
    [IdMetodoPago]               INT            NULL,
    [ProcesadoSIPAC]             BIT            NULL,
    [NumeroPolizaContable]       INT            NULL,
    [Intereses]                  MONEY          CONSTRAINT [DF_FI_Transfer_Intereses] DEFAULT ((0)) NULL,
    [PDF]                        NVARCHAR (MAX) NULL,
    [CreadoPor]                  INT            NULL,
    [CreadoEn]                   DATETIME       NULL,
    [ModificadoPor]              INT            NULL,
    [ModificadoEn]               DATETIME       NULL,
    [HashSHA256]                 NVARCHAR (300) NULL,
    [IdFacturaPago]              INT            CONSTRAINT [DF_FI_Transfer_IdFacturaPago] DEFAULT ((0)) NULL,
    [AWSPDFId]                   INT            NULL,
    [IdFormaPago]                INT            NULL,
    [IdTransferenciaImportacion] INT            NULL,
    CONSTRAINT [PK_FI_Transfer] PRIMARY KEY CLUSTERED ([IdTransferencia] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_FI_Transfer_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [FK_FI_Transfer_PV_CuentaDestino] FOREIGN KEY ([IdCuentaDestino]) REFERENCES [dbo].[PV_CuentaBancaria] ([DatoBancarioID]),
    CONSTRAINT [FK_FI_Transfer_PV_CuentaOrigen] FOREIGN KEY ([IdCuentaOrigen]) REFERENCES [dbo].[PV_CuentaBancaria] ([DatoBancarioID]),
    CONSTRAINT [FK_FI_Transfer_PV_MetodoPago] FOREIGN KEY ([IdMetodoPago]) REFERENCES [dbo].[PV_MetodoPago] ([idMetodoPago]),
    CONSTRAINT [FK_FI_Transfer_PV_TipoMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda])
);

