CREATE TABLE [dbo].[FI_TransferImportacion] (
    [IdTransferenciaImportacion] INT           NOT NULL,
    [IdContrato]                 INT           NOT NULL,
    [Id]                         INT           NULL,
    [FechaFactura]               DATETIME      NULL,
    [RFCEmisor]                  VARCHAR (15)  NOT NULL,
    [Proveedor]                  VARCHAR (350) NOT NULL,
    [FormaPago]                  VARCHAR (50)  NOT NULL,
    [BancoOrigen]                VARCHAR (50)  NOT NULL,
    [CuentaOrigen]               VARCHAR (50)  NOT NULL,
    [BancoDestino]               VARCHAR (50)  NOT NULL,
    [CuentaDestino]              VARCHAR (20)  NOT NULL,
    [FechaPago]                  DATETIME      NOT NULL,
    [MontoPagado]                FLOAT (53)    NOT NULL,
    [Interes]                    FLOAT (53)    NOT NULL,
    [MonedaPago]                 VARCHAR (5)   NOT NULL,
    [Concepto]                   VARCHAR (250) NOT NULL,
    [NumeroPoliza]               INT           NOT NULL,
    [UUIDFactura]                VARCHAR (60)  NOT NULL,
    [ValorFactura]               FLOAT (53)    NOT NULL,
    [MonedaFactura]              VARCHAR (5)   NOT NULL,
    [Contrato]                   VARCHAR (100) NOT NULL,
    [Sincronizar]                BIT           NOT NULL,
    [Procesado]                  BIT           NULL,
    [IdTransferFactura]          INT           NULL,
    [TieneError]                 BIT           NOT NULL,
    [Error]                      VARCHAR (350) NULL,
    [CreadoEl]                   DATETIME      NOT NULL,
    [ModificadoEl]               DATETIME      NULL,
    CONSTRAINT [PK_FI_TransferImportacion] PRIMARY KEY CLUSTERED ([IdTransferenciaImportacion] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_FI_TransferImportacion_CO_Contrato] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato])
);

