CREATE TABLE [dbo].[GastosIHSA2019_v2] (
    [ID]                  FLOAT (53)     NULL,
    [Fecharegistro]       DATETIME       NULL,
    [FechaFactura]        DATETIME       NULL,
    [Poliza]              VARCHAR (255)  NULL,
    [NOPoliza]            FLOAT (53)     NULL,
    [Tipodocumento]       VARCHAR (255)  NULL,
    [Codprocedenciamov]   VARCHAR (255)  NULL,
    [Nombreprocedencia]   VARCHAR (255)  NULL,
    [NOdocumentoExterno]  FLOAT (53)     NULL,
    [UUID]                VARCHAR (255)  NULL,
    [NOCuenta]            FLOAT (53)     NULL,
    [HaberDivOrigen]      VARCHAR (255)  NULL,
    [DebeDivOrigen]       FLOAT (53)     NULL,
    [ImporteOriginal]     FLOAT (53)     NULL,
    [CodDivisaOriginal]   VARCHAR (255)  NULL,
    [Descripcion]         VARCHAR (255)  NULL,
    [NOproyecto]          VARCHAR (255)  NULL,
    [Presupuesto]         VARCHAR (255)  NULL,
    [NOtareaproyecto]     VARCHAR (255)  NULL,
    [OtCodigo]            FLOAT (53)     NULL,
    [Pozo]                VARCHAR (255)  NULL,
    [SeleccionRubro]      VARCHAR (255)  NULL,
    [CostoAtribuidoAdmon] VARCHAR (255)  NULL,
    [CUENTASECTORHIDRO]   VARCHAR (255)  NULL,
    [PropocionCN]         FLOAT (53)     NULL,
    [fechainicio]         DATETIME       NULL,
    [FechaFin]            DATETIME       NULL,
    [PedidoCompra]        VARCHAR (255)  NULL,
    [IdPRESUP]            FLOAT (53)     NULL,
    [CONTRATOFACTURA]     NVARCHAR (255) NULL,
    [PRESUPUESTOLINEA]    NVARCHAR (255) NULL,
    [CONTRATOPRESUPUESTO] NVARCHAR (255) NULL,
    [IdFactura]           INT            NULL,
    [IdInstalacion]       INT            NULL,
    [IdGastoRubro]        INT            NULL,
    [IdCatalogoCuentasSH] INT            NULL,
    [IdContratoFactura]   INT            NULL
);

