CREATE TABLE [dbo].[Gastos_Layout] (
    [IdGastosLayout]    INT            IDENTITY (1, 1) NOT NULL,
    [IdVendor]          INT            NULL,
    [VendorName]        NVARCHAR (MAX) NULL,
    [Folio]             NVARCHAR (250) NULL,
    [Total]             FLOAT (53)     NULL,
    [Subtotal]          FLOAT (53)     NULL,
    [TotalUsd]          FLOAT (53)     NULL,
    [SubtotalUsd]       FLOAT (53)     NULL,
    [Moneda]            NVARCHAR (100) NULL,
    [TipoCambio]        FLOAT (53)     NULL,
    [DocumentoFactura]  INT            NULL,
    [DocumentoClearing] INT            NULL,
    [TextoClearing]     NVARCHAR (MAX) NULL,
    [Area]              NVARCHAR (150) NULL,
    [FechaClearing]     DATE           NULL,
    [FechaDoc]          DATE           NULL,
    [Cuenta]            INT            NULL,
    [IdFmp]             NVARCHAR (250) NULL,
    [Fmp]               NVARCHAR (MAX) NULL,
    [Wbs]               NVARCHAR (250) NULL,
    [Ac]                NVARCHAR (150) NULL,
    [Sa]                NVARCHAR (150) NULL,
    [Ta]                NVARCHAR (150) NULL,
    [UUIDFactura]       NVARCHAR (300) NULL,
    [ComplementoPago]   NVARCHAR (300) NULL,
    [Activo]            BIT            NULL,
    [CreadoEl]          DATETIME       NULL,
    [CreadoPor]         INT            NULL,
    [ModificadoPor]     INT            NULL,
    [ModificadoEl]      DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([IdGastosLayout] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

