CREATE TABLE [dbo].[GastosOgarrio2019] (
    [ID]                      FLOAT (53)     NULL,
    [RF_00]                   NVARCHAR (255) NULL,
    [PA_00]                   NVARCHAR (255) NULL,
    [PA_01]                   NVARCHAR (255) NULL,
    [PA_04]                   NVARCHAR (255) NULL,
    [PA_05]                   NVARCHAR (255) NULL,
    [PA_06]                   NVARCHAR (255) NULL,
    [PA_07]                   NVARCHAR (255) NULL,
    [PA_08]                   VARCHAR (150)  NULL,
    [PA_09]                   NVARCHAR (255) NULL,
    [PA_10]                   NVARCHAR (255) NULL,
    [PA_11]                   NVARCHAR (255) NULL,
    [PA_12]                   VARCHAR (500)  NULL,
    [PA_13]                   FLOAT (53)     NULL,
    [F15]                     NVARCHAR (255) NULL,
    [PA_14]                   DATETIME       NULL,
    [PA_15]                   DATETIME       NULL,
    [PA_16]                   NVARCHAR (255) NULL,
    [PA_17]                   DATETIME       NULL,
    [PA_18]                   NVARCHAR (255) NULL,
    [PA_19]                   NVARCHAR (255) NULL,
    [PA_20]                   NVARCHAR (255) NULL,
    [PA_21]                   FLOAT (53)     NULL,
    [PA_22]                   NVARCHAR (255) NULL,
    [PA_23]                   NVARCHAR (255) NULL,
    [PA_24]                   NVARCHAR (255) NULL,
    [PA_25]                   NVARCHAR (255) NULL,
    [PA_26]                   NVARCHAR (255) NULL,
    [IdContrato]              INT            NULL,
    [IdFactura]               INT            NULL,
    [IdInstalacion]           INT            NULL,
    [IdServiccio]             INT            NULL,
    [IdActividadPetrolera]    INT            NULL,
    [IdSubactividadPetrolera] INT            NULL,
    [IdTareaPetrolera]        INT            NULL,
    [IdCuentaSH]              INT            NULL,
    [IdLineaPresupuestoMes]   INT            NULL,
    [IdRegistro]              INT            NULL
);

