CREATE TABLE [dbo].[GastosPCM] (
    [FECHA_FACTURA]                            DATETIME       NULL,
    [RFC_EMISOR]                               NVARCHAR (255) NULL,
    [NOMBRE_PROVEEDOR]                         NVARCHAR (255) NULL,
    [LINEA_PRESUPUESTO_SUBACTIVIDAD]           NVARCHAR (255) NULL,
    [MES_APLICABLE]                            NVARCHAR (255) NULL,
    [DOCUMENTO]                                NVARCHAR (255) NULL,
    [RUBRO]                                    NVARCHAR (255) NULL,
    [CONTENIDO NACIONAL]                       FLOAT (53)     NULL,
    [UUID]                                     NVARCHAR (255) NULL,
    [INICIO_EJECUCION]                         DATETIME       NULL,
    [FIN_EJECUCION]                            DATETIME       NULL,
    [MONTO_EJERCIDO]                           FLOAT (53)     NULL,
    [INSTALACION]                              NVARCHAR (255) NULL,
    [COMENTARIOS]                              NVARCHAR (255) NULL,
    [CUENTA_SECTOR_HIDROCARBUROS]              NVARCHAR (255) NULL,
    [NUMERO_POLIZA]                            FLOAT (53)     NULL,
    [GASTO_ADMINISTRATIVO_1_GASTO_OPERATIVO_2] FLOAT (53)     NULL,
    [IdPrograma]                               INT            NULL,
    [IdFactura]                                INT            NULL,
    [IdCatalogoCuentasSH]                      INT            NULL,
    [IdServicio]                               INT            NULL,
    [IdInstalacion]                            INT            NULL,
    [Anio]                                     INT            NULL,
    [mes]                                      INT            NULL
);

