CREATE TABLE [dbo].[IndicativoRICOS2018] (
    [ID]    FLOAT (53)     NULL,
    [RF_00] NVARCHAR (255) NULL,
    [PA_00] NVARCHAR (255) NULL,
    [PA_01] NVARCHAR (255) NULL,
    [PA_02] DATETIME       NULL,
    [PA_03] DATETIME       NULL,
    [PA_04] NVARCHAR (255) NULL,
    [PA_05] NVARCHAR (255) NULL,
    [PA_06] NVARCHAR (255) NULL,
    [PA_07] NVARCHAR (255) NULL,
    [PA_08] NVARCHAR (255) NULL,
    [PA_09] NVARCHAR (255) NULL,
    [PA_10] NVARCHAR (255) NULL,
    [PA_11] NVARCHAR (255) NULL,
    [PA_12] NVARCHAR (255) NULL,
    [PA_13] NVARCHAR (255) NULL,
    [PA_14] NVARCHAR (255) NULL,
    [PA_15] NVARCHAR (255) NULL,
    [PA_16] NVARCHAR (255) NULL,
    [Mes1]  MONEY          NULL,
    [Mes2]  MONEY          NULL,
    [Mes3]  MONEY          NULL,
    [Mes4]  MONEY          NULL,
    [Mes5]  MONEY          NULL,
    [Mes6]  MONEY          NULL,
    [Mes7]  MONEY          NULL,
    [Mes8]  MONEY          NULL,
    [Mes9]  MONEY          NULL,
    [Mes10] MONEY          NULL,
    [Mes11] MONEY          NULL,
    [Mes12] MONEY          NULL
);

