CREATE TABLE [dbo].[J_50CROM] (
    [ID del contratista asignado por el SIPAC (RF_00)]                 NVARCHAR (255) NULL,
    [ID registro fiduciario del contrato (RI_00)]                      NVARCHAR (255) NULL,
    [ID del contrato asignado por CNH (RF01_01)]                       NVARCHAR (255) NULL,
    [Mes de reporte (RM50_00)]                                         FLOAT (53)     NULL,
    [Año de reporte (RM50_01)]                                         FLOAT (53)     NULL,
    [Producción: Volumen contractual de petróleo (RM50_02)]            FLOAT (53)     NULL,
    [Volumen contractual: producción de metano de gas natural asociad] FLOAT (53)     NULL,
    [Producción: Volumen contractual de etano de gas natural asociado] FLOAT (53)     NULL,
    [Producción: Volumen contractual de propano de gas natural asocia] FLOAT (53)     NULL,
    [Producción: Volumen contractual de butano de gas natural asociad] FLOAT (53)     NULL,
    [Producción: Volumen contractual de metano de gas natural no asoc] FLOAT (53)     NULL,
    [Producción: Volumen contractual de etano de gas natural no asoci] FLOAT (53)     NULL,
    [Producción: Volumen contractual de propano de gas natural no aso] FLOAT (53)     NULL,
    [Producción: Volumen contractual de butano de gas natural no asoc] FLOAT (53)     NULL,
    [Producción: Volumen contractual de condensados (RM50_11)]         FLOAT (53)     NULL,
    [Precio contractual: petróleo (RM50_12)]                           NVARCHAR (255) NULL,
    [Precio contractual: metano (RM50_13)]                             FLOAT (53)     NULL,
    [Precio contractual: etano (RM50_14)]                              FLOAT (53)     NULL,
    [Precio contractual: propano (RM50_15)]                            FLOAT (53)     NULL,
    [Precio contractual: butano (RM50_16)]                             FLOAT (53)     NULL,
    [Precio contractual: condensados (RM50_17)]                        FLOAT (53)     NULL,
    [Tipo de precio que aplicó en la determinación del precio contrac] NVARCHAR (255) NULL,
    [Tipo de precio que aplicó en la determinación del precio contra1] FLOAT (53)     NULL,
    [Tipo de precio que aplicó en la determinación del precio contra2] FLOAT (53)     NULL,
    [Tipo de precio que aplicó en la determinación del precio contra3] FLOAT (53)     NULL,
    [Tipo de precio que aplicó en la determinación del precio contra4] FLOAT (53)     NULL,
    [Tipo de precio que aplicó en la determinación del precio contra5] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?: ] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:1] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:2] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:3] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:4] FLOAT (53)     NULL,
    [¿Se aplicó ajuste por utilizar fórmula en periodos anteriores?:5] FLOAT (53)     NULL,
    [Valor contractual: petróleo (RM50_30)]                            NVARCHAR (255) NULL,
    [Valor contractual: metano de gas natural asociado (RM50_31)]      NVARCHAR (255) NULL,
    [Valor contractual: etano de gas natural asociado (RM50_32)]       NVARCHAR (255) NULL,
    [Valor contractual: propano de gas natural asociado (RM50_33)]     NVARCHAR (255) NULL,
    [Valor contractual: butano de gas natural asociado (RM50_34)]      NVARCHAR (255) NULL,
    [Valor contractual: metano de gas natural no asociado (RM50_35)]   FLOAT (53)     NULL,
    [Valor contractual: etano de gas natural no asociado (RM50_36)]    FLOAT (53)     NULL,
    [Valor contractual: propano de gas natural no asociado (RM50_37)]  FLOAT (53)     NULL,
    [Valor contractual: butano de gas natural no asociado (RM50_38)]   FLOAT (53)     NULL,
    [Valor contractual: condensados (RM50_39)]                         FLOAT (53)     NULL,
    [Total del valor contractual de los hidrocarburos (RM50_40)]       FLOAT (53)     NULL,
    [Tasa aplicable para el pago de la Regalía Base: petróleo (RM50_4] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas na] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas nat] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas n] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas na] NVARCHAR (255) NULL,
    [Tasa aplicable para el pago de la Regalía Base: metano de gas n1] FLOAT (53)     NULL,
    [Tasa aplicable para el pago de la Regalía Base: etano de gas na1] FLOAT (53)     NULL,
    [Tasa aplicable para el pago de la Regalía Base: propano de gas 1] FLOAT (53)     NULL,
    [Tasa aplicable para el pago de la Regalía Base: butano de gas n1] FLOAT (53)     NULL,
    [Tasa aplicable para el pago de la Regalía Base: condensados (RM5] FLOAT (53)     NULL,
    [¿Se aplicó el mecanismo de ajuste? (RM50_51)]                     FLOAT (53)     NULL,
    [Factor de ajuste para la determinación del monto de la contrapre] NVARCHAR (255) NULL,
    [Factor de ajuste para la determinación del monto de la contrapr1] NVARCHAR (255) NULL,
    [Tasa aplicable al valor contractual del petróleo y condensados e] FLOAT (53)     NULL,
    [Tasa aplicable al valor contractual del gas natural en el period] FLOAT (53)     NULL,
    [Estado (activo)]                                                  NVARCHAR (255) NULL,
    [Fecha registro (fechaRegistro)]                                   NVARCHAR (255) NULL
);

