CREATE TABLE [dbo].[JaguarCorreccion] (
    [NumeroContrato]           NVARCHAR (255) NULL,
    [NombreAreaContractual]    NVARCHAR (255) NULL,
    [IdRegistro]               FLOAT (53)     NULL,
    [Servicio]                 NVARCHAR (255) NULL,
    [Tarea]                    NVARCHAR (255) NULL,
    [InstalacionPresupuestada] NVARCHAR (255) NULL,
    [FechaInicio]              DATETIME       NULL,
    [FechaFin]                 DATETIME       NULL,
    [TipoDocumento]            NVARCHAR (255) NULL,
    [Numero]                   NVARCHAR (255) NULL,
    [FechaDocumento]           DATETIME       NULL,
    [MontoUSD]                 FLOAT (53)     NULL,
    [Subcontratista]           NVARCHAR (255) NULL,
    [InstalacionRegistro]      NVARCHAR (255) NULL,
    [InicioEjecucion]          DATETIME       NULL,
    [FinEjecucion]             DATETIME       NULL,
    [CreadoPor]                NVARCHAR (255) NULL,
    [MontoRegistro]            FLOAT (53)     NULL,
    [Moneda]                   NVARCHAR (255) NULL,
    [MesPresentacion]          DATETIME       NULL,
    [TipoDeServicio]           NVARCHAR (255) NULL,
    [Actividad]                NVARCHAR (255) NULL,
    [SubActividad]             NVARCHAR (255) NULL,
    [EstadoValidacion]         NVARCHAR (255) NULL,
    [Area]                     NVARCHAR (255) NULL,
    [Comentarios]              NVARCHAR (255) NULL,
    [Identificador]            FLOAT (53)     NULL,
    [LineaPresupuesto]         FLOAT (53)     NULL,
    [Presupuesto]              NVARCHAR (255) NULL,
    [Mes]                      NVARCHAR (255) NULL,
    [Año]                      FLOAT (53)     NULL,
    [FechaTransferencia]       DATETIME       NULL,
    [MontoTransferencia]       FLOAT (53)     NULL,
    [Para CNH]                 NVARCHAR (255) NULL
);

