CREATE TABLE [dbo].[ListaDocsTemporal] (
    [ID]                     INT            NULL,
    [IDPadre]                INT            NULL,
    [Titulo]                 NVARCHAR (MAX) NULL,
    [EtapaId]                NVARCHAR (MAX) NULL,
    [ReceptorEntregableId]   INT            NULL,
    [PozoInstalacionId]      INT            NULL,
    [MarcoLegalId]           INT            NULL,
    [EtapaPozoId]            INT            NULL,
    [EntregableId]           INT            NULL,
    [FrecuenciaId]           NVARCHAR (MAX) NULL,
    [Frecuencia]             NVARCHAR (MAX) NULL,
    [FechaEntregaAnioMes]    NVARCHAR (MAX) NULL,
    [FechaProgramadaEntrega] DATETIME       NULL,
    [DocumentoEntregableId]  INT            NULL,
    [CantidadArchivos]       INT            NULL,
    [Detalle]                NVARCHAR (MAX) NULL,
    [Icono]                  NVARCHAR (MAX) NULL,
    [Acciones]               NVARCHAR (MAX) NULL,
    [Mime]                   NVARCHAR (MAX) NULL,
    [Nivel]                  INT            NULL,
    [TipoArchivo]            NVARCHAR (MAX) NULL,
    [FechaCarga]             DATETIME       NULL,
    [CargadoPor]             NVARCHAR (MAX) NULL,
    [Origen]                 NVARCHAR (MAX) NULL,
    [FechaInicioEtapa]       DATETIME       NULL,
    [FechaFinEtapa]          DATETIME       NULL,
    [IdContrato]             INT            NULL
);

