CREATE TABLE [dbo].[MM_CatalogoSAP] (
    [Id]              INT            IDENTITY (10000, 1) NOT NULL,
    [COD GRUPO]       NVARCHAR (255) NULL,
    [GRUPO]           NVARCHAR (255) NULL,
    [F3]              FLOAT (53)     NULL,
    [COD FAM]         NVARCHAR (255) NULL,
    [FAMILIA]         NVARCHAR (255) NULL,
    [F6]              NVARCHAR (255) NULL,
    [COD# SUBFAMILIA] NVARCHAR (255) NULL,
    [SUBFAMILIA]      NVARCHAR (255) NULL,
    [UNIDAD RECOMEN#] NVARCHAR (255) NULL,
    [TIPOMATERIAL]    NVARCHAR (255) NULL,
    [F11]             NVARCHAR (255) NULL,
    CONSTRAINT [PK_MM_CatalogoSAP] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

