CREATE TABLE [dbo].[MM_EstadoMaterial] (
    [IdEstadoMaterial] INT IDENTITY (10000, 1) NOT NULL,
    CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED ([IdEstadoMaterial] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

