CREATE TABLE [dbo].[MM_Material] (
    [IdMaterial]                INT            IDENTITY (10000, 1) NOT NULL,
    [IdAuxiliar]                NVARCHAR (MAX) NULL,
    [IdEstadoMaterial]          INT            NULL,
    [IdTipo]                    INT            NULL,
    [DescripcionCorta]          NVARCHAR (MAX) NULL,
    [DescripcionLarga]          NVARCHAR (MAX) NOT NULL,
    [IdMarca]                   INT            NULL,
    [Modelo]                    NVARCHAR (MAX) NULL,
    [NumeroParte]               NVARCHAR (MAX) NULL,
    [IdUnidad]                  INT            NULL,
    [IdUnidadAlterna]           INT            NULL,
    [Presentacion]              NVARCHAR (MAX) NULL,
    [Consumible]                BIT            NULL,
    [Inventariable]             BIT            NULL,
    [Activo]                    BIT            NULL,
    [TiempoEntregaEstimadoDias] INT            NULL,
    [Costo]                     MONEY          NULL,
    [IdMoneda]                  INT            NULL,
    [IdTipoMaterial]            INT            NULL,
    [IdGrupoDisciplina]         INT            NULL,
    [IdFamilia]                 INT            NULL,
    [IdSubFamilia]              INT            NULL,
    [Ubicacion]                 NVARCHAR (MAX) NULL,
    [CreadoPor]                 INT            NULL,
    [Marca]                     NVARCHAR (MAX) NULL,
    [FechaAlta]                 DATETIME       NULL,
    [FechaAutorizacion]         DATETIME       NULL,
    [IsPublico]                 BIT            NULL,
    [IdAdminValidador]          INT            NULL,
    [Imagen]                    NVARCHAR (MAX) NULL,
    [FichaTecnica]              NVARCHAR (MAX) NULL,
    [FechaActualizacion]        DATETIME       NULL,
    CONSTRAINT [PK_MM_Material] PRIMARY KEY CLUSTERED ([IdMaterial] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MM_Material_MM_EstadoMaterial] FOREIGN KEY ([IdEstadoMaterial]) REFERENCES [dbo].[MM_EstadoMaterial] ([IdEstadoMaterial]),
    CONSTRAINT [FK_MM_Material_MM_MarcaMaterial] FOREIGN KEY ([IdMarca]) REFERENCES [dbo].[MM_MaterialMarca] ([IdMarca]),
    CONSTRAINT [FK_MM_Material_MM_MaterialFamilia] FOREIGN KEY ([IdFamilia]) REFERENCES [dbo].[MM_MaterialFamilia] ([IdMaterialFamilia]),
    CONSTRAINT [FK_MM_Material_MM_MaterialGrupo] FOREIGN KEY ([IdGrupoDisciplina]) REFERENCES [dbo].[MM_MaterialGrupoDisciplina] ([IdGrupoDisciplina]),
    CONSTRAINT [FK_MM_Material_MM_MaterialSubFamilia] FOREIGN KEY ([IdSubFamilia]) REFERENCES [dbo].[MM_MaterialSubFamilia] ([IdSubFamilia]),
    CONSTRAINT [FK_MM_Material_MM_MaterialTipo] FOREIGN KEY ([IdTipoMaterial]) REFERENCES [dbo].[MM_MaterialTipo] ([IdTipoMaterial]),
    CONSTRAINT [FK_MM_Material_MM_Unidad] FOREIGN KEY ([IdUnidad]) REFERENCES [dbo].[MM_Unidad] ([IdUnidad]),
    CONSTRAINT [FK_MM_Material_PV_TipoMoneda] FOREIGN KEY ([IdMoneda]) REFERENCES [dbo].[PV_TipoMoneda] ([IdMoneda])
);

