CREATE TABLE [dbo].[MM_MovimientoAlmacen] (
    [IdMovimiento]           INT            IDENTITY (1, 1) NOT NULL,
    [Folio]                  INT            NULL,
    [Cantidad]               FLOAT (53)     NULL,
    [Descripcion]            NVARCHAR (MAX) NULL,
    [Posicion]               INT            NULL,
    [Fecha]                  DATETIME       NULL,
    [IdDetallePedido]        INT            NULL,
    [Comentarios]            NVARCHAR (MAX) NULL,
    [recibido_en]            NVARCHAR (250) NULL,
    [fecha_recibido]         DATE           NULL,
    [hra_recibido]           DATETIME       NULL,
    [recibido_por_nombre]    NVARCHAR (250) NULL,
    [almacen_nombre]         NVARCHAR (250) NULL,
    [transportista_nombre]   NVARCHAR (250) NULL,
    [transportista_fecha]    DATE           NULL,
    [transportista_hra]      DATETIME       NULL,
    [vigilancia_nombre]      NVARCHAR (250) NULL,
    [vigilancia_fecha]       DATE           NULL,
    [vigilancia_hra]         DATETIME       NULL,
    [usuario_nombre]         NVARCHAR (250) NULL,
    [usuario_fecha]          DATE           NULL,
    [usuario_hra]            DATETIME       NULL,
    [recibido_fecha]         DATE           NULL,
    [firmaautorizada]        NVARCHAR (250) NULL,
    [firmaautorizadafecha]   DATE           NULL,
    [firmaautorizadahra]     DATETIME       NULL,
    [entregado_en]           NVARCHAR (250) NULL,
    [utilizado_en]           NVARCHAR (250) NULL,
    [entregado_a_nombre]     NVARCHAR (250) NULL,
    [entregado_a_apellido]   NVARCHAR (250) NULL,
    [entregado_a_empresa]    NVARCHAR (250) NULL,
    [almacen_fecha]          DATE           NULL,
    [almacen_hra]            DATETIME       NULL,
    [recibido_nombre]        NVARCHAR (250) NULL,
    [tipomovimiento]         INT            NULL,
    [id_producto]            NVARCHAR (250) NULL,
    [id_almacen]             INT            NULL,
    [utilizado_en_area]      NVARCHAR (MAX) NULL,
    [utilizado_en_loc]       NVARCHAR (MAX) NULL,
    [utilizado_en_eq]        NVARCHAR (MAX) NULL,
    [usuario]                NVARCHAR (MAX) NULL,
    [fechaoperacion]         DATETIME       NULL,
    [no_folio_]              NVARCHAR (MAX) NULL,
    [clave_almacen]          NVARCHAR (MAX) NULL,
    [comentario]             NVARCHAR (MAX) NULL,
    [segunda_cant]           FLOAT (53)     NULL,
    [nombre_recepcionsta]    NVARCHAR (MAX) NULL,
    [folio_salida_reingreso] NVARCHAR (MAX) NULL,
    [pendiente_reingreso]    FLOAT (53)     NULL,
    [orden_trabajo]          NVARCHAR (MAX) NULL,
    [localizacion_ot]        NVARCHAR (MAX) NULL,
    [recibido_final_nombre]  NVARCHAR (MAX) NULL,
    [recibido_final_fecha]   DATE           NULL,
    [recibido_final_hra]     DATETIME       NULL,
    [tipo_material_alma]     NVARCHAR (MAX) NULL,
    [id_precio]              INT            NULL,
    [OTM]                    NVARCHAR (50)  NULL,
    [CreadoPor]              INT            NULL,
    CONSTRAINT [PK_admin_movimientos_almacn_1] PRIMARY KEY CLUSTERED ([IdMovimiento] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

