CREATE TABLE [dbo].[MM_PeticionOferta] (
    [IdPeticionOferta]     INT      IDENTITY (1, 1) NOT NULL,
    [IdLicitacion]         INT      NULL,
    [IdSolicitudPedido]    INT      NULL,
    [IdEmpresaSolicitante] INT      NULL,
    [IdSubcontratista]     INT      NULL,
    [Fecha]                DATETIME NULL,
    [CreadoPor]            INT      NULL,
    [CreadoEl]             DATETIME NULL,
    [ModificadoPor]        INT      NULL,
    [ModificadoEl]         DATETIME NULL,
    [Activo]               BIT      NULL,
    [Visto]                BIT      NULL,
    [Iniciada]             BIT      NULL,
    [Finalizado]           BIT      NULL,
    [FechaFinalizado]      DATETIME NULL,
    [Cotizado]             BIT      NULL,
    [IdEstatus]            INT      NULL,
    CONSTRAINT [PK_MM_PeticionOferta] PRIMARY KEY CLUSTERED ([IdPeticionOferta] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MM_PeticionOferta_MM_Licitacion] FOREIGN KEY ([IdPeticionOferta]) REFERENCES [dbo].[MM_Licitacion] ([IdLicitacion]),
    CONSTRAINT [FK_MM_PeticionOferta_MM_SolicitudPedido] FOREIGN KEY ([IdSolicitudPedido]) REFERENCES [dbo].[MM_SolicitudPedido] ([IdSolicitudPedido]),
    CONSTRAINT [FK_MM_PeticionOferta_PV_Subcontratista] FOREIGN KEY ([IdSubcontratista]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista]),
    CONSTRAINT [FK_MM_PeticionOferta_PV_Subcontratista1] FOREIGN KEY ([IdEmpresaSolicitante]) REFERENCES [dbo].[PV_Subcontratista] ([IdSubcontratista])
);

