CREATE TABLE [dbo].[MM_Pedido] (
    [IdPedido]           INT            IDENTITY (1000, 1) NOT NULL,
    [IdSolicitudPedido]  INT            NULL,
    [IdContrato]         INT            NULL,
    [IdSubcontratista]   INT            NULL,
    [Fecha]              DATETIME       NULL,
    [FechaEntrega]       DATETIME       NULL,
    [Comentarios]        NVARCHAR (MAX) NULL,
    [Editado]            BIT            NULL,
    [Version]            INT            NULL,
    [Activado]           NVARCHAR (50)  NULL,
    [Aprobado]           BIT            NULL,
    [Clave]              NVARCHAR (MAX) NULL,
    [ConfirmacionClave]  NVARCHAR (MAX) NULL,
    [IdMoneda]           INT            NULL,
    [Enviado]            BIT            NULL,
    [CondicionesPago]    INT            NULL,
    [Anticipo]           FLOAT (53)     NULL,
    [Impuesto]           FLOAT (53)     NULL,
    [Envio]              FLOAT (53)     NULL,
    [Importacion]        FLOAT (53)     NULL,
    [IVA]                FLOAT (53)     NULL,
    [CreadoPor]          INT            NULL,
    [CreadoEl]           DATETIME       NULL,
    [ModificadoPor]      INT            NULL,
    [ModificadoEl]       DATETIME       NULL,
    [Activo]             BIT            NULL,
    [TotalPedido]        FLOAT (53)     NULL,
    [SubTotal]           FLOAT (53)     NULL,
    [LugarEntrega]       NVARCHAR (MAX) NULL,
    [Descuento]          BIT            NULL,
    [ValorRetencion]     FLOAT (53)     NULL,
    [CantidadDescuento]  FLOAT (53)     NULL,
    [PedidoAutomatico]   BIT            NULL,
    [IdDomicilioEntrega] INT            NULL,
    CONSTRAINT [PK_MM_Pedido] PRIMARY KEY CLUSTERED ([IdPedido] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

