CREATE TABLE [dbo].[MM_PeticionOfertaDetalle] (
    [IdPeticionOfertaDetalle]  INT            IDENTITY (10000, 1) NOT NULL,
    [IdPeticionOferta]         INT            NULL,
    [IdMaterial]               INT            NULL,
    [ComentariosComprador]     NVARCHAR (MAX) NULL,
    [PrecioUnitario]           FLOAT (53)     NULL,
    [IdMoneda]                 INT            NULL,
    [Disponibilidad]           FLOAT (53)     NULL,
    [Dias]                     FLOAT (53)     NULL,
    [ComentarioSubcontratista] NVARCHAR (MAX) NULL,
    [Fecha]                    DATETIME       NULL,
    [Cotizado]                 BIT            NULL,
    [Editable]                 BIT            NULL,
    [CreadoPor]                INT            NULL,
    [CreadoEl]                 DATETIME       NULL,
    [ModificadoPor]            INT            NULL,
    [ModificadoEl]             DATETIME       NULL,
    [Activo]                   BIT            NULL,
    [NoMaterialesRequeridos]   INT            NULL,
    [IdEstatus]                INT            NULL,
    [IdProveedorVenta]         INT            NULL,
    [IVA_Porcentaje]           FLOAT (53)     NULL,
    [SubTotal]                 INT            NULL,
    [IVA_Activo]               BIT            NULL,
    [AddPedidoTemp]            BIT            NULL,
    [AddCantidadTemp]          INT            NULL,
    [AddSubTotalTemp]          FLOAT (53)     NULL,
    [AddValidado]              BIT            NULL,
    [PrecioMasIVA]             FLOAT (53)     NULL,
    [CantidadIVa]              FLOAT (53)     NULL,
    CONSTRAINT [PK_MM_PeticionOfertaDetalle] PRIMARY KEY CLUSTERED ([IdPeticionOfertaDetalle] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

