CREATE TABLE [dbo].[MM_SolicitudPedidoDetalle] (
    [IdSolicitudPedidoDetalle]         INT            IDENTITY (1, 1) NOT NULL,
    [IdSolicitudPedido]                INT            NULL,
    [Fecha]                            DATETIME       NULL,
    [IdMaterial]                       INT            NULL,
    [Cantidad]                         FLOAT (53)     NULL,
    [MatrizEvaluacionTecnicaRequerida] BIT            NULL,
    [SeguroRequerido]                  BIT            NULL,
    [capitulo]                         NCHAR (10)     NULL,
    [puesto]                           NCHAR (50)     NULL,
    [area]                             NCHAR (50)     NULL,
    [depto]                            NCHAR (45)     NULL,
    [prioridad]                        NCHAR (20)     NULL,
    [proveedor]                        NCHAR (50)     NULL,
    [observaciones]                    NCHAR (270)    NULL,
    [numero]                           NVARCHAR (50)  NULL,
    [unidad]                           NVARCHAR (50)  NULL,
    [descripcion]                      NVARCHAR (480) NULL,
    [valor_aprox]                      FLOAT (53)     NULL,
    [cert_calidad]                     NCHAR (10)     NULL,
    [cargo_a]                          NCHAR (20)     NULL,
    [cargo_en]                         NCHAR (40)     NULL,
    [aprobacion]                       NCHAR (10)     NULL,
    [desc_gral]                        NCHAR (260)    NULL,
    [fecha_aprob]                      DATETIME       NULL,
    [fechacomp]                        DATETIME       NULL,
    [desaprobado]                      NCHAR (10)     NULL,
    [impreso]                          NCHAR (10)     NULL,
    [fechaimpreso]                     DATETIME       NULL,
    [concepto]                         NCHAR (90)     NULL,
    [partida]                          NCHAR (90)     NULL,
    [max_cantidad]                     NUMERIC (18)   NULL,
    [orden_trbjo]                      NCHAR (50)     NULL,
    [mon_nacnl]                        FLOAT (53)     NULL,
    [mon_extranjera]                   FLOAT (53)     NULL,
    [localizacion]                     NCHAR (80)     NULL,
    [impreso_por]                      NVARCHAR (50)  NULL,
    [editado]                          NCHAR (10)     NULL,
    [no_edicion]                       NCHAR (10)     NULL,
    [id_producto]                      NVARCHAR (50)  NULL,
    [fecha_req_user]                   DATETIME       NULL,
    [cargo_mult]                       NVARCHAR (50)  NULL,
    [equipo_perf]                      NVARCHAR (50)  NULL,
    [cap_info]                         NVARCHAR (MAX) NULL,
    [id_]                              INT            NOT NULL,
    [CreadoPor]                        INT            NULL,
    CONSTRAINT [PK_MM_SolicitudPedidoDetalle] PRIMARY KEY CLUSTERED ([IdSolicitudPedidoDetalle] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MM_SolicitudPedidoDetalle_MM_Material] FOREIGN KEY ([IdMaterial]) REFERENCES [dbo].[MM_Material] ([IdMaterial]),
    CONSTRAINT [FK_MM_SolicitudPedidoDetalle_MM_SolicitudPedido] FOREIGN KEY ([IdSolicitudPedido]) REFERENCES [dbo].[MM_SolicitudPedido] ([IdSolicitudPedido])
);

