CREATE TABLE [dbo].[MM_SolicitudCotizacion] (
    [no_idsolicitud]  NUMERIC (18)    NULL,
    [material_name]   NVARCHAR (480)  NULL,
    [caracteristicas] NVARCHAR (280)  NULL,
    [proveedor]       NCHAR (80)      NULL,
    [emailproveedor]  NCHAR (80)      NULL,
    [no_req]          NCHAR (20)      NULL,
    [empleado]        NCHAR (80)      NULL,
    [capitulo]        NCHAR (10)      NULL,
    [area]            NCHAR (30)      NULL,
    [fecha]           DATETIME        NULL,
    [enviado]         NCHAR (10)      NULL,
    [unidad]          NCHAR (80)      NULL,
    [cantidad]        NCHAR (50)      NULL,
    [numero]          NCHAR (10)      NOT NULL,
    [id_solfin]       NCHAR (120)     NULL,
    [id_encryptado]   NCHAR (120)     NOT NULL,
    [num_sol]         NCHAR (80)      NULL,
    [precio_unit]     NUMERIC (18, 2) NULL,
    [comentarios]     NVARCHAR (MAX)  NULL,
    [fecha_cot]       DATETIME2 (7)   NULL,
    [cotizado]        NCHAR (10)      NULL,
    [precio_total]    NUMERIC (18, 2) NULL,
    [fecha_entrega]   DATETIME        NULL,
    [cant_exist]      NUMERIC (18)    NULL,
    [moneda]          NVARCHAR (50)   NULL,
    [pago_term]       NVARCHAR (50)   NULL,
    [lugar_entrega]   NVARCHAR (50)   NULL,
    [comprador]       NVARCHAR (50)   NULL,
    [edicion]         NVARCHAR (50)   NULL,
    [edit_req_prsn]   NVARCHAR (130)  NULL,
    [req_edit_fecha]  DATETIME        NULL,
    [precio_ant]      NUMERIC (18, 2) NULL,
    [activado]        NVARCHAR (50)   NULL,
    [activado_por]    NVARCHAR (50)   NULL,
    [fecha_activado]  DATETIME        NULL,
    [id_registro]     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [id_proveedor]    NVARCHAR (255)  NULL,
    [id_producto]     NVARCHAR (150)  NULL,
    [fin_cot]         INT             NULL,
    [fecha_fin_cot]   DATETIME        NULL,
    [descuento]       FLOAT (53)      NULL,
    [CreadoPor]       INT             NULL,
    CONSTRAINT [PK_admin_sol_cotizacion] PRIMARY KEY CLUSTERED ([numero] ASC, [id_encryptado] ASC, [id_registro] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

