CREATE TABLE [dbo].[MM_SolicitudPedido] (
    [IdSolicitudPedido]          INT            IDENTITY (10000, 1) NOT NULL,
    [IdContrato]                 INT            NULL,
    [IdTipoSolicitudPedido]      INT            NULL,
    [IdUsuarioSolicitante]       INT            NULL,
    [AdjudicableParcialmente]    BIT            NULL,
    [IdPrioridadSolicitudPedido] INT            NULL,
    [MotivoUrgencia]             NVARCHAR (MAX) NULL,
    [IdEstado]                   INT            NULL,
    [VisitaRequerida]            BIT            NULL,
    [JuntaAclaracionesRequerida] BIT            NULL,
    [IdProcedimientoProcura]     INT            NULL,
    [IdTipoContrato]             INT            NULL,
    [UnaSolaEntregaRequerida]    BIT            NULL,
    [Activo]                     BIT            NULL,
    [FechaEntregaRequerida]      DATE           NULL,
    [FechaEntregaFinRequerida]   DATETIME       NULL,
    [IdProveedor]                INT            NULL,
    [FechaAlta]                  DATETIME       NULL,
    [EntregasParciales]          BIT            NULL,
    [PeticionEnviada]            BIT            NULL,
    CONSTRAINT [PK_MM_SolicitudPedido] PRIMARY KEY CLUSTERED ([IdSolicitudPedido] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MM_SolicitudPedido_AP_Usuario] FOREIGN KEY ([IdUsuarioSolicitante]) REFERENCES [dbo].[AP_Usuario] ([UsuarioID]),
    CONSTRAINT [FK_MM_SolicitudPedido_MM_PrioridadSolicitudPedido] FOREIGN KEY ([IdPrioridadSolicitudPedido]) REFERENCES [dbo].[MM_PrioridadSolicitudPedido] ([IdPrioridadSolicitudPedido]),
    CONSTRAINT [FK_MM_SolicitudPedido_MM_ProcedimientoProcura] FOREIGN KEY ([IdProcedimientoProcura]) REFERENCES [dbo].[MM_ProcedimientoProcura] ([IdProcedimientoProcura]),
    CONSTRAINT [FK_MM_SolicitudPedido_MM_TipoContrato] FOREIGN KEY ([IdTipoContrato]) REFERENCES [dbo].[MM_TipoContrato] ([IdTipoContrato]),
    CONSTRAINT [FK_MM_SolicitudPedido_MM_TipoSolicitudPedido] FOREIGN KEY ([IdTipoSolicitudPedido]) REFERENCES [dbo].[MM_TipoSolicitudPedido] ([IdTipoSolicitudPedido])
);

