CREATE TABLE [dbo].[MPY062019] (
    [ID]                    FLOAT (53)     NULL,
    [Date]                  DATETIME       NULL,
    [Clearing Document]     NVARCHAR (255) NULL,
    [Account Number]        NVARCHAR (255) NULL,
    [Bank ID]               NVARCHAR (255) NULL,
    [Transaction]           NVARCHAR (255) NULL,
    [Currency]              NVARCHAR (255) NULL,
    [Amount]                MONEY          NULL,
    [ExRate]                MONEY          NULL,
    [Credit/Debit]          NVARCHAR (255) NULL,
    [Customer Reference]    NVARCHAR (255) NULL,
    [Bank Reference]        NVARCHAR (255) NULL,
    [Vendor]                NVARCHAR (255) NULL,
    [TaxID]                 NVARCHAR (255) NULL,
    [Vendor Bank]           NVARCHAR (255) NULL,
    [Vendor Account Number] NVARCHAR (255) NULL,
    [Invoice (s)]           FLOAT (53)     NULL,
    [Folio Fiscal]          VARCHAR (MAX)  NULL,
    [Journal Entry]         NVARCHAR (255) NULL,
    [Payment Entry]         NVARCHAR (255) NULL,
    [AC]                    NVARCHAR (255) NULL,
    [SA]                    NVARCHAR (255) NULL,
    [TA]                    NVARCHAR (255) NULL,
    [GL Account]            FLOAT (53)     NULL,
    [Hidrocarburos]         NVARCHAR (255) NULL,
    [Balance/Value Date]    NVARCHAR (255) NULL,
    [Text]                  NVARCHAR (MAX) NULL,
    [IdTransfer]            FLOAT (53)     NULL
);

