CREATE TABLE [dbo].[MurphyAbril2019] (
    [Id]                    FLOAT (53)     NULL,
    [Date]                  FLOAT (53)     NULL,
    [Account_Number]        NVARCHAR (255) NULL,
    [Bank_ID]               NVARCHAR (255) NULL,
    [Transaction]           NVARCHAR (255) NULL,
    [Currency]              NVARCHAR (255) NULL,
    [Amount]                FLOAT (53)     NULL,
    [ExRate]                FLOAT (53)     NULL,
    [Credit_Debit]          NVARCHAR (255) NULL,
    [Customer_Reference]    NVARCHAR (255) NULL,
    [Bank_Reference]        NVARCHAR (255) NULL,
    [Vendor]                NVARCHAR (255) NULL,
    [TaxID]                 NVARCHAR (255) NULL,
    [Vendor_Bank]           NVARCHAR (255) NULL,
    [Vendor_Account_Number] NVARCHAR (255) NULL,
    [Invoices]              NVARCHAR (255) NULL,
    [FOLIOFISCAL]           VARCHAR (8000) NULL,
    [Journal_Entry]         FLOAT (53)     NULL,
    [Payment_Entry]         FLOAT (53)     NULL,
    [AC]                    NVARCHAR (255) NULL,
    [SA]                    NVARCHAR (255) NULL,
    [TA]                    NVARCHAR (255) NULL,
    [GL_Account]            FLOAT (53)     NULL,
    [Hidrocarburos]         NVARCHAR (255) NULL,
    [Balance_Value_Date]    NVARCHAR (255) NULL,
    [Fecha]                 DATE           NULL,
    [idtransferencia]       INT            NULL
);

