CREATE TABLE [dbo].[OT_BI_Tablero] (
    [NumeroContrato]                   VARCHAR (100)  NOT NULL,
    [IdOTSolicitud]                    INT            NOT NULL,
    [IdSolicitudPedido]                INT            NULL,
    [Folio]                            VARCHAR (30)   NOT NULL,
    [Objeto]                           VARCHAR (1000) NULL,
    [CentroCosto]                      VARCHAR (200)  NULL,
    [RazonSocialProv]                  VARCHAR (2000) NOT NULL,
    [Tarea]                            VARCHAR (350)  NULL,
    [SubTarea]                         VARCHAR (350)  NULL,
    [Estatus]                          VARCHAR (100)  NOT NULL,
    [RegistroDeOT]                     DATETIME       NOT NULL,
    [Requisitor]                       VARCHAR (650)  NOT NULL,
    [Responsable1aAprobacion]          VARCHAR (650)  NULL,
    [Fecha1aAprobacion]                DATETIME       NULL,
    [DiasEspera1aAprobacion]           FLOAT (53)     NULL,
    [Estatus1aAprobacion]              VARCHAR (350)  NULL,
    [Responsable2aAprobacion]          VARCHAR (650)  NULL,
    [Fecha2aAprobacion]                DATETIME       NULL,
    [DiasEspera2aAprobacion]           FLOAT (53)     NULL,
    [Estatus2aAprobacion]              VARCHAR (350)  NULL,
    [FechaCargaPR]                     DATETIME       NULL,
    [NumberPR]                         VARCHAR (100)  NULL,
    [DiasPR]                           FLOAT (53)     NULL,
    [ProgramaDel]                      DATETIME       NULL,
    [ProgramaAl]                       DATETIME       NULL,
    [FechaCargaAvance]                 DATETIME       NULL,
    [VolumetriaAvance]                 VARCHAR (30)   NOT NULL,
    [DiasCargaAvance]                  FLOAT (53)     NULL,
    [DiasRegistroPR_CargaAvance]       FLOAT (53)     NULL,
    [FechaVoBoOperadora]               DATETIME       NULL,
    [ResponsableVoBoOperadora]         VARCHAR (650)  NULL,
    [DiasVoBoOperadora]                FLOAT (53)     NULL,
    [FechaCierreSemana]                DATETIME       NULL,
    [Responsable_Cierre_Semana]        VARCHAR (650)  NULL,
    [DiasCierreSemana]                 FLOAT (53)     NULL,
    [DiasAvanceSemanal]                FLOAT (53)     NULL,
    [FechaDeEstimacion]                DATETIME       NULL,
    [ResponsableEstimacion]            VARCHAR (650)  NULL,
    [DiasEstimacion]                   FLOAT (53)     NULL,
    [DiasTotales]                      FLOAT (53)     NULL,
    [NumeroPO]                         VARCHAR (200)  NULL,
    [FechaRegistroPO]                  DATETIME       NULL,
    [IdPedido]                         INT            NULL,
    [UsuarioRelacionPOSAP]             VARCHAR (650)  NULL,
    [NumeroPOSAP]                      VARCHAR (50)   NULL,
    [FechaRelacionPOSAP]               DATETIME       NULL,
    [DiasRelacionPOSAP]                VARCHAR (200)  NULL,
    [NumeroAceptacionPedido]           INT            NULL,
    [FechaRecepcionCartaCN]            DATETIME       NULL,
    [DiasRecepcionCartaCartaCN]        VARCHAR (100)  NULL,
    [DiasRelacionPO_CartaCN]           VARCHAR (100)  NULL,
    [UsuarioApruebaCartaCN]            VARCHAR (100)  NULL,
    [FechaAprobacionCartaCN]           DATETIME       NULL,
    [DiasAprobacionCartaCN]            VARCHAR (100)  NULL,
    [DiasAprobacionCartaCN2]           VARCHAR (100)  NULL,
    [EstatusCartaCN]                   VARCHAR (100)  NULL,
    [FechaRecepcionFactura]            DATETIME       NULL,
    [DiasRecepcionFactura]             VARCHAR (100)  NULL,
    [FolioFactura]                     VARCHAR (100)  NULL,
    [Responsable1aAprobacion_Fac]      VARCHAR (100)  NULL,
    [Fecha1aAprobacion_Fac]            DATETIME       NULL,
    [DiasEspera1aAprobacionFac]        VARCHAR (100)  NULL,
    [Estatus1aAprobacion_Fac]          VARCHAR (100)  NULL,
    [Responsable2aAprobacion_Fac]      VARCHAR (100)  NULL,
    [Fecha2aAprobacion_Fac]            DATETIME       NULL,
    [DiasEspera2aAprobacion_Fac]       VARCHAR (100)  NULL,
    [Estatus2aAprobacion_Fac]          VARCHAR (100)  NULL,
    [DiasRelacionPO_AprobacionFactura] VARCHAR (100)  NULL,
    [AvanceFinanciero]                  FLOAT          NULL
);

