CREATE TABLE [dbo].[OT_Estatus] (
    [IdOtEstatus] TINYINT      NOT NULL,
    [Descripcion] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_OT_Estatus] PRIMARY KEY CLUSTERED ([IdOtEstatus] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

