CREATE TABLE [dbo].[PC_DistribucionIngresos_] (
    [IdDI]                                     INT            IDENTITY (1, 1) NOT NULL,
    [Mes]                                      NVARCHAR (255) NULL,
    [Sector]                                   NVARCHAR (255) NULL,
    [Material]                                 NVARCHAR (255) NULL,
    [Texto breve de material]                  NVARCHAR (255) NULL,
    [Pto#expedic#/Pto#recepción]               NVARCHAR (255) NULL,
    [Denominación]                             NVARCHAR (255) NULL,
    [Región]                                   NVARCHAR (255) NULL,
    [Descripción Región Organizacional]        NVARCHAR (255) NULL,
    [Descripción Activo]                       NVARCHAR (255) NULL,
    [Cve#Activo]                               NVARCHAR (255) NULL,
    [Des#Cmpo#]                                NVARCHAR (255) NULL,
    [Cve#Cmpo#]                                NVARCHAR (255) NULL,
    [Participación Volumétrica]                FLOAT (53)     NULL,
    [Factor de Distribución Volumétrica]       FLOAT (53)     NULL,
    [Distribución Volumétrica]                 FLOAT (53)     NULL,
    [Un#medida venta]                          NVARCHAR (255) NULL,
    [GVP máximo por Campo]                     FLOAT (53)     NULL,
    [GPV máximo por Material]                  FLOAT (53)     NULL,
    [GPV Ponderado por Campo]                  FLOAT (53)     NULL,
    [Precio de Equilibrio]                     FLOAT (53)     NULL,
    [Precio de Referencia]                     FLOAT (53)     NULL,
    [Factor de Distribución de Ingresos]       FLOAT (53)     NULL,
    [Distribución de Ingresos]                 FLOAT (53)     NULL,
    [Distribución de Ingresos en Moneda Local] FLOAT (53)     NULL,
    [Moneda local]                             NVARCHAR (255) NULL,
    [Distribución de Ingresos en USD]          FLOAT (53)     NULL,
    [Mon#local 2]                              NVARCHAR (255) NULL,
    [Organismo secundario]                     NVARCHAR (255) NULL,
    [Descripción Organismo secundario]         NVARCHAR (255) NULL,
    CONSTRAINT [PK_PC_DistribucionIngresos] PRIMARY KEY CLUSTERED ([IdDI] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

