CREATE TABLE [dbo].[PC_GPA2145] (
    [IdGPA] INT        IDENTITY (1, 1) NOT NULL,
    [C1]    FLOAT (53) NULL,
    [C2]    FLOAT (53) NULL,
    [C3]    FLOAT (53) NULL,
    [C4]    FLOAT (53) NULL,
    [IC4]   FLOAT (53) NULL,
    [C5Mas] FLOAT (53) NULL,
    CONSTRAINT [PK_PC_GPA2145] PRIMARY KEY CLUSTERED ([IdGPA] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

