CREATE TABLE [dbo].[PozosIHSA] (
    [Contrato]                             NVARCHAR (255) NULL,
    [Region_Fiscal]                        NVARCHAR (255) NULL,
    [Tipo_hidrocarburo]                    NVARCHAR (255) NULL,
    [Zona]                                 NVARCHAR (255) NULL,
    [bloque]                               VARCHAR (30)   NULL,
    [Campo]                                NVARCHAR (255) NULL,
    [Nombre_Pozo]                          NVARCHAR (255) NULL,
    [Anexo9_Inventario_Activos]            NVARCHAR (255) NULL,
    [IDPozo_Anexo3]                        NVARCHAR (255) NULL,
    [Tipo_Hidocarburo_RepCNH]              NVARCHAR (255) NULL,
    [Factor_Conversion_Estrangulador]      FLOAT (53)     NULL,
    [Factor_Conversion_Presion_Linea]      FLOAT (53)     NULL,
    [Factor_Conversion_Presion_Cabeza]     FLOAT (53)     NULL,
    [RGA]                                  NVARCHAR (255) NULL,
    [Punto_Medicion]                       NVARCHAR (255) NULL,
    [Ubicación_Punto_Medicion]             NVARCHAR (255) NULL,
    [Tag_Patin_Medicion ]                  NVARCHAR (255) NULL,
    [Tipo_Medidor]                         NVARCHAR (255) NULL,
    [Tag_Medidor ]                         NVARCHAR (255) NULL,
    [Clasificacion_Sistema_Medicion_LTMMH] NVARCHAR (255) NULL,
    [IdContrato]                           INT            NULL,
    [IdPuntoMedicion]                      INT            NULL,
    [IdBloque]                             INT            NULL,
    [IdCampo]                              INT            NULL,
    [IdPozo]                               INT            NULL,
    [IdInstalacion]                        INT            NULL,
    [PuntoEntregaID]                       INT            NULL
);

