CREATE TABLE [dbo].[PR_Aforo] (
    [IdAforo]            INT           IDENTITY (1, 10000) NOT NULL,
    [IdContrato]         INT           NULL,
    [IdPozo]             INT           NULL,
    [Fecha]              DATETIME      NULL,
    [PresionCabeza]      REAL          NULL,
    [Estrangulador]      REAL          NULL,
    [PresionLinea]       REAL          NULL,
    [Temperatura]        REAL          NULL,
    [ProduccionPetroleo] REAL          NULL,
    [ProduccionGas]      REAL          NULL,
    [ProduccionAgua]     REAL          NULL,
    [RGA]                REAL          NULL,
    [Observaciones]      VARCHAR (300) NULL,
    [FechaCreacion]      DATETIME      NULL,
    [CreadoPor]          INT           NULL,
    [FechaModificacion]  DATETIME      NULL,
    [PetroleoNeto]       FLOAT (53)    NULL,
    [CondensadoNeto]     FLOAT (53)    NULL,
    [GasNoAsociado]      FLOAT (53)    NULL,
    CONSTRAINT [PK__PR_Aforo__D1CB373CBC3246EC] PRIMARY KEY CLUSTERED ([IdAforo] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [fk_IdContratopozo] FOREIGN KEY ([IdContrato]) REFERENCES [dbo].[CO_Contrato] ([IdContrato]),
    CONSTRAINT [fk_IdPozoPozo] FOREIGN KEY ([IdPozo]) REFERENCES [dbo].[PR_Pozo] ([Id])
);

