CREATE TABLE [dbo].[PR_CalibracionSistemas] (
    [IdCalibracion]         INT            IDENTITY (10000, 1) NOT NULL,
    [IdContrato]            INT            NULL,
    [IdSistema]             INT            NULL,
    [Certificado]           VARCHAR (250)  NULL,
    [Fecha]                 DATETIME       NULL,
    [FechaProxima]          DATETIME       NULL,
    [IntervaloCalibracion]  VARCHAR (250)  NULL,
    [InvervaloVerificacion] VARCHAR (250)  NULL,
    [IncertidumbreMagnitud] VARCHAR (250)  NULL,
    [Laboratorio]           VARCHAR (250)  NULL,
    [EsAcreditado]          BIT            NULL,
    [PuertoDisponible]      VARCHAR (250)  NULL,
    [ConfiguracionPuerto]   VARCHAR (250)  NULL,
    [ProtocoloComunicacion] VARCHAR (250)  NULL,
    [AreaRestringida]       BIT            NULL,
    [Observaciones]         VARCHAR (2000) NULL,
    [Vigente]               BIT            NOT NULL,
    [CreadoPor]             INT            NULL,
    [CreadoEl]              DATETIME       NULL,
    [ModificadoPor]         INT            NULL,
    [ModificadoEl]          DATETIME       NULL,
    CONSTRAINT [PK_PR_CalibracionSistemas] PRIMARY KEY CLUSTERED ([IdCalibracion] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_PR_CalibracionSistemas_PR_SistemaMedicion] FOREIGN KEY ([IdSistema]) REFERENCES [dbo].[PR_SistemasMedicion] ([IdSistema])
);

