CREATE TABLE [dbo].[PR_ControlPozo] (
    [Id]               INT             IDENTITY (1, 1) NOT NULL,
    [Fecha]            DATETIME        NOT NULL,
    [Pozo]             INT             NOT NULL,
    [ProduccionBruta]  DECIMAL (24, 8) NOT NULL,
    [pctAgua]          DECIMAL (24, 8) NOT NULL,
    [ProduccionNeta]   DECIMAL (24, 8) NOT NULL,
    [Valido]           TINYINT         NOT NULL,
    [Oficial]          TINYINT         NOT NULL,
    [HoraInicio]       DATETIME        NOT NULL,
    [HoraFin]          DATETIME        NOT NULL,
    [Duracion]         INT             NULL,
    [MedidaInicio]     DECIMAL (24, 8) NOT NULL,
    [MedidaFin]        DECIMAL (24, 8) NOT NULL,
    [Tanque]           INT             NOT NULL,
    [Gas]              DECIMAL (24, 8) NULL,
    [RPM]              DECIMAL (24, 8) NULL,
    [PresionTP]        DECIMAL (24, 8) NULL,
    [PresionTR]        DECIMAL (24, 8) NULL,
    [PresionLinea]     DECIMAL (24, 8) NULL,
    [GolpeMn]          DECIMAL (24, 8) NULL,
    [Carrera]          DECIMAL (24, 8) NULL,
    [PresionInyeccion] DECIMAL (24, 8) NULL,
    [Modificado]       DATETIME        NULL,
    [ModificadoPor]    VARCHAR (200)   NULL,
    [ModificadoServer] DATETIME        NULL,
    [FechaValidacion]  DATETIME        NULL,
    [AperturaShaffer]  DECIMAL (24, 8) NULL,
    [timestamp]        ROWVERSION      NULL,
    [Estrangulador]    FLOAT (53)      NULL,
    [Temperatura]      FLOAT (53)      NULL,
    CONSTRAINT [PK_PR_ControlPozo] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_ControlPozo_Pozo] FOREIGN KEY ([Pozo]) REFERENCES [dbo].[PR_Pozo] ([Id]),
    CONSTRAINT [FK_ControlPozo_Tanque] FOREIGN KEY ([Tanque]) REFERENCES [dbo].[PR_Tanque] ([Id])
);

