CREATE TABLE [dbo].[PR_Pozo] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [Clave]                VARCHAR (20)    NULL,
    [Nombre]               VARCHAR (200)   NULL,
    [Descripcion]          NVARCHAR (2000) NULL,
    [Estatus]              INT             NULL,
    [LDD]                  TINYINT         NULL,
    [Estacion]             INT             NULL,
    [Campo]                INT             NULL,
    [ProduccionNeta]       DECIMAL (24, 8) NULL,
    [Tanque]               INT             NULL,
    [UltimoControl]        DATETIME        NULL,
    [SubEstado]            INT             NULL,
    [TipoProduccion]       INT             NULL,
    [ActividadIncremental] INT             NULL,
    [TipoSistema]          INT             NULL,
    [PozoTipo]             INT             NULL,
    [Modificado]           DATETIME        NULL,
    [ModificadoPor]        VARCHAR (200)   NULL,
    [ModificadoServer]     DATETIME        NULL,
    [Alta]                 DATETIME        NULL,
    [Comentarios]          NVARCHAR (MAX)  NULL,
    [AnioActividad]        INT             NULL,
    [UltimoControlValido]  INT             NULL,
    [ProduccionBruta]      DECIMAL (24, 8) NULL,
    [PorcentajeAgua]       DECIMAL (8, 4)  NULL,
    [X]                    FLOAT (53)      NULL,
    [Y]                    FLOAT (53)      NULL,
    [PotencialOperativo]   DECIMAL (24, 8) NULL,
    [PotencialOptimo]      DECIMAL (24, 8) NULL,
    [OFM]                  VARCHAR (20)    NULL,
    [RegionFiscal]         NVARCHAR (100)  NULL,
    [TipoFluidoPetroleo]   NVARCHAR (150)  NULL,
    [TipoFluidoGas]        NVARCHAR (150)  NULL,
    [PuntoEntregaID]       INT             NULL,
    [FechaConfirmacionDescubrimiento] DATETIME NULL, 
    CONSTRAINT [PK_PR_Pozo] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_Pozo_Campo] FOREIGN KEY ([Campo]) REFERENCES [dbo].[PR_Campo] ([Id]),
    CONSTRAINT [FK_Pozo_Estacion] FOREIGN KEY ([Estacion]) REFERENCES [dbo].[PR_Estacion] ([Id]),
    CONSTRAINT [FK_Pozo_Tanque] FOREIGN KEY ([Tanque]) REFERENCES [dbo].[PR_Tanque] ([Id])
);

