USE Petrovendor
GO
DROP PROCEDURE IF EXISTS SP_MM_ValidaCURPCartaCNProveedorProveedor
GO
CREATE PROC SP_MM_ValidaCURPCartaCNProveedorProveedor
@IdProveedor   INT,  
@IdAceptacionPedido INT
AS
BEGIN
DECLARE @IDCONTRATO INT = 0,
		@CANTIDADPREFERENCIAS INT =0,
		@MOSTRARALERTARFCPROVEEDOR BIT = 0,
		@CURPPROVEEDOR VARCHAR(100) = NULL,
		@IDTIPOREGIMENPERSONAFISICA INT = (SELECT IdTipoRegimen FROM S_TIPOREGIMEN WHERE RTRIM(LTRIM(TipoRegimen)) = 'Persona Fisica'),
		@IDTIPOREGIMENPROVEEDOR INT = (SELECT IDTIPOREGIMEN FROM S_Proveedor WHERE IdProveedor = @IdProveedor);

--SE OBTIENE EL CONTRATO
SET @IDCONTRATO = (SELECT     
	P.IdContrato
	FROM MM_AceptacionPedido AS AP  
    INNER JOIN MM_Pedido AS P 
		ON AP.IdPedido = P.IdPedido  
    INNER JOIN MM_Pedidos AS PG 
		ON P.IdPedido = PG.IdIdentificador 
		AND P.IdProveedorCompras = PG.IdProveedorCliente
		AND PG.IdTipoPedido in (2,4, 6)
    WHERE 
	P.IdSubcontratista =@IdProveedor  
	AND AP.IdAceptacionPedido = @IdAceptacionPedido)

--SE BUSCA SI EL CONTRATO DE LA ACEPTACIÓN TIENE CONFIGURADA LA OPCIÓN DE CARTA PROVEEDOR - PROVEEDOR
SET @CANTIDADPREFERENCIAS = (
SELECT count (1)
	FROM PV_ConfiguracionProveedoresOperadoras AS O(NOLOCK)
	JOIN Adinco..CO_CONTRATO AS C 
	ON O.IDCONTRATO = C.IDCONTRATO
	JOIN Adinco..CO_AreaContractual AS AC 
	ON C.IdAreaContractual = AC.IdAreaContractual
	WHERE O.TipoConfiguracion = 'CARTA_PR_PR'
	and O.Activo = 1
	AND C.Activo = 1
	AND O.IdContrato = @IDCONTRATO)

-- SI LA CANTIDAD DE PREFERENCIAS > 0 ES PORQUE LA OPERADORA TIENE CONFIGURADO LA CARTA PROVEEDOR-PROVEEDOR
-- SI LA CANTIDAD DE PREFERENCIAS = 0 ES PORQUE LA OPERADORA NO TIENE CONFIGURADO LA CARTA PROVEEDOR-PROVEEDOR / NO APLICA VALIDACIÓN DE RFC
IF @CANTIDADPREFERENCIAS = 0
	BEGIN
		SET @MOSTRARALERTARFCPROVEEDOR = 0;
	END
	ELSE
	BEGIN
		IF @IDTIPOREGIMENPERSONAFISICA = @IDTIPOREGIMENPROVEEDOR
		BEGIN
			SET @CURPPROVEEDOR = (SELECT ISNULL(CURP,'') AS RFC FROM S_Proveedor WHERE IdProveedor = @IdProveedor)	
			IF @CURPPROVEEDOR = ''
			BEGIN
				SET @MOSTRARALERTARFCPROVEEDOR = 1;
			END
			ELSE
			BEGIN
				SET @MOSTRARALERTARFCPROVEEDOR = 0;
			END
		END
	END

SELECT @MOSTRARALERTARFCPROVEEDOR AS MOSTRARALERTARFCPROVEEDOR
END
