-- =============================================
-- Author:		Daniel AC
-- Create date: 24-05-17
-- Description:	Procedimiento que indica si las peticiones agregadas al pedido estan validadas y se puede proceder a solicitar el pedido
-- =============================================
CREATE PROCEDURE [dbo].[SP_MM_ConsultarValidacionesPedido]
	-- Add the parameters for the stored procedure here

	@IdSolicitudPedido int
	 
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

	SET NOCOUNT ON;
	DECLARE @CANT_PETICIONES INT
	DECLARE @CANT_PETICIONES_VALIDADAS INT 


	 SET @CANT_PETICIONES =  (SELECT COUNT(POD.IDPETICIONOFERTADETALLE) 
	  FROM [DBO].[MM_PETICIONOFERTADETALLE]  AS POD
	  INNER JOIN MM_PETICIONOFERTA AS PO ON PO.IDPETICIONOFERTA=POD.IDPETICIONOFERTA
	  INNER JOIN MM_SOLICITUDPEDIDO AS SP ON SP.IDSOLICITUDPEDIDO = PO.IDSOLICITUDPEDIDO
	  WHERE PO.IDSOLICITUDPEDIDO = @IDSOLICITUDPEDIDO AND	ADDPEDIDOTEMP = 1)

	 SET @CANT_PETICIONES_VALIDADAS = (SELECT COUNT(POD.IDPETICIONOFERTADETALLE) 
	  FROM [DBO].[MM_PETICIONOFERTADETALLE]  AS POD
	  INNER JOIN MM_PETICIONOFERTA AS PO ON PO.IDPETICIONOFERTA=POD.IDPETICIONOFERTA
	  INNER JOIN MM_SOLICITUDPEDIDO AS SP ON SP.IDSOLICITUDPEDIDO = PO.IDSOLICITUDPEDIDO
	  WHERE PO.IDSOLICITUDPEDIDO = @IDSOLICITUDPEDIDO AND	ADDPEDIDOTEMP = 1 AND ADDVALIDADO= 1)

	  IF @CANT_PETICIONES = @CANT_PETICIONES_VALIDADAS AND @CANT_PETICIONES > 0
		BEGIN 
			SELECT 'TRUE'
		END 
	  ELSE 
	    BEGIN 
			SELECT 'FALSE'
		END 

END
