CREATE TABLE [dbo].[APP_BitacoraRestauracionProcesosDetalle]
(
	ID INT,
	ID_PADRE INT,
	PROCESO NVARCHAR(MAX),
	ESTATUS NVARCHAR(MAX),
	IDESTATUS INT,
	CLASS NVARCHAR(MAX), 
	CLAVE_PROCESO NVARCHAR(MAX),
	ACCION_EJECUTAR NVARCHAR(MAX),
	ID_PROCESO INT, 
	ID_PROCESO_PUBLICO INT,
	ID_ELIMINADO INT,
	CREADO_EL DATETIME,
	CREADO_POR INT 
)
GO
ALTER TABLE APP_BitacoraRestauracionProcesosDetalle ADD
CONSTRAINT [FK_APP_BitacoraRestauracionProcesosDetalle_AD_RegistroEliminacion_ID_ELIMINADO] FOREIGN KEY ([ID_ELIMINADO]) 
REFERENCES [dbo].[AD_RegistroEliminacion] ([IdEliminacion])
