CREATE TABLE [dbo].[APP_TransaccionesProcura] (
    [Bloque]                    VARCHAR (150) NULL,
    [IdSolicitudPedido]         INT           NULL,
    [SPDetalleRegistro]         VARCHAR (150) NULL,
    [SPCentroCosto]             VARCHAR (300) NULL,
    [SPSolicitante]             VARCHAR (100) NULL,
    [SPDetalleAprobador1]       VARCHAR (200) NULL,
    [SPDetalleAprobador2]       VARCHAR (200) NULL,
    [SPEstatus]                 VARCHAR (100) NULL,
    [SPComprador]               VARCHAR (200) NULL,
    [EnvioCotizacion]           VARCHAR (200) NULL,
    [FinalizacionCotizacion]    VARCHAR (200) NULL,
    [DetalleNoPedido]           VARCHAR (150) NULL,
    [NumPO]                     VARCHAR (100) NULL,
    [PedidoDetalleRegistro]     VARCHAR (150) NULL,
    [PedidoDetalleAprobador1]   VARCHAR (200) NULL,
    [PedidoEstatusRelacionPO]   VARCHAR (200) NULL,
    [PedidoEstatus]             VARCHAR (100) NULL,
    [PedidoEstatusConfirmacion] VARCHAR (200) NULL,
    [SASDetalleRegistro]        VARCHAR (150) NULL,
    [SASAprobadorSolitante]     VARCHAR (200) NULL,
    [SASAprobadorOBS]           VARCHAR (200) NULL,
    [AceptacionPedido]          VARCHAR (150) NULL,
    [CargaCartaCN]              VARCHAR (150) NULL,
    [AceptacionCartaCN]         VARCHAR (150) NULL,
    [EstatusCartaCN]            VARCHAR (150) NULL,
    [CargaFactura]              VARCHAR (200) NULL,
    [AceptacionFactura]         VARCHAR (200) NULL,
    [AceptacionAP]              VARCHAR (200) NULL,
    [EstatusFinal]              VARCHAR (200) NULL,
    [PeriodoEnADINCO]           INT           NULL
);

