CREATE TABLE [dbo].[AX_ComparativaLog] (
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [FechaRegistro]       DATETIME       NULL,
    [LineaPresupuesto]    NVARCHAR (500) NULL,
    [Item]                NVARCHAR (MAX) NULL,
    [Cantidad]            FLOAT (53)     NULL,
    [Unidad]              NVARCHAR (500) NULL,
    [LugarEntrega]        NVARCHAR (MAX) NULL,
    [Instalacion]         NVARCHAR (MAX) NULL,
    [FechaEntrega]        DATE           NULL,
    [TipoAdjudicacion]    INT            NULL,
    [JustificacionPedido] NVARCHAR (MAX) NULL,
    [CentroCosto]         NVARCHAR (500) NULL,
    [Aprobadores]         NVARCHAR (MAX) NULL,
    [MensajeAprobacion]   NVARCHAR (MAX) NULL,
    [IdComparativa]       NVARCHAR (MAX) NULL,
    [IdPosicion]          NVARCHAR (MAX) NULL,
    [DataAreaID]          NVARCHAR (500) NULL,
    [FechaEntregaExist]   BIT            NULL,
    [IdProveedor]         INT            NULL,
    [IdUsuario]           INT            NULL,
    [p1]                  VARCHAR (MAX)  NULL,
    [p2]                  VARCHAR (MAX)  NULL,
    [p3]                  VARCHAR (MAX)  NULL,
    [p4]                  VARCHAR (MAX)  NULL,
    [p5]                  VARCHAR (MAX)  NULL,
    [p6]                  VARCHAR (MAX)  NULL,
    [p7]                  VARCHAR (MAX)  NULL,
    [p8]                  VARCHAR (MAX)  NULL,
    [p9]                  VARCHAR (MAX)  NULL,
    [p10]                 VARCHAR (MAX)  NULL
);

