CREATE TABLE [dbo].[AX_Comparativa] (
    [IdDinamicsAx]             INT            IDENTITY (1, 1) NOT NULL,
    [LineaPresupuesto]         NVARCHAR (500) NULL,
    [Item]                     NVARCHAR (500) NULL,
    [Cantidad]                 FLOAT (53)     NULL,
    [Unidad]                   NVARCHAR (500) NULL,
    [LugarEntrega]             NVARCHAR (500) NULL,
    [Instalacion]              NVARCHAR (500) NULL,
    [FechaEntrega]             DATE           NULL,
    [TipoAdjudicacion]         INT            NULL,
    [JustificacionPedido]      NVARCHAR (MAX) NULL,
    [CentroCosto]              NVARCHAR (500) NULL,
    [Aprobadores]              NVARCHAR (MAX) NULL,
    [MensajeAprobacion]        NVARCHAR (MAX) NULL,
    [Moneda]                   INT            NULL,
    [IdComparativa]            NVARCHAR (500) NULL,
    [IdPosicion]               NVARCHAR (50)  NULL,
    [DataAreaId]               NVARCHAR (500) NULL,
    [FechaRegistro]            DATETIME       NULL,
    [IdProveedor]              INT            NULL,
    [IdUsuario]                INT            NULL,
    [EditadoPor]               INT            NULL,
    [EditadoEl]                DATETIME       NULL,
    [Activo]                   BIT            NULL,
    [IdContrato]               INT            NULL,
    [IdSolicitudPedido]        INT            NULL,
    [IdSolicitudPedidoDetalle] INT            NULL,
    [pool1]                    VARCHAR (MAX)  NULL,
    [pool2]                    VARCHAR (MAX)  NULL,
    [pool3]                    VARCHAR (MAX)  NULL,
    [pool4]                    VARCHAR (MAX)  NULL,
    [pool5]                    VARCHAR (MAX)  NULL,
    [pool6]                    NVARCHAR (MAX) NULL,
    [pool7]                    NVARCHAR (MAX) NULL,
    [pool8]                    NVARCHAR (MAX) NULL,
    [pool9]                    NVARCHAR (MAX) NULL,
    [pool10]                   NVARCHAR (MAX) NULL,
    [IdLineaPresupuesto]       INT            NULL,
    [Editado]                  BIT            NULL,
    [EnvioCorreo]              BIT            NULL,
    CONSTRAINT [PK_AX_Comparativa_gral] PRIMARY KEY CLUSTERED ([IdDinamicsAx] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

