CREATE TABLE [dbo].[BI_AvancePedido] (
    [IdPedido]                 INT            NULL,
    [IdPedidoGeneral]          INT            NULL,
    [IdSolicitudPedido]        INT            NULL,
    [Proveedor]                VARCHAR (MAX)  NULL,
    [Corporativo]              VARCHAR (MAX)  NULL,
    [Contrato]                 VARCHAR (MAX)  NULL,
    [EstatusAprobacion]        VARCHAR (MAX)  NULL,
    [EstatusConfirmacion]      VARCHAR (MAX)  NULL,
    [TotalidadAceptada]        BIT            NULL,
    [PorcentajeAceptadoPedido] FLOAT (53)     NULL,
    [IdAceptacionPedido]       INT            NULL,
    [PorcentajeAceptado]       FLOAT (53)     NULL,
    [PedidoAprobado]           BIT            NULL,
    [PedidoConfirmado]         BIT            NULL,
    [Recepcionado]             BIT            NULL,
    [CargaCNN]                 BIT            NULL,
    [AprobacionCNN]            BIT            NULL,
    [CargaFactura]             BIT            NULL,
    [AprobacionFactura]        BIT            NULL,
    [PagoRealizado]            BIT            NULL,
    [MontoAceptado]            FLOAT (53)     NULL,
    [MontoFacturado]           FLOAT (53)     NULL,
    [FlujoAceptacionTerminado] BIT            NULL,
    [QuienDebe]                VARCHAR (10)   NULL,
    [EstatusAvancePedido]      VARCHAR (MAX)  NULL,
    [MontoPedido]              FLOAT (53)     NULL,
    [Moneda]                   VARCHAR (200)  NULL,
    [ValorEstatus]             FLOAT (53)     NULL,
    [MontoPedidoUSD]           FLOAT (53)     NULL,
    [MontoFacturadoUSD]        FLOAT (53)     NULL,
    [MontoAceptadoUSD]         FLOAT (53)     NULL,
    [ValorEstatusUSD]          FLOAT (53)     NULL,
    [FechaRegistro]            DATETIME       NULL,
    [Solicitante]              VARCHAR (3000) NULL,
    [MonedaFactura]            VARCHAR (100)  NULL
);

