CREATE TABLE [dbo].[BI_Facturas] (
    [Id_BI_Factura]       INT            IDENTITY (1, 1) NOT NULL,
    [IdSolicitudPedido]   INT            NULL,
    [IdAceptacionPedido]  INT            NULL,
    [IdUnicoFactura]      INT            NULL,
    [FechaCarga]          DATE           NULL,
    [FechaAprobacion]     DATE           NULL,
    [EstatusPedido]       VARCHAR (MAX)  NULL,
    [EstatusPago]         VARCHAR (MAX)  NULL,
    [AprobadorActual]     VARCHAR (3000) NULL,
    [IdPedido]            INT            NULL,
    [FechaRechazo]        DATETIME       NULL,
    [MontoAceptado]       FLOAT (53)     NULL,
    [MontoFacturacion]    FLOAT (53)     NULL,
    [Contrato]            VARCHAR (MAX)  NULL,
    [IdPedidoInterno]     INT            NULL,
    [RazonSocial]         VARCHAR (MAX)  NULL,
    [FacturaFolio]        VARCHAR (1000) NULL,
    [CondicionPago]       VARCHAR (1000) NULL,
    [DiasCredito]         INT            NULL,
    [UUID]                VARCHAR (1000) NULL,
    [MonedaFactura]       VARCHAR (100)  NULL,
    [MonedaPedido]        VARCHAR (100)  NULL,
    [MontoAceptadoUSD]    FLOAT (53)     NULL,
    [MontoFacturacionUSD] FLOAT (53)     NULL,
    [MontoMes]            FLOAT (53)     NULL,
    CONSTRAINT [PK_BI_Facturas] PRIMARY KEY CLUSTERED ([Id_BI_Factura] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

