CREATE TABLE [dbo].[BI_Pedido] (
    [ID_BI_Pedido]             INT            IDENTITY (1, 1) NOT NULL,
    [IdPedido]                 INT            NULL,
    [IdSolicitudPedido]        INT            NULL,
    [FechaPedido]              DATETIME       NULL,
    [RazonSocial]              VARCHAR (2500) NULL,
    [MaterialCotizadoTextoC]   VARCHAR (2500) NULL,
    [MaterialCotizadoTextoL]   VARCHAR (5000) NULL,
    [Nombre]                   VARCHAR (600)  NULL,
    [NumeroPedido]             INT            NULL,
    [EstatusPedido]            VARCHAR (600)  NULL,
    [IdSolicitudPedidoDetalle] INT            NULL,
    [Cantidad]                 FLOAT (53)     NULL,
    [UnidadProveedor]          VARCHAR (500)  NULL,
    [PrecioUnitario]           MONEY          NULL,
    [Subtotal]                 MONEY          NULL,
    [AprobadorActual]          VARCHAR (600)  NULL,
    [FechaAprobado]            DATETIME       NULL,
    [FechaEntregaInicial]      DATETIME       NULL,
    [FechaEntregaFinal]        DATETIME       NULL,
    [ConfirmacionPedido]       VARCHAR (600)  NULL,
    [DiasCredito]              VARCHAR (500)  NULL,
    [Moneda]                   VARCHAR (150)  NULL,
    [Eliminado]                VARCHAR (2)    NULL,
    [Contrato]                 VARCHAR (3000) NULL,
    [Periodo]                  VARCHAR (3000) NULL,
    [Corporativo]              VARCHAR (3000) NULL,
    [Instalacion]              VARCHAR (3000) NULL,
    [FechaRechazo]             DATETIME       NULL,
    [NoPartidaDetalle]         INT            NULL,
    [DescripcionGralReq]       VARCHAR (3000) NULL,
    [Solicitante]              VARCHAR (3000) NULL,
    [SubtotalUSD]              MONEY          NULL,
    [PartidaDetalleReq]        VARCHAR (3000) NULL,
    [PartidaReq]               VARCHAR (3000) NULL,
    [ObservacionPartidaReq]    VARCHAR (MAX)  NULL,
    [PedidoCerrado]            VARCHAR (100)  NULL,
    [Presupuesto]              VARCHAR (3000) NULL,
    [Tarea]                    VARCHAR (3000) NULL,
    [Marca]                    VARCHAR (MAX)  NULL,
    [Modelo]                   VARCHAR (MAX)  NULL,
    [NumeroParte]              VARCHAR (MAX)  NULL,
    [CentroCosto]              VARCHAR (300)  NULL,
    [TotalPedido]              MONEY          NULL,
    [TotalPedidoAceptado]      MONEY          NULL,
    CONSTRAINT [PK_BI_Pedido] PRIMARY KEY CLUSTERED ([ID_BI_Pedido] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

