CREATE TABLE [dbo].[BI_Requisicion] (
    [ID_BI_SolicitudPedido]        INT            IDENTITY (1, 1) NOT NULL,
    [IdUnicoDeRequisicion]         INT            NULL,
    [Contrato]                     VARCHAR (1000) NULL,
    [FechaRegistro]                DATETIME       NULL,
    [Solicitante]                  VARCHAR (1000) NULL,
    [IdRequisicion]                INT            NULL,
    [Periodo]                      VARCHAR (1000) NULL,
    [Presupuesto]                  VARCHAR (1000) NULL,
    [EstatusRequisicion]           VARCHAR (1000) NULL,
    [Tarea]                        VARCHAR (1000) NULL,
    [Subtarea]                     VARCHAR (1000) NULL,
    [NombreInstalacion]            VARCHAR (1000) NULL,
    [LugarEntrega]                 VARCHAR (1000) NULL,
    [Eliminado]                    VARCHAR (100)  NULL,
    [Concepto]                     VARCHAR (1000) NULL,
    [Descripcion]                  VARCHAR (4000) NULL,
    [AprobadorActual]              VARCHAR (1000) NULL,
    [IdSolicitudPedidoDetalle]     INT            NULL,
    [TienePedido]                  NVARCHAR (100) NULL,
    [FechaAprobacion]              DATETIME       NULL,
    [EstatusCotizacion]            VARCHAR (500)  NULL,
    [DescripcionGral]              VARCHAR (4000) NULL,
    [NoPartidaDetalle]             INT            NULL,
    [ObservacionPartidaReq]        VARCHAR (MAX)  NULL,
    [Marca]                        VARCHAR (MAX)  NULL,
    [Modelo]                       VARCHAR (MAX)  NULL,
    [NumeroParte]                  VARCHAR (MAX)  NULL,
    [CentroCosto]                  VARCHAR (300)  NULL,
    [CantidadProveedoresCotizaron] VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_BI_Requisicion] PRIMARY KEY CLUSTERED ([ID_BI_SolicitudPedido] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

