CREATE TABLE [dbo].[BI_Recepcion] (
    [IdRecepcion]            INT            IDENTITY (1, 1) NOT NULL,
    [IdPedidoUnico]          INT            NULL,
    [IdSolicitudPedido]      INT            NULL,
    [IdAceptacionPedido]     INT            NULL,
    [NumeroAceptacion]       INT            NULL,
    [NumeroContrato]         VARCHAR (90)   NULL,
    [IdPedido]               INT            NULL,
    [MaterialCotizadoTextoC] VARCHAR (2500) NULL,
    [MaterialCotizadoTextoL] VARCHAR (5000) NULL,
    [NombreRecibidoPor]      VARCHAR (1000) NULL,
    [CantidadPedido]         FLOAT (53)     NULL,
    [CantidadAcceptada]      FLOAT (53)     NULL,
    [CantidadRestante]       FLOAT (53)     NULL,
    [MontoAceptado]          MONEY          NULL,
    [FechaRecepcion]         DATETIME       NULL,
    [EstatusCN]              VARCHAR (5000) NULL,
    [LugarEntrega]           VARCHAR (5000) NULL,
    [PrecioUnitario]         FLOAT (53)     NULL,
    [Partida]                INT            NULL,
    [Instalacion]            VARCHAR (3000) NULL,
    [PartidaReq]             VARCHAR (3000) NULL,
    [PartidaDetalleReq]      VARCHAR (3000) NULL,
    [DescripcionGralReq]     VARCHAR (3000) NULL,
    [Solicitante]            VARCHAR (3000) NULL,
    [Comprador]              VARCHAR (3000) NULL,
    [FechaPedido]            DATETIME       NULL,
    [Moneda]                 VARCHAR (100)  NULL,
    [MontoAceptadoUSD]       MONEY          NULL,
    [Proveedor]              VARCHAR (3000) NULL,
    [NoPartidaDetalle]       INT            NULL,
    [UUID]                   VARCHAR (500)  NULL,
    [PedidoCerrado]          VARCHAR (100)  NULL,
    [EstatusPago]            VARCHAR (100)  NULL,
    [SubtotalPedidoUSD]      MONEY          NULL,
    [EstatusConfirmacion]    VARCHAR (1000) NULL,
    [Presupuesto]            VARCHAR (3000) NULL,
    [Tarea]                  VARCHAR (3000) NULL,
    [Marca]                  VARCHAR (MAX)  NULL,
    [Modelo]                 VARCHAR (MAX)  NULL,
    [NumeroParte]            VARCHAR (MAX)  NULL,
    [CentroCosto]            VARCHAR (300)  NULL,
    CONSTRAINT [PK_BI_Recepcion] PRIMARY KEY CLUSTERED ([IdRecepcion] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

