CREATE TABLE [dbo].[DEA_ProcesoAceptaciones_Estatus] (
    [IdSolicitudPedido]            NVARCHAR (100)  NULL,
    [Folio]                        NVARCHAR (100)  NULL,
    [Descripcion]                  NVARCHAR (MAX)  NULL,
    [CentroCosto]                  NVARCHAR (100)  NULL,
    [FechaRegistroSolicitudPedido] NVARCHAR (100)  NULL,
    [NumeroPedido]                 NVARCHAR (100)  NULL,
    [Proveedor]                    NVARCHAR (1000) NULL,
    [FechaPedidoFechaConfirmacion] NVARCHAR (100)  NULL,
    [TipoEntrega]                  NVARCHAR (50)   NULL,
    [UsuarioAceptaPedido]          NVARCHAR (100)  NULL,
    [FechaAceptacionPedido]        NVARCHAR (100)  NULL,
    [DiasAceptacionPedido]         NVARCHAR (100)  NULL,
    [NumeroAceptacionPedido]       NVARCHAR (100)  NULL,
    [FechaRecepcionCartaCN]        NVARCHAR (100)  NULL,
    [DiasRecepcionCartaCN]         NVARCHAR (100)  NULL,
    [UsuarioApruebaCartaCN]        NVARCHAR (100)  NULL,
    [FechaAprobacionCartaCN]       NVARCHAR (100)  NULL,
    [DiasAprobacionCartaCN]        NVARCHAR (100)  NULL,
    [EstatusCartaCN]               NVARCHAR (100)  NULL,
    [FechaRecepcionFactura]        NVARCHAR (100)  NULL,
    [DiasRecepcionFactura]         NVARCHAR (100)  NULL,
    [FolioFactura]                 NVARCHAR (1000) NULL,
    [Responsable1aAprobacion]      NVARCHAR (100)  NULL,
    [Fecha1aAprobacion]            NVARCHAR (100)  NULL,
    [DiasEspera1aAprobacion]       NVARCHAR (100)  NULL,
    [Estatus1aAprobacion]          NVARCHAR (100)  NULL,
    [Responsable2aAprobacion]      NVARCHAR (100)  NULL,
    [Fecha2aAprobacion]            NVARCHAR (100)  NULL,
    [DiasEspera2aAprobacion]       NVARCHAR (100)  NULL,
    [Estatus2aAprobacion]          NVARCHAR (100)  NULL,
    [DiasEnAprobacion]             DECIMAL (5, 2)  NULL,
    [DiasTotal]                    NVARCHAR (100)  NULL,
    [EstatusAprobacionFactura]     NVARCHAR (100)  NULL,
    [NumeroPO]                     NVARCHAR (100)  NULL,
    [FechaRegistroPO]              DATETIME        NULL,
    [Contrato]                     VARCHAR (MAX)   NULL,
    [AreaContractual]              VARCHAR (MAX)   NULL
);

