CREATE TABLE [dbo].[DEA_ProcesoAceptaciones] (
    [IdSolicitudPedido]            INT             NULL,
    [Folio]                        NVARCHAR (100)  NULL,
    [Descripcion]                  NVARCHAR (MAX)  NULL,
    [CentroCosto]                  NVARCHAR (100)  NULL,
    [NumeroPedido]                 INT             NULL,
    [Proveedor]                    NVARCHAR (1000) NULL,
    [FechaPedidoFechaConfirmacion] DATETIME        NULL,
    [TipoEntrega]                  NVARCHAR (50)   NULL,
    [UsuarioAceptaPedido]          NVARCHAR (100)  NULL,
    [FechaAceptacionPedido]        DATETIME        NULL,
    [DiasAceptacionPedido]         DECIMAL (5, 2)  NULL,
    [NumeroAceptacionPedido]       INT             NULL,
    [FechaRecepcionCartaCN]        DATETIME        NULL,
    [DiasRecepcionCartaCN]         DECIMAL (5, 2)  NULL,
    [UsuarioApruebaCartaCN]        NVARCHAR (100)  NULL,
    [FechaAprobacionCartaCN]       DATETIME        NULL,
    [DiasAprobacionCartaCN]        DECIMAL (5, 2)  NULL,
    [EstatusCartaCN]               NVARCHAR (100)  NULL,
    [FechaRecepcionFactura]        DATETIME        NULL,
    [DiasRecepcionFactura]         DECIMAL (5, 2)  NULL,
    [FolioFactura]                 NVARCHAR (1000) NULL,
    [Responsable1aAprobacion]      NVARCHAR (100)  NULL,
    [Fecha1aAprobacion]            DATETIME        NULL,
    [DiasEspera1aAprobacion]       DECIMAL (5, 2)  NULL,
    [Estatus1aAprobacion]          NVARCHAR (100)  NULL,
    [Responsable2aAprobacion]      NVARCHAR (100)  NULL,
    [Fecha2aAprobacion]            DATETIME        NULL,
    [DiasEspera2aAprobacion]       DECIMAL (5, 2)  NULL,
    [Estatus2aAprobacion]          NVARCHAR (100)  NULL,
    [DiasEnAprobacion]             DECIMAL (5, 2)  NULL,
    [DiasTotal]                    DECIMAL (5, 2)  NULL,
    [EstatusAprobacionFactura]     NVARCHAR (100)  NULL,
    [NumeroPO]                     NVARCHAR (100)  NULL,
    [FechaRegistroPO]              DATETIME        NULL
);

