CREATE TABLE [dbo].[DEA_ProcesoOferta_Estatus] (
    [IdSolicitudPedido]              NVARCHAR (100)  NULL,
    [Folio]                          NVARCHAR (100)  NULL,
    [Descripcion]                    NVARCHAR (MAX)  NULL,
    [CentroCosto]                    NVARCHAR (100)  NULL,
    [Requisitor]                     NVARCHAR (100)  NULL,
    [FechaRegistroSolicitudPedido]   NVARCHAR (100)  NULL,
    [Fecha1aAsignacionFechaCargaPR]  NVARCHAR (100)  NULL,
    [CompradorAsignado1]             NVARCHAR (1000) NULL,
    [Fecha2aAsignacion]              NVARCHAR (100)  NULL,
    [CompradorAsignado2]             NVARCHAR (1000) NULL,
    [Dias2aAsignacion]               NVARCHAR (100)  NULL,
    [Comprador]                      NVARCHAR (1000) NULL,
    [NumeroProveedores]              INT             NULL,
    [FechaEnvioCotizacion]           NVARCHAR (100)  NULL,
    [DiasEnvioCotizacion]            NVARCHAR (100)  NULL,
    [DiasSolicitudOferta]            NVARCHAR (100)  NULL,
    [NumeroProveedoresCotizaron]     INT             NULL,
    [FechaRecepcionUltimaCotizacion] NVARCHAR (100)  NULL,
    [DiasRecepcionUltimaCotizacion]  NVARCHAR (100)  NULL,
    [UsuarioEnviaPedido]             NVARCHAR (100)  NULL,
    [FechaEnvioPedido]               NVARCHAR (100)  NULL,
    [NumeroPedido]                   NVARCHAR (100)  NULL,
    [DiasEnvioPedido]                NVARCHAR (100)  NULL,
    [AprobadorPedido]                NVARCHAR (100)  NULL,
    [FechaAprobacionPedido]          NVARCHAR (100)  NULL,
    [DiasAprobacionPedido]           NVARCHAR (100)  NULL,
    [EstatusAprobacionPedido]        NVARCHAR (50)   NULL,
    [DiasAsignacionProveedor]        NVARCHAR (100)  NULL,
    [UsuarioRelacionPOSAP]           NVARCHAR (100)  NULL,
    [NumeroPOSAP]                    NVARCHAR (100)  NULL,
    [FechaRelacionPOSAP]             NVARCHAR (100)  NULL,
    [DiasRelacionPOSAP]              NVARCHAR (100)  NULL,
    [FechaConfirmacionPedido]        NVARCHAR (100)  NULL,
    [DiasConfirmacionPedido]         NVARCHAR (100)  NULL,
    [DiasTotal]                      NVARCHAR (100)  NULL,
    [EstatusFinal]                   NVARCHAR (100)  NULL,
    [Contrato]                       VARCHAR (MAX)   NULL,
    [AreaContractual]                VARCHAR (MAX)   NULL
);

