CREATE TABLE [dbo].[DEA_ProcesoSolicitudPedido] (
    [IdSolicitudPedido]                INT             NULL,
    [Folio]                            NVARCHAR (50)   NULL,
    [Descripcion]                      NVARCHAR (MAX)  NULL,
    [CentroCosto]                      NVARCHAR (100)  NULL,
    [Requisitor]                       NVARCHAR (100)  NULL,
    [FechaRegistro]                    DATETIME        NULL,
    [Responsable1aAprobacion]          NVARCHAR (1000) NULL,
    [Fecha1aAprobacion]                DATETIME        NULL,
    [DiasEspera1aAprobacion]           DECIMAL (5, 2)  NULL,
    [Estatus1aAprobacion]              NVARCHAR (50)   NULL,
    [Responsable1aReasignacion]        NVARCHAR (1000) NULL,
    [FechaAprobacion1aReasignacion]    DATETIME        NULL,
    [DiasEspera1aReasignacion]         DECIMAL (5, 2)  NULL,
    [EstatusAprobacion1aReasignacionn] NVARCHAR (50)   NULL,
    [Responsable2aAprobacion]          NVARCHAR (1000) NULL,
    [Fecha2aAprobacion]                DATETIME        NULL,
    [DiasEspera2aAprobacion]           DECIMAL (5, 2)  NULL,
    [Estatus2aAprobacion]              NVARCHAR (50)   NULL,
    [Responsable2aReasignacion]        NVARCHAR (1000) NULL,
    [FechaAprobacion2aReasignacion]    DATETIME        NULL,
    [DiasEspera2aReasignacion]         DECIMAL (5, 2)  NULL,
    [EstatusAprobacion2aReasignacion]  NVARCHAR (50)   NULL,
    [DiasEnAprobacionGeneral]          DECIMAL (5, 2)  NULL,
    [UsuarioCargaPR]                   NVARCHAR (1000) NULL,
    [FechaCargaPR]                     DATETIME        NULL,
    [DiasCargaPR]                      DECIMAL (5, 2)  NULL,
    [NumeroPR]                         NVARCHAR (100)  NULL,
    [DiasTotal]                        DECIMAL (5, 2)  NULL,
    [EstatusFinal]                     NVARCHAR (50)   NULL
);

