CREATE TABLE [dbo].[DEA_ProcesoOferta] (
    [IdSolicitudPedido]              INT             NULL,
    [Folio]                          NVARCHAR (100)  NULL,
    [Descripcion]                    NVARCHAR (MAX)  NULL,
    [CentroCosto]                    NVARCHAR (100)  NULL,
    [Fecha1aAsignacionFechaCargaPR]  DATETIME        NULL,
    [CompradorAsignado1]             NVARCHAR (1000) NULL,
    [Fecha2aAsignacion]              DATETIME        NULL,
    [CompradorAsignado2]             NVARCHAR (1000) NULL,
    [Dias2aAsignacion]               DECIMAL (5, 2)  NULL,
    [Comprador]                      NVARCHAR (1000) NULL,
    [NumeroProveedores]              INT             NULL,
    [FechaEnvioCotizacion]           DATETIME        NULL,
    [DiasEnvioCotizacion]            DECIMAL (5, 2)  NULL,
    [DiasSolicitudOferta]            DECIMAL (5, 2)  NULL,
    [NumeroProveedoresCotizaron]     INT             NULL,
    [FechaRecepcionUltimaCotizacion] DATETIME        NULL,
    [DiasRecepcionUltimaCotizacion]  DECIMAL (5, 2)  NULL,
    [FechaEnvioPedido]               DATETIME        NULL,
    [NumeroPedido]                   INT             NULL,
    [DiasEnvioPedido]                DECIMAL (5, 2)  NULL,
    [FechaAprobacionPedido]          DATETIME        NULL,
    [DiasAprobacionPedido]           DECIMAL (5, 2)  NULL,
    [EstatusAprobacionPedido]        NVARCHAR (50)   NULL,
    [DiasAsignacionProveedor]        DECIMAL (5, 2)  NULL,
    [NumeroPOSAP]                    NVARCHAR (100)  NULL,
    [FechaRelacionPOSAP]             DATETIME        NULL,
    [DiasRelacionPOSAP]              DECIMAL (5, 2)  NULL,
    [FechaConfirmacionPedido]        DATETIME        NULL,
    [DiasConfirmacionPedido]         DECIMAL (5, 2)  NULL,
    [DiasTotal]                      DECIMAL (5, 2)  NULL,
    [EstatusFinal]                   NVARCHAR (100)  NULL
);

