CREATE TABLE [dbo].[DEA_Documento_S3] (
    [IdDocumento]               INT            IDENTITY (1, 1) NOT NULL,
    [IdTipoDocumento]           INT            NULL,
    [IdUsuario]                 INT            NULL,
    [IdTipoValidacionDocumento] INT            NULL,
    [IdProveedor]               INT            NULL,
    [Activo]                    BIT            NULL,
    [Documento]                 NVARCHAR (MAX) NULL,
    [CreadoPor]                 INT            NULL,
    [CreadoEl]                  DATETIME       NULL,
    [ModificadoPor]             INT            NULL,
    [ModificadoEl]              DATETIME       NULL,
    [Descripcion]               NVARCHAR (MAX) NULL,
    [Carpeta]                   NVARCHAR (MAX) NULL,
    [Identificador]             NVARCHAR (MAX) NULL,
    [Mime]                      NVARCHAR (MAX) NULL,
    [Extension]                 NVARCHAR (MAX) NULL,
    [NombreDocumento]           NVARCHAR (MAX) NULL,
    [Duplicado]                 NVARCHAR (40)  NULL,
    [IsEliminado]               BIT            NULL,
    [EliminadoPor]              INT            NULL,
    [EliminadoEl]               DATETIME       NULL,
    [SizeDocumento]             FLOAT (53)     NULL,
    [IdDocumentoTabla]          INT            NULL,
    PRIMARY KEY CLUSTERED ([IdDocumento] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

