CREATE TABLE [dbo].[EstatusPedidosJaguar] (
    [IdConsecutivo]             INT            NOT NULL,
    [IdContrato]                INT            NULL,
    [Contrato]                  VARCHAR (50)   NULL,
    [IdPedido]                  INT            NULL,
    [OrdenCompra]               INT            NULL,
    [SolicitudPedido]           INT            NULL,
    [CreadoEl]                  DATETIME       NULL,
    [DiasPedido]                VARCHAR (150)  NULL,
    [Proveedor]                 VARCHAR (500)  NULL,
    [CorreoProveedor]           VARCHAR (500)  NULL,
    [RFC]                       VARCHAR (100)  NULL,
    [Estado]                    VARCHAR (250)  NULL,
    [Version]                   INT            NULL,
    [Moneda]                    VARCHAR (5)    NULL,
    [TipoPedido]                VARCHAR (100)  NULL,
    [Aprobadores]               VARCHAR (500)  NULL,
    [EstatusAprobador]          VARCHAR (100)  NULL,
    [IdEstatus]                 INT            NULL,
    [EstatusFactura]            VARCHAR (100)  NULL,
    [EstatusPago]               VARCHAR (50)   NULL,
    [Factura]                   VARCHAR (100)  NULL,
    [EstatusRecepcionServicio]  VARCHAR (250)  NULL,
    [EstatusCN]                 VARCHAR (250)  NULL,
    [Entidad_Jaguar]            VARCHAR (550)  NULL,
    [CuentaOrigen]              VARCHAR (150)  NULL,
    [CuentaDestino]             VARCHAR (150)  NULL,
    [FechaRegistroTranferencia] DATETIME       NULL,
    [MontoTransfer]             FLOAT (53)     NULL,
    [MonedaTransfer]            VARCHAR (5)    NULL,
    [MontoTotalOrdenCompra]     FLOAT (53)     NULL,
    [Instalacion]               VARCHAR (3000) NULL,
    [Motivo]                    VARCHAR (3000) NULL,
    [PedidoCancelado]           BIT            NULL,
    [MontoAceptacion]           FLOAT (53)     NULL,
    [DiasCredito]               INT            NULL,
    [FechaPagoSegunDiasCredito] DATE           NULL,
    [FechaIngreso]              DATETIME       NULL,
    [UUIDFactura]               VARCHAR (500)  NULL,
    [UUIDComplemento]           VARCHAR (500)  NULL,
    [UltimaFechaAprobaciones]   DATETIME       NULL,
    [FechaTransferencia]        DATE           NULL,
    [FechaCotizacion]           DATETIME       NULL,
    [FechaAprobacionOC]         DATETIME       NULL,
    [FechaAprobacionCartaCN]    DATETIME       NULL,
    [FechaAprobacionFactura]    DATETIME       NULL,
    [FechaFactura]              DATETIME       NULL,
    [RecepcionServicio]         BIT            NULL,
    [FecMovto]                  DATETIME       NULL,
    [IdProveedorCompras]        INT            NULL,
    [UUID_Adinco]               VARCHAR (500)  NULL,
    [ActividadPetrolera]        VARCHAR (5000) NULL,
    [SubactividadPetrolera]     VARCHAR (5000) NULL,
    [TareaPetrolera]            VARCHAR (5000) NULL,
    [MetodoPago]                VARCHAR (5000) NULL,
    [MontoPagadoFactura]        FLOAT (53)     NULL,
    [TotalFactura]              MONEY          NULL,
    [ConceptoFactura]           VARCHAR (8000) NULL,
    [SubTotalFactura]           MONEY          NULL,
    [Servicio]                  VARCHAR (6000) NULL,
    [IdAceptacionPedido]        INT            NULL,
    [MesSIPAC]                  DATE           NULL,
    CONSTRAINT [PK_EstatusPedidosJaguar] PRIMARY KEY CLUSTERED ([IdConsecutivo] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

