CREATE TABLE [dbo].[FI_PedimentoComprobante] (
    [IdPedimentoComprobante]     INT            IDENTITY (1, 1) NOT NULL,
    [IdContrato]                 INT            NULL,
    [NumeroPedimento]            NVARCHAR (50)  NULL,
    [ClavePedimento]             INT            NULL,
    [FolioComprobante]           NVARCHAR (50)  NULL,
    [FechaPago]                  DATE           NULL,
    [Regimen]                    NVARCHAR (200) NULL,
    [IdSubcontratistaImportador] INT            NULL,
    [AduanaES]                   NVARCHAR (50)  NULL,
    [IdSubcontratistaExportador] INT            NULL,
    [IdFormaPago]                INT            NULL,
    [IdMoneda]                   INT            NULL,
    [AcuseElectronico]           NVARCHAR (200) NULL,
    [IdEstudioPrecioTransfer]    INT            NULL,
    [IdDocFacturacionSIPAC]      NVARCHAR (50)  NULL,
    [CvTipoDocFacturacion]       INT            NULL,
    [ProcesadoSIPAC]             BIT            CONSTRAINT [DF_FI_PedimentoComprobante_ProcesadoSIPAC] DEFAULT ((0)) NULL,
    [CreadoPor]                  INT            NULL,
    [CreadoEn]                   DATETIME       NULL,
    [ModificadoPor]              INT            NULL,
    [ModificadoEn]               DATETIME       NULL,
    [HashSHA256]                 NVARCHAR (300) NULL,
    [IsEliminado]                BIT            NULL,
    [IsActivo]                   BIT            NULL,
    [IsBorrador]                 BIT            NULL,
    [IdOrigen]                   INT            NULL,
    [TipoOrigen]                 NVARCHAR (30)  NULL,
    [IdPedidoGeneral]            INT            NULL,
    [IdEstatusEliminado]         INT            NULL,
    [IdEliminado]                INT            NULL,
    [Reportado]                  BIT            NULL,
    [IdFiscalP]                  NVARCHAR (50)  NULL,
    [RazonSocialP]               NVARCHAR (MAX) NULL,
    [CuentaBancaria]             NVARCHAR (50)  NULL,
    [NumFacturaC]                NVARCHAR (50)  NULL,
    [EsnotaCredito]              BIT            NULL,
    [IdCuentaContable]           INT            NULL,
    [IdCentroCosto]              INT            NULL,
    [DiasCredito]                INT            NULL,
    [IdPeriodo]                  INT            NULL,
    [IdPresupuesto]              INT            NULL,
    [IdLineaPresupuesto]         INT            NULL,
    CONSTRAINT [PK_FI_PedimentoComprobante] PRIMARY KEY CLUSTERED ([IdPedimentoComprobante] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK__FI_PedimentoComprobante__CC_CentroCosto] FOREIGN KEY ([IdCentroCosto]) REFERENCES [dbo].[CC_CentroCosto] ([IdCentroCosto])
);

