CREATE TABLE [dbo].[InfoSAT] (
    [Id]           INT            NOT NULL,
    [DireccionWeb] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

