CREATE TABLE MM_ActividadClasificacionGasto(
Id INT IDENTITY(1,1) NOT NULL, 
Nombre VARCHAR(MAX) NOT NULL,
Activo BIT NOT NULL,
CreadoEl DATETIME NOT NULL, 
ModificadoEl DATETIME  NULL,
CONSTRAINT [PK_MM_ActividadClasificacionGasto] PRIMARY KEY CLUSTERED ([Id] ASC)
)