CREATE TABLE [dbo].[MM_Material] (
    [IdMaterial]                INT            IDENTITY (10000, 1) NOT NULL,
    [IdProveedor]               INT            NULL,
    [IdSubFamilia]              INT            NULL,
    [IdUnidad]                  INT            NULL,
    [IdTipo]                    INT            NULL,
    [DescripcionCorta]          NVARCHAR (MAX) NULL,
    [DescripcionLarga]          NVARCHAR (MAX) NULL,
    [Modelo]                    NVARCHAR (MAX) NULL,
    [NumeroParte]               NVARCHAR (MAX) NULL,
    [Presentacion]              NVARCHAR (MAX) NULL,
    [Consumible]                BIT            NULL,
    [Inventariable]             BIT            NULL,
    [TiempoEntregaEstimadoDias] INT            NULL,
    [Marca]                     NVARCHAR (200) NULL,
    [IsPublico]                 BIT            NULL,
    [Imagen]                    NVARCHAR (MAX) CONSTRAINT [DF_MM_Material_Imagen] DEFAULT (NULL) NULL,
    [FichaTecnica]              NVARCHAR (MAX) CONSTRAINT [DF_MM_Material_FichaTecnica] DEFAULT (NULL) NULL,
    [FechaAlta]                 DATETIME       NULL,
    [FechaActualizacion]        DATETIME       NULL,
    [Activo]                    BIT            NULL,
    [IsEliminado]               BIT            NULL,
    [CreadoPor]                 INT            NULL,
    [ModificadoPor]             INT            NULL,
    [IdMaestro]                 INT            NULL,
    [IsClasificionMaestro]      BIT            NULL,
    [IdBienServicioEconomia]    INT            NULL,
    [IdTipoProveedor]           INT            NULL,
    [IdUnidad_1]                INT            NULL,
    [IdUnidad_2]                INT            NULL,
    [IdUnidad_3]                INT            NULL,
    [IdTipoCatalogoMaestro]     INT            NULL,
    [Imagen_real]               IMAGE          NULL,
    [Imagen_thumb]              IMAGE          NULL,
    CONSTRAINT [PK_MM_Material] PRIMARY KEY CLUSTERED ([IdMaterial] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MM_Material_MM_BS_Actividad] FOREIGN KEY ([IdBienServicioEconomia]) REFERENCES [dbo].[MM_BS_Actividad] ([IdActividad]),
    CONSTRAINT [FK_MM_Material_MM_TipoProveedor] FOREIGN KEY ([IdTipoProveedor]) REFERENCES [dbo].[MM_TipoProveedor] ([IdTipoProveedor]),
    CONSTRAINT [FK_MM_Material_PV_MM_MaterialSubFamilia] FOREIGN KEY ([IdSubFamilia]) REFERENCES [dbo].[PV_MM_MaterialSubFamilia] ([IdSubFamilia]),
    CONSTRAINT [FK_MM_Material_PV_MM_MaterialUnidad_Unidad1] FOREIGN KEY ([IdUnidad_1]) REFERENCES [dbo].[PV_MM_MaterialUnidad] ([IdUnidad]),
    CONSTRAINT [FK_MM_Material_PV_MM_MaterialUnidad_Unidad2] FOREIGN KEY ([IdUnidad_2]) REFERENCES [dbo].[PV_MM_MaterialUnidad] ([IdUnidad]),
    CONSTRAINT [FK_MM_Material_PV_MM_MaterialUnidad_Unidad3] FOREIGN KEY ([IdUnidad_3]) REFERENCES [dbo].[PV_MM_MaterialUnidad] ([IdUnidad]),
    CONSTRAINT [FK_MM_Material_S_Proveedor] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[S_Proveedor] ([IdProveedor])
);

