CREATE TABLE [dbo].[MM_PeticionOfertaEliminadas] (
    [IdPeticionOferta]          INT            NOT NULL,
    [IdLicitacion]              INT            NULL,
    [IdSolicitudPedido]         INT            NULL,
    [IdSubcontratista]          INT            NULL,
    [Fecha]                     DATETIME       NULL,
    [CreadoPor]                 INT            NULL,
    [CreadoEl]                  DATETIME       NULL,
    [ModificadoPor]             INT            NULL,
    [ModificadoEl]              DATETIME       NULL,
    [Activo]                    BIT            NULL,
    [Visto]                     BIT            NULL,
    [Iniciada]                  BIT            NULL,
    [Finalizado]                BIT            NULL,
    [FechaFinalizado]           DATETIME       NULL,
    [Cotizado]                  BIT            NULL,
    [IdEstatus]                 INT            NULL,
    [NoCotizar]                 BIT            NULL,
    [NoSecuencia]               INT            NULL,
    [AceptoTerminosCondiciones] BIT            NULL,
    [Verificable]               BIT            NULL,
    [IdTipoProceso]             INT            NULL,
    [JustificacionAdjDirecta]   NVARCHAR (MAX) NULL,
    [DocAdjudicacionDirecta]    NVARCHAR (MAX) NULL,
    [Visible]                   BIT            NULL,
    [AMS3]                      BIT            NULL,
    [IdEstatusEliminado]        INT            NULL,
    [JustificacionAmplicacion]  NVARCHAR (MAX) NULL,
    [FechaAmpliacion]           DATETIME       NULL,
    [AmpliacionPor]             INT            NULL,
    [IdEliminado]               INT            NULL,
    [CotizacionRestringida]     BIT            NULL,
    [EliminadoEl]               DATETIME       NULL
);

