CREATE TABLE [dbo].[MM_PedidoDetalleHistorico] (
    [IdPedidoDetalle]               INT            NOT NULL,
    [IdPedido]                      INT            NULL,
    [IdMaterial]                    INT            NULL,
    [IdPeticionOfertaDetalle]       INT            NULL,
    [Posicion]                      INT            NULL,
    [PrecioUnitario]                FLOAT (53)     NULL,
    [Cantidad]                      FLOAT (53)     NULL,
    [PorcentajeIVA]                 INT            NULL,
    [Subtotal]                      FLOAT (53)     NULL,
    [Activo]                        BIT            NULL,
    [ComentariosCompras]            NVARCHAR (MAX) NULL,
    [Entregado]                     BIT            NULL,
    [AceptacionServicio]            BIT            NULL,
    [RecepcionPedido]               BIT            NULL,
    [FechaAceptacionServicio]       DATETIME       NULL,
    [IdUsuarioAceptacionServicio]   INT            NULL,
    [FechaRecepcionPedido]          DATETIME       NULL,
    [IdUsuarioRecepcionServicio]    INT            NULL,
    [ComentarioAceptacionServicio]  NVARCHAR (MAX) NULL,
    [PorcentajeContenidoNacional]   FLOAT (53)     NULL,
    [PorcentajeContenidoExtranjero] FLOAT (53)     NULL,
    [IsBienServicioNacional]        BIT            NULL,
    [CreadoPor]                     INT            NULL,
    [CreadoEl]                      DATETIME       NULL,
    [ModificadoPor]                 INT            NULL,
    [ModificadoEl]                  DATETIME       NULL,
    [IdMoneda]                      INT            NULL,
    [IdMaterialVendedor]            INT            NULL,
    [IdUnidad]                      INT            NULL,
    [IdUnidadProveedor]             INT            NULL,
    [NuevaCantidad]                 FLOAT (53)     NULL
);

