CREATE TABLE [dbo].[MPY_MM_AceptacionFactura] (
    [IdAceptacionFactura] INT            IDENTITY (1, 1) NOT NULL,
    [IdFactura]           INT            NULL,
    [IdEstatus]           INT            NOT NULL,
    [IdAceptacionPedido]  INT            NULL,
    [CreadoPor]           INT            NULL,
    [ModificadoPor]       INT            NULL,
    [ModificadoEl]        DATETIME       NULL,
    [IdEstatusXML]        INT            NULL,
    [IdEstatusPDF]        INT            NULL,
    [IdUsuarioEvaluador]  INT            NULL,
    [FechaEvaluacionXML]  DATETIME       NULL,
    [FechaEvaluacionPDF]  DATETIME       NULL,
    [FechaCargaPDF]       DATETIME       NULL,
    [FechaCargaXML]       DATETIME       NULL,
    [CreadoEl]            DATETIME       NULL,
    [IdEstatusEliminado]  INT            NULL,
    [IdEliminado]         INT            NULL,
    [IdAprobadorRechazo]  INT            NULL,
    [Comentario]          NVARCHAR (MAX) NULL,
    [IdAprobador]         INT            NULL,
    [FechaAprobacion]     DATETIME       NULL,
    [RegistroSAP]         BIT            NULL,
    [CuentaContable]      VARCHAR (50)   NULL,
    [CuentaCSH]           VARCHAR (50)   NULL,
    CONSTRAINT [PK_MPY_MM_AceptacionFactura] PRIMARY KEY CLUSTERED ([IdAceptacionFactura] ASC) WITH (STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MPY_MM_AceptacionFactura_MM_AceptacionPedido] FOREIGN KEY ([IdEstatus]) REFERENCES [dbo].[S_TipoValidacionDoc] ([IdTipoValidacionDoc]),
    CONSTRAINT [FK_MPY_MM_AceptacionFactura_MM_AceptacionPedido1] FOREIGN KEY ([IdAceptacionPedido]) REFERENCES [dbo].[MPY_MM_AceptacionPedido] ([IdAceptacionPedido]),
    CONSTRAINT [FK_MPY_MM_AceptacionFactura_S_TipoValidacionDoc] FOREIGN KEY ([IdEstatusPDF]) REFERENCES [dbo].[S_TipoValidacionDoc] ([IdTipoValidacionDoc]),
    CONSTRAINT [FK_MPY_MM_AceptacionFactura_S_TipoValidacionDoc1] FOREIGN KEY ([IdEstatusXML]) REFERENCES [dbo].[S_TipoValidacionDoc] ([IdTipoValidacionDoc]),
    CONSTRAINT [FK_MPY_MM_AceptacionFactura_S_Usuario] FOREIGN KEY ([CreadoPor]) REFERENCES [dbo].[S_Usuario] ([IdUsuario])
);

