CREATE TABLE [dbo].[MPY_MM_AceptacionPedido] (
    [IdAceptacionPedido]      INT            IDENTITY (1, 1) NOT NULL,
    [IdProveedor]             VARCHAR (20)   NULL,
    [IdPedido]                VARCHAR (100)  NULL,
    [Comentario]              VARCHAR (1500) NULL,
    [NombreUsuarioEntrega]    NVARCHAR (300) NULL,
    [Activo]                  BIT            NULL,
    [Creado]                  DATETIME       NULL,
    [IdDomicilioEntrega]      NVARCHAR (MAX) NULL,
    [CreadorPor]              INT            NULL,
    [Modificado]              DATETIME       NULL,
    [ModificadoPor]           INT            NULL,
    [IdSubContratista]        NVARCHAR (20)  NULL,
    [IdContrato]              NVARCHAR (MAX) NULL,
    [Version]                 REAL           NULL,
    [CostObject]              NVARCHAR (MAX) NULL,
    [MaterialGroup]           NVARCHAR (MAX) NULL,
    [MaterialgroupDesc2]      NVARCHAR (MAX) NULL,
    [Qty]                     NVARCHAR (MAX) NULL,
    [Price]                   NVARCHAR (MAX) NULL,
    [costobject2]             NVARCHAR (MAX) NULL,
    [ServiceGroup]            NVARCHAR (MAX) NULL,
    [SAPNumber]               NVARCHAR (MAX) NULL,
    [PaisSAP]                 NVARCHAR (MAX) NULL,
    [Contacto]                NVARCHAR (MAX) NULL,
    [CorreoContacto]          NVARCHAR (MAX) NULL,
    [VendorsName]             NVARCHAR (MAX) NULL,
    [VendorAddress]           NVARCHAR (MAX) NULL,
    [ServiceLineNumber]       VARCHAR (50)   NULL,
    [ShortText]               VARCHAR (100)  NULL,
    [ParentLineUOM]           VARCHAR (50)   NULL,
    [ServiceShortText]        VARCHAR (50)   NULL,
    [ServicesUOM]             VARCHAR (50)   NULL,
    [ReferenceNumber]         VARCHAR (20)   NULL,
    [IdPrefactura]            INT            NULL,
    [IdPDFPrefacturaS3]       INT            NULL,
    [PCN_Agregado]            BIT            NULL,
    [NombreRecibidoPor]       NVARCHAR (MAX) NULL,
    [DocumentoDescargado]     BIT            NULL,
    [IdEstatusEliminado]      INT            NULL,
    [IdNacionalidadProveedor] INT            NULL,
    [IdPRESES]                INT            NULL,
    [DocumentDate]            VARCHAR (15)   NULL,
    CONSTRAINT [PK_MPY_MM_AceptacionPedido] PRIMARY KEY CLUSTERED ([IdAceptacionPedido] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK_MPYAceptacion_Factura] FOREIGN KEY ([IdPrefactura]) REFERENCES [dbo].[FI_Factura] ([IdFactura]),
    CONSTRAINT [FK_MPYAceptacion_PDFFacturaS3] FOREIGN KEY ([IdPDFPrefacturaS3]) REFERENCES [dbo].[S_Documento_S3] ([IdDocumento])
);

