CREATE TABLE [dbo].[MPY_MM_AceptacionPedidoDetalle] (
    [IdAceptacionPedidoDetalle]  INT            IDENTITY (1, 1) NOT NULL,
    [IdAceptacionPedido]         INT            NULL,
    [IdPedidoDetalle]            INT            NULL,
    [Cantidad]                   FLOAT (53)     NULL,
    [Detalle]                    VARCHAR (1500) NULL,
    [CreadoPor]                  INT            NULL,
    [Creado]                     DATETIME       NULL,
    [Excedente]                  FLOAT (53)     NULL,
    [PCN]                        FLOAT (53)     NULL,
    [PCN_Agregado]               BIT            NULL,
    [EditadoPor]                 INT            NULL,
    [EditadoEl]                  DATETIME       NULL,
    [IdEstatusEliminado]         INT            NULL,
    [IdEliminado]                INT            NULL,
    [ClasificacionCN]            INT            NULL,
    [PrecioUnitario]             FLOAT (53)     NULL,
    [IdMoneda]                   NVARCHAR (MAX) NULL,
    [Unidad]                     NVARCHAR (MAX) NULL,
    [IdMaterialVendendor]        INT            NULL,
    [id]                         INT            NULL,
    [ordenId]                    INT            NULL,
    [articuloCodigoInterno]      NVARCHAR (MAX) NULL,
    [importe]                    FLOAT (53)     NULL,
    [ocTareaId]                  INT            NULL,
    [ocTareaCodigo]              NVARCHAR (MAX) NULL,
    [ocTareaNombre]              NVARCHAR (MAX) NULL,
    [articuloUnidadId]           INT            NULL,
    [monedaId]                   INT            NULL,
    [ocProductoCompaniaId]       INT            NULL,
    [ocProductoNombre]           NVARCHAR (MAX) NULL,
    [ocProductoCodigo]           NVARCHAR (MAX) NULL,
    [articuloNombre]             NVARCHAR (MAX) NULL,
    [articuloId]                 NVARCHAR (MAX) NULL,
    [observaciones]              NVARCHAR (MAX) NULL,
    [textNav]                    NVARCHAR (MAX) NULL,
    [fechaRecepcion]             DATE           NULL,
    [recibido]                   BIT            NULL,
    [proyectoOtId]               INT            NULL,
    [proyectoOtNombre]           NVARCHAR (MAX) NULL,
    [ocSubTareaId]               INT            NULL,
    [ocSubTareaNombre]           NVARCHAR (MAX) NULL,
    [ocActividadPetroleraId]     INT            NULL,
    [ocActividadPetroleraNombre] NVARCHAR (MAX) NULL,
    [tipoTareaId]                INT            NULL,
    [tipoTareaNombre]            NVARCHAR (MAX) NULL,
    [descuento]                  FLOAT (53)     NULL,
    [ocSubTareaCodigo]           NVARCHAR (MAX) NULL,
    [cuentaContable]             NVARCHAR (MAX) NULL,
    [SAPNumber]                  NVARCHAR (MAX) NULL,
    [Partida]                    NVARCHAR (MAX) NULL,
    [DescripcionCorta]           NVARCHAR (MAX) NULL,
    [DescripcionLarga]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_MPY_MM_AceptacionPedidoDetalle] PRIMARY KEY CLUSTERED ([IdAceptacionPedidoDetalle] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

