CREATE TABLE [dbo].[MPY_MM_Pedido] (
    [IdPedido]                   INT            NULL,
    [IdSolicitudPedido]          INT            NULL,
    [IdContrato]                 INT            NULL,
    [IdSubcontratista]           INT            NULL,
    [Fecha]                      DATETIME       NULL,
    [FechaEntrega]               DATETIME       NULL,
    [Comentarios]                NVARCHAR (MAX) NULL,
    [LugarEntrega]               NVARCHAR (MAX) NULL,
    [Editado]                    BIT            NULL,
    [Version]                    INT            NULL,
    [Activado]                   NVARCHAR (50)  NULL,
    [Aprobado]                   BIT            NULL,
    [ValorRetencion]             FLOAT (53)     NULL,
    [Clave]                      NVARCHAR (MAX) NULL,
    [ConfirmacionClave]          NVARCHAR (MAX) NULL,
    [IdMoneda]                   INT            NULL,
    [Enviado]                    BIT            NULL,
    [CondicionesPago]            INT            NULL,
    [Anticipo]                   FLOAT (53)     NULL,
    [Impuesto]                   FLOAT (53)     NULL,
    [Envio]                      FLOAT (53)     NULL,
    [Importacion]                FLOAT (53)     NULL,
    [IVA]                        FLOAT (53)     NULL,
    [Descuento]                  BIT            NULL,
    [CantidadDescuento]          FLOAT (53)     NULL,
    [PedidoAutomatico]           BIT            NULL,
    [CreadoPor]                  INT            NULL,
    [CreadoEl]                   DATETIME       NULL,
    [ModificadoPor]              INT            NULL,
    [ModificadoEl]               DATETIME       NULL,
    [Activo]                     BIT            NULL,
    [TotalPedido]                FLOAT (53)     NULL,
    [SubTotal]                   FLOAT (53)     NULL,
    [IdDomicilioEntrega]         INT            NULL,
    [RecepcionServicio]          BIT            NULL,
    [FechaRecepcionServicio]     DATETIME       NULL,
    [IdUsuarioRecepcionServicio] INT            NULL,
    [AceptacionPedidoGral]       BIT            NULL,
    [AprobacionPedido]           BIT            NULL,
    [IdProveedorCompras]         INT            NULL,
    [IdPeticionOferta]           INT            NULL,
    [FechaEnvioPedido]           DATETIME       NULL,
    [NoSecuencia]                INT            NULL,
    [IdFirma]                    NVARCHAR (35)  NULL,
    [IdEstatusEliminado]         INT            NULL,
    [DiasCredito]                INT            NULL,
    [IdEliminado]                INT            NULL,
    [Aprobadores_CN]             NVARCHAR (MAX) NULL,
    [Aprobadores_factura]        NVARCHAR (MAX) NULL
);

