CREATE TABLE [dbo].[PR_FI_PedimentoComprobante] (
    [IdPedimentoComprobante]            INT            NOT NULL,
    [IdContrato]                        INT            NULL,
    [NumeroPedimento]                   NVARCHAR (50)  NULL,
    [ClavePedimento]                    INT            NULL,
    [FolioComprobante]                  NVARCHAR (50)  NULL,
    [FechaPago]                         DATE           NULL,
    [Regimen]                           NVARCHAR (200) NULL,
    [IdSubcontratistaImportador]        INT            NULL,
    [AduanaES]                          NVARCHAR (50)  NULL,
    [IdSubcontratistaExportador]        INT            NULL,
    [IdFormaPago]                       INT            NULL,
    [IdMoneda]                          INT            NULL,
    [AcuseElectronico]                  NVARCHAR (200) NULL,
    [IdEstudioPrecioTransfer]           INT            NULL,
    [IdDocFacturacionSIPAC]             NVARCHAR (50)  NULL,
    [CvTipoDocFacturacion]              INT            NULL,
    [ProcesadoSIPAC]                    BIT            NULL,
    [CreadoPor]                         INT            NULL,
    [CreadoEn]                          DATETIME       NULL,
    [ModificadoPor]                     INT            NULL,
    [ModificadoEn]                      DATETIME       NULL,
    [HashSHA256]                        NVARCHAR (300) NULL,
    [Activo]                            BIT            NULL,
    [IdOrigen]                          INT            NULL,
    [IdPedimentoComprobantePetrovendor] INT            NULL,
    [FechaIntercambio]                  DATETIME       NULL,
    [FechaModificacionIntercambio]      DATETIME       NULL,
    [IdEliminacion]                     INT            NULL,
    [IdReciclaje]                       INT            IDENTITY (1, 1) NOT NULL
);

