CREATE TABLE [dbo].[PV_ConfiguracionProveedoresOperadoras](
	[IdConfiguracionProveedoresOperadoras] [int] IDENTITY(1,1) NOT NULL,
	[TipoConfiguracion] [nvarchar](100) NULL, --CABLE DE LA CONFIGURACION
	[Descripcion] [nvarchar](2000) NULL,--DESCRIPCION DETALLADA DE LA CONFIGURACION
	[RFC] [nvarchar](100) NULL,--RFC DEL PROVEEDOR (SOLO APLICARIA PARA CONFIGURACIONES DE PETROVENDOR)
	[IdContrato] [int] NULL,--CONTRATO DE LA OPERADORA (PUEDE APLICAR EN PETROVENDOR Y PROCURA)
	[Operadora] [bit] NULL,--EL BIT ACTIVO  SE�ALA QUE ES UNA RESTRICCION PARA LA OPERADORA
	[Proveedor] [bit] NULL,--EL BIT ACTIVO SE�ALA QUE ES UNA RESTRICCION PARA EL PROVEEDOR
	[Activo] [bit] NULL,--EL BIT ACTIVO SE�ALA QUE LA CONFIGURACION ESTA ACTIVADA
	[FechaIncio] [datetime] NULL,--FECHA INICIAL PARA CONFIGURAR UN RANGO DE FECHAS DE CONFIGURACION (VIGENCIA DE CONFIGURACION)
	[FechaFin] [datetime] NULL,--FECHA FINAL PARA CONFIGURAR UN RANGO DE FECHAS DE CONFIGURACION (VIGENCIA DE CONFIGURACION)
	[CreadoEl] [datetime] NULL,--FECHA DE CREACION DE LA CONFIGURACION
	[CreadoPor] [int] NULL,--USUARIO QUE REGISTRO LA CONFIGURACION (ACTUALMENTE NO APLICA)
	[ModificadoPor] [int] NULL,
	[ModificadoEl] [datetime] NULL
, 
	CONSTRAINT [PK_PV_ConfiguracionProveedoresOperadoras]
GO