CREATE TABLE [dbo].[PV_SectorPyMES] (
    [IdSector] INT            IDENTITY (1, 1) NOT NULL,
    [Nombre]   NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_PV_SectorPyMES] PRIMARY KEY CLUSTERED ([IdSector] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

