CREATE TABLE [dbo].[ReporteTablero] (
    [IdRequisicion]               INT            NULL,
    [Descripcion]                 NVARCHAR (MAX) NULL,
    [TareaRequisicion]            NVARCHAR (MAX) NULL,
    [SubTareaRequisicion]         NVARCHAR (MAX) NULL,
    [FechaRegistro]               DATETIME       NULL,
    [Requisitor]                  NVARCHAR (MAX) NULL,
    [FechaRechazado]              DATETIME       NULL,
    [FechaAprobacionManager]      DATETIME       NULL,
    [FechaAprobadoPrSAP]          DATETIME       NULL,
    [FechaAsignacion]             DATETIME       NULL,
    [CompradorAsignado]           NVARCHAR (MAX) NULL,
    [IdPeticionOferta]            INT            NULL,
    [FechaPeticionOferta]         DATETIME       NULL,
    [RazonSocial]                 NVARCHAR (MAX) NULL,
    [IdProveedor]                 INT            NULL,
    [FechaCotizacionOC]           DATE           NULL,
    [FechaPedido]                 DATETIME       NULL,
    [NumPedido]                   INT            NULL,
    [Version]                     INT            NULL,
    [Aprobador1]                  DATETIME       NULL,
    [Aprobador2]                  DATETIME       NULL,
    [Aprobador3]                  DATETIME       NULL,
    [Aprobador4]                  DATETIME       NULL,
    [Aprobador5]                  DATETIME       NULL,
    [AprobacionPedido]            DATETIME       NULL,
    [EstatusPedido]               NVARCHAR (MAX) NULL,
    [Costo]                       MONEY          NULL,
    [Moneda]                      NVARCHAR (200) NULL,
    [FechaRelacionPedidoPo]       DATETIME       NULL,
    [NumPoSAP]                    NVARCHAR (MAX) NULL,
    [OrdenCompra]                 DATETIME       NULL,
    [IdAceptacionPedido]          INT            NULL,
    [EntregaRecepcion]            DATETIME       NULL,
    [ResponsableAceptacion]       NVARCHAR (MAX) NULL,
    [RegistroPCN]                 NVARCHAR (MAX) NULL,
    [AprobacionPCN]               DATETIME       NULL,
    [RecepcionFactura]            DATETIME       NULL,
    [AprobacionFactura]           DATETIME       NULL,
    [NombreAreaContractual]       NVARCHAR (MAX) NULL,
    [IdInstalacion]               INT            NULL,
    [NombreInstalacion]           NVARCHAR (MAX) NULL,
    [EstatusRequisicion]          NVARCHAR (MAX) NULL,
    [ResponsableRecepcionFactura] NVARCHAR (MAX) NULL,
    [SubtotalFactura]             MONEY          NULL,
    [MontoAceptado]               FLOAT (53)     NULL,
    [DiasEnAprobacion]            INT            NULL,
    [UUID]                        NVARCHAR (MAX) NULL
);

