CREATE TABLE [dbo].[S_Documento_S3] (
    [IdDocumento]               INT            IDENTITY (1, 1) NOT NULL,
    [IdTipoDocumento]           INT            NULL,
    [IdUsuario]                 INT            NULL,
    [IdTipoValidacionDocumento] INT            NULL,
    [IdProveedor]               INT            NULL,
    [Activo]                    BIT            NULL,
    [Documento]                 NVARCHAR (MAX) NULL,
    [CreadoPor]                 INT            NULL,
    [CreadoEl]                  DATETIME       NULL,
    [ModificadoPor]             INT            NULL,
    [ModificadoEl]              DATETIME       NULL,
    [Descripcion]               NVARCHAR (MAX) NULL,
    [Carpeta]                   NVARCHAR (MAX) NULL,
    [Identificador]             NVARCHAR (MAX) NULL,
    [Mime]                      NVARCHAR (MAX) NULL,
    [Extension]                 NVARCHAR (MAX) NULL,
    [NombreDocumento]           NVARCHAR (MAX) NULL,
    [Duplicado]                 NVARCHAR (40)  NULL,
    [SizeDocumento]             FLOAT (53)     NULL,
    [IdDocumentoTabla]          INT            NULL,
    [Bucket]                    VARCHAR (50)   NULL,
    CONSTRAINT [PK_S_DocumentoS3] PRIMARY KEY CLUSTERED ([IdDocumento] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON),
    CONSTRAINT [FK__S_Documento__S_Usuario] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[S_Usuario] ([IdUsuario]),
    CONSTRAINT [FK__S_DocumentoS3__S_TipoDocumento] FOREIGN KEY ([IdTipoDocumento]) REFERENCES [dbo].[S_TipoDocumento] ([IdTipoDocumento]),
    CONSTRAINT [FK__S_DocumentoS3_S_TipoValidacionDoc] FOREIGN KEY ([IdTipoValidacionDocumento]) REFERENCES [dbo].[S_TipoValidacionDoc] ([IdTipoValidacionDoc]),
    CONSTRAINT [FK__S_Documentos3_SE__S_Proveedor] FOREIGN KEY ([IdProveedor]) REFERENCES [dbo].[S_Proveedor] ([IdProveedor])
);

