CREATE TABLE [dbo].[Temp] (
    [GRUPO]        NVARCHAR (255) NULL,
    [CODFAM]       NVARCHAR (255) NULL,
    [FAMILIA]      NVARCHAR (255) NULL,
    [CODSUB]       NVARCHAR (255) NULL,
    [SUBFAMILIA]   NVARCHAR (255) NULL,
    [UNIDAD]       NVARCHAR (255) NULL,
    [TIPOMATERIAL] NVARCHAR (255) NULL
);

