CREATE TABLE [dbo].[VISTA_ComprasDirectas] (
    [idFactura]                  INT            NULL,
    [UUID_Petrovendor]           VARCHAR (100)  NULL,
    [Serie]                      VARCHAR (100)  NULL,
    [Folio]                      VARCHAR (100)  NULL,
    [UUID_Adinco]                VARCHAR (100)  NULL,
    [NumeroContrato]             VARCHAR (100)  NULL,
    [Moneda]                     VARCHAR (10)   NULL,
    [TotalFactura]               FLOAT (53)     NULL,
    [ConceptoFactura]            VARCHAR (8000) NULL,
    [SubTotalFactura]            FLOAT (53)     NULL,
    [Receptor]                   VARCHAR (20)   NULL,
    [Proveedor]                  VARCHAR (1000) NULL,
    [RFCProveedor]               VARCHAR (20)   NULL,
    [FechaAprobacionFactura]     DATETIME       NULL,
    [idOperacion]                INT            NULL,
    [Pedido]                     INT            NULL,
    [CreadoEl]                   DATETIME       NULL,
    [DiasPedido]                 VARCHAR (150)  NULL,
    [Estado]                     VARCHAR (250)  NULL,
    [NombreOperacion]            VARCHAR (120)  NULL,
    [Aprobadores]                VARCHAR (500)  NULL,
    [EstatusFactura]             VARCHAR (100)  NULL,
    [EstatusPago]                VARCHAR (50)   NULL,
    [EstatusCN]                  VARCHAR (250)  NULL,
    [RSContratista]              VARCHAR (550)  NULL,
    [CuentaOrigen]               VARCHAR (150)  NULL,
    [CuentaDestino]              VARCHAR (150)  NULL,
    [FechaRegistroTransferencia] DATETIME       NULL,
    [MontoTransfer]              FLOAT (53)     NULL,
    [MonedaTransfer]             VARCHAR (5)    NULL,
    [MontoRegistro]              FLOAT (53)     NULL,
    [Instalacion]                VARCHAR (3000) NULL,
    [Motivo]                     VARCHAR (3000) NULL,
    [UUID_C]                     VARCHAR (500)  NULL,
    [FechaTransferencia]         DATETIME       NULL,
    [FechaFactura]               DATETIME       NULL,
    [MontoTransferFactura]       FLOAT (53)     NULL,
    [MetodoPago]                 VARCHAR (5000) NULL
);

