CREATE TABLE [dbo].[vwReporteDEA] (
    [Contrato]                   NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IdSolicitudPedido]          INT            NULL,
    [FechaAlta]                  DATETIME       NULL,
    [Objeto]                     NVARCHAR (MAX) NULL,
    [Folio]                      NVARCHAR (MAX) NULL,
    [PedidoADINCO]               INT            NULL,
    [IdAceptacionPedido]         INT            NULL,
    [DescripcionCorta]           NVARCHAR (MAX) NULL,
    [DescripcionLarga]           NVARCHAR (MAX) NULL,
    [Unidad]                     NVARCHAR (350) NULL,
    [CantidadSolicitada]         FLOAT (53)     NULL,
    [CantidadRecibida]           FLOAT (53)     NULL,
    [PrecioUnitario]             FLOAT (53)     NULL,
    [Moneda]                     NVARCHAR (MAX) NULL,
    [Descripcion]                NVARCHAR (MAX) NULL,
    [NombreInstalacion]          NVARCHAR (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mes]                        NVARCHAR (MAX) NULL,
    [Actividad]                  NVARCHAR (MAX) NULL,
    [SubActividad]               NVARCHAR (MAX) NULL,
    [Tarea]                      NVARCHAR (MAX) NULL,
    [ClaveTarea]                 VARCHAR (150)  NULL,
    [SubTarea]                   VARCHAR (8000) NULL,
    [TipoPedido]                 NVARCHAR (300) NULL,
    [Proveedor]                  NVARCHAR (MAX) NULL,
    [FechaConfirmacionPedido]    DATETIME       NULL,
    [CentroCostos]               NVARCHAR (300) NULL,
    [MontoPedido]                FLOAT (53)     NULL,
    [MontoAceptado]              FLOAT (53)     NULL,
    [UUID]                       VARCHAR (500)  NULL,
    [FechaCargaXML]              DATETIME       NULL,
    [Estatus_de_factura]         NVARCHAR (MAX) NULL,
    [SolicitudPedido_Eliminada]  VARCHAR (2)    NOT NULL,
    [AceptaciónPedido_Eliminada] VARCHAR (2)    NOT NULL,
    [Pedido_Eliminado]           VARCHAR (2)    NOT NULL
);

