CREATE TABLE [dbo].[WA_PedimentoComprobante] (
    [IdPedimentoComprobante]     INT            NULL,
    [IdContrato]                 INT            NULL,
    [NumeroPedimento]            NVARCHAR (50)  NULL,
    [ClavePedimento]             INT            NULL,
    [FolioComprobante]           NVARCHAR (50)  NULL,
    [FechaPago]                  DATE           NULL,
    [Regimen]                    NVARCHAR (200) NULL,
    [IdSubcontratistaImportador] INT            NULL,
    [AduanaES]                   NVARCHAR (50)  NULL,
    [IdSubcontratistaExportador] INT            NULL,
    [IdFormaPago]                INT            NULL,
    [IdMoneda]                   INT            NULL,
    [AcuseElectronico]           NVARCHAR (200) NULL,
    [IdEstudioPrecioTransfer]    INT            NULL,
    [IdDocFacturacionSIPAC]      NVARCHAR (50)  NULL,
    [CvTipoDocFacturacion]       INT            NULL,
    [ProcesadoSIPAC]             BIT            NULL,
    [CreadoPor]                  INT            NULL,
    [CreadoEn]                   DATETIME       NULL,
    [ModificadoPor]              INT            NULL,
    [ModificadoEn]               DATETIME       NULL,
    [HashSHA256]                 NVARCHAR (300) NULL,
    [IsEliminado]                BIT            NULL,
    [IsActivo]                   BIT            NULL,
    [IsBorrador]                 BIT            NULL,
    [IdOrigen]                   INT            NULL,
    [TipoOrigen]                 NVARCHAR (30)  NULL,
    [IdPedidoGeneral]            INT            NULL,
    [IdEstatusEliminado]         INT            NULL,
    [IdEliminado]                INT            NULL,
    [Reportado]                  BIT            NULL
);

