CREATE TABLE [dbo].[WDEA_PurchasingDocumentsImportados] (
    [IDIMPORTACION]           INT           IDENTITY (1, 1) NOT NULL,
    [IDLAYOUT]                INT           NULL,
    [ITEM]                    VARCHAR (MAX) NULL,
    [PURCHASE_ORGANIZATION]   VARCHAR (MAX) NULL,
    [IDCONTRATO]              INT           NULL,
    [COST_CENTER]             VARCHAR (MAX) NULL,
    [WBS_ELEMENT]             VARCHAR (MAX) NULL,
    [IDLINEAPRESUPUESTOMES]   INT           NULL,
    [OUTLINE_AGREEMENT]       VARCHAR (MAX) NULL,
    [SHORT_TEXT]              VARCHAR (MAX) NULL,
    [IDMATERIAL]              VARCHAR (MAX) NULL,
    [VALIDITY_PER_START]      DATE          NULL,
    [VALIDITY_PER_END]        DATE          NULL,
    [DELETION_INDICATOR]      VARCHAR (MAX) NULL,
    [PLANT]                   VARCHAR (MAX) NULL,
    [ORDER_QUANTITY]          FLOAT (53)    NULL,
    [ORDER_UNIT]              VARCHAR (MAX) NULL,
    [IDUNIDAD]                VARCHAR (MAX) NULL,
    [NET_PRICE]               FLOAT (53)    NULL,
    [CURRENCY]                VARCHAR (MAX) NULL,
    [IDMONEDA]                INT           NULL,
    [VENDOR_SUPPLIYING_PLANT] VARCHAR (MAX) NULL,
    [IDPROVEEDOR]             INT           NULL,
    [PURCHASING_DOCUMENT]     VARCHAR (MAX) NULL,
    [RELEASE_STATE]           VARCHAR (MAX) NULL,
    [NAME_OF_VENDOR]          VARCHAR (MAX) NULL,
    [ORDER_PRICE_UNIT]        VARCHAR (MAX) NULL,
    [NET_ORDER_VALUE]         FLOAT (53)    NULL,
    [REQUISITIONER]           VARCHAR (MAX) NULL,
    [IDUSUARIOSOLICITANTE]    INT           NULL,
    [TERMINOS_DE_PAGO]        VARCHAR (MAX) NULL,
    [JUSTIFICACION]           VARCHAR (MAX) NULL,
    [IdBitacora]              INT           NULL,
    [IdPedidoADINCO]          INT           NULL,
    [MECANISMO_CONTRATACION]  NVARCHAR (20) NULL,
    CONSTRAINT [PK_WDEA_PurchasingDocumentsImportados] PRIMARY KEY CLUSTERED ([IDIMPORTACION] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

