CREATE TABLE [dbo].[WS_URLs] (
    [IdUrl]       INT             IDENTITY (1, 1) NOT NULL,
    [URL]         NVARCHAR (1000) NOT NULL,
    [Descripcion] NVARCHAR (1500) NULL,
    CONSTRAINT [PK_WS_URLs] PRIMARY KEY CLUSTERED ([IdUrl] ASC) WITH (STATISTICS_NORECOMPUTE = ON)
);

