CREATE VIEW BI_SP_DEA_OT_ConsultaTablero
AS

SELECT
IdOTSolicitud, 
Folio,
CentroCosto,
Objeto,
Tarea,
SubTarea,
Estatus,
Fecha_Registro_OT,
Requisitor,
Fecha_Rechazo,
Fecha_AprobacionManager,
Fecha_Aprobacion_PRSAP,
No_PR_SAP,
Fecha_Aceptacion_Proveedor,
Fecha_Carga_Avance,
Fecha_Cierre_Semana,
Responsable_Cierre_Semana,
Fecha_Estimacion,
Responsable_Estimacion,
Fecha_Aceptacion_Pedido,
No_Aceptacion_Pedido,
Responsable_Aceptacion,
Fecha_Pedido,
No_Pedido,
Moneda,
Costo,
Estatus_Pedido,
FechaRelacion_PedidoPo,
Num_PO_SAP,
RegistroPCN,
Fecha_Aprobacion_PCN,
Fecha_Recepcion_Factura,
ResponsableRecepcionFactura,
Fecha_Aprobacion_Factura,
SubtotalFactura,
MontoAceptado,
RazonSocialProv
 FROM Adinco..OT_ReporteTablero

