CREATE PROCEDURE Layout_InsertCGI
(
    @CompanyCode NVARCHAR(200),
    @DocumentType NVARCHAR(150),
    @Documento NVARCHAR(200),
    @FiscalYear INT,
    @PostingPeriod TINYINT,
    @PostingDate DATE,
    @DocumentDate DATE,
    @JointVenture NVARCHAR(200),
    @AccountNumber NVARCHAR(200),
    @AreaContractual NVARCHAR(100),
    @Texto NVARCHAR(MAX),
    @WBSElement NVARCHAR(200),
    @CostCenter NVARCHAR(500),
    @TransactionAmount FLOAT,
    @TransactionCurrency NVARCHAR(100),
    @JoinOperAgreem NVARCHAR(200),
    @LocalAmount FLOAT,
    @Subtotal FLOAT,
    @LocalCurrency NVARCHAR(100),
    @Vendor NVARCHAR(200),
	@IdUsuario INT
)
AS
BEGIN
    INSERT INTO dbo.CGI_Layout
    (
        CompanyCode,
        DocumentType,
        Documento,
        FiscalYear,
        PostingPeriod,
        PostingDate,
        DocumentDate,
        JointVenture,
        AccountNumber,
        AreaContractual,
        Texto,
        WBSElement,
        CostCenter,
        TransactionAmount,
        TransactionCurrency,
        JoinOperAgreem,
        LocalAmount,
        Subtotal,
        LocalCurrency,
        Vendor,
		CreadoPor,
		CreadoEl,
		activo	
    )
    SELECT @CompanyCode,
           @DocumentType,
           @Documento,
           @FiscalYear,
           @PostingPeriod,
           @PostingDate,
           @DocumentDate,
           @JointVenture,
           @AccountNumber,
           @AreaContractual,
           @Texto,
           @WBSElement,
           @CostCenter,
           @TransactionAmount,
           @TransactionCurrency,
           @JoinOperAgreem,
           @LocalAmount,
           @Subtotal,
           @LocalCurrency,
           @Vendor,
		   @IdUsuario,
		   GETDATE(),
		   1
END;