CREATE PROCEDURE Layout_InsertarGasto
(
    @IdVendor INT,
    @VendorName NVARCHAR(MAX),
    @Folio NVARCHAR(250),
    @Total FLOAT,
    @Subtotal FLOAT,
    @TotalUsd FLOAT,
    @SubtotalUsd FLOAT,
    @Moneda NVARCHAR(100),
    @TipoCambio FLOAT,
    @DocumentoFactura INT,
    @DocumentoClearing INT,
    @TextoClearing NVARCHAR(MAX),
    @Area NVARCHAR(150),
    @FechaClearing DATE,
    @FechaDoc DATE,
    @Cuenta INT,
    @IdFmp NVARCHAR(250),
    @Fmp NVARCHAR(MAX),
    @Wbs NVARCHAR(250),
    @Ac NVARCHAR(150),
    @Sa NVARCHAR(150),
    @Ta NVARCHAR(150),
    @UUIDFactura NVARCHAR(300),
    @ComplementoPago NVARCHAR(300),
    @CreadoPor INT
)
AS
BEGIN
    INSERT INTO dbo.Gastos_Layout
    (
        IdVendor,
        VendorName,
        Folio,
        Total,
        Subtotal,
        TotalUsd,
        SubtotalUsd,
        Moneda,
        TipoCambio,
        DocumentoFactura,
        DocumentoClearing,
        TextoClearing,
        Area,
        FechaClearing,
        FechaDoc,
        Cuenta,
        IdFmp,
        Fmp,
        Wbs,
        Ac,
        Sa,
        Ta,
        UUIDFactura,
        ComplementoPago,
        Activo,
        CreadoEl,
        CreadoPor
    )
    SELECT @IdVendor INT,
           @VendorName,
           @Folio,
           @Total,
           @Subtotal,
           @TotalUsd,
           @SubtotalUsd,
           @Moneda,
           @TipoCambio,
           @DocumentoFactura,
           @DocumentoClearing,
           @TextoClearing,
           @Area,
           @FechaClearing,
           @FechaDoc,
           @Cuenta,
           @IdFmp,
           @Fmp,
           @Wbs,
           @Ac,
           @Sa,
           @Ta,
           @UUIDFactura,
           @ComplementoPago,
           1,
           GETDATE(),
           @CreadoPor;
END;