Create Proc p_CO_ObtenerLineaPresupuestoMes
@pIdLineaProgramaActividadMes int
as


	select IdLineaPresupuestoMes,
			IdPresupuesto,
			IdTipoServicio,
			IdActividad,
			IdSubactividad,
			IdClasificacion,
			IdSubactividad002,
			AC_TERMINADO,
			IdInstalacion,
			AC_PRESUP_MES,
			IdServicio,
			AC_FEC_INI,
			AC_FEC_FIN,
			IdActvidadHidrocarburo,
			ID_PADRE,
			IdArea,
			IdRubro,
			Volumetria,
			PrecioUnitario,
			Monto,
			IdUsuario,
			FecMovto,
			IdExcel,
			IdAnexo4,
			IdRubroInterno,
			CPXOPX,
			Actividad,
			MesActividadIni,
			MesActividadFin,
			IdActividadPetrolera,
			IdSubactividadPetrolera,
			IdTareaPetrolera,
			IdCatalogoCuentasSH,
			MOExt,
			MOCNac,
			BSExt,
			BSCNac,
			SExt,
			SNac,
			CExt,
			CNac,
			TTec,
			ISoc,
			CreadoPor,
			IdLineaProgramaActividadMes,
			CAPEX,
			AC_DESCRIPCION
	from [CO_LineaPresupuestoMes]
	where IdLineaProgramaActividadMes =@pIdLineaProgramaActividadMes 