--SET QUOTED_IDENTIFIER ON|OFF  
--SET ANSI_NULLS ON|OFF  
--GO  
CREATE PROCEDURE [dbo].[SP_APUsuarios]  
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| 'user_name'  
AS  
    SELECT UsuarioID,Nombre,Usuario FROM dbo.AP_Usuario
	WHERE ISNULL(IsGrupo,0)=0; 