-- =============================================
-- Author:		Manuel Cruz
-- Create date: 2018-09-04
-- Description:	
-- =============================================
create PROCEDURE [dbo].[SP_CNH_FormatoPlanes_Inversion_MC]
--exec[SP_CNH_FormatoPlanes_Inversion] 0,1,'2019-02-01',10058
--exec[SP_CNH_FormatoPlanes_Inversion] 0,1,'2019-02-01',10078
--exec[SP_CNH_FormatoPlanes_Inversion] 0,1,'2018-08-01',10008
-- Add the parameters for the stored procedure here
@IdContrato          INT, 
@IdUsuario           INT, 
@Mes                 DATE, 
@IdProgramaActividad INT
AS
     BEGIN
         -- SET NOCOUNT ON added to prevent extra result sets from
         -- interfering with SELECT statements.
         SET NOCOUNT ON;

         -- Insert statements for procedure here

/*DROP TABLE #DATOS;
DROP TABLE #PIVOT;
DROP TABLE #RESULTADO;*/

         CREATE TABLE #DATOS
         (IdTipoProgramaActividad INT, 
          IdActividadPetrolera    INT, 
          IdSubactividadPetrolera INT, 
          IdTareaPetrolera        INT, 
          IdServicio              INT, 
          IdGastoRubro            INT, 
          MontoRegistro           FLOAT, 
          MesPresentacion         DATE, 
          PCN                     FLOAT, 
          InicioPresup            DATE, 
          ANIO                    INT, 
          MES                     INT, 
          IdRegistro              INT,
		  MesPresentacionOrig	DATE
         );

         /**/

         CREATE TABLE #PIVOT
         (ANIO                    INT, 
          MES                     INT, 
          MesPresentacion         DATE, 
          IdTipoProgramaActividad INT, 
          IdActividadPetrolera    INT, 
          IdSubactividadPetrolera INT, 
          IdTareaPetrolera        INT, 
          IdServicio              INT, 
          PCN                     FLOAT, 
          InicioPresup            DATE, 
          MONac                   FLOAT, 
          MOExt                   FLOAT, 
          BiNac                   FLOAT, 
          BiExt                   FLOAT, 
          SerNac                  FLOAT, 
          SerExt                  FLOAT, 
          CapNac                  FLOAT, 
          CapExt                  FLOAT, 
          TransTec                FLOAT, 
          InfraSoc                FLOAT
         );

         /**/

         CREATE TABLE #RESULTADO
         (IdLinea                 INT IDENTITY(1, 1) PRIMARY KEY, 
          IdTipoProgramaActividad INT, 
          IdActividadPetrolera    INT, 
          IdSubactividadPetrolera INT, 
          IdTareaPetrolera        INT, 
          IdServicio              INT, 
          MONAC01                 FLOAT, 
          MONAC02                 FLOAT, 
          MONAC03                 FLOAT, 
          MONAC04                 FLOAT, 
          MONAC05                 FLOAT, 
          MONAC06                 FLOAT, 
          MONAC07                 FLOAT, 
          MONAC08                 FLOAT, 
          MONAC09                 FLOAT, 
          MONAC10                 FLOAT, 
          MONAC11                 FLOAT, 
          MONAC12                 FLOAT, 
          MONAC13                 FLOAT, 
          MONAC14                 FLOAT, 
          MONAC15                 FLOAT, 
          MONAC16                 FLOAT, 
          MOEXT01                 FLOAT, 
          MOEXT02                 FLOAT, 
          MOEXT03                 FLOAT, 
          MOEXT04                 FLOAT, 
          MOEXT05                 FLOAT, 
          MOEXT06                 FLOAT, 
          MOEXT07                 FLOAT, 
          MOEXT08                 FLOAT, 
          MOEXT09                 FLOAT, 
          MOEXT10                 FLOAT, 
          MOEXT11                 FLOAT, 
          MOEXT12                 FLOAT, 
          MOEXT13                 FLOAT, 
          MOEXT14                 FLOAT, 
          MOEXT15                 FLOAT, 
          MOEXT16                 FLOAT, 
          BINAC01                 FLOAT, 
          BINAC02                 FLOAT, 
          BINAC03                 FLOAT, 
          BINAC04                 FLOAT, 
          BINAC05                 FLOAT, 
          BINAC06                 FLOAT, 
          BINAC07                 FLOAT, 
          BINAC08                 FLOAT, 
          BINAC09                 FLOAT, 
          BINAC10                 FLOAT, 
          BINAC11                 FLOAT, 
          BINAC12                 FLOAT, 
          BINAC13                 FLOAT, 
          BINAC14                 FLOAT, 
          BINAC15                 FLOAT, 
          BINAC16                 FLOAT, 
          BIEXT01                 FLOAT, 
          BIEXT02                 FLOAT, 
          BIEXT03                 FLOAT, 
          BIEXT04                 FLOAT, 
          BIEXT05                 FLOAT, 
          BIEXT06                 FLOAT, 
          BIEXT07                 FLOAT, 
          BIEXT08                 FLOAT, 
          BIEXT09                 FLOAT, 
          BIEXT10                 FLOAT, 
          BIEXT11                 FLOAT, 
          BIEXT12                 FLOAT, 
          BIEXT13                 FLOAT, 
          BIEXT14                 FLOAT, 
          BIEXT15                 FLOAT, 
          BIEXT16                 FLOAT, 
          SERNAC01                FLOAT, 
          SERNAC02                FLOAT, 
          SERNAC03                FLOAT, 
          SERNAC04                FLOAT, 
          SERNAC05                FLOAT, 
          SERNAC06                FLOAT, 
          SERNAC07                FLOAT, 
          SERNAC08                FLOAT, 
          SERNAC09                FLOAT, 
          SERNAC10                FLOAT, 
          SERNAC11                FLOAT, 
          SERNAC12                FLOAT, 
          SERNAC13                FLOAT, 
          SERNAC14                FLOAT, 
          SERNAC15                FLOAT, 
          SERNAC16                FLOAT, 
          SEREXT01                FLOAT, 
          SEREXT02                FLOAT, 
          SEREXT03                FLOAT, 
          SEREXT04                FLOAT, 
          SEREXT05                FLOAT, 
          SEREXT06                FLOAT, 
          SEREXT07                FLOAT, 
          SEREXT08                FLOAT, 
          SEREXT09                FLOAT, 
          SEREXT10                FLOAT, 
          SEREXT11                FLOAT, 
          SEREXT12                FLOAT, 
          SEREXT13                FLOAT, 
          SEREXT14                FLOAT, 
          SEREXT15                FLOAT, 
          SEREXT16                FLOAT, 
          CAPNAC01                FLOAT, 
          CAPNAC02                FLOAT, 
          CAPNAC03                FLOAT, 
          CAPNAC04                FLOAT, 
          CAPNAC05                FLOAT, 
          CAPNAC06                FLOAT, 
          CAPNAC07                FLOAT, 
          CAPNAC08                FLOAT, 
          CAPNAC09                FLOAT, 
          CAPNAC10                FLOAT, 
          CAPNAC11                FLOAT, 
          CAPNAC12                FLOAT, 
          CAPNAC13                FLOAT, 
          CAPNAC14                FLOAT, 
          CAPNAC15                FLOAT, 
          CAPNAC16                FLOAT, 
          CAPEXT01                FLOAT, 
          CAPEXT02                FLOAT, 
          CAPEXT03                FLOAT, 
          CAPEXT04                FLOAT, 
          CAPEXT05                FLOAT, 
          CAPEXT06                FLOAT, 
          CAPEXT07                FLOAT, 
          CAPEXT08                FLOAT, 
          CAPEXT09                FLOAT, 
          CAPEXT10                FLOAT, 
          CAPEXT11                FLOAT, 
          CAPEXT12                FLOAT, 
          CAPEXT13                FLOAT, 
          CAPEXT14                FLOAT, 
          CAPEXT15                FLOAT, 
          CAPEXT16                FLOAT, 
          TRANSTEC01              FLOAT, 
          TRANSTEC02              FLOAT, 
          TRANSTEC03              FLOAT, 
          TRANSTEC04              FLOAT, 
          TRANSTEC05              FLOAT, 
          TRANSTEC06              FLOAT, 
          TRANSTEC07              FLOAT, 
          TRANSTEC08              FLOAT, 
          TRANSTEC09              FLOAT, 
          TRANSTEC10              FLOAT, 
          TRANSTEC11              FLOAT, 
          TRANSTEC12              FLOAT, 
          TRANSTEC13              FLOAT, 
          TRANSTEC14              FLOAT, 
          TRANSTEC15              FLOAT, 
          TRANSTEC16              FLOAT, 
          INFRASOC01              FLOAT, 
          INFRASOC02              FLOAT, 
          INFRASOC03              FLOAT, 
          INFRASOC04              FLOAT, 
          INFRASOC05              FLOAT, 
          INFRASOC06              FLOAT, 
          INFRASOC07              FLOAT, 
          INFRASOC08              FLOAT, 
          INFRASOC09              FLOAT, 
          INFRASOC10              FLOAT, 
          INFRASOC11              FLOAT, 
          INFRASOC12              FLOAT, 
          INFRASOC13              FLOAT, 
          INFRASOC14              FLOAT, 
          INFRASOC15              FLOAT, 
          INFRASOC16              FLOAT
         );

/*DECLARE 
	@IdProgramaActividad INT,
	@MesReporte	DATE

SELECT
	@IdProgramaActividad = 10058,
	@MesReporte	=	'20180801'*/

         INSERT INTO #DATOS
                SELECT PA.IdTipoProgramaActividad, 
                       LPM.IdActividadPetrolera, 
                       LPM.IdSubactividadPetrolera, 
                       LPM.IdTareaPetrolera, 
                       LPM.IdServicio, 
                       R.IdGastoRubro,
                       CASE
                           WHEN ISNULL(R.MontoRegistro, 0) <> 0
                           THEN CAST(ROUND((ISNULL(R.MontoRegistro, 0) / TCD.TipoCambio), 2) AS DECIMAL(15, 2))
                           ELSE 0
                       END AS MontoRegistro, 
                       R.MesPresentacion, 
                       ISNULL(R.PCN, 0) AS PCN, 
                       AC.Inicio AS [InicioPresup], 
                       YEAR(R.MesPresentacion) AS [ANIO], 
                       MONTH(R.MesPresentacion) AS [MES], 
                       R.IdRegistro,
					   R.MesPresentacion
                FROM dbo.CO_Registro R
                     INNER JOIN dbo.CO_LineaPresupuestoMes LPM ON LPM.IdLineaPresupuestoMes = R.IdPrograma
                     INNER JOIN dbo.CO_Presupuesto P ON P.IdPresupuesto = LPM.IdPresupuesto
                     INNER JOIN dbo.CO_AnioContractual AC ON P.IdAnioContractual = AC.IdAnioContractual
                     INNER JOIN dbo.CO_ProgramaActividad PA ON PA.IdProgramaActividad = P.IdProgramaActividad
                     LEFT JOIN dbo.FI_Factura F ON R.IdFactura = F.IdFactura
                     LEFT JOIN dbo.CO_TipoCambioDiario TCD ON F.IdMoneda = TCD.IdMoneda
                                                              AND DAY(TCD.Fecha) = DAY(F.Fecha)
                                                              AND MONTH(TCD.Fecha) = MONTH(F.Fecha)
                                                              AND YEAR(TCD.Fecha) = YEAR(F.Fecha)
                WHERE P.IdProgramaActividad = @IdProgramaActividad
                      AND R.MesPresentacion <= @Mes--'2018-10-01' 
                      AND R.CvTipoDocFacturacion = 1
                UNION
                SELECT PA.IdTipoProgramaActividad, 
                       LPM.IdActividadPetrolera, 
                       LPM.IdSubactividadPetrolera, 
                       LPM.IdTareaPetrolera, 
                       LPM.IdServicio, 
           R.IdGastoRubro,
                       CASE
                           WHEN ISNULL(R.MontoRegistro, 0) <> 0
                           THEN CAST(ROUND((ISNULL(R.MontoRegistro, 0) / TCD.TipoCambio), 2) AS DECIMAL(15, 2))
                           ELSE 0
                       END AS MontoRegistro, 
                       R.MesPresentacion, 
                       ISNULL(R.PCN, 0) AS PCN, 
                       AC.Inicio AS [InicioPresup], 
                       YEAR(R.MesPresentacion) AS [ANIO], 
                       MONTH(R.MesPresentacion) AS [MES], 
                       R.IdRegistro,
					   R.MesPresentacion
                FROM dbo.CO_Registro R
                     INNER JOIN dbo.CO_LineaPresupuestoMes LPM ON LPM.IdLineaPresupuestoMes = R.IdPrograma
                     INNER JOIN dbo.CO_Presupuesto P ON P.IdPresupuesto = LPM.IdPresupuesto
                     INNER JOIN dbo.CO_AnioContractual AC ON P.IdAnioContractual = AC.IdAnioContractual
                     INNER JOIN dbo.CO_ProgramaActividad PA ON PA.IdProgramaActividad = P.IdProgramaActividad
                     LEFT JOIN dbo.FI_PedimentoComprobante PC ON R.IdPedimentoComprobante = PC.IdPedimentoComprobante
                     LEFT JOIN dbo.CO_TipoCambioDiario TCD ON PC.IdMoneda = TCD.IdMoneda
                                                              AND DAY(TCD.Fecha) = DAY(PC.FechaPago)
                                                              AND MONTH(TCD.Fecha) = MONTH(PC.FechaPago)
                                                              AND YEAR(TCD.Fecha) = YEAR(PC.FechaPago)
                WHERE P.IdProgramaActividad = @IdProgramaActividad
                      AND R.MesPresentacion <= @Mes--'2018-10-01'
                      AND R.CvTipoDocFacturacion IN(2, 3);

         -------------------------------------------
         DECLARE @diferenciames INT= 0;
         SELECT @diferenciames = 1 - MONTH(InicioPresup)--marzo =-2
         FROM #DATOS;
         --
         UPDATE #DATOS
           SET 
               MesPresentacion = DATEADD(month, @diferenciames, MesPresentacion) --=1
               --anio = YEAR(DATEADD(month, @diferenciames, MesPresentacion)), 
               --mes = MONTH(DATEADD(month, @diferenciames, MesPresentacion));

         UPDATE #DATOS
           SET 
				anio = YEAR(MesPresentacion), 
               mes = MONTH( MesPresentacion);
         ------

		 UPDATE #DATOS
			SET MES = CASE WHEN DATEDIFF(MM,InicioPresup,MesPresentacionOrig) >= 12
						THEN MES + 12
						ELSE	MES
						END
         -------------------------------------------

         /**/

         INSERT INTO #PIVOT
                SELECT anio, 
                       Mes, 
                       MesPresentacion, 
                       IdTipoProgramaActividad, 
                       IdActividadPetrolera, 
                       IdSubactividadPetrolera, 
                       IdTareaPetrolera, 
                       IdServicio, 
                       PCN, 
                       InicioPresup, 
                       ISNULL([1], 0) * ISNULL(PCN, 0) AS [MONac], 
                       ISNULL([1], 0) * (1 - ISNULL(PCN, 0)) AS [MOExt], 
                       ISNULL([2], 0) * ISNULL(PCN, 0) AS [BiNac], 
                       ISNULL([2], 0) * (1 - ISNULL(PCN, 0)) AS [BiExt], 
                       ISNULL([3], 0) * ISNULL(PCN, 0) AS [SerNac], 
                       ISNULL([3], 0) * (1 - ISNULL(PCN, 0)) AS [SerExt], 
                       ISNULL([4], 0) * ISNULL(PCN, 0) AS [CapNac], 
                       ISNULL([4], 0) * (1 - ISNULL(PCN, 0)) AS [CapExt], 
                       ISNULL([5], 0) * ISNULL(PCN, 0) AS [TransTec], 
                       ISNULL([6], 0) * ISNULL(PCN, 0) AS [InfraSoc]
                FROM
                (
                    SELECT IdTipoProgramaActividad, 
                           IdActividadPetrolera, 
                           IdSubactividadPetrolera, 
                           IdTareaPetrolera, 
                           IdServicio, 
                           IdGastoRubro, 
                           MontoRegistro, 
        MesPresentacion, 
                           Mes, 
                           ANIO, 
                           PCN, 
                           InicioPresup
                    FROM #DATOS
                ) AS SourceTable PIVOT(SUM(MontoRegistro) FOR IdGastoRubro IN([1], 
                                                                              [2], 
                                                                              [3], 
                                                                              [4], 
                                                                              [5], 
                                                                              [6])) AS PivotTable;

         /**/

         INSERT INTO #RESULTADO
                SELECT IdTipoProgramaActividad, 
                       IdActividadPetrolera, 
                       IdSubactividadPetrolera, 
                       IdTareaPetrolera, 
                       IdServicio, 
                       SUM(ISNULL([1], 0)), 
                       SUM(ISNULL([2], 0)), 
                       SUM(ISNULL([3], 0)), 
                       SUM(ISNULL([4], 0)), 
                       SUM(ISNULL([5], 0)), 
                       SUM(ISNULL([6], 0)), 
                       SUM(ISNULL([7], 0)), 
                       SUM(ISNULL([8], 0)), 
                       SUM(ISNULL([9], 0)), 
                       SUM(ISNULL([10], 0)), 
                       SUM(ISNULL([11], 0)), 
                       SUM(ISNULL([12], 0)), 
                       SUM(ISNULL([13], 0)), 
                       SUM(ISNULL([14], 0)), 
                       SUM(ISNULL([15], 0)), 
                       SUM(ISNULL([16], 0)), 
                       SUM(ISNULL([201], 0)), 
                       SUM(ISNULL([202], 0)), 
                       SUM(ISNULL([203], 0)), 
                       SUM(ISNULL([204], 0)), 
                       SUM(ISNULL([205], 0)), 
                       SUM(ISNULL([206], 0)), 
                       SUM(ISNULL([207], 0)), 
                       SUM(ISNULL([208], 0)), 
                       SUM(ISNULL([209], 0)), 
                       SUM(ISNULL([210], 0)), 
                       SUM(ISNULL([211], 0)), 
                       SUM(ISNULL([212], 0)), 
                       SUM(ISNULL([213], 0)), 
                       SUM(ISNULL([214], 0)), 
                       SUM(ISNULL([215], 0)), 
                       SUM(ISNULL([216], 0)), 
                       SUM(ISNULL([301], 0)), 
                       SUM(ISNULL([302], 0)), 
                       SUM(ISNULL([303], 0)), 
                       SUM(ISNULL([304], 0)), 
                       SUM(ISNULL([305], 0)), 
                       SUM(ISNULL([306], 0)), 
                       SUM(ISNULL([307], 0)), 
                       SUM(ISNULL([308], 0)), 
                       SUM(ISNULL([309], 0)), 
                       SUM(ISNULL([310], 0)), 
                       SUM(ISNULL([311], 0)), 
                       SUM(ISNULL([312], 0)), 
                       SUM(ISNULL([313], 0)), 
                       SUM(ISNULL([314], 0)), 
                       SUM(ISNULL([315], 0)), 
                       SUM(ISNULL([316], 0)), 
                       SUM(ISNULL([401], 0)), 
                       SUM(ISNULL([402], 0)), 
                       SUM(ISNULL([403], 0)), 
                       SUM(ISNULL([404], 0)), 
                       SUM(ISNULL([405], 0)), 
                       SUM(ISNULL([406], 0)), 
                       SUM(ISNULL([407], 0)), 
                       SUM(ISNULL([408], 0)), 
                       SUM(ISNULL([409], 0)), 
                       SUM(ISNULL([410], 0)), 
                       SUM(ISNULL([411], 0)), 
                       SUM(ISNULL([412], 0)), 
                       SUM(ISNULL([413], 0)), 
                       SUM(ISNULL([414], 0)), 
                       SUM(ISNULL([415], 0)), 
                       SUM(ISNULL([416], 0)), 
                       SUM(ISNULL([501], 0)), 
                       SUM(ISNULL([502], 0)), 
                       SUM(ISNULL([503], 0)), 
                       SUM(ISNULL([504], 0)), 
                       SUM(ISNULL([505], 0)), 
                       SUM(ISNULL([506], 0)), 
                       SUM(ISNULL([507], 0)), 
                       SUM(ISNULL([508], 0)), 
                       SUM(ISNULL([509], 0)), 
                       SUM(ISNULL([510], 0)), 
                       SUM(ISNULL([511], 0)), 
                       SUM(ISNULL([512], 0)), 
                       SUM(ISNULL([513], 0)), 
                       SUM(ISNULL([514], 0)), 
                       SUM(ISNULL([515], 0)), 
                       SUM(ISNULL([516], 0)), 
                       SUM(ISNULL([601], 0)), 
                       SUM(ISNULL([602], 0)), 
                       SUM(ISNULL([603], 0)), 
                       SUM(ISNULL([604], 0)), 
                       SUM(ISNULL([605], 0)), 
                       SUM(ISNULL([606], 0)), 
                       SUM(ISNULL([607], 0)), 
                       SUM(ISNULL([608], 0)), 
                       SUM(ISNULL([609], 0)), 
                       SUM(ISNULL([610], 0)), 
                       SUM(ISNULL([611], 0)), 
                       SUM(ISNULL([612], 0)), 
                       SUM(ISNULL([613], 0)), 
                       SUM(ISNULL([614], 0)), 
                       SUM(ISNULL([615], 0)), 
                       SUM(ISNULL([616], 0)), 
                       SUM(ISNULL([701], 0)), 
                       SUM(ISNULL([702], 0)), 
                       SUM(ISNULL([703], 0)), 
                       SUM(ISNULL([704], 0)), 
                       SUM(ISNULL([705], 0)), 
                       SUM(ISNULL([706], 0)), 
                       SUM(ISNULL([707], 0)), 
                       SUM(ISNULL([708], 0)), 
                       SUM(ISNULL([709], 0)), 
                       SUM(ISNULL([710], 0)), 
                       SUM(ISNULL([711], 0)), 
                       SUM(ISNULL([712], 0)), 
                       SUM(ISNULL([713], 0)), 
                       SUM(ISNULL([714], 0)), 
                       SUM(ISNULL([715], 0)), 
                       SUM(ISNULL([716], 0)), 
                       SUM(ISNULL([801], 0)), 
                       SUM(ISNULL([802], 0)), 
                       SUM(ISNULL([803], 0)), 
                       SUM(ISNULL([804], 0)), 
                       SUM(ISNULL([805], 0)), 
                       SUM(ISNULL([806], 0)), 
                       SUM(ISNULL([807], 0)), 
                       SUM(ISNULL([808], 0)), 
                       SUM(ISNULL([809], 0)), 
                       SUM(ISNULL([810], 0)), 
                       SUM(ISNULL([811], 0)), 
                       SUM(ISNULL([812], 0)), 
                       SUM(ISNULL([813], 0)), 
                       SUM(ISNULL([814], 0)), 
                       SUM(ISNULL([815], 0)), 
                       SUM(ISNULL([816], 0)), 
                       SUM(ISNULL([901], 0)), 
                       SUM(ISNULL([902], 0)), 
                       SUM(ISNULL([903], 0)), 
                       SUM(ISNULL([904], 0)), 
                       SUM(ISNULL([905], 0)), 
                       SUM(ISNULL([906], 0)), 
                       SUM(ISNULL([907], 0)), 
                       SUM(ISNULL([908], 0)), 
                       SUM(ISNULL([909], 0)), 
                       SUM(ISNULL([910], 0)), 
                       SUM(ISNULL([911], 0)), 
                       SUM(ISNULL([912], 0)), 
                       SUM(ISNULL([913], 0)), 
                       SUM(ISNULL([914], 0)), 
                       SUM(ISNULL([915], 0)), 
                       SUM(ISNULL([916], 0)), 
                       SUM(ISNULL([1001], 0)), 
                       SUM(ISNULL([1002], 0)), 
                SUM(ISNULL([1003], 0)), 
                       SUM(ISNULL([1004], 0)), 
                       SUM(ISNULL([1005], 0)), 
                       SUM(ISNULL([1006], 0)), 
                       SUM(ISNULL([1007], 0)), 
                       SUM(ISNULL([1008], 0)), 
                       SUM(ISNULL([1009], 0)), 
                       SUM(ISNULL([1010], 0)), 
                       SUM(ISNULL([1011], 0)), 
                       SUM(ISNULL([1012], 0)), 
                       SUM(ISNULL([1013], 0)), 
                       SUM(ISNULL([1014], 0)), 
                       SUM(ISNULL([1015], 0)), 
                       SUM(ISNULL([1016], 0))
                FROM
                (
                    SELECT IdTipoProgramaActividad, 
                           IdActividadPetrolera, 
                           IdSubactividadPetrolera, 
                           IdTareaPetrolera, 
                           IdServicio, 
                           InicioPresup, 
                           Mes, 
                           Mes + 200 AS [Mes2], 
                           Mes + 300 AS [Mes3], 
                           Mes + 400 AS [Mes4], 
                           Mes + 500 AS [Mes5], 
                           Mes + 600 AS [Mes6], 
                           Mes + 700 AS [Mes7], 
                           Mes + 800 AS [Mes8], 
                           Mes + 900 AS [Mes9], 
                           Mes + 1000 AS [Mes10], 
                           ANIO, 
                           MONac, 
                           MOExt, 
                           BiNac, 
                           BiExt, 
                           SerNac, 
                           SerExt, 
                           CapNac, 
                           CapExt, 
                           TransTec, 
                           InfraSoc
                    FROM #PIVOT
                ) AS SourceTable PIVOT(SUM(MONac) FOR MES IN([1], 
                                                             [2], 
                                                             [3], 
                                                             [4], 
                                                             [5], 
                                                             [6], 
                                                             [7], 
                                                             [8], 
                                                             [9], 
                                                             [10], 
                                                             [11], 
                                                             [12], 
                                                             [13], 
                                                             [14], 
                                                             [15], 
                                                             [16])) AS PV1 PIVOT(SUM(MOExt) FOR MES2 IN([201], 
                                                                                                        [202], 
                                                                                                        [203], 
                                                                                                        [204], 
                                                                                                        [205], 
                                                                                                        [206], 
                                                                                                        [207], 
                                                                                                        [208], 
                                                                                                        [209], 
                                                                             [210], 
                                                                                                        [211], 
                                                                                                        [212], 
                                                                                                        [213], 
                                                                                                        [214], 
                                                                                                        [215], 
                                                                                                        [216])) AS PV2 PIVOT(SUM(BiNac) FOR MES3 IN([301], 
                                                                                                                                                    [302], 
                                                                                                                                                    [303], 
                                                                                                                                                    [304], 
                                                                                                                                                    [305], 
                                                                                                                                                    [306], 
                                                                                                                                                    [307], 
                                                                                                                                                    [308], 
                                                                                                                                                    [309], 
                                                                                                                                                    [310], 
                                                                                                                                                    [311], 
                                                                                                                                                    [312], 
                                                                                                                                                    [313], 
                                                                                                                                                    [314], 
                                                                                                                                                    [315], 
                                                                                                                                                    [316])) AS PV3 PIVOT(SUM(BiExt) FOR MES4 IN([401], 
                                                                                                                                                                                                [402], 
                                                                                                                                                                                                [403], 
                                                                                                                                                                                                [404], 
  [405], 
                                                                                                                                                                                                [406], 
                                                                                                                                                                                                [407], 
                                                                                                                                                                                                [408], 
                                                                                                                                                                                                [409], 
                                                                                                                                                                                                [410], 
                                                                                                                                                                                                [411], 
                                                                                                                                                                                                [412], 
                                                                                                                                                                                                [413], 
                                                                                                                                                                                                [414], 
                                                                                                                                                                                                [415], 
                                                                                                                                                                                                [416])) AS PV4 PIVOT(SUM(SerNac) FOR MES5 IN([501], 
                                                                                                                                                                                                                                             [502], 
                                                                                                                                                                                                                                             [503], 
                                                                                                                                                                                                                                             [504], 
                                                                                                                                                                                                                                             [505], 
                                                                                                                                                                                                                                             [506], 
                                                                                                                                                                                                                                             [507], 
                                                                                                                                                                                                                                             [508], 
                                                                                                                                                                                                                                  [509], 
                                                                                                                                                                                                                                             [510], 
                                                                                                                                                                                                                                             [511], 
                                                                                                                                                                                                                                             [512], 
                                                                                                                                                                                                                                             [513], 
                                                                                                                                                                                                                                             [514], 
                                                                                                                                                                                                                                             [515], 
                                                                                                                                                                                                                                             [516])) AS PV5 PIVOT(SUM(SerExt) FOR MES6 IN([601], 
                                                                                                                                                                                                                                                               
                           [602], 
                           [603], 
                           [604], 
                           [605], 
                           [606], 
                           [607], 
                              [608], 
                           [609], 
                           [610], 
                           [611], 
                           [612], 
                           [613], 
                           [614], 
                           [615], 
                           [616])) AS PV6 PIVOT(SUM(CapNac) FOR MES7 IN([701], 
                                                                        [702], 
                                                                        [703], 
                                                                        [704], 
                                                                        [705], 
                                                                                   [706], 
                                                                        [707], 
                                                                        [708], 
                                                                        [709], 
                                                                        [710], 
                                                                        [711], 
                                                                        [712], 
                                                                        [713], 
                                                                        [714], 
                                                                        [715], 
                                                                        [716])) AS PV7 PIVOT(SUM(CapExt) FOR MES8 IN([801], 
                                                                                                                     [802], 
                                                                                                                     [803], 
                                                                                                                     [804], 
                                                                                                                     [805], 
                                                                                                                     [806], 
                                                                                                                     [807], 
                                                                                                                     [808], 
                                                                                                                     [809], 
                                                                                                                     [810], 
                                                                                                                     [811], 
                                                                                                                     [812], 
                                                            [813], 
                                                                                                                     [814], 
                                                                                                                     [815], 
                                                                                                                     [816])) AS PV8 PIVOT(SUM(TransTec) FOR MES9 IN([901], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [902], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [903], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [904], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [905], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [906], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [907], 
                                                                                                                                                                                                                                                      [908], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [909], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [910], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [911], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [912], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [913], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [914], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [915], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                    [916])) AS PV9 PIVOT(SUM(InfraSoc) FOR MES10 IN([1001], 
                                                                                                                                                                                                   [1002], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1003], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1004], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1005], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1006], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1007], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1008], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1009], 
           [1010], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1011], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1012], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1013], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1014], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1015], 
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                    [1016])) AS PV10
                GROUP BY IdTipoProgramaActividad, 
                         IdActividadPetrolera, 
                         IdSubactividadPetrolera, 
                         IdTareaPetrolera, 
                         IdServicio;

         /**/

         SELECT
         --MesPresentacion,
         UPPER(dbo.RemoverAcentos(TPA.TipoPrograma)) AS TipoPrograma, 
         UPPER(dbo.RemoverAcentos(AP.DescripcionActividadPetrolera)) AS DescripcionActividadPetrolera, 
         UPPER(dbo.RemoverAcentos(SAP.SubactividadPetrolera)) AS SubactividadPetrolera, 
         UPPER(dbo.RemoverAcentos(TP.TareaPetrolera)) AS TareaPetrolera, 
         UPPER(dbo.RemoverAcentos(S.NombreServicio)) AS NombreServicio, 
         R.MONAC01, 
         R.MOEXT01, 
         R.BINAC01, 
         R.BIEXT01, 
         R.SERNAC01, 
         R.SEREXT01, 
         R.CAPNAC01, 
         R.CAPEXT01, 
         R.TRANSTEC01, 
         R.INFRASOC01, 
         R.MONAC02, 
         R.MOEXT02, 
         R.BINAC02, 
         R.BIEXT02, 
         R.SERNAC02, 
         R.SEREXT02, 
         R.CAPNAC02, 
    R.CAPEXT02, 
         R.TRANSTEC02, 
         R.INFRASOC02, 
         R.MONAC03, 
         R.MOEXT03, 
         R.BINAC03, 
         R.BIEXT03, 
         R.SERNAC03, 
         R.SEREXT03, 
         R.CAPNAC03, 
         R.CAPEXT03, 
         R.TRANSTEC03, 
         R.INFRASOC03, 
         R.MONAC04, 
         R.MOEXT04, 
         R.BINAC04, 
         R.BIEXT04, 
         R.SERNAC04, 
         R.SEREXT04, 
         R.CAPNAC04, 
         R.CAPEXT04, 
         R.TRANSTEC04, 
         R.INFRASOC04, 
         R.MONAC05, 
         R.MOEXT05, 
         R.BINAC05, 
         R.BIEXT05, 
         R.SERNAC05, 
         R.SEREXT05, 
         R.CAPNAC05, 
         R.CAPEXT05, 
         R.TRANSTEC05, 
         R.INFRASOC05, 
         R.MONAC06, 
         R.MOEXT06, 
         R.BINAC06, 
         R.BIEXT06, 
         R.SERNAC06, 
         R.SEREXT06, 
         R.CAPNAC06, 
         R.CAPEXT06, 
         R.TRANSTEC06, 
         R.INFRASOC06, 
         R.MONAC07, 
         R.MOEXT07, 
         R.BINAC07, 
         R.BIEXT07, 
         R.SERNAC07, 
         R.SEREXT07, 
         R.CAPNAC07, 
         R.CAPEXT07, 
         R.TRANSTEC07, 
         R.INFRASOC07, 
         R.MONAC08, 
         R.MOEXT08, 
         R.BINAC08, 
         R.BIEXT08, 
         R.SERNAC08, 
         R.SEREXT08, 
         R.CAPNAC08, 
         R.CAPEXT08, 
         R.TRANSTEC08, 
         R.INFRASOC08, 
         R.MONAC09, 
         R.MOEXT09, 
         R.BINAC09, 
         R.BIEXT09, 
         R.SERNAC09, 
         R.SEREXT09, 
         R.CAPNAC09, 
         R.CAPEXT09, 
         R.TRANSTEC09, 
         R.INFRASOC09, 
         R.MONAC10, 
         R.MOEXT10, 
         R.BINAC10, 
         R.BIEXT10, 
         R.SERNAC10, 
         R.SEREXT10, 
         R.CAPNAC10, 
         R.CAPEXT10, 
         R.TRANSTEC10, 
         R.INFRASOC10, 
         R.MONAC11, 
         R.MOEXT11, 
         R.BINAC11, 
         R.BIEXT11, 
         R.SERNAC11, 
         R.SEREXT11, 
         R.CAPNAC11, 
         R.CAPEXT11, 
         R.TRANSTEC11, 
         R.INFRASOC11, 
         R.MONAC12, 
         R.MOEXT12, 
         R.BINAC12, 
         R.BIEXT12, 
         R.SERNAC12, 
         R.SEREXT12, 
         R.CAPNAC12, 
         R.CAPEXT12, 
         R.TRANSTEC12, 
         R.INFRASOC12, 
         R.MONAC13, 
         R.MOEXT13, 
         R.BINAC13, 
         R.BIEXT13, 
         R.SERNAC13, 
         R.SEREXT13, 
         R.CAPNAC13, 
         R.CAPEXT13, 
         R.TRANSTEC13, 
         R.INFRASOC13, 
         R.MONAC14, 
         R.MOEXT14, 
         R.BINAC14, 
         R.BIEXT14, 
         R.SERNAC14, 
         R.SEREXT14, 
         R.CAPNAC14, 
         R.CAPEXT14, 
         R.TRANSTEC14, 
         R.INFRASOC14, 
         R.MONAC15, 
         R.MOEXT15, 
         R.BINAC15, 
         R.BIEXT15, 
         R.SERNAC15, 
         R.SEREXT15, 
         R.CAPNAC15, 
         R.CAPEXT15, 
         R.TRANSTEC15, 
         R.INFRASOC15, 
         R.MONAC16, 
         R.MOEXT16, 
         R.BINAC16, 
         R.BIEXT16, 
         R.SERNAC16, 
         R.SEREXT16, 
         R.CAPNAC16, 
         R.CAPEXT16, 
         R.TRANSTEC16, 
         R.INFRASOC16, 
         0 AS MONAC17, 
         0 AS MOEXT17, 
         0 AS BINAC17, 
         0 AS BIEXT17, 
         0 AS SERNAC17, 
         0 AS SEREXT17, 
         0 AS CAPNAC17, 
         0 AS CAPEXT17, 
         0 AS TRANSTEC17, 
         0 AS INFRASOC17, 
         0 AS MONAC18, 
         0 AS MOEXT18, 
         0 AS BINAC18, 
         0 AS BIEXT18, 
         0 AS SERNAC18, 
         0 AS SEREXT18, 
         0 AS CAPNAC18, 
         0 AS CAPEXT18, 
         0 AS TRANSTEC18, 
         0 AS INFRASOC18, 
         0 AS MONAC19, 
         0 AS MOEXT19, 
         0 AS BINAC19, 
         0 AS BIEXT19, 
         0 AS SERNAC19, 
         0 AS SEREXT19, 
         0 AS CAPNAC19, 
         0 AS CAPEXT19, 
         0 AS TRANSTEC19, 
         0 AS INFRASOC19, 
         0 AS MONAC20, 
         0 AS MOEXT20, 
         0 AS BINAC20, 
         0 AS BIEXT20, 
         0 AS SERNAC20, 
         0 AS SEREXT20, 
         0 AS CAPNAC20, 
         0 AS CAPEXT20, 
         0 AS TRANSTEC20, 
         0 AS INFRASOC20, 
         0 AS MONAC21, 
         0 AS MOEXT21, 
         0 AS BINAC21, 
         0 AS BIEXT21, 
         0 AS SERNAC21, 
         0 AS SEREXT21, 
         0 AS CAPNAC21, 
         0 AS CAPEXT21, 
         0 AS TRANSTEC21, 
         0 AS INFRASOC21, 
         0 AS MONAC22, 
         0 AS MOEXT22, 
         0 AS BINAC22, 
         0 AS BIEXT22, 
         0 AS SERNAC22, 
         0 AS SEREXT22, 
         0 AS CAPNAC22, 
         0 AS CAPEXT22, 
         0 AS TRANSTEC22, 
         0 AS INFRASOC22, 
         0 AS MONAC23, 
         0 AS MOEXT23, 
         0 AS BINAC23, 
         0 AS BIEXT23, 
         0 AS SERNAC23, 
         0 AS SEREXT23, 
         0 AS CAPNAC23, 
         0 AS CAPEXT23, 
         0 AS TRANSTEC23, 
         0 AS INFRASOC23, 
         0 AS MONAC24, 
         0 AS MOEXT24, 
         0 AS BINAC24, 
         0 AS BIEXT24, 
         0 AS SERNAC24, 
         0 AS SEREXT24, 
         0 AS CAPNAC24, 
         0 AS CAPEXT24, 
         0 AS TRANSTEC24, 
         0 AS INFRASOC24, 
         0 AS MONAC25, 
         0 AS MOEXT25, 
         0 AS BINAC25, 
         0 AS BIEXT25, 
         0 AS SERNAC25, 
         0 AS SEREXT25, 
         0 AS CAPNAC25, 
         0 AS CAPEXT25, 
         0 AS TRANSTEC25, 
         0 AS INFRASOC25, 
         (R.MONAC01 + R.MOEXT01 + R.BINAC01 + R.BIEXT01 + R.SERNAC01 + R.SEREXT01 + R.CAPNAC01 + R.CAPEXT01 + R.TRANSTEC01 + R.INFRASOC01 + R.MONAC02 + R.MOEXT02 + R.BINAC02 + R.BIEXT02 + R.SERNAC02 + R.SEREXT02 + R.CAPNAC02 + R.CAPEXT02 + R.TRANSTEC02 +
 R.INFRASOC02 + R.MONAC03 + R.MOEXT03 + R.BINAC03 + R.BIEXT03 + R.SERNAC03 + R.SEREXT03 + R.CAPNAC03 + R.CAPEXT03 + R.TRANSTEC03 + R.INFRASOC03 + R.MONAC04 + R.MOEXT04 + R.BINAC04 + R.BIEXT04 + R.SERNAC04 + R.SEREXT04 + R.CAPNAC04 + R.CAPEXT04 + R.TRANSTEC04 + R.INFRASOC04 + R.MONAC05 + R.MOEXT05 + R.BINAC05 + R.BIEXT05 + R.SERNAC05 + R.SEREXT05 + R.CAPNAC05 + R.CAPEXT05 + R.TRANSTEC05 + R.INFRASOC05 + R.MONAC06 + R.MOEXT06 + R.BINAC06 + R.BIEXT06 + R.SERNAC06 + R.SEREXT06 + R.CAPNAC06 + R.CAPEXT06 + R.TRANSTEC06 + R.INFRASOC06 + R.MONAC07 + R.MOEXT07 + R.BINAC07 + R.BIEXT07 + R.SERNAC07 + R.SEREXT07 + R.CAPNAC07 + R.CAPEXT07 + R.TRANSTEC07 + R.INFRASOC07 + R.MONAC08 + R.MOEXT08 + R.BINAC08 + R.BIEXT08 + R.SERNAC08 + R.SEREXT08 + R.CAPNAC08 + R.CAPEXT08 +
 R.TRANSTEC08 + R.INFRASOC08 + R.MONAC09 + R.MOEXT09 + R.BINAC09 + R.BIEXT09 + R.SERNAC09 + R.SEREXT09 + R.CAPNAC09 + R.CAPEXT09 + R.TRANSTEC09 + R.INFRASOC09 + R.MONAC10 + R.MOEXT10 + R.BINAC10 + R.BIEXT10 + R.SERNAC10 + R.SEREXT10 + R.CAPNAC10 + R.CAPEXT10 + R.TRANSTEC10 + R.INFRASOC10 + R.MONAC11 + R.MOEXT11 + R.BINAC11 + R.BIEXT11 + R.SERNAC11 + R.SEREXT11 + R.CAPNAC11 + R.CAPEXT11 + R.TRANSTEC11 + R.INFRASOC11 + R.MONAC12 + R.MOEXT12 + R.BINAC12 + R.BIEXT12 + R.SERNAC12 + R.SEREXT12 + R.CAPNAC12 + R.CAPEXT12 + R.TRANSTEC12 + R.INFRASOC12 + R.MONAC13 + R.MOEXT13 + R.BINAC13 + R.BIEXT13 + R.SERNAC13 + R.SEREXT13 + R.CAPNAC13 + R.CAPEXT13 + R.TRANSTEC13 + R.INFRASOC13 + R.MONAC14 + R.MOEXT14 + R.BINAC14 + R.BIEXT14 + R.SERNAC14 + R.SEREXT14 + R.CAPNAC14 + R.CAPEXT14 + R.TRANSTEC14 + R.INFRASOC14 + R.MONAC12 + R.MOEXT15 + R.BINAC15 + R.BIEXT15 + R.SERNAC15 + R.SEREXT15 + R.CAPNAC15 + R.CAPEXT15 + R.TRANSTEC15 + R.INFRASOC15 + R.MONAC16 + R.MOEXT16 + R.BINAC16 + R.BIEXT16 + R.SERNAC16 + R.SEREXT16 + R.CAPNAC16 + R.CAPEXT16 + R.TRANSTEC16 + R.INFRASOC16) AS Total
         FROM #RESULTADO R
              INNER JOIN dbo.CO_ActividadPetroleraCNH AP ON AP.IdActividadPetrolera = R.IdActividadPetrolera
              INNER JOIN dbo.CO_SubactividadPetrolera SAP ON SAP.IdSubactividadPetrolera = R.IdSubactividadPetrolera
              INNER JOIN dbo.CO_TareaPetrolera TP ON TP.IdTareaPetrolera = R.IdTareaPetrolera
              INNER JOIN dbo.CO_Servicio S ON S.IdServicio = R.IdServicio
              INNER JOIN dbo.CO_TipoProgramaActividad TPA ON TPA.IdTipoProgramaActividad = R.IdTipoProgramaActividad
         --WHERE UPPER(dbo.RemoverAcentos(TP.TareaPetrolera)) <> ''
         ORDER BY TipoPrograma, 
                  DescripcionActividadPetrolera, 
                  SubactividadPetrolera, 
                  TareaPetrolera;

/*

         SELECT R.IdLinea, 
                (R.MONAC01 + R.MOEXT01 + R.BINAC01 + R.BIEXT01 + R.SERNAC01 + R.SEREXT01 + R.CAPNAC01 + R.CAPEXT01 + R.TRANSTEC01 + R.INFRASOC01 + R.MONAC02 + R.MOEXT02 + R.BINAC02 + R.BIEXT02 + R.SERNAC02 + R.SEREXT02 + R.CAPNAC02 + R.CAPEXT02 + R.TRANST
EC02 + R.INFRASOC02 + R.MONAC03 + R.MOEXT03 + R.BINAC03 + R.BIEXT03 + R.SERNAC03 + R.SEREXT03 + R.CAPNAC03 + R.CAPEXT03 + R.TRANSTEC03 + R.INFRASOC03 + R.MONAC04 + R.MOEXT04 + R.BINAC04 + R.BIEXT04 + R.SERNAC04 + R.SEREXT04 + R.CAPNAC04 + R.CAPEXT04 + R.T
RANSTEC04 + R.INFRASOC04 + R.MONAC05 + R.MOEXT05 + R.BINAC05 + R.BIEXT05 + R.SERNAC05 + R.SEREXT05 + R.CAPNAC05 + R.CAPEXT05 + R.TRANSTEC05 + R.INFRASOC05 + R.MONAC06 + R.MOEXT06 + R.BINAC06 + R.BIEXT06 + R.SERNAC06 + R.SEREXT06 + R.CAPNAC06 + R.CAPEXT06 
+ R.TRANSTEC06 + R.INFRASOC06 + R.MONAC07 + R.MOEXT07 + R.BINAC07 + R.BIEXT07 + R.SERNAC07 + R.SEREXT07 + R.CAPNAC07 + R.CAPEXT07 + R.TRANSTEC07 + R.INFRASOC07 + R.MONAC08 + R.MOEXT08 + R.BINAC08 + R.BIEXT08 + R.SERNAC08 + R.SEREXT08 + R.CAPNAC08 + R.CAPE
XT08 + R.TRANSTEC08 + R.INFRASOC08 + R.MONAC09 + R.MOEXT09 + R.BINAC09 + R.BIEXT09 + R.SERNAC09 + R.SEREXT09 + R.CAPNAC09 + R.CAPEXT09 + R.TRANSTEC09 + R.INFRASOC09 + R.MONAC10 + R.MOEXT10 + R.BINAC10 + R.BIEXT10 + R.SERNAC10 + R.SEREXT10 + R.CAPNAC10 + R
.CAPEXT10 + R.TRANSTEC10 + R.INFRASOC10 + R.MONAC11 + R.MOEXT11 + R.BINAC11 + R.BIEXT11 + R.SERNAC11 + R.SEREXT11 + R.CAPNAC11 + R.CAPEXT11 + R.TRANSTEC11 + R.INFRASOC11 + R.MONAC12 + R.MOEXT12 + R.BINAC12 + R.BIEXT12 + R.SERNAC12 + R.SEREXT12 + R.CAPNAC1
2 + R.CAPEXT12 + R.TRANSTEC12 + R.INFRASOC12) AS Total
         FROM #RESULTADO R
         ORDER BY R.IdTipoProgramaActividad, 
                  R.IdActividadPetrolera, 
                  R.IdSubactividadPetrolera, 
                  R.IdTareaPetrolera;*/

     END;