CREATE PROCEDURE [dbo].[CO_SP_AgregaContratos]
	@NumeroContrato VARCHAR(300),
	@DescripcionContrato VARCHAR(500),
	@IdContratista INT,
	@IdAreaContractual INT,
	@Activo bit,
	@IDRegFiducidiario VARCHAR(300),
	@Duracion INT,
	@FechaFirma DATE,
	@InicioVigencia DATE ,
	@FinVigencia DATE,
	@IdTipoContrato INT,
	@ValorRegaliaAdicional FLOAT,
	@IncrementoProgramaMinimo FLOAT, 
	@CreadoPor INT,
	@UsaProcura BIT,
	@PorcentajeRecuperacion FLOAT,
	@GasNoAsociado bit,
	@IdUbicacionGeografica int,
	@MesPresentacionCGI date,
	@IdRonda INT,
	@IsPC int,
	@IsConsorcio bit,
	@ParticipacionEstado varchar(500),
	@FechaArranqueEntregables date,
	@ContratoFicticio bit,
	@IDSIPAC varchar(20)
AS
    BEGIN

	INSERT INTO [CO_Contrato] 
	([NumeroContrato], 
	[DescripcionContrato], 
	[IdContratista], 
	[IdAreaContractual], 
	[Activo], 
	[IDRegFiducidiario], 
	[Duracion], 
	[FechaFirma], 
	[InicioVigencia], 
	[FinVigencia],
	[IdTipoContrato], 
	[ValorRegaliaAdicional], 
	[IncrementoProgramaMinimo], 
	[CreadoPor],
	[CreadoEl],
	[UsaProcura],
	[PorcentajeRecuperacion],
	[GasNoAsociado],
	[IdUbicacionGeografica],
	[MesPresentacionCGI],
	[IdRonda],
	[IsPC],
	[IsConsorcio],
	[ParticipacionEstado],
	[FechaArranqueEntregables],
	[ContratoFicticio],
	[IDSIPAC]) VALUES 
	(
	RTRIM(LTRIM(@NumeroContrato)), 
	RTRIM(LTRIM(@DescripcionContrato)),
	@IdContratista, 
	@IdAreaContractual, 
	@Activo, 
	@IDRegFiducidiario, 
	@Duracion, 
	@FechaFirma, 
	@InicioVigencia,
	@FinVigencia, 
	@IdTipoContrato, 
	@ValorRegaliaAdicional, 
	@IncrementoProgramaMinimo, 
	@CreadoPor,
	GETDATE(),
	@UsaProcura,
	@PorcentajeRecuperacion,
	@GasNoAsociado,
	@IdUbicacionGeografica,
	@MesPresentacionCGI,
	@IdRonda,
	@IsPC,
	@IsConsorcio,
	@ParticipacionEstado,
	@FechaArranqueEntregables,
	@ContratoFicticio,
	RTRIM(LTRIM(@IDSIPAC)))

END;
