
CREATE PROC p_CO_WDEA_Produccion_Diaria_Detalle_GRD
@Id INT
AS

		SELECT [Id]
			   ,[Pozo]
			   ,[BateriaSeparacion]
			   ,[Operativo]
			   ,[Descarga]
			   ,[Sistema]
			   ,[BN]
			   ,[MedicionFecha]
			   ,[MedicionCIA]
			   ,[MedicionQBruto]
			   ,[MedicionQNeto]
			   ,[MedicionQAgua]
			   ,[MedicionFAgua]
			   ,[MedicionQGasTotal]
			   ,[MedicionQGasForm]
			   ,[MedicionQGasiny]
			   ,[CA_LAB_Fw]
			   ,[ProduccionQBruto]
			   ,[ProduccionQNeto]
			   ,[ProduccionQAgua]
			   ,[ProduccionFAgua]
			   ,[ProduccionQGasTotal]
			   ,[ProduccionQGasForm]
			   ,[ProduccionQGasiny]
			   ,[ProduccionPGasiny]
			   ,[ProduccionRGA]
			   ,[ProduccionEstTp]
			   ,[ProduccionPTP]
			   ,[ProduccionObservaciones]
			   ,[EstadoQBruto]
			   ,[EstadoQNeto]
			   ,[EstadoQAgua]
			   ,[EstadoFAgua]
			   ,[EstadoQGasTotal]
			   ,[EstadoQGasForm]
			   ,[EstadoQGasiny]
			   ,[EstadoRGA]
			   ,[DiferenciaQBruto]
			   ,[DiferenciaQNeto]
			   ,[DiferenciaQAgua]
			   ,[DiferenciaFAgua]
			   ,[DiferenciaQGasTotal]
			   ,[DiferenciaQGasForm]
			   ,[DiferenciaQGasiny]
			   ,[DiferenciaRGA]
			   ,[DiferenciaObservaciones]
			   ,[MovimientoPozo]
			   ,[MovimientoSistema]
			   ,[MovimientoBateria]
			   ,[MovimientoHrsCierre]
			   ,[MovimientoPB]
			   ,[MovimientoAgua]
			   ,[MovimientoPN]
			   ,[MovimientoGF]
			   ,[MovimientoGI]
			   ,[MovimientoPB_BLS]
			   ,[MovimientoPN_BLS]
			   ,[MovimientoPRES_TP]
			   ,[MovimientoPRES_LDD]
			   ,[MovimientoAjusteEst]
			   ,[MovimientoAjustePB]
			   ,[MovimientoAjustePN]
			   ,[MovimientoAjusteGF]
			   ,[MovimientoAjusteGI]
			   ,[CreadoEl]
			   ,[CreadoPor]
	FROM [CO_WDEA_Produccion_Diaria_Detalle]
	WHERE Id = @Id

	