CREATE proc [dbo].[p_UpdateProformaSES_GR]
AS 
begin
	CREATE TABLE #SESPROFROMATEMP
	(
		ID INT IDENTITY(1,1),
		PROFORMA INT,
		SES NVARCHAR(50)
	);

	INSERT INTO #SESPROFROMATEMP
	SELECT
		PSES.IdPRESES,
		SES.SESNumber
	FROM Adinco.dbo.CO_SAPPRESES AS PSES
	LEFT JOIN Adinco.dbo.CO_SAPVendor AS VE ON VE.VendorIDSAP = PSES.SAPVendorNumber
	LEFT JOIN Adinco.dbo.CO_SAPPO AS PO ON PO.SAPPONumber = PSES.SAPPONumber
	LEFT JOIN Adinco.dbo.CO_SAPSES AS SES ON SES.PO_SAPNumer = PSES.SAPPONumber AND SES.SESReferenceNumber = PSES.SAPSESNumber and 
									po.Plant = ses.Plant
	WHERE SES.SESNumber <> isnull(PSES.SESN,'') and 
	ISNULL(SES.SESNumber,'') <> '' AND
	pses.IdEstatus IN (1,2)
	
	GROUP BY PSES.IdPRESES,
			 SES.SESNumber

	

	DECLARE @CONTPROFOR INT = (SELECT COUNT(IdPRESES) FROM Adinco.dbo.CO_SAPPRESES);
	DECLARE @CONT INT = 1;
	DECLARE @SESNUMBER NVARCHAR(50);

	WHILE @CONT < @CONTPROFOR
	BEGIN
	
		SET @SESNUMBER = (SELECT SES FROM #SESPROFROMATEMP WHERE ID = @CONT)

		UPDATE Adinco.dbo.CO_SAPPRESES
		SET SESN = @SESNUMBER
		WHERE IdPRESES IN (SELECT PROFORMA FROM #SESPROFROMATEMP WHERE ID = @CONT)

		SET @CONT = @CONT + 1;

	END
END