IF EXISTS
(
    SELECT 1
    FROM dbo.sysobjects
    WHERE name = 'SP_FACTURAS_COMPROBARSIEXISTE'
)
    DROP PROCEDURE SP_FACTURAS_COMPROBARSIEXISTE;
GO

CREATE PROCEDURE [dbo].[SP_FACTURAS_COMPROBARSIEXISTE]
	@idFacturaHijo INT
AS
BEGIN
    SET NOCOUNT ON;

    --
    SELECT TOP 1
        idFacturaHijo
    FROM FI_RelacionRefacturas (NOLOCK)
    WHERE idFacturaHijo = @idFacturaHijo
END;