-- =============================================
-- Author:		Miguel
-- Create date: 5-12-16
-- Description:	Inserta una factura
-- =============================================
create PROCEDURE [dbo].[sp_FI_InsertaFactura_v2]
-- Add the parameters for the stored procedure here
@Serie             NVARCHAR(MAX),
@Folio             NVARCHAR(MAX),
@Fecha             DATETIME,
@Sello             NVARCHAR(MAX),
@FormaPago         NVARCHAR(MAX),
@NoCertificado     NVARCHAR(MAX),
@Certificado       NVARCHAR(MAX),
@CondicionesDePago NVARCHAR(MAX),
@SubTotal          MONEY,
@Descuento         MONEY,
@TipoCambio        MONEY,
@Moneda            NVARCHAR(MAX),
@MontoConIva       MONEY,
@TipoComprobante   NVARCHAR(MAX),
@MetodoPago        NVARCHAR(MAX),
@LugarExpedicion   NVARCHAR(MAX),
@NumCtaPago        NVARCHAR(MAX),
@Emisor            NVARCHAR(MAX),
@Receptor          NVARCHAR(MAX),
@UUID              NVARCHAR(MAX),
@FechaTimbrado     DATETIME,
@SelloCFD          NVARCHAR(MAX),
@NoCertificadoSAT  NVARCHAR(MAX),
@SelloSAT          NVARCHAR(MAX),
@Tipo              NVARCHAR(MAX),
@FechaRecepcion    DATETIME,
@IdSubcontratista  INT,
@IdMoneda          INT,
@IdContrato        INT,
@XML               NVARCHAR(MAX),
@Activa            BIT,
@ArchivoPDF        NVARCHAR(MAX),
@ArchivoXML        NVARCHAR(MAX),
@IdUsuario         INT,
@RegimenFiscal     NVARCHAR(MAX),
@UsoCFDI		    NVARCHAR(MAX),
@VersionCFDI       NVARCHAR(MAX)
AS
         BEGIN
             SET NOCOUNT ON;
             DECLARE @ENCONTRADO AS INTEGER;
             IF LEN(RTRIM(@UUID)) > 0
                 BEGIN
                     SELECT @ENCONTRADO = COUNT(1)
                     FROM FI_Factura F
                     WHERE F.UUID = @UUID;
                     IF(@ENCONTRADO > 0)
                         BEGIN
                             SELECT IDFACTURA AS INSERTADO,
                                    'La factura '+SERIE+'-'+FOLIO+' se ha registrado correctamente con el id '+IDFACTURA AS MSG
                             FROM FI_Factura
                             WHERE UUID = @UUID;
                         END;
                         ELSE
                         BEGIN
                             INSERT INTO [dbo].[FI_Factura]
						  ([Serie],
						   [Folio],
						   [Fecha],
						   [Sello],
						   [FormaPago],
						   [NoCertificado],
						   [Certificado],
						   [CondicionesDePago],
						   [SubTotal],
						   [Descuento],
						   [TipoCambio],
						   [Moneda],
						   [MontoConIva],
						   [TipoComprobante],
						   [MetodoPago],
						   [LugarExpedicion],
						   [NumCtaPago],
						   [Emisor],
						   [Receptor],
						   [UUID],
						   [FechaTimbrado],
						   [SelloCFD],
						   [NoCertificadoSAT],
						   [SelloSAT],
						   [Tipo],
						   [FechaRecepcion],
						   [IdSubcontratista],
						   [IdMoneda],
						   [IdContrato],
						   [XML],
						   [Activa],
						   [ArchivoPDF],
						   [ArchivoXML],
						   [CreadoPor],
						   [CreadoEn],
						   [ModificadoPor],
						   [ModificadoEn],
						   [ProcesadoSIPAC],
						   [RegimenFiscal],
						   [UsoCFDI],
						   [VersionCFDI]
						  )
                             VALUES
						  (@Serie,
						   @Folio,
						   @Fecha,
						   @Sello,
						   @FormaPago,
						   @NoCertificado,
						   @Certificado,
						   @CondicionesDePago,
						   @SubTotal,
						   @Descuento,
						   @TipoCambio,
						   @Moneda,
						   @MontoConIva,
						   @TipoComprobante,
						   @MetodoPago,
						   @LugarExpedicion,
						   @NumCtaPago,
						   @Emisor,
						   @Receptor,
						   @UUID,
						   @FechaTimbrado,
						   @SelloCFD,
						   @NoCertificadoSAT,
						   @SelloSAT,
						   @Tipo,
						   @FechaRecepcion,
						   @IdSubcontratista,
						   @IdMoneda,
						   @IdContrato,
						   @XML,
						   @Activa,
						   @ArchivoPDF,
						   @ArchivoXML,
						   @IdUsuario,
						   CURRENT_TIMESTAMP,
						   @IdUsuario,
						   CURRENT_TIMESTAMP,
						   0,
						   @RegimenFiscal,
						   @UsoCFDI,
						   @VersionCFDI
						  );
                             SELECT CAST(@@IDENTITY AS NVARCHAR) AS INSERTADO,
                                    'La factura '+@Serie+'-'+@Folio+' se ha registrado correctamente con el id '+CAST(@@IDENTITY AS NVARCHAR) AS MSG;
                         END;
                 END;
                 ELSE
                 BEGIN
                     INSERT INTO [dbo].[FI_Factura]
				    ([Serie],
					[Folio],
					[Fecha],
					[Sello],
					[FormaPago],
					[NoCertificado],
					[Certificado],
					[CondicionesDePago],
					[SubTotal],
					[Descuento],
					[TipoCambio],
					[Moneda],
					[MontoConIva],
					[TipoComprobante],
					[MetodoPago],
					[LugarExpedicion],
					[NumCtaPago],
					[Emisor],
					[Receptor],
					[UUID],
					[FechaTimbrado],
					[SelloCFD],
					[NoCertificadoSAT],
					[SelloSAT],
					[Tipo],
					[FechaRecepcion],
					[IdSubcontratista],
					[IdMoneda],
					[IdContrato],
					[XML],
					[Activa],
					[ArchivoPDF],
					[ArchivoXML],
					[CreadoPor],
					[CreadoEn],
					[ModificadoPor],
					[ModificadoEn],
					[ProcesadoSIPAC],
				     [RegimenFiscal],
				     [UsoCFDI],
				     [VersionCFDI]
				    )
                     VALUES
				    (@Serie,
					@Folio,
					@Fecha,
					@Sello,
					@FormaPago,
					@NoCertificado,
					@Certificado,
					@CondicionesDePago,
					@SubTotal,
					@Descuento,
					@TipoCambio,
					@Moneda,
					@MontoConIva,
					@TipoComprobante,
					@MetodoPago,
					@LugarExpedicion,
					@NumCtaPago,
					@Emisor,
					@Receptor,
					@UUID,
					@FechaTimbrado,
					@SelloCFD,
					@NoCertificadoSAT,
					@SelloSAT,
					@Tipo,
					@FechaRecepcion,
					@IdSubcontratista,
					@IdMoneda,
					@IdContrato,
					@XML,
					@Activa,
					@ArchivoPDF,
					@ArchivoXML,
					@IdUsuario,
					CURRENT_TIMESTAMP,
					@IdUsuario,
					CURRENT_TIMESTAMP,
					0,
				     @RegimenFiscal,
				     @UsoCFDI,
				     @VersionCFDI
				    );
                     SELECT CAST(@@IDENTITY AS NVARCHAR) AS INSERTADO,
                            'La factura Serie- '+@Serie+' Folio- '+@Folio+' UUID- '+@UUID+' se ha registrado correctamente con el id '+CAST(@@IDENTITY AS NVARCHAR) AS MSG;
                 END;
         END;