--==================================
-- LUIS DAVID
-- 22/04/22
-- SE CAMBIA LA LONGITUD DE CARACTERES DEL PARAMETRO PARA NO TRUNCAR LA DESCRIPCION
CREATE PROCEDURE WS_sp_ObtenWSURLPorDescripcion
@descripcion varchar(500)
as
BEGIN 
	SELECT * FROM WS_URLS 
	WHERE DESCRIPCION = @descripcion
END