CREATE VIEW [dbo].[Estatus_de_pedidos_Detalle]
AS
    SELECT
		UUIDFactura AS UUID_Procura,
        UUID_Adinco,
        Contrato,
		IdAceptacionPedido AS [No. Aceptación Servicio],
        OrdenCompra AS [Pedido/OrdenCompra], 
        SolicitudPedido,
        CreadoEl,
        DiasPedido  AS [Dias del Pedido], 
        Proveedor,
        CorreoProveedor,
        RFC,
        Estado,
        Version,
        Moneda,
        TipoPedido,
        Aprobadores,
        EstatusAprobador,
        EstatusFactura,
        EstatusPago,
        Factura,
        EstatusRecepcionServicio AS ConfirmacionPedidoProveedor,
        EstatusCN,
        Entidad_Jaguar,
        CuentaOrigen,
        CuentaDestino,
        FechaRegistroTranferencia,
        MontoTransfer,
        MonedaTransfer,
        MontoTotalOrdenCompra,
        Instalacion,
        Motivo,
        CASE WHEN PedidoCancelado = 0 THEN 'NO' ELSE 'SI' END AS PedidoCancelado,
        MontoAceptacion,
        DiasCredito,
        FechaPagoSegunDiasCredito,
        FechaIngreso    AS FechaRecepcionServicio,
        UUIDComplemento,
        UltimaFechaAprobaciones,
        FechaTransferencia,
        FechaCotizacion,
        FechaAprobacionOC,
        FechaAprobacionCartaCN,
        FechaAprobacionFactura,
        FechaFactura,
        Actividad,
        Subactividad,
        Tarea,
        Servicio,
        ADN
    FROM
        EstatusPedidosJaguar_Detalle    (NOLOCK)
    WHERE
        IdProveedorCompras IN   (606, 690, 1835)
