create view [dbo].[vwRPT_tableroAndreaWDEA]
as
SELECT        BLOQUE, SOLPEDS, REGISTROSOLPED, CENTROCOSTO, SOLICITANTE, APROBACIONSOLPEDPROCURA, APROBACIONSOLPEDOPERACIONES, ESTATUSSOLPED, ASIGNACIONCOMPRADOR, ENVIOCOTIZACION, PROVEEDOR, 
                         PEDIDO, REGISTROPEDIDO, APROBACIONPEDIDOPROCURA, RELACIONPO, ESATUSPEDIDO, CONFIRMACIONPROVEEDOR, SAS, SASAPROBACIONSOLICITANTE, SASAPROBACIONOBS, ACEPTACIONPEDIDO, CARGACN, 
                         ACEPTACIONCARTACN, ESTATUSCARTACN, CARGAFACTURA, ACEPTACIONFACTURA, ACEPTACIONAP, ESTATUSFACTURA, PERIODOADINCO
FROM            Petrovendor.dbo.RPT_TableroAndreaWDEA
