CREATE FUNCTION [dbo].[fn_EN_getNombreDocumentoConjuncion]
(
@TmpConjunciones TableConjunciones READONLY,
@NombreDocumento varchar(max))
RETURNS varchar(max) AS
BEGIN
    DECLARE
	@counter INT,
	@count INT = 1,
	@ID_PALABRA INT,
	@palabra VARCHAR(max),
	@sustitucion VARCHAR(max),
	@EXTENSION VARCHAR(10),
	@NOMBRE_FINAL VARCHAR(MAX) = '';
	DECLARE @PUNTO TABLE(PALABRAS VARCHAR(MAX), ID INT IDENTITY(1,1));
	DECLARE @ESPACIOS TABLE(PALABRAS VARCHAR(MAX), ID INT IDENTITY(1,1));
	--EN CASO DE QUE EL NOMBRE TENGA PUNTOS EN EN SI, SE OBTIENE EL ULTIMO PARA OBTENER LA EXTENSIO DEL ARCHIVO,
	--PARA SUSTITUIRLA POR EL CATALOGO Y FINALMENTE ENVIARLO CON SU RESPECTIVA EXTENCION
	INSERT INTO @PUNTO
	SELECT splitdata FROM dbo.fnSplitString(@NombreDocumento,'.')

	--SE OBTIENE LA EXTENSION DEL ARCHIVO
	SET @EXTENSION = '.' + (SELECT TOP 1 PALABRAS FROM @PUNTO ORDER BY ID DESC);

	--SE OBTIENEN LAS PALABRAS DEL ARCHIVO, QUITANDO LA EXTENCION DEL ARCHIVO
	INSERT INTO @ESPACIOS
	SELECT REPLACE(splitdata,@EXTENSION,'') FROM dbo.fnSplitString(@NombreDocumento,' ')

	--CONTADOR PARA RECORRER LAS PALABRAS DEL NOMBRE DEL ARCHIVO
	SET @counter = (SELECT COUNT(1) FROM @ESPACIOS);

	--RECORREMOS LAS PALABRAS DEL NOMBRE DEL ARCHIVO
	WHILE @count <= @counter
	BEGIN

		SET @palabra = (SELECT LTRIM(RTRIM(PALABRAS)) FROM @ESPACIOS WHERE ID = @count);
		SET @ID_PALABRA = (SELECT id FROM @TmpConjunciones WHERE LTRIM(RTRIM(palabra)) = @palabra);
		SET @sustitucion = (SELECT LTRIM(RTRIM(sustitucion)) FROM @TmpConjunciones WHERE LTRIM(RTRIM(palabra)) = @palabra);

		--VALIDAMOS QUE EXISTA LA PALABRA EN EL CATALOGO
		IF ISNULL(@ID_PALABRA,0) > 0
		BEGIN
			SET @NOMBRE_FINAL = CONCAT(@NOMBRE_FINAL,'_',@sustitucion);
		END
		ELSE
		BEGIN
			SET @NOMBRE_FINAL = CONCAT(@NOMBRE_FINAL,'_',@palabra);
		END
	
		SET @count = @count + 1;

	END

	RETURN STUFF(REPLACE(LTRIM(RTRIM(CONCAT(@NOMBRE_FINAL,@EXTENSION))),' ','_'),1,2,'');
END;